/**
 * energy-dissipation 개념 선언.
 *
 * 마찰을 말하는 셋 가운데 이쪽만 **행방**을 묻는다.
 *   energy-dissipation      잃은 것이 **어디에 남는가** — 문지른 자리에 두께로 쌓인다
 *   non-conservative-force  **얼마나** 잃는가 — 경로가 길수록 크다 (두 경로 견줌)
 *   kinetic-friction        마찰력 자체의 성질
 * 이쪽만 「사라지지 않는다」 · 「열로 남는다」 · 「몫의 경계가 옮겨 간다」 어휘를 갖고,
 * 경로 비교 · 두 점 사이 · 변위라는 말은 쓰지 않는다.
 */

import type { Aperi21ConceptSource } from '../concept-types.js';

export const energyDissipationConcept: Aperi21ConceptSource = {
  id: 'energy-dissipation',
  label: 'Energy Dissipation',
  canonicalSim: 'aperi21:energy-dissipation',

  surface: {
    definition:
      'The share friction takes out of a motion, which does not vanish but settles as heat in the very places that were rubbed, until nothing mechanical is left.',
    exemplarKeywords: [
      'energy dissipation',
      'where does the energy lost to friction go',
      'friction turns motion into heat',
      'is energy destroyed when something stops',
      'damping and why the swinging dies away',
      'the energy did not disappear it became heat',
      'heat generated by rubbing',
      'losing mechanical energy to a rough surface',
      'why a vibration slowly stops',
      'what happens to the energy of a body that comes to rest',
    ],
  },

  briefing: {
    observable: [
      'A body tied to a spring slides back and forth across a rough floor, and each half-swing carries it a little less far than the last, until after six of them it comes to rest where the spring is neither stretched nor squeezed.',
      'Underneath the floor, a shape grows downward wherever the body has passed, and its depth at each place is how much sliding that place has had beneath the body.',
      'Because the middle is crossed on every swing while the far ends are reached only once, the shape ends up thickest in the middle and thinnest at the outer edges — the settled outline is itself the answer to where the energy went.',
      'Beside the scene stands a single bar whose whole length is the energy the motion started with. The length never changes; only the boundary inside it climbs.',
      'Everything the mechanical share loses, the heat share gains at the same instant, so the two parts of the bar are always a single quantity divided in two.',
      'When the body finally stops, the bar is heat from end to end.',
      'Three names are written beside the picture — one on each share of the bar, and one under the thickest part of the piled heat.',
      'When a cycle ends the piled heat is swept away and the bar is refilled from the top while the body is drawn back to the start, so the heat is never seen flowing backwards into motion.',
      'Nothing numeric appears anywhere — no scale on the bar, no grid, no values. What can be read is a thickness and the position of a boundary.',
      'The heat is drawn below the floor line rather than above it, so the body always travels on the plain floor and never rides over a heap.',
    ],

    screen: {
      affordances: [
        'The dying-away swings, the coming to rest and the clearing away happen in order and then begin again.',
        'The run opens with the second swing already under way, a thin layer of heat already down and the bar already divided.',
        'The body and the mechanical share of the bar carry one colour, the piled heat and the heat share of the bar carry another, so which part of the bar belongs to what on the floor needs no legend.',
        'The bar has no ticks on it, because what is to be read is where the boundary has got to and not any value.',
        'The floor and the body take up the same heat regardless of which of them would really warm; only one side of it is drawn, since where it arose is the same either way.',
      ],
    },

    useWhen: [
      'The article has said that energy is never destroyed and the reader is looking at something that plainly stopped. The bar whose length never changes while its boundary climbs is what reconciles the two.',
      'A passage is about damping, or about a motion that dies away, and a picture is wanted in which the dying away and the account of the missing energy are the same event.',
      'The claim is that the heat appears where the rubbing happened rather than somewhere in general, and a case is wanted where the settled shape can be read as a map of the rubbing.',
    ],

    avoidWhen: [
      'The article compares two routes between the same points and asks which loses more. Only one body and one route are on screen here.',
      'The question is how the loss adds up with distance covered, or how a work done by friction is to be calculated. What is drawn here is the destination of the loss, not its accounting.',
      'The point is how the mechanical total divides between motion and store. The bar here has only two parts, and the mechanical share is left undivided on purpose.',
      'Heat flowing away, temperature evening out, or anything cooling down is the theme. The piled heat here never spreads and never fades while the body is moving.',
      'The subject is the period of an oscillation, or how a mass on a spring keeps time. The swings here are drawn to run down, not to be timed.',
      'Values are wanted — a coefficient, an energy in joules, a temperature. Nothing numeric is written.',
    ],

    contrastWith: [
      {
        concept: 'non-conservative-force',
        note: 'One asks what became of the energy friction took and answers by showing where it settled; the other asks how much is taken and finds it decided by the length of the route.',
      },
      {
        concept: 'conservation-of-mechanical-energy',
        note: 'One is the case where the mechanical total falls away to nothing while a wider total stays whole; the other is the case where the mechanical total alone already holds.',
      },
      {
        concept: 'kinetic-friction',
        note: 'One follows the energy that friction removes; the other is about the force itself and what its size depends on.',
      },
      {
        concept: 'terminal-velocity',
        note: 'Both are about a resisting force settling a motion, but one follows the energy account until nothing mechanical is left, while the other watches a speed stop changing.',
      },
      {
        concept: 'conservative-force',
        note: 'One is a loss that is never returned and can be pointed at afterwards; the other is work borrowed and given back, leaving nothing behind at all.',
      },
    ],
  },
};
