/**
 * 자동 생성 파일 — 직접 편집하지 말 것.
 *
 * 생성: pnpm catalog:gen  (scripts/gen-aperi21-catalog.mts)
 * 출처: 각 sim 의 schema(label/description — description 의 원본은 topics.yaml desc) + docs/topics/topics.yaml(분야).
 */

import type { Aperi21Catalog } from '../catalog-types.js';

export const CATALOG: Aperi21Catalog = {
  locale: "ar",
  domains: [
    {"id":"kinematics","name":"علم الحركة"},
    {"id":"newtonian-mechanics","name":"الميكانيكا النيوتونية"},
    {"id":"energy-momentum","name":"الشغل والطاقة وكمية الحركة"},
    {"id":"rotation-oscillation","name":"الدوران والاهتزاز"},
    {"id":"gravitation","name":"الجاذبية وعلم الفلك"},
    {"id":"fluids","name":"الموائع"},
    {"id":"thermodynamics","name":"الفيزياء الحرارية والإحصائية"},
    {"id":"waves-acoustics","name":"الموجات والصوتيات"},
    {"id":"optics","name":"البصريات"},
    {"id":"electromagnetism","name":"الكهرومغناطيسية"},
    {"id":"modern-physics","name":"الفيزياء الحديثة"},
  ],
  entries: [
    {"id":"aperi21:reference-frame","title":"الإطار المرجعي","description":"كيف يتوقف وصف الحركة على الراصد","domain":"kinematics"},
    {"id":"aperi21:coordinate-choice","title":"اختيار المحاور","description":"كيف يغيّر اختيار المحاور المعادلات","domain":"kinematics"},
    {"id":"aperi21:average-velocity","title":"السرعة المتوسطة","description":"سرعة واحدة تمثّل فترة كاملة","domain":"kinematics"},
    {"id":"aperi21:average-acceleration","title":"التسارع المتوسط","description":"معدل تغيّر السرعة خلال فترة، الذي تحدده سرعتا بدايتها ونهايتها فقط","domain":"kinematics"},
    {"id":"aperi21:direction-of-acceleration","title":"اتجاه التسارع","description":"إذا اتجه مع السرعة أسرع الجسم، وإذا عاكسها تباطأ","domain":"kinematics"},
    {"id":"aperi21:uniform-motion","title":"الحركة المنتظمة","description":"حركة لا تتغير سرعتها المتجهة","domain":"kinematics"},
    {"id":"aperi21:uniformly-accelerated-motion","title":"الحركة بتسارع منتظم","description":"حركة تزداد فيها المسافة المقطوعة في كل فترة متساوية بمقدار ثابت","domain":"kinematics"},
    {"id":"aperi21:position-time-graph","title":"التمثيل البياني للموضع والزمن","description":"تمثيل يكون ميله هو السرعة المتجهة","domain":"kinematics"},
    {"id":"aperi21:velocity-time-graph","title":"التمثيل البياني للسرعة والزمن","description":"تمثيل تُقرأ فيه المساحة تحت المنحنى على أنها المسافة المقطوعة","domain":"kinematics"},
    {"id":"aperi21:acceleration-time-graph","title":"التمثيل البياني للتسارع والزمن","description":"المساحة تحت المنحنى هي التغير في السرعة","domain":"kinematics"},
    {"id":"aperi21:free-fall","title":"السقوط الحر","description":"حركة تحت الجاذبية وحدها يسقط فيها الثقيل والخفيف جنبًا إلى جنب","domain":"kinematics"},
    {"id":"aperi21:vertical-throw","title":"القذف الرأسي","description":"تماثل الصعود والهبوط","domain":"kinematics"},
    {"id":"aperi21:gravitational-acceleration","title":"تسارع الجاذبية","description":"تسارع لا يتوقف حتى حين تكون السرعة صفرًا","domain":"kinematics"},
    {"id":"aperi21:terminal-velocity","title":"السرعة الحدية","description":"السرعة التي تتوازن عندها قوة السحب مع الجاذبية","domain":"kinematics"},
    {"id":"aperi21:vector-decomposition","title":"مركّبات المتجه","description":"تجزئة متجه واحد على امتداد المحاور","domain":"kinematics"},
    {"id":"aperi21:vector-addition","title":"جمع المتجهات","description":"جمع يصل ذيل المتجه برأس الآخر","domain":"kinematics"},
    {"id":"aperi21:relative-velocity","title":"السرعة النسبية","description":"تحويل السرعة المتجهة بين الأطر المرجعية","domain":"kinematics"},
    {"id":"aperi21:river-crossing","title":"عبور النهر","description":"المسار الناتج عن تركيب سرعتين متجهتين","domain":"kinematics"},
    {"id":"aperi21:projectile-motion","title":"حركة المقذوفات","description":"استقلال المركبتين الأفقية والرأسية","domain":"kinematics"},
    {"id":"aperi21:projectile-range","title":"المدى وزاوية الإطلاق","description":"كيف تغيّر زاوية الإطلاق المسافة التي يقطعها","domain":"kinematics"},
    {"id":"aperi21:trajectory-equation","title":"معادلة المسار","description":"العلاقة بين المسافة الأفقية والارتفاع التي تبقى بعد إزالة الزمن","domain":"kinematics"},
    {"id":"aperi21:uniform-circular-motion","title":"الحركة الدائرية المنتظمة","description":"مسار دائري بسرعة ثابتة المقدار","domain":"kinematics"},
    {"id":"aperi21:centripetal-acceleration","title":"التسارع المركزي","description":"الاتجاه الذي يشير إليه تغيّر السرعة المتجهة في حركة لا يتغير مقدار سرعتها","domain":"kinematics"},
    {"id":"aperi21:angular-acceleration","title":"التسارع الزاوي","description":"معدل تغيّر السرعة الزاوية","domain":"kinematics"},
    {"id":"aperi21:tangential-normal-acceleration","title":"التسارع المماسي والتسارع العمودي","description":"فصل تغيّر مقدار السرعة عن تغيّر الاتجاه","domain":"kinematics"},
    {"id":"aperi21:radius-of-curvature","title":"نصف قطر الانحناء","description":"الدائرة التي يشبهها المنحنى موضعيًا","domain":"kinematics"},
    {"id":"aperi21:stopping-distance","title":"مسافة التوقف","description":"مجموع مسافة رد الفعل ومسافة الكبح","domain":"kinematics"},
    {"id":"aperi21:newtons-first-law","title":"قانون نيوتن الأول","description":"حالة الحركة عند غياب القوة المحصلة","domain":"newtonian-mechanics"},
    {"id":"aperi21:newtons-second-law","title":"قانون نيوتن الثاني","description":"محصلة القوى والكتلة والتسارع","domain":"newtonian-mechanics"},
    {"id":"aperi21:newtons-third-law","title":"الفعل ورد الفعل","description":"زوج قوى يؤثر في جسمين مختلفين","domain":"newtonian-mechanics"},
    {"id":"aperi21:net-force","title":"محصلة القوى","description":"المجموع المتجهي لعدة قوى","domain":"newtonian-mechanics"},
    {"id":"aperi21:free-body-diagram","title":"مخطط الجسم الحر","description":"عزل القوى المؤثرة في جسم واحد","domain":"newtonian-mechanics"},
    {"id":"aperi21:inertial-vs-gravitational-mass","title":"الكتلة القصورية والكتلة الثقالية","description":"تعريفان مختلفان يعطيان القيمة نفسها","domain":"newtonian-mechanics"},
    {"id":"aperi21:normal-force","title":"القوة العمودية","description":"الدفع العمودي لسطح التلامس","domain":"newtonian-mechanics"},
    {"id":"aperi21:apparent-weight","title":"الوزن الظاهري","description":"ميزان في مصعد متسارع","domain":"newtonian-mechanics"},
    {"id":"aperi21:static-friction","title":"الاحتكاك السكوني","description":"القوة التي تصمد حتى يتحرك الجسم","domain":"newtonian-mechanics"},
    {"id":"aperi21:kinetic-friction","title":"الاحتكاك الحركي","description":"الاحتكاك أثناء الانزلاق","domain":"newtonian-mechanics"},
    {"id":"aperi21:angle-of-friction","title":"زاوية الاحتكاك","description":"الميل الذي يبدأ عنده الانزلاق","domain":"newtonian-mechanics"},
    {"id":"aperi21:inclined-plane","title":"المستوى المائل","description":"تحليل الجاذبية على امتداد المنحدر وعموديًا عليه","domain":"newtonian-mechanics"},
    {"id":"aperi21:tension","title":"قوة الشد","description":"كيف ينقل الحبل قوة السحب","domain":"newtonian-mechanics"},
    {"id":"aperi21:pulley-system","title":"البكرات","description":"أداة كلما زادت فيها فروع الحبل قلّت قوة الشد وطال الحبل المسحوب","domain":"newtonian-mechanics"},
    {"id":"aperi21:connected-bodies","title":"أجسام متصلة","description":"تسارع أجسام تتحرك معًا","domain":"newtonian-mechanics"},
    {"id":"aperi21:spring-force","title":"قوة النابض","description":"قوة إرجاع تتناسب مع الاستطالة","domain":"newtonian-mechanics"},
    {"id":"aperi21:centripetal-force","title":"القوة المركزية","description":"القوة المتجهة إلى الداخل التي تُبقي الحركة دائرية، والمسار حين تزول","domain":"newtonian-mechanics"},
    {"id":"aperi21:conical-pendulum","title":"البندول المخروطي","description":"حركة دائرية من قوة الشد والجاذبية","domain":"newtonian-mechanics"},
    {"id":"aperi21:banked-curve","title":"المنعطف المائل","description":"زاوية الميل التي تُدير السيارة دون احتكاك","domain":"newtonian-mechanics"},
    {"id":"aperi21:vertical-loop","title":"الحلقة الرأسية","description":"النقطة التي يترك عندها الجسم القضيب حين تكون سرعته غير كافية للدوران في الحلقة","domain":"newtonian-mechanics"},
    {"id":"aperi21:drag-force","title":"مقاومة الهواء","description":"مقاومة تتناسب مع السرعة ومع مربعها","domain":"newtonian-mechanics"},
    {"id":"aperi21:buoyant-force-as-force","title":"قوة الطفو بوصفها قوة","description":"دفع المائع إلى الأعلى","domain":"newtonian-mechanics"},
    {"id":"aperi21:non-inertial-frame","title":"الإطار المرجعي غير القصوري","description":"الحركة كما تُرى من إطار مرجعي متسارع","domain":"newtonian-mechanics"},
    {"id":"aperi21:fictitious-force","title":"القوة الوهمية","description":"القوة الظاهرية في إطار مرجعي غير قصوري","domain":"newtonian-mechanics"},
    {"id":"aperi21:coriolis-effect","title":"تأثير كوريوليس","description":"مسار ينحني في إطار مرجعي دوّار","domain":"newtonian-mechanics"},
    {"id":"aperi21:impulse-force-relation","title":"القوة والدفع","description":"قوة قصيرة كبيرة وأخرى طويلة صغيرة","domain":"newtonian-mechanics"},
    {"id":"aperi21:equilibrium-of-forces","title":"اتزان القوى","description":"محصلة القوى صفر","domain":"newtonian-mechanics"},
    {"id":"aperi21:atwood-machine","title":"آلة أتوود","description":"نظام من ثقلين موصولين عبر بكرة","domain":"newtonian-mechanics"},
    {"id":"aperi21:balance-scale","title":"موازنة الميزان","description":"توازن يحدده طول الذراع والوزن معًا","domain":"newtonian-mechanics"},
    {"id":"aperi21:mechanical-advantage","title":"الفائدة الآلية","description":"كيف تقايض الروافع والأسطح المائلة قوةً أصغر بمسافةٍ أطول","domain":"newtonian-mechanics"},
    {"id":"aperi21:youngs-modulus","title":"معامل يونغ","description":"صلابة تخص المادة لا خيطًا بعينه","domain":"newtonian-mechanics"},
    {"id":"aperi21:stress-strain-curve","title":"منحنى الإجهاد–الانفعال","description":"كيف تستجيب المادة عند شدّها","domain":"newtonian-mechanics"},
    {"id":"aperi21:work-by-variable-force","title":"الشغل الذي تبذله قوة متغيرة","description":"المساحة تحت منحنى القوة–الإزاحة","domain":"energy-momentum"},
    {"id":"aperi21:kinetic-energy","title":"الطاقة الحركية","description":"الطاقة التي تحملها السرعة","domain":"energy-momentum"},
    {"id":"aperi21:work-energy-theorem","title":"مبرهنة الشغل والطاقة","description":"مهما قُسِّمت القوة والمسافة، يعطي الشغل نفسه السرعة النهائية نفسها","domain":"energy-momentum"},
    {"id":"aperi21:gravitational-potential-energy","title":"طاقة الوضع الجاذبية","description":"طاقة مخزّنة في الارتفاع","domain":"energy-momentum"},
    {"id":"aperi21:elastic-potential-energy","title":"طاقة الوضع المرونية","description":"الطاقة المخزّنة في التشوّه","domain":"energy-momentum"},
    {"id":"aperi21:conservative-force","title":"القوة المحافظة","description":"قوة تبذل الشغل نفسه أيًّا كان المسار","domain":"energy-momentum"},
    {"id":"aperi21:non-conservative-force","title":"القوة غير المحافظة","description":"شغل يعتمد على المسار","domain":"energy-momentum"},
    {"id":"aperi21:conservation-of-mechanical-energy","title":"حفظ الطاقة الميكانيكية","description":"الحصة المختزنة في الموضع والحصة المختزنة في الحركة تتبادلان المكان بينما يبقى مجموعهما ثابتًا","domain":"energy-momentum"},
    {"id":"aperi21:energy-dissipation","title":"تبدّد الطاقة","description":"الحصة التي يأخذها الاحتكاك، وإلى أين تذهب","domain":"energy-momentum"},
    {"id":"aperi21:potential-energy-curve","title":"منحنى طاقة الوضع","description":"كيف يحدد شكل المنحنى الحركة","domain":"energy-momentum"},
    {"id":"aperi21:equilibrium-points","title":"نقاط الاتزان","description":"الاتزان المستقر وغير المستقر والمحايد","domain":"energy-momentum"},
    {"id":"aperi21:efficiency","title":"الكفاءة","description":"الحصة مما يدخل التي تخرج ناتجًا مفيدًا","domain":"energy-momentum"},
    {"id":"aperi21:impulse-momentum-theorem","title":"مبرهنة الدفع والزخم","description":"الدفع يساوي التغير في الزخم","domain":"energy-momentum"},
    {"id":"aperi21:conservation-of-momentum","title":"حفظ الزخم","description":"الزخم الكلي عندما لا تؤثر أي قوة خارجية","domain":"energy-momentum"},
    {"id":"aperi21:elastic-collision","title":"التصادم المرن","description":"تصادم يتبادل فيه الجسمان السرعة","domain":"energy-momentum"},
    {"id":"aperi21:inelastic-collision","title":"التصادم غير المرن","description":"تصادم تضيع فيه حصة لا تُستعاد","domain":"energy-momentum"},
    {"id":"aperi21:perfectly-inelastic-collision","title":"التصادم غير المرن تمامًا","description":"عندما يلتصق الجسمان ويتحركان معًا","domain":"energy-momentum"},
    {"id":"aperi21:two-dimensional-collision","title":"التصادم في بُعدين","description":"حفظ يتحقق لكل مركّبة على حدة","domain":"energy-momentum"},
    {"id":"aperi21:center-of-mass-motion","title":"حركة مركز الكتلة","description":"الحركة التي لا تستطيع القوى الداخلية تغييرها","domain":"energy-momentum"},
    {"id":"aperi21:explosion-and-recoil","title":"الانفجار والارتداد","description":"عندما ينقسم نظام ساكن","domain":"energy-momentum"},
    {"id":"aperi21:rocket-equation","title":"معادلة الصاروخ","description":"سرعة تُكتسب بقذف الوقود","domain":"energy-momentum"},
    {"id":"aperi21:ballistic-pendulum","title":"البندول القذفي","description":"القياس الذي يربط التصادم بحفظ الطاقة","domain":"energy-momentum"},
    {"id":"aperi21:energy-in-collision","title":"الطاقة في التصادمات","description":"التمييز بين ما يُحفَظ وما لا يُحفَظ","domain":"energy-momentum"},
    {"id":"aperi21:energy-flow-diagram","title":"مخطط تدفق الطاقة","description":"إلى أين تذهب الطاقة، مبيَّنًا بسُمك الفروع","domain":"energy-momentum"},
    {"id":"aperi21:torque","title":"عزم الدوران","description":"ما يجعل الأشياء تدور، وطول ذراع القوة","domain":"rotation-oscillation"},
    {"id":"aperi21:moment-of-inertia","title":"عزم القصور الذاتي","description":"كيف يحدد توزيع الكتلة مقاومة الدوران","domain":"rotation-oscillation"},
    {"id":"aperi21:parallel-axis-theorem","title":"مبرهنة المحاور المتوازية","description":"عزم القصور الذاتي عند إزاحة المحور","domain":"rotation-oscillation"},
    {"id":"aperi21:rotational-kinetic-energy","title":"الطاقة الحركية الدورانية","description":"الطاقة التي يحملها الدوران","domain":"rotation-oscillation"},
    {"id":"aperi21:angular-momentum","title":"الزخم الزاوي","description":"الكمية التي تجعل الجسم الدوّار يحافظ على محوره","domain":"rotation-oscillation"},
    {"id":"aperi21:conservation-of-angular-momentum","title":"حفظ الزخم الزاوي","description":"لماذا يزداد دورانك سرعةً حين تضم ذراعيك","domain":"rotation-oscillation"},
    {"id":"aperi21:rolling-without-slipping","title":"التدحرج دون انزلاق","description":"القيد الذي يربط الانتقال بالدوران","domain":"rotation-oscillation"},
    {"id":"aperi21:rolling-race","title":"سباق الأجسام المتدحرجة","description":"ترتيب الوصول يحدده توزيع الكتلة","domain":"rotation-oscillation"},
    {"id":"aperi21:static-equilibrium","title":"الاتزان السكوني","description":"محصلة القوى ومحصلة العزوم كلتاهما صفر","domain":"rotation-oscillation"},
    {"id":"aperi21:center-of-gravity","title":"مركز الثقل","description":"النقطة التي تحدد متى تنقلب الأشياء","domain":"rotation-oscillation"},
    {"id":"aperi21:gyroscopic-precession","title":"المبادرة الجيروسكوبية","description":"عزم الدوران يُدير اتجاه الزخم الزاوي","domain":"rotation-oscillation"},
    {"id":"aperi21:angular-momentum-vector","title":"اتجاه الزخم الزاوي","description":"قاعدة اليد اليمنى ومحور الدوران","domain":"rotation-oscillation"},
    {"id":"aperi21:simple-harmonic-motion","title":"الحركة التوافقية البسيطة","description":"الحركة تحت قوة إرجاع تتناسب مع الإزاحة","domain":"rotation-oscillation"},
    {"id":"aperi21:shm-energy","title":"الطاقة في الحركة التوافقية البسيطة","description":"تتبادل الطاقة الحركية وطاقة الوضع","domain":"rotation-oscillation"},
    {"id":"aperi21:mass-spring-system","title":"كتلة معلّقة بنابض","description":"الدور الذي تحدده الكتلة وثابت النابض","domain":"rotation-oscillation"},
    {"id":"aperi21:simple-pendulum","title":"البندول البسيط","description":"الدور عند سعة صغيرة","domain":"rotation-oscillation"},
    {"id":"aperi21:physical-pendulum","title":"البندول الفيزيائي","description":"تذبذب جسم ممتد","domain":"rotation-oscillation"},
    {"id":"aperi21:pendulum-amplitude-dependence","title":"السعة والدور","description":"تساوي الأزمنة الذي ينهار عند السعات الكبيرة","domain":"rotation-oscillation"},
    {"id":"aperi21:damped-oscillation","title":"التذبذب المُخمَّد","description":"تذبذب يفقد الطاقة","domain":"rotation-oscillation"},
    {"id":"aperi21:damping-regimes","title":"ثلاثة أنظمة للتخميد","description":"الحركة المخمَّدة تخميدًا ناقصًا وحرجًا ومفرطًا","domain":"rotation-oscillation"},
    {"id":"aperi21:driven-oscillation","title":"التذبذب القسري","description":"الاستجابة لقوة دافعة خارجية","domain":"rotation-oscillation"},
    {"id":"aperi21:resonance","title":"الرنين","description":"عندما يطابق تردد التشغيل التردد الطبيعي","domain":"rotation-oscillation"},
    {"id":"aperi21:quality-factor","title":"معامل الجودة","description":"كلما كان الرنين أحدّ طال الاهتزاز","domain":"rotation-oscillation"},
    {"id":"aperi21:coupled-oscillators","title":"المتذبذبات المقترنة","description":"متذبذبان يتبادلان الطاقة","domain":"rotation-oscillation"},
    {"id":"aperi21:normal-modes","title":"الأنماط العادية","description":"الأشكال الطبيعية التي يهتز بها النظام","domain":"rotation-oscillation"},
    {"id":"aperi21:beats-in-oscillation","title":"الضربات في التذبذب","description":"مجموع ترددين متقاربين","domain":"rotation-oscillation"},
    {"id":"aperi21:phase-space","title":"فضاء الطور","description":"الحركة كما تُرى على مستوى الموضع–السرعة","domain":"rotation-oscillation"},
    {"id":"aperi21:nonlinear-oscillation","title":"التذبذب غير الخطي","description":"عندما تكفّ قوة الإرجاع عن التناسب","domain":"rotation-oscillation"},
    {"id":"aperi21:gears","title":"التروس","description":"كيف يقايض عدد الأسنان سرعة الدوران بعزم الدوران","domain":"rotation-oscillation"},
    {"id":"aperi21:newtons-law-of-gravitation","title":"قانون نيوتن للجذب العام","description":"قوة تضعف مع مربع المسافة","domain":"gravitation"},
    {"id":"aperi21:gravitational-field","title":"مجال الجاذبية","description":"شدة الجاذبية الموزعة في الفضاء","domain":"gravitation"},
    {"id":"aperi21:range-and-surface-gravity","title":"الجاذبية والمدى","description":"كيف يبلغ الإطلاق نفسه مدى أبعد حيث تكون الجاذبية أضعف","domain":"gravitation"},
    {"id":"aperi21:shell-theorem","title":"مبرهنة القشرة","description":"الجاذبية داخل قشرة كروية وخارجها","domain":"gravitation"},
    {"id":"aperi21:gravity-inside-earth","title":"الجاذبية داخل الأرض","description":"جاذبية تضعف مع العمق","domain":"gravitation"},
    {"id":"aperi21:gravitational-potential-energy-general","title":"طاقة الوضع الجاذبية (الحالة العامة)","description":"طاقة سالبة تُقاس من اللانهاية","domain":"gravitation"},
    {"id":"aperi21:escape-velocity","title":"سرعة الإفلات","description":"أقل سرعة تتحرر من الجاذبية","domain":"gravitation"},
    {"id":"aperi21:orbital-velocity","title":"السرعة المدارية","description":"السرعة التي تُبقي المدار دائريًا","domain":"gravitation"},
    {"id":"aperi21:circular-orbit","title":"المدار الدائري","description":"حركة تكون فيها الجاذبية هي القوة المركزية","domain":"gravitation"},
    {"id":"aperi21:elliptical-orbit","title":"المدار الإهليلجي","description":"الجرم المركزي يقع في إحدى البؤرتين","domain":"gravitation"},
    {"id":"aperi21:keplers-first-law","title":"قانون كبلر الأول","description":"مدارات إهليلجية تقع الشمس في إحدى بؤرتيها","domain":"gravitation"},
    {"id":"aperi21:keplers-second-law","title":"قانون كبلر الثاني","description":"مساحات متساوية في أزمنة متساوية","domain":"gravitation"},
    {"id":"aperi21:keplers-third-law","title":"قانون كبلر الثالث","description":"زمن الدورة الواحدة الذي يطول أسرع بكثير من نصف القطر","domain":"gravitation"},
    {"id":"aperi21:two-body-problem","title":"مسألة الجسمين","description":"جرمان يدوران حول مركز كتلتهما المشترك","domain":"gravitation"},
    {"id":"aperi21:tidal-force","title":"قوة المد","description":"تمدّد يصنعه فرق في الجاذبية","domain":"gravitation"},
    {"id":"aperi21:roche-limit","title":"حد روش","description":"المسافة التي تمزّق عندها قوى المد جرمًا سماويًا","domain":"gravitation"},
    {"id":"aperi21:weightlessness","title":"انعدام الوزن","description":"الوزن الظاهري أثناء السقوط الحر","domain":"gravitation"},
    {"id":"aperi21:geostationary-orbit","title":"المدار الثابت بالنسبة للأرض","description":"مدار فوق خط الاستواء دوره مساوٍ لدوران الأرض","domain":"gravitation"},
    {"id":"aperi21:gravitational-slingshot","title":"المساعدة بالجاذبية","description":"تغيير السرعة بالمرور قرب كوكب","domain":"gravitation"},
    {"id":"aperi21:lagrange-points","title":"نقاط لاغرانج","description":"خمسة مواضع تُجاري جرمين يدوران معًا","domain":"gravitation"},
    {"id":"aperi21:orbital-transfer","title":"الانتقال المداري","description":"انتقال هوهمان من مدار منخفض إلى مدار أعلى","domain":"gravitation"},
    {"id":"aperi21:black-hole-horizon","title":"أفق الحدث","description":"نصف القطر الذي تبلغ عنده سرعة الإفلات سرعة الضوء","domain":"gravitation"},
    {"id":"aperi21:diurnal-motion","title":"الحركة اليومية الظاهرية","description":"المسار الذي تدور فيه السماء الليلية كلها حول نقطة واحدة في يوم","domain":"gravitation"},
    {"id":"aperi21:earth-rotation-day-night","title":"دوران الأرض والليل والنهار","description":"لماذا يتعاقب الليل والنهار على أرض تدور","domain":"gravitation"},
    {"id":"aperi21:earth-revolution-constellations","title":"مدار الأرض والكوكبات","description":"لماذا تتغير الكوكبات التي نراها مع الفصول","domain":"gravitation"},
    {"id":"aperi21:solar-altitude-shadow","title":"ارتفاع الشمس والظلال","description":"حين يتغير الارتفاع يتغير طول الظل والمساحة التي ينتشر عليها ضوء الشمس معًا","domain":"gravitation"},
    {"id":"aperi21:seasonal-sun-path","title":"مسار الشمس عبر الفصول","description":"كيف يتغير ارتفاع الشمس عند الظهر وطول النهار معًا","domain":"gravitation"},
    {"id":"aperi21:axial-tilt-seasons","title":"ميل محور الدوران والفصول","description":"الفصول التي تصنعها أرضٌ تدور مائلة","domain":"gravitation"},
    {"id":"aperi21:moon-phases","title":"أطوار القمر","description":"أيُّ جزء من القمر المضاء بالشمس يواجهنا","domain":"gravitation"},
    {"id":"aperi21:eclipse","title":"الكسوف والخسوف","description":"عندما تصطف الشمس والأرض والقمر","domain":"gravitation"},
    {"id":"aperi21:stellar-parallax","title":"اختلاف المنظر النجمي","description":"الزاوية التي ينزاح بها نجم قريب بينما تدور الأرض حول الشمس","domain":"gravitation"},
    {"id":"aperi21:apparent-brightness","title":"السطوع الظاهري","description":"كيف يبدو النجم نفسه أكثر سطوعًا أو خفوتًا بحسب بعده","domain":"gravitation"},
    {"id":"aperi21:magnitude-scale","title":"القدر النجمي","description":"كيف يُعبَّر عن السطوع بالقدر","domain":"gravitation"},
    {"id":"aperi21:star-color-temperature","title":"لون النجم ودرجة حرارة سطحه","description":"كيف تحدّد درجة حرارة السطح لون ضوء النجم","domain":"gravitation"},
    {"id":"aperi21:expanding-universe","title":"تمدد الكون","description":"مجرات تبتعد في كل الاتجاهات","domain":"gravitation"},
    {"id":"aperi21:stellar-luminosity","title":"الضياء","description":"مقدار الضوء الذي يطلقه النجم فعلًا","domain":"gravitation"},
    {"id":"aperi21:hr-diagram","title":"مخطط HR","description":"مخطط درجة الحرارة والضياء لعنقود نجمي، تغادر فيه أثقل النجوم النسق الأساسي أولًا مع تقدّم عمره","domain":"gravitation"},
    {"id":"aperi21:star-radiation-gravity-balance","title":"توازن الضغط والجاذبية","description":"لماذا لا ينهار النجم ولا يتناثر","domain":"gravitation"},
    {"id":"aperi21:orbital-decay","title":"اضمحلال المدار","description":"مدار يعيقه هواء رقيق","domain":"gravitation"},
    {"id":"aperi21:inverse-square-law","title":"قانون التربيع العكسي","description":"يخفّ كلما انتشر","domain":"gravitation"},
    {"id":"aperi21:stellar-nucleosynthesis","title":"التخليق النووي النجمي","description":"اندماج نووي في لبّ النجم يبني عناصر أثقل خطوةً خطوة حتى الحديد","domain":"gravitation"},
    {"id":"aperi21:star-life-cycle","title":"دورة حياة النجم","description":"كيف تحدد الكتلة مسار النجم","domain":"gravitation"},
    {"id":"aperi21:stellar-spectral-class","title":"الأصناف الطيفية للنجوم","description":"أنماط خطوط الامتصاص التي تحددها درجة الحرارة","domain":"gravitation"},
    {"id":"aperi21:supernova-and-neutron-star","title":"المستعر الأعظم والنجم النيوتروني","description":"انهيار أخير وارتداد","domain":"gravitation"},
    {"id":"aperi21:exoplanet-detection","title":"رصد الكواكب الخارجية","description":"الآثار التي يتركها الكوكب","domain":"gravitation"},
    {"id":"aperi21:projectile-in-wind","title":"الرياح والمدى","description":"كيف تُزيح الريح نقطة الهبوط للإطلاق نفسه","domain":"fluids"},
    {"id":"aperi21:pressure-isotropy","title":"تساوي الضغط في جميع الاتجاهات","description":"المقدار نفسه أيًّا كان الاتجاه","domain":"fluids"},
    {"id":"aperi21:hydrostatic-pressure","title":"الضغط الهيدروستاتيكي","description":"ضغط يزداد مع العمق","domain":"fluids"},
    {"id":"aperi21:pressure-and-container-shape","title":"شكل الوعاء والضغط عند القاعدة","description":"كيف لا يعتمد الضغط على القاع على الشكل","domain":"fluids"},
    {"id":"aperi21:atmospheric-pressure","title":"الضغط الجوي","description":"وزن عمود الهواء","domain":"fluids"},
    {"id":"aperi21:barometer","title":"البارومتر","description":"ارتفاع عمود الزئبق","domain":"fluids"},
    {"id":"aperi21:manometer","title":"المانومتر","description":"قراءة الضغط من عمود سائل","domain":"fluids"},
    {"id":"aperi21:pascals-principle","title":"مبدأ باسكال","description":"انتقال الضغط والمكبس الهيدروليكي","domain":"fluids"},
    {"id":"aperi21:buoyancy","title":"قوة الطفو","description":"القوة المتجهة إلى الأعلى التي تبقى لأن الوجه السفلي يُدفع بقوة أكبر","domain":"fluids"},
    {"id":"aperi21:archimedes-principle","title":"مبدأ أرخميدس — مقدار قوة الطفو","description":"القوة المؤثرة تساوي وزن المائع المُزاح","domain":"fluids"},
    {"id":"aperi21:floating-and-draft","title":"إلى أي عمق يغوص الجسم الطافي","description":"ما الذي يحدد الحجم المغمور","domain":"fluids"},
    {"id":"aperi21:stability-of-floating-body","title":"استقرار الجسم الطافي","description":"العلاقة بين مركز الثقل ومركز الطفو","domain":"fluids"},
    {"id":"aperi21:continuity-equation","title":"معادلة الاستمرارية","description":"مساحة المقطع وسرعة التدفق تتبادلان","domain":"fluids"},
    {"id":"aperi21:bernoullis-principle","title":"مبدأ برنولي","description":"التبادل بين السرعة والضغط","domain":"fluids"},
    {"id":"aperi21:venturi-effect","title":"تأثير فنتوري","description":"ضغط أقل حيث يضيق الأنبوب","domain":"fluids"},
    {"id":"aperi21:torricellis-law","title":"قانون تورشيلي","description":"سرعة التدفق الخارج من ثقب","domain":"fluids"},
    {"id":"aperi21:lift-force","title":"قوة الرفع","description":"كيف يتدفق الهواء فوق الجناح وتحته","domain":"fluids"},
    {"id":"aperi21:viscosity","title":"اللزوجة","description":"الاحتكاك بين الطبقات","domain":"fluids"},
    {"id":"aperi21:poiseuille-flow","title":"الجريان الطبقي في أنبوب","description":"يزداد معدل التدفق مع القوة الرابعة لنصف القطر","domain":"fluids"},
    {"id":"aperi21:stokes-drag","title":"قوة سحب ستوكس","description":"في التدفق البطيء تغوص الكرة ذات نصف القطر المضاعف أسرع بأربع مرات","domain":"fluids"},
    {"id":"aperi21:laminar-vs-turbulent","title":"الجريان الطبقي والجريان المضطرب","description":"نمطان للتدفق","domain":"fluids"},
    {"id":"aperi21:reynolds-number","title":"عدد رينولدز","description":"العدد اللابُعدي الذي يحدد طابع التدفق","domain":"fluids"},
    {"id":"aperi21:boundary-layer","title":"الطبقة الحدية","description":"الطبقة الرقيقة التي ترتفع فيها سرعة التدفق من الصفر عند الجدار إلى سرعة التدفق الخارجي","domain":"fluids"},
    {"id":"aperi21:surface-tension","title":"التوتر السطحي","description":"شدّ سطح الماء الذي يغيّر اتجاهه ليحمل ثقلًا","domain":"fluids"},
    {"id":"aperi21:laplace-pressure","title":"ضغط لابلاس","description":"قفزة الضغط التي يُحدثها سطح منحنٍ","domain":"fluids"},
    {"id":"aperi21:capillary-action","title":"الخاصية الشعرية","description":"الصعود والهبوط في الأنابيب الضيقة","domain":"fluids"},
    {"id":"aperi21:wetting-and-contact-angle","title":"الترطيب وزاوية التماس","description":"مدى انتشار السائل على سطح صلب","domain":"fluids"},
    {"id":"aperi21:drag-in-fluid","title":"قوة السحب في المائع","description":"مقاومة في التدفق السريع يحددها شكل المؤخرة","domain":"fluids"},
    {"id":"aperi21:thermal-equilibrium","title":"الاتزان الحراري","description":"الحالة التي يبلغها نظامان متلامسان","domain":"thermodynamics"},
    {"id":"aperi21:specific-heat","title":"الحرارة النوعية","description":"مقدار تغيّر درجة الحرارة من مادة إلى أخرى","domain":"thermodynamics"},
    {"id":"aperi21:calorimetry","title":"قياس كمية الحرارة","description":"درجة الحرارة النهائية للمزيج","domain":"thermodynamics"},
    {"id":"aperi21:latent-heat","title":"الحرارة الكامنة","description":"لماذا تتوقف درجة الحرارة أثناء تغيّر الحالة","domain":"thermodynamics"},
    {"id":"aperi21:phase-diagram","title":"مخطط الأطوار","description":"الطور الذي يحدده الضغط ودرجة الحرارة","domain":"thermodynamics"},
    {"id":"aperi21:triple-point","title":"النقطة الثلاثية","description":"الشرط الذي تتعايش عنده ثلاثة أطوار","domain":"thermodynamics"},
    {"id":"aperi21:thermal-conduction","title":"التوصيل الحراري","description":"حرارة تنتشر عبر المادة، بسرعة في الفولاذ وببطء في الخشب","domain":"thermodynamics"},
    {"id":"aperi21:thermal-convection","title":"الحمل الحراري","description":"حرارة يحملها مائع متحرك","domain":"thermodynamics"},
    {"id":"aperi21:thermal-radiation","title":"الإشعاع الحراري","description":"حرارة تنتقل دون وسط","domain":"thermodynamics"},
    {"id":"aperi21:stefan-boltzmann-law","title":"قانون ستيفان–بولتزمان","description":"إشعاع يزداد مع القوة الرابعة لدرجة الحرارة","domain":"thermodynamics"},
    {"id":"aperi21:thermal-expansion","title":"التمدد الحراري","description":"تغيّر طول الجسم الصلب مع درجة الحرارة","domain":"thermodynamics"},
    {"id":"aperi21:bimetal","title":"الشريط ثنائي الفلز","description":"انحناء ناتج عن تمدد غير متساوٍ","domain":"thermodynamics"},
    {"id":"aperi21:ideal-gas-law","title":"قانون الغاز المثالي","description":"العلاقة بين الضغط والحجم ودرجة الحرارة","domain":"thermodynamics"},
    {"id":"aperi21:boyles-law","title":"قانون بويل","description":"الضغط والحجم عند ثبات درجة الحرارة","domain":"thermodynamics"},
    {"id":"aperi21:charles-law","title":"قانون شارل","description":"الحجم ودرجة الحرارة عند ضغط ثابت","domain":"thermodynamics"},
    {"id":"aperi21:gas-pressure","title":"الجزيئات والضغط","description":"كيف يجعل رفع درجة الحرارة الجزيئات تضرب الجدار بتكرار أكبر وقوة أشد فيرتفع الضغط","domain":"thermodynamics"},
    {"id":"aperi21:pressure-from-collisions","title":"الضغط الناتج عن التصادمات","description":"أقوى وأكثر تكرارًا: ضغط على الجدار يزداد مع مربع سرعة الجزيئات","domain":"thermodynamics"},
    {"id":"aperi21:maxwell-boltzmann-distribution","title":"توزيع ماكسويل–بولتزمان","description":"توزيع سرعات الجزيئات","domain":"thermodynamics"},
    {"id":"aperi21:mean-free-path","title":"متوسط المسار الحر","description":"المسافة بين التصادمات","domain":"thermodynamics"},
    {"id":"aperi21:first-law-of-thermodynamics","title":"القانون الأول للديناميكا الحرارية","description":"العلاقة بين الطاقة الداخلية والشغل والحرارة","domain":"thermodynamics"},
    {"id":"aperi21:pv-diagram","title":"مخطط PV","description":"حيث تكون المساحة شغلًا","domain":"thermodynamics"},
    {"id":"aperi21:isothermal-process","title":"العملية متساوية الحرارة","description":"تغيّر يُبقي درجة الحرارة ثابتة","domain":"thermodynamics"},
    {"id":"aperi21:adiabatic-process","title":"العملية الأديباتية","description":"تغيّر لا تدخل فيه حرارة ولا تخرج","domain":"thermodynamics"},
    {"id":"aperi21:isobaric-isochoric","title":"العمليتان متساوية الضغط ومتساوية الحجم","description":"تغيّرات عند ضغط ثابت أو حجم ثابت","domain":"thermodynamics"},
    {"id":"aperi21:cyclic-process","title":"العملية الدورية","description":"تغيّر يعود إلى حيث بدأ","domain":"thermodynamics"},
    {"id":"aperi21:second-law-of-thermodynamics","title":"القانون الثاني للديناميكا الحرارية","description":"تغيّر يسير في اتجاه واحد","domain":"thermodynamics"},
    {"id":"aperi21:irreversibility","title":"الإنتروبيا واللاانعكاسية","description":"لماذا لا يمكن التراجع عنه","domain":"thermodynamics"},
    {"id":"aperi21:heat-engine","title":"المحرك الحراري","description":"دورة لا تحوّل إلا جزءًا من الحرارة إلى شغل وتطرح الباقي إلى الجانب البارد","domain":"thermodynamics"},
    {"id":"aperi21:carnot-cycle","title":"دورة كارنو","description":"الكفاءة القصوى النظرية","domain":"thermodynamics"},
    {"id":"aperi21:refrigerator-heat-pump","title":"الثلاجات والمضخات الحرارية","description":"نقل الحرارة ببذل شغل","domain":"thermodynamics"},
    {"id":"aperi21:brownian-motion","title":"الحركة البراونية","description":"حركة عشوائية تُحدثها التصادمات الجزيئية","domain":"thermodynamics"},
    {"id":"aperi21:diffusion","title":"الانتشار","description":"تدفّق يحرّكه فرق في التركيز","domain":"thermodynamics"},
    {"id":"aperi21:random-walk","title":"المشي العشوائي","description":"الانتشار عن نقطة البداية الذي لا يزداد إلا بالجذر التربيعي لعدد الخطوات","domain":"thermodynamics"},
    {"id":"aperi21:statistical-fluctuation","title":"التقلّب الإحصائي","description":"التذبذب الذي يكبر حين تقلّ الجسيمات","domain":"thermodynamics"},
    {"id":"aperi21:maxwells-demon","title":"شيطان ماكسويل","description":"غاز ينفصل بقدر ما يُراقَب","domain":"thermodynamics"},
    {"id":"aperi21:insulation","title":"العزل الحراري","description":"إبطاء انتقال الحرارة","domain":"thermodynamics"},
    {"id":"aperi21:albedo","title":"الألبيدو","description":"نسبة الضوء المُرتدّ","domain":"thermodynamics"},
    {"id":"aperi21:radiative-equilibrium","title":"الاتزان الإشعاعي","description":"درجة الحرارة التي تتحدد حين يساوي الخارجُ الداخلَ","domain":"thermodynamics"},
    {"id":"aperi21:greenhouse-effect","title":"أثر الدفيئة","description":"طبقة تعيد الأشعة تحت الحمراء إلى الأسفل فتدفّئ سطح الأرض","domain":"thermodynamics"},
    {"id":"aperi21:wave-basics","title":"الكميات الأساسية للموجة","description":"الطول الموجي والتردد والسرعة والسعة","domain":"waves-acoustics"},
    {"id":"aperi21:wave-vs-particle-transport","title":"ما تحمله الموجة","description":"الوسط يبقى في مكانه، والطاقة تمضي","domain":"waves-acoustics"},
    {"id":"aperi21:transverse-wave","title":"الموجة المستعرضة","description":"يهتز الوسط عموديًا على اتجاه انتقال الموجة","domain":"waves-acoustics"},
    {"id":"aperi21:longitudinal-wave","title":"الموجة الطولية","description":"اهتزاز موازٍ لاتجاه الانتشار","domain":"waves-acoustics"},
    {"id":"aperi21:wave-speed-in-medium","title":"سرعة الموجة والوسط","description":"السرعة التي تحددها قوة الشد والكثافة الطولية","domain":"waves-acoustics"},
    {"id":"aperi21:wavefront-and-ray","title":"جبهات الموجة والأشعة","description":"أسطح الطور المتساوي والخطوط العمودية عليها","domain":"waves-acoustics"},
    {"id":"aperi21:huygens-principle","title":"مبدأ هويغنز","description":"كل نقطة على جبهة الموجة تصبح مصدرًا جديدًا","domain":"waves-acoustics"},
    {"id":"aperi21:superposition","title":"التراكب","description":"ماذا يحدث حين تتراكب الموجات","domain":"waves-acoustics"},
    {"id":"aperi21:constructive-destructive","title":"التداخل البنّاء والتداخل الهدّام","description":"كيف يحدّد فرق الطور حجم المجموع","domain":"waves-acoustics"},
    {"id":"aperi21:interference","title":"التداخل","description":"النمط الذي يصنعه مصدران","domain":"waves-acoustics"},
    {"id":"aperi21:standing-wave","title":"الموجة الموقوفة","description":"موجة تبقى عُقدها وبطونها ثابتة","domain":"waves-acoustics"},
    {"id":"aperi21:harmonics","title":"التوافقيات","description":"ترددات تحددها الحدود","domain":"waves-acoustics"},
    {"id":"aperi21:string-vibration","title":"الوتر المهتز","description":"حدّة الصوت التي يحددها الطول المهتز","domain":"waves-acoustics"},
    {"id":"aperi21:air-column-resonance","title":"رنين عمود الهواء","description":"الأنبوب المفتوح مقابل الأنبوب المغلق","domain":"waves-acoustics"},
    {"id":"aperi21:beats","title":"الضربات","description":"مجموع ترددين متقاربين","domain":"waves-acoustics"},
    {"id":"aperi21:doppler-effect","title":"تأثير دوبلر","description":"كيف يفرّق المصدر المتحرك المسافات بين جبهات الموجة أمامه وخلفه","domain":"waves-acoustics"},
    {"id":"aperi21:doppler-source-vs-observer","title":"مصدر متحرك مقابل راصد متحرك","description":"عدم التماثل بحسب من يتحرك","domain":"waves-acoustics"},
    {"id":"aperi21:shock-wave","title":"موجة الصدمة","description":"المخروط الذي يتكوّن بعد تجاوز سرعة الصوت","domain":"waves-acoustics"},
    {"id":"aperi21:sound-intensity","title":"شدة الصوت","description":"شدة تتناقص مع مربع المسافة بينما لا ينخفض مستوى الديسيبل إلا قليلًا","domain":"waves-acoustics"},
    {"id":"aperi21:reflection-of-waves","title":"انعكاس الموجات","description":"الطور عند طرف مثبت وعند طرف حر","domain":"waves-acoustics"},
    {"id":"aperi21:refraction-of-waves","title":"انكسار الموجات","description":"تغيّر السرعة يغيّر الاتجاه","domain":"waves-acoustics"},
    {"id":"aperi21:diffraction","title":"الحيود","description":"موجات تنحني حول العوائق","domain":"waves-acoustics"},
    {"id":"aperi21:slit-width-and-diffraction","title":"عرض الشق والحيود","description":"كيف تحدّد نسبة عرض الفتحة إلى الطول الموجي مقدار الانتشار","domain":"waves-acoustics"},
    {"id":"aperi21:wave-energy","title":"طاقة الموجة","description":"تزداد الطاقة مع مربع السعة","domain":"waves-acoustics"},
    {"id":"aperi21:wave-attenuation","title":"توهين الموجة","description":"سعة تنخفض بالنسبة نفسها عبر كل مسافة متساوية","domain":"waves-acoustics"},
    {"id":"aperi21:impedance-mismatch","title":"عدم تطابق الممانعة","description":"كم ينعكس عند الحد الفاصل","domain":"waves-acoustics"},
    {"id":"aperi21:noise-cancellation","title":"إلغاء الضوضاء النشط","description":"تراكب موجة معكوسة","domain":"waves-acoustics"},
    {"id":"aperi21:sound-source-vibration","title":"الصوت والاهتزاز","description":"الجسم المُصدِر للصوت يهتز، وحين يتوقف الاهتزاز يتوقف الصوت أيضًا","domain":"waves-acoustics"},
    {"id":"aperi21:sound-through-materials","title":"انتقال الصوت عبر المواد","description":"سرعة الصوت وعبوره كما يحددهما الوسط","domain":"waves-acoustics"},
    {"id":"aperi21:digital-vs-analog-signal","title":"الإشارات الرقمية والتناظرية","description":"طريقتان لمقاومة الضجيج","domain":"waves-acoustics"},
    {"id":"aperi21:seismic-waves","title":"الموجات الزلزالية","description":"مناطق الظل التي تنشأ حين يحجب اللب الخارجي السائل موجات S ويحني موجات P","domain":"waves-acoustics"},
    {"id":"aperi21:rectilinear-propagation","title":"ينتشر الضوء في خطوط مستقيمة","description":"الظلال ونموذج الشعاع","domain":"optics"},
    {"id":"aperi21:shadow-umbra-penumbra","title":"الظل وشبه الظل","description":"كيف يشكّل حجم مصدر الضوء حافة الظل","domain":"optics"},
    {"id":"aperi21:pinhole-camera","title":"الكاميرا ذات الثقب","description":"الصورة التي يكوّنها ثقب واحد","domain":"optics"},
    {"id":"aperi21:law-of-reflection","title":"قانون الانعكاس","description":"زاوية السقوط وزاوية الانعكاس","domain":"optics"},
    {"id":"aperi21:specular-diffuse-reflection","title":"الانعكاس المنتظم والانعكاس المنتشر","description":"انعكاس تحدده خشونة السطح","domain":"optics"},
    {"id":"aperi21:plane-mirror-image","title":"الصورة في مرآة مستوية","description":"الصورة التقديرية خلف المرآة حيث يلتقي الضوء المتتبَّع إلى الخلف","domain":"optics"},
    {"id":"aperi21:multiple-mirror-images","title":"الصور في مرآتين","description":"كيف تحدد الزاوية بين مرآتين عدد الصور","domain":"optics"},
    {"id":"aperi21:concave-mirror","title":"المرآة المقعرة","description":"صورة حقيقية ما دام الجسم خارج البؤرة، ووهمية حين يدخلها","domain":"optics"},
    {"id":"aperi21:convex-mirror","title":"المرآة المحدبة","description":"مجال رؤية أوسع وصورة وهمية صغيرة معتدلة","domain":"optics"},
    {"id":"aperi21:snells-law","title":"قانون سنل","description":"كيف ينحني المسار باختلاف الوسط","domain":"optics"},
    {"id":"aperi21:apparent-depth","title":"العمق الظاهري","description":"لماذا تبدو الأشياء تحت الماء مرتفعة","domain":"optics"},
    {"id":"aperi21:total-internal-reflection","title":"الانعكاس الكلي الداخلي","description":"الزاوية الحرجة وشرطها","domain":"optics"},
    {"id":"aperi21:optical-fiber","title":"الألياف البصرية","description":"ضوء محبوس بالانعكاس الكلي الداخلي","domain":"optics"},
    {"id":"aperi21:mirage","title":"السراب","description":"ضوء ينحني بفعل تدرّج الكثافة","domain":"optics"},
    {"id":"aperi21:dispersion","title":"تفريق الضوء","description":"معامل انكسار يتوقف على الطول الموجي","domain":"optics"},
    {"id":"aperi21:prism","title":"المنشور","description":"طيف ينتشر بفعل تفريق الضوء","domain":"optics"},
    {"id":"aperi21:rainbow","title":"قوس قزح","description":"الانكسار والانعكاس داخل قطرات المطر","domain":"optics"},
    {"id":"aperi21:thin-lens","title":"العدسة الرقيقة","description":"البؤر وتكوّن الصورة","domain":"optics"},
    {"id":"aperi21:converging-diverging-lens","title":"العدسة المجمعة والعدسة المفرقة","description":"عدسة تجمع الضوء وعدسة تفرّقه","domain":"optics"},
    {"id":"aperi21:magnification","title":"التكبير","description":"حجم الصورة وحجم الجسم","domain":"optics"},
    {"id":"aperi21:focal-length","title":"البعد البؤري","description":"كيف يحدد البعد البؤري موضع تكوّن الصورة","domain":"optics"},
    {"id":"aperi21:real-vs-virtual-image","title":"الصور الحقيقية والوهمية","description":"هل يلتقي الضوء فعلًا؟","domain":"optics"},
    {"id":"aperi21:lens-combination","title":"تركيب العدسات","description":"البؤرة المركّبة لعدستين","domain":"optics"},
    {"id":"aperi21:spherical-aberration","title":"الزيغ الكروي","description":"الأشعة الطرفية تتجمع في موضع مختلف","domain":"optics"},
    {"id":"aperi21:chromatic-aberration","title":"الزيغ اللوني","description":"بؤرة مختلفة لكل طول موجي","domain":"optics"},
    {"id":"aperi21:human-eye-accommodation","title":"تكيّف العين","description":"كيف تُبئِّر عدسة العين الأشياء","domain":"optics"},
    {"id":"aperi21:myopia-hyperopia","title":"قصر النظر وطول النظر","description":"أين تتكوّن الصورة، وكيف تصحّحها النظارات","domain":"optics"},
    {"id":"aperi21:magnifying-glass","title":"العدسة المكبِّرة","description":"جسم داخل البؤرة يُرى صورةً وهميةً كبيرة معتدلة","domain":"optics"},
    {"id":"aperi21:microscope","title":"المجهر","description":"يُضرب تكبير العدسة الشيئية في تكبير العدسة العينية","domain":"optics"},
    {"id":"aperi21:telescope","title":"التلسكوب","description":"تكبير تحدده النسبة بين البعدين البؤريين","domain":"optics"},
    {"id":"aperi21:youngs-double-slit","title":"الشق المزدوج ليونغ","description":"دليل على أن الضوء موجة","domain":"optics"},
    {"id":"aperi21:single-slit-diffraction","title":"حيود الشق المفرد","description":"الشريط المضيء المركزي الذي يتسع كلما ضاق الشق","domain":"optics"},
    {"id":"aperi21:diffraction-grating","title":"محزوز الحيود","description":"قمم حادة تصنعها شقوق كثيرة","domain":"optics"},
    {"id":"aperi21:thin-film-interference","title":"تداخل الأغشية الرقيقة","description":"لون يصنعه السُّمك","domain":"optics"},
    {"id":"aperi21:newtons-rings","title":"حلقات نيوتن","description":"التداخل بين سطح منحنٍ وسطح مستوٍ","domain":"optics"},
    {"id":"aperi21:resolving-power","title":"قدرة التحليل","description":"حدّ التمييز بين نقطتين","domain":"optics"},
    {"id":"aperi21:polarization","title":"الاستقطاب","description":"انتقاء مستوى الاهتزاز","domain":"optics"},
    {"id":"aperi21:malus-law","title":"قانون مالوس","description":"الشدة عبر المستقطِب","domain":"optics"},
    {"id":"aperi21:brewster-angle","title":"زاوية بروستر","description":"الزاوية التي يصبح عندها الضوء المنعكس مستقطبًا كليًا","domain":"optics"},
    {"id":"aperi21:birefringence","title":"الانكسار المزدوج","description":"ضوء ينقسم إلى حزمتين تهتزان بزاوية قائمة فتُرى الصورة مزدوجة","domain":"optics"},
    {"id":"aperi21:scattering","title":"التشتت","description":"حجم الجسيمات الذي يفرّق بين السماء الزرقاء والغيوم البيضاء","domain":"optics"},
    {"id":"aperi21:rayleigh-scattering","title":"تشتت رايلي","description":"تشتت يزداد بحدة كلما قصر الطول الموجي","domain":"optics"},
    {"id":"aperi21:seeing-requires-light","title":"الرؤية تحتاج إلى الضوء","description":"من دون ضوء لا يمكن رؤية الجسم","domain":"optics"},
    {"id":"aperi21:color-addition","title":"جمع الضوء","description":"اللون الذي تكوّنه ثلاثة أضواء حيث تتداخل","domain":"optics"},
    {"id":"aperi21:object-color","title":"لون الجسم","description":"اللون الذي يحدده الضوء الذي يردّه الجسم","domain":"optics"},
    {"id":"aperi21:light-through-materials","title":"الضوء والمواد","description":"نفاذ الضوء يتوقف على المادة","domain":"optics"},
    {"id":"aperi21:electric-charge","title":"الشحنة الكهربائية","description":"شحنة لها نوعان فقط","domain":"electromagnetism"},
    {"id":"aperi21:charging-methods","title":"طرق الشحن","description":"الاحتكاك والتلامس والحث","domain":"electromagnetism"},
    {"id":"aperi21:coulombs-law","title":"قانون كولوم","description":"القوة بين الشحنات، تضعف بمربع عدد مرات تباعدها","domain":"electromagnetism"},
    {"id":"aperi21:superposition-of-forces","title":"تراكب القوى الكهربائية","description":"جمع القوى الناتجة عن عدة شحنات","domain":"electromagnetism"},
    {"id":"aperi21:electric-field","title":"المجال الكهربائي","description":"القوة المؤثرة في شحنة الوحدة","domain":"electromagnetism"},
    {"id":"aperi21:field-lines","title":"خطوط المجال الكهربائي","description":"اصطلاح رسم المجال ومعناه","domain":"electromagnetism"},
    {"id":"aperi21:field-of-dipole","title":"المجال الكهربائي لثنائي القطب","description":"شحنتان متعاكستان متقاربتان","domain":"electromagnetism"},
    {"id":"aperi21:uniform-field","title":"المجال الكهربائي المنتظم","description":"المجال بين لوحين متوازيين","domain":"electromagnetism"},
    {"id":"aperi21:charge-in-uniform-field","title":"شحنة في مجال منتظم","description":"تمامًا مثل المقذوف","domain":"electromagnetism"},
    {"id":"aperi21:gausss-law","title":"قانون غاوس","description":"التدفق الكهربائي عبر سطح مغلق","domain":"electromagnetism"},
    {"id":"aperi21:field-of-charged-sphere","title":"مجال كرة مشحونة","description":"لماذا يختلف الداخل عن الخارج","domain":"electromagnetism"},
    {"id":"aperi21:equipotential-surface","title":"أسطح تساوي الجهد","description":"أسطح عمودية على المجال","domain":"electromagnetism"},
    {"id":"aperi21:potential-vs-field","title":"الجهد والمجال الكهربائي","description":"علاقة الميل","domain":"electromagnetism"},
    {"id":"aperi21:electrostatic-shielding","title":"الحجب الكهروستاتيكي","description":"لماذا ينعدم المجال داخل الموصل","domain":"electromagnetism"},
    {"id":"aperi21:charge-on-conductor-surface","title":"الشحنة على سطح موصل","description":"تتكدس الشحنة عند الطرف المدبب","domain":"electromagnetism"},
    {"id":"aperi21:dielectric","title":"العازل الكهربائي","description":"الاستقطاب يُضعف المجال","domain":"electromagnetism"},
    {"id":"aperi21:parallel-plate-capacitor","title":"مكثف ذو لوحين متوازيين","description":"سعة تحددها المساحة والمسافة بين اللوحين","domain":"electromagnetism"},
    {"id":"aperi21:capacitors-in-circuit","title":"توصيل المكثفات","description":"الجمع على التوالي وعلى التوازي","domain":"electromagnetism"},
    {"id":"aperi21:energy-in-capacitor","title":"طاقة المكثف","description":"الشغل المبذول لنقل الشحنة","domain":"electromagnetism"},
    {"id":"aperi21:electric-current","title":"التيار الكهربائي","description":"تدفق الشحنة واصطلاح اتجاهه","domain":"electromagnetism"},
    {"id":"aperi21:drift-velocity","title":"سرعة الانجراف","description":"السرعة التي تزحف بها الإلكترونات داخل السلك","domain":"electromagnetism"},
    {"id":"aperi21:ohms-law","title":"قانون أوم","description":"الجهد والتيار والمقاومة","domain":"electromagnetism"},
    {"id":"aperi21:resistance-and-geometry","title":"المقاومة والشكل","description":"تأثير الطول ومساحة المقطع العرضي","domain":"electromagnetism"},
    {"id":"aperi21:temperature-and-resistance","title":"درجة الحرارة والمقاومة","description":"المعادن وأشباه الموصلات تسلك اتجاهين متعاكسين","domain":"electromagnetism"},
    {"id":"aperi21:series-parallel-resistors","title":"المقاومات على التوالي وعلى التوازي","description":"كيف يغيّر أسلوب التوصيل التيار الذي تعطيه بطارية واحدة","domain":"electromagnetism"},
    {"id":"aperi21:emf-and-internal-resistance","title":"القوة الدافعة الكهربائية والمقاومة الداخلية","description":"لماذا ينخفض الجهد الطرفي","domain":"electromagnetism"},
    {"id":"aperi21:kirchhoffs-current-law","title":"قانون كيرشوف للتيار","description":"حفظ الشحنة عند العقدة","domain":"electromagnetism"},
    {"id":"aperi21:kirchhoffs-voltage-law","title":"قانون كيرشوف للجهد","description":"حفظ الطاقة حول حلقة مغلقة","domain":"electromagnetism"},
    {"id":"aperi21:wheatstone-bridge","title":"قنطرة ويتستون","description":"قياس مقاومة بالاتزان","domain":"electromagnetism"},
    {"id":"aperi21:joule-heating","title":"التسخين بتأثير جول","description":"الحرارة التي تولّدها المقاومة","domain":"electromagnetism"},
    {"id":"aperi21:rc-circuit","title":"دائرة RC","description":"الثابت الزمني للشحن والتفريغ","domain":"electromagnetism"},
    {"id":"aperi21:magnetic-field","title":"المجال المغناطيسي","description":"كيف تتوزع القوة المغناطيسية حول المغناطيس","domain":"electromagnetism"},
    {"id":"aperi21:magnetic-field-lines","title":"خطوط المجال المغناطيسي","description":"خطوط لا تنقطع وتنغلق دائمًا","domain":"electromagnetism"},
    {"id":"aperi21:lorentz-force","title":"قوة لورنتز","description":"القوة المؤثرة في شحنة تتحرك في مجال مغناطيسي","domain":"electromagnetism"},
    {"id":"aperi21:charged-particle-in-magnetic-field","title":"شحنات تدور في مجال مغناطيسي","description":"زمن الدورة نفسه مهما اختلفت السرعة","domain":"electromagnetism"},
    {"id":"aperi21:velocity-selector","title":"مُنتقي السرعة","description":"موازنة القوتين الكهربائية والمغناطيسية","domain":"electromagnetism"},
    {"id":"aperi21:mass-spectrometer","title":"مطياف الكتلة","description":"فرز الكتل حسب نصف القطر","domain":"electromagnetism"},
    {"id":"aperi21:force-on-current-wire","title":"القوة المؤثرة في سلك يحمل تيارًا","description":"القوة المغناطيسية على سلك يمر فيه تيار","domain":"electromagnetism"},
    {"id":"aperi21:biot-savart-law","title":"قانون بيو–سافار","description":"المجال المغناطيسي لعناصر التيار","domain":"electromagnetism"},
    {"id":"aperi21:field-of-straight-wire","title":"المجال المغناطيسي الناتج عن التيار","description":"شدة تتناقص كلما زادت المسافة","domain":"electromagnetism"},
    {"id":"aperi21:field-of-loop-and-solenoid","title":"الحلقة والملف اللولبي","description":"مجال مغناطيسي تجعله الحلقات المتراصة منتظمًا وقويًا في الداخل وضعيفًا في الخارج","domain":"electromagnetism"},
    {"id":"aperi21:amperes-law","title":"قانون أمبير","description":"دوران المجال المغناطيسي حول تيار","domain":"electromagnetism"},
    {"id":"aperi21:force-between-wires","title":"القوة بين سلكين متوازيين","description":"تيّاران متوازيان يتجاذبان أو يتنافران","domain":"electromagnetism"},
    {"id":"aperi21:magnetic-dipole","title":"ثنائي القطب المغناطيسي","description":"حلقة التيار والمغناطيس شيء واحد","domain":"electromagnetism"},
    {"id":"aperi21:magnetic-materials","title":"المواد المغناطيسية","description":"الحديدية المغناطيسية والبارامغناطيسية والديامغناطيسية","domain":"electromagnetism"},
    {"id":"aperi21:faradays-law","title":"قانون فاراداي","description":"القوة الدافعة الكهربائية الناتجة عن تغيّر التدفق","domain":"electromagnetism"},
    {"id":"aperi21:lenzs-law","title":"قانون لنز","description":"تيار مستحث يعاكس التغيّر","domain":"electromagnetism"},
    {"id":"aperi21:motional-emf","title":"القوة الدافعة الكهربائية الحركية","description":"الجهد الناتج عن سلك متحرك","domain":"electromagnetism"},
    {"id":"aperi21:eddy-current","title":"التيارات الدوامية","description":"تيارات مستحثة داخل موصل مصمت","domain":"electromagnetism"},
    {"id":"aperi21:self-inductance","title":"المحاثة الذاتية","description":"ملف يُولّد جهدًا يعاكس التغيّر حين يتغيّر تياره","domain":"electromagnetism"},
    {"id":"aperi21:mutual-inductance","title":"المحاثة المتبادلة","description":"قوة دافعة كهربائية مستحثة في دائرة مجاورة","domain":"electromagnetism"},
    {"id":"aperi21:energy-in-inductor","title":"طاقة المحث","description":"الطاقة المخزنة في المجال المغناطيسي","domain":"electromagnetism"},
    {"id":"aperi21:rl-circuit","title":"دائرة RL","description":"لماذا يرتفع التيار ببطء","domain":"electromagnetism"},
    {"id":"aperi21:lc-oscillation","title":"تذبذب LC","description":"تتبادل الطاقتان الكهربائية والمغناطيسية الأدوار","domain":"electromagnetism"},
    {"id":"aperi21:ac-generation","title":"توليد التيار المتردد","description":"ملف يدور وموجة جيبية","domain":"electromagnetism"},
    {"id":"aperi21:reactance","title":"المفاعلة والممانعة","description":"كيف يعيق الملف التيار المتردد أكثر ويعيقه المكثف أقل كلما ارتفع التردد","domain":"electromagnetism"},
    {"id":"aperi21:phase-in-ac-circuit","title":"فرق الطور في دوائر التيار المتردد","description":"خروج الجهد والتيار عن التوافق","domain":"electromagnetism"},
    {"id":"aperi21:series-rlc-resonance","title":"رنين RLC","description":"التردد الذي تكون عنده الممانعة أصغر ما يمكن","domain":"electromagnetism"},
    {"id":"aperi21:transformer","title":"المحوّل","description":"عدد اللفات ونسبة الجهد","domain":"electromagnetism"},
    {"id":"aperi21:motor","title":"المحرك الكهربائي","description":"الدوران بفعل القوة المؤثرة في التيار","domain":"electromagnetism"},
    {"id":"aperi21:generator","title":"المولد الكهربائي","description":"أشعل المصباح فيثقل المقبض","domain":"electromagnetism"},
    {"id":"aperi21:displacement-current","title":"تيار الإزاحة","description":"الحدّ الذي يعبر فجوة المكثف","domain":"electromagnetism"},
    {"id":"aperi21:maxwells-equations","title":"معادلات ماكسويل","description":"السلسلة التي يولّد فيها الكهرباء والمغناطيس أحدهما الآخر","domain":"electromagnetism"},
    {"id":"aperi21:electromagnetic-wave","title":"الموجات الكهرومغناطيسية","description":"مجالان كهربائي ومغناطيسي ينتشران ذاتيًا","domain":"electromagnetism"},
    {"id":"aperi21:poynting-vector","title":"متجه بوينتنغ","description":"الطاقة المارّة عبر الفضاء المحيط بالسلك","domain":"electromagnetism"},
    {"id":"aperi21:radiation-pressure","title":"ضغط الإشعاع","description":"دفع الضوء","domain":"electromagnetism"},
    {"id":"aperi21:antenna-radiation","title":"إشعاع الهوائي","description":"الموجات التي يرسلها الهوائي أقوى ما تكون نحو جانبيه ولا يرسل شيئًا على امتداد محوره","domain":"electromagnetism"},
    {"id":"aperi21:magnet-attraction","title":"ما يلتصق بالمغناطيس","description":"أشياء يجذبها المغناطيس وأشياء لا يجذبها","domain":"electromagnetism"},
    {"id":"aperi21:magnetic-poles","title":"قطبا المغناطيس","description":"الأقطاب المتشابهة تتنافر والمختلفة تتجاذب","domain":"electromagnetism"},
    {"id":"aperi21:simple-circuit","title":"بناء دائرة كهربائية","description":"لا يسري التيار إلا عند الاتصال، وإذا قُطع انطفأ المصباح","domain":"electromagnetism"},
    {"id":"aperi21:electromagnet","title":"مغناطيس كهربائي","description":"مغناطيس لا يعمل إلا أثناء سريان التيار","domain":"electromagnetism"},
    {"id":"aperi21:iv-characteristic","title":"منحنيات الخواص I–V","description":"عناصر لا يتبع تيارها الجهدَ في خط مستقيم","domain":"electromagnetism"},
    {"id":"aperi21:thermistor-and-ldr","title":"الثرمستور والمقاومة الضوئية","description":"مقاومة تتغير مع درجة الحرارة والضوء","domain":"electromagnetism"},
    {"id":"aperi21:potential-divider","title":"مجزئ الجهد","description":"تقسيم الجهد بالمقاومات","domain":"electromagnetism"},
    {"id":"aperi21:millikan-experiment","title":"تجربة ميليكان لقطرة الزيت","description":"دليل على أن الشحنة تأتي في كمّيات منفصلة","domain":"electromagnetism"},
    {"id":"aperi21:power-transmission","title":"نقل الطاقة الكهربائية","description":"رفع الجهد لتقليل الفقد","domain":"electromagnetism"},
    {"id":"aperi21:loudspeaker-and-microphone","title":"مكبر الصوت والميكروفون","description":"تحويل التيار إلى اهتزاز والعكس","domain":"electromagnetism"},
    {"id":"aperi21:michelson-morley","title":"تجربة ميكلسون ومورلي","description":"دليل على عدم وجود الأثير","domain":"modern-physics"},
    {"id":"aperi21:relativity-of-simultaneity","title":"نسبية التزامن","description":"«تزامن» يختلف من إطار مرجعي إلى آخر","domain":"modern-physics"},
    {"id":"aperi21:time-dilation","title":"تمدد الزمن","description":"الساعة المتحركة تتباطأ","domain":"modern-physics"},
    {"id":"aperi21:light-clock","title":"الساعة الضوئية","description":"التجربة الذهنية وراء تمدد الزمن","domain":"modern-physics"},
    {"id":"aperi21:length-contraction","title":"انكماش الطول","description":"انكماش على امتداد اتجاه الحركة","domain":"modern-physics"},
    {"id":"aperi21:muon-decay-evidence","title":"ميونات تصل إلى الأرض","description":"دليل رصدي على تمدد الزمن","domain":"modern-physics"},
    {"id":"aperi21:relativistic-velocity-addition","title":"الجمع النسبي للسرعات","description":"تركيب لا يتجاوز سرعة الضوء أبدًا","domain":"modern-physics"},
    {"id":"aperi21:twin-paradox","title":"مفارقة التوأم","description":"الاستدارة التي تصنع عدم التماثل","domain":"modern-physics"},
    {"id":"aperi21:spacetime-diagram","title":"مخطط الزمكان","description":"خط العالم وخط التزامن","domain":"modern-physics"},
    {"id":"aperi21:light-cone","title":"المخروط الضوئي","description":"حيث يمكن أن يصل السبب","domain":"modern-physics"},
    {"id":"aperi21:relativistic-momentum","title":"الزخم النسبي","description":"زخم يتزايد بلا حدّ كلما اقتربت السرعة من سرعة الضوء","domain":"modern-physics"},
    {"id":"aperi21:relativistic-doppler","title":"تأثير دوبلر النسبي","description":"تغيّر التردد مع إضافة تمدد الزمن","domain":"modern-physics"},
    {"id":"aperi21:equivalence-principle","title":"مبدأ التكافؤ","description":"لا يمكن التمييز بين التسارع والجاذبية","domain":"modern-physics"},
    {"id":"aperi21:gravitational-time-dilation","title":"تمدد الزمن الجذبي","description":"تسير الساعات بمعدلات مختلفة عند جهود مختلفة","domain":"modern-physics"},
    {"id":"aperi21:gravitational-redshift","title":"الانزياح الأحمر الجذبي","description":"ضوء يحمرّ وهو يخرج","domain":"modern-physics"},
    {"id":"aperi21:light-bending-by-gravity","title":"انحناء الضوء","description":"ينحني مسار الضوء قرب الكتلة","domain":"modern-physics"},
    {"id":"aperi21:blackbody-radiation","title":"إشعاع الجسم الأسود","description":"حيث تنهار النظرية الكلاسيكية","domain":"modern-physics"},
    {"id":"aperi21:wien-displacement-law","title":"قانون فين للإزاحة","description":"درجة الحرارة وطول موجة الذروة","domain":"modern-physics"},
    {"id":"aperi21:photoelectric-effect","title":"التأثير الكهروضوئي","description":"دليل على أن الضوء يأتي على هيئة جسيمات","domain":"modern-physics"},
    {"id":"aperi21:work-function-and-threshold","title":"دالة الشغل وتردد العتبة","description":"عتبة تختلف من فلز إلى آخر، وميل واحد للجميع","domain":"modern-physics"},
    {"id":"aperi21:compton-scattering","title":"تشتت كومبتون","description":"دليل على أن للفوتون زخمًا","domain":"modern-physics"},
    {"id":"aperi21:pair-production","title":"إنتاج الأزواج","description":"طاقة تتحول إلى مادة","domain":"modern-physics"},
    {"id":"aperi21:de-broglie-wavelength","title":"طول موجة دي بروي","description":"الطول الموجي للمادة كما تحدده سرعتها","domain":"modern-physics"},
    {"id":"aperi21:electron-diffraction","title":"حيود الإلكترونات","description":"رؤية الموجات المادية","domain":"modern-physics"},
    {"id":"aperi21:double-slit-with-electrons","title":"الشق المزدوج بالإلكترونات","description":"نمط يتكوّن إلكترونًا تلو الآخر","domain":"modern-physics"},
    {"id":"aperi21:uncertainty-principle","title":"مبدأ عدم اليقين","description":"إلى أي حد يمكن تحديد كميتين مترافقتين بدقة في آن واحد","domain":"modern-physics"},
    {"id":"aperi21:wave-function","title":"دالة الموجة","description":"سعة الاحتمال وما تعنيه","domain":"modern-physics"},
    {"id":"aperi21:superposition-quantum","title":"التراكب الكمومي","description":"أن يكون الشيء مجموعًا لعدة حالات","domain":"modern-physics"},
    {"id":"aperi21:measurement-collapse","title":"القياس والانهيار","description":"كيف تحسم الملاحظة الحالة","domain":"modern-physics"},
    {"id":"aperi21:particle-in-a-box","title":"البئر المربع اللانهائي","description":"تكميم الطاقة الذي تفرضه الجدران","domain":"modern-physics"},
    {"id":"aperi21:finite-well","title":"البئر المربع المحدود","description":"مستويات طاقة أدنى لأن دالة الموجة تتسرّب داخل الجدران","domain":"modern-physics"},
    {"id":"aperi21:quantum-tunneling","title":"النفق الكمومي","description":"احتمال عبور الحاجز","domain":"modern-physics"},
    {"id":"aperi21:scanning-tunneling-microscope","title":"مجهر المسح النفقي","description":"رسم سطح بتيار النفق","domain":"modern-physics"},
    {"id":"aperi21:quantum-harmonic-oscillator","title":"المتذبذب التوافقي الكمومي","description":"مستويات متساوية التباعد وطاقة نقطة الصفر","domain":"modern-physics"},
    {"id":"aperi21:hydrogen-spectrum","title":"طيف الهيدروجين","description":"طيف خطي متقطع","domain":"modern-physics"},
    {"id":"aperi21:bohr-model","title":"نموذج بور","description":"مدارات مُكمّاة","domain":"modern-physics"},
    {"id":"aperi21:atomic-orbital","title":"الفلك الذري","description":"الإلكترون بوصفه توزيعًا احتماليًا","domain":"modern-physics"},
    {"id":"aperi21:pauli-exclusion","title":"مبدأ باولي للاستبعاد","description":"لا يشترك اثنان في الحالة نفسها","domain":"modern-physics"},
    {"id":"aperi21:electron-configuration","title":"التوزيع الإلكتروني","description":"كيف ينشأ الجدول الدوري","domain":"modern-physics"},
    {"id":"aperi21:spin","title":"السبين","description":"زخم زاوي لا نظير له في الفيزياء الكلاسيكية","domain":"modern-physics"},
    {"id":"aperi21:stern-gerlach","title":"تجربة شتيرن-غيرلاخ","description":"حزمة ذرية تنقسم","domain":"modern-physics"},
    {"id":"aperi21:zeeman-effect","title":"تأثير زيمان","description":"مستويات طاقة يشطرها مجال مغناطيسي","domain":"modern-physics"},
    {"id":"aperi21:laser-and-stimulated-emission","title":"الليزر والانبعاث المحفَّز","description":"تضخيم الضوء المتوافق في الطور","domain":"modern-physics"},
    {"id":"aperi21:nuclear-structure","title":"مِمَّ تتكوّن النواة","description":"عدد البروتونات يحدد العنصر، وعدد النيوترونات يحدد النظير","domain":"modern-physics"},
    {"id":"aperi21:binding-energy-curve","title":"منحنى طاقة الربط","description":"لماذا تبلغ ذروتها عند الحديد","domain":"modern-physics"},
    {"id":"aperi21:radioactive-decay","title":"الاضمحلال الإشعاعي","description":"عمر النصف والاضمحلال الأسي","domain":"modern-physics"},
    {"id":"aperi21:decay-types","title":"أنواع إشعاعات الاضمحلال","description":"ألفا وبيتا وغاما","domain":"modern-physics"},
    {"id":"aperi21:radiometric-dating","title":"التأريخ الإشعاعي","description":"قياس الزمن بما تبقّى","domain":"modern-physics"},
    {"id":"aperi21:nuclear-fission","title":"الانشطار النووي","description":"الطاقة المنطلقة عند انشطار نواة ثقيلة","domain":"modern-physics"},
    {"id":"aperi21:chain-reaction","title":"التفاعل المتسلسل","description":"انشطار تواصله النيوترونات","domain":"modern-physics"},
    {"id":"aperi21:nuclear-fusion","title":"الاندماج النووي","description":"الطاقة المنطلقة عند اتحاد النوى الخفيفة","domain":"modern-physics"},
    {"id":"aperi21:antimatter","title":"المادة المضادة","description":"قرين الإلكترون الذي يفنى معه ويطلق فوتونين في اتجاهين متعاكسين","domain":"modern-physics"},
    {"id":"aperi21:band-theory","title":"نظرية النطاقات","description":"ما يميّز الموصلات والعوازل وأشباه الموصلات","domain":"modern-physics"},
    {"id":"aperi21:fermi-level","title":"مستوى فيرمي","description":"إلى أي ارتفاع تمتلئ الإلكترونات","domain":"modern-physics"},
    {"id":"aperi21:semiconductor-doping","title":"التطعيم","description":"كيف تصنع الشوائب النوع n والنوع p","domain":"modern-physics"},
    {"id":"aperi21:pn-junction","title":"الوصلة p–n","description":"طبقة الاستنزاف والتقويم","domain":"modern-physics"},
    {"id":"aperi21:diode-and-led","title":"الصمامات الثنائية ومصابيح LED","description":"تيار في اتجاه واحد وانبعاث الضوء","domain":"modern-physics"},
    {"id":"aperi21:transistor-principle","title":"الترانزستور","description":"إشارة صغيرة تتحكم في تيار كبير","domain":"modern-physics"},
    {"id":"aperi21:photovoltaic-effect","title":"التأثير الفوتوفولطي","description":"جهد يولّده الضوء","domain":"modern-physics"},
    {"id":"aperi21:superconductivity","title":"الموصلية الفائقة","description":"الحالة التي تختفي فيها المقاومة","domain":"modern-physics"},
    {"id":"aperi21:meissner-effect","title":"تأثير مايسنر","description":"الموصل الفائق يطرد المجال المغناطيسي","domain":"modern-physics"},
    {"id":"aperi21:bose-einstein-condensate","title":"تكاثف بوز–أينشتاين","description":"جسيمات باردة تتزاحم في حالة واحدة","domain":"modern-physics"},
    {"id":"aperi21:scale-of-universe","title":"مقياس الكون","description":"أحجام من الذرة إلى الكون، تربطها قوى العشرة","domain":"modern-physics"},
    {"id":"aperi21:rutherford-scattering","title":"تشتت رذرفورد","description":"التجربة التي نفذت فيها معظم الجسيمات وارتدّ القليل منها","domain":"modern-physics"},
    {"id":"aperi21:photon-bond-threshold","title":"الفوتون الذي يكسر الرابطة","description":"عتبة الأشعة فوق البنفسجية التي يبدأ عندها فوتون واحد بكسر رابطة واحدة","domain":"modern-physics"},
    {"id":"aperi21:exchange-particles","title":"جسيمات التبادل","description":"فوتونات بين الإلكترونات، وغلوونات بين الكواركات","domain":"modern-physics"},
  ],
};
