/**
 * 자동 생성 파일 — 직접 편집하지 말 것.
 *
 * 생성: pnpm catalog:gen  (scripts/gen-aperi21-catalog.mts)
 * 출처: 각 sim 의 schema(title/description) + docs/topics/topics.yaml(분야).
 */

import type { Aperi21Catalog } from '../catalog-types.js';

export const CATALOG: Aperi21Catalog = {
  locale: "en",
  domains: [
    {"id":"kinematics","name":"Kinematics"},
    {"id":"newtonian-mechanics","name":"Newtonian Mechanics"},
    {"id":"energy-momentum","name":"Work, Energy and Momentum"},
    {"id":"rotation-oscillation","name":"Rotation and Oscillation"},
    {"id":"gravitation","name":"Gravitation and Astronomy"},
    {"id":"fluids","name":"Fluids"},
    {"id":"thermodynamics","name":"Thermal and Statistical Physics"},
    {"id":"waves-acoustics","name":"Waves and Acoustics"},
    {"id":"optics","name":"Optics"},
    {"id":"electromagnetism","name":"Electromagnetism"},
    {"id":"modern-physics","name":"Modern Physics"},
  ],
  entries: [
    {"id":"aperi21:reference-frame","title":"Reference frame","domain":"kinematics"},
    {"id":"aperi21:coordinate-choice","title":"Choosing axes","domain":"kinematics"},
    {"id":"aperi21:average-velocity","title":"Average velocity","domain":"kinematics"},
    {"id":"aperi21:average-acceleration","title":"Average acceleration","domain":"kinematics"},
    {"id":"aperi21:direction-of-acceleration","title":"Direction of acceleration","domain":"kinematics"},
    {"id":"aperi21:uniform-motion","title":"Uniform motion","domain":"kinematics"},
    {"id":"aperi21:uniformly-accelerated-motion","title":"Uniformly accelerated motion","domain":"kinematics"},
    {"id":"aperi21:position-time-graph","title":"Position-time graph","domain":"kinematics"},
    {"id":"aperi21:velocity-time-graph","title":"Velocity-time graph","domain":"kinematics"},
    {"id":"aperi21:acceleration-time-graph","title":"Acceleration-time graph","domain":"kinematics"},
    {"id":"aperi21:free-fall","title":"Free fall","domain":"kinematics"},
    {"id":"aperi21:vertical-throw","title":"Vertical throw","domain":"kinematics"},
    {"id":"aperi21:gravitational-acceleration","title":"Gravitational acceleration","domain":"kinematics"},
    {"id":"aperi21:terminal-velocity","title":"Terminal velocity","domain":"kinematics"},
    {"id":"aperi21:vector-decomposition","title":"Vector components","domain":"kinematics"},
    {"id":"aperi21:vector-addition","title":"Vector addition","domain":"kinematics"},
    {"id":"aperi21:relative-velocity","title":"Relative velocity","domain":"kinematics"},
    {"id":"aperi21:river-crossing","title":"Crossing a river","domain":"kinematics"},
    {"id":"aperi21:projectile-motion","title":"Projectile motion","domain":"kinematics"},
    {"id":"aperi21:projectile-range","title":"Range and launch angle","domain":"kinematics"},
    {"id":"aperi21:trajectory-equation","title":"Trajectory equation","domain":"kinematics"},
    {"id":"aperi21:uniform-circular-motion","title":"Uniform circular motion","domain":"kinematics"},
    {"id":"aperi21:centripetal-acceleration","title":"Centripetal acceleration","domain":"kinematics"},
    {"id":"aperi21:angular-acceleration","title":"Angular acceleration","domain":"kinematics"},
    {"id":"aperi21:tangential-normal-acceleration","title":"Tangential and normal acceleration","domain":"kinematics"},
    {"id":"aperi21:radius-of-curvature","title":"Radius of curvature","domain":"kinematics"},
    {"id":"aperi21:stopping-distance","title":"Stopping distance","domain":"kinematics"},
    {"id":"aperi21:newtons-first-law","title":"Inertial frame","domain":"newtonian-mechanics"},
    {"id":"aperi21:newtons-second-law","title":"Newton's second law","domain":"newtonian-mechanics"},
    {"id":"aperi21:newtons-third-law","title":"Action and reaction","domain":"newtonian-mechanics"},
    {"id":"aperi21:net-force","title":"Net force","domain":"newtonian-mechanics"},
    {"id":"aperi21:free-body-diagram","title":"Free-body diagram","domain":"newtonian-mechanics"},
    {"id":"aperi21:inertial-vs-gravitational-mass","title":"Inertial and gravitational mass","domain":"newtonian-mechanics"},
    {"id":"aperi21:normal-force","title":"Normal force","domain":"newtonian-mechanics"},
    {"id":"aperi21:apparent-weight","title":"Apparent weight","domain":"newtonian-mechanics"},
    {"id":"aperi21:static-friction","title":"Static friction","domain":"newtonian-mechanics"},
    {"id":"aperi21:kinetic-friction","title":"Kinetic friction","domain":"newtonian-mechanics"},
    {"id":"aperi21:angle-of-friction","title":"Angle of friction","domain":"newtonian-mechanics"},
    {"id":"aperi21:inclined-plane","title":"Inclined plane","domain":"newtonian-mechanics"},
    {"id":"aperi21:tension","title":"Tension","domain":"newtonian-mechanics"},
    {"id":"aperi21:pulley-system","title":"Pulleys","domain":"newtonian-mechanics"},
    {"id":"aperi21:connected-bodies","title":"Connected bodies","domain":"newtonian-mechanics"},
    {"id":"aperi21:spring-force","title":"Spring force","domain":"newtonian-mechanics"},
    {"id":"aperi21:centripetal-force","title":"Centripetal force","domain":"newtonian-mechanics"},
    {"id":"aperi21:conical-pendulum","title":"Conical pendulum","domain":"newtonian-mechanics"},
    {"id":"aperi21:banked-curve","title":"Banked curve","domain":"newtonian-mechanics"},
    {"id":"aperi21:vertical-loop","title":"Vertical loop","domain":"newtonian-mechanics"},
    {"id":"aperi21:drag-force","title":"Air drag","domain":"newtonian-mechanics"},
    {"id":"aperi21:buoyant-force-as-force","title":"Buoyant force as a force","domain":"newtonian-mechanics"},
    {"id":"aperi21:non-inertial-frame","title":"Non-inertial frame","domain":"newtonian-mechanics"},
    {"id":"aperi21:fictitious-force","title":"Fictitious force","domain":"newtonian-mechanics"},
    {"id":"aperi21:coriolis-effect","title":"Coriolis effect","domain":"newtonian-mechanics"},
    {"id":"aperi21:impulse-force-relation","title":"Force and impulse","domain":"newtonian-mechanics"},
    {"id":"aperi21:equilibrium-of-forces","title":"Equilibrium of forces","domain":"newtonian-mechanics"},
    {"id":"aperi21:atwood-machine","title":"Atwood machine","domain":"newtonian-mechanics"},
    {"id":"aperi21:balance-scale","title":"Balancing a scale","domain":"newtonian-mechanics"},
    {"id":"aperi21:mechanical-advantage","title":"Mechanical advantage","domain":"newtonian-mechanics"},
    {"id":"aperi21:youngs-modulus","title":"Young's modulus","domain":"newtonian-mechanics"},
    {"id":"aperi21:stress-strain-curve","title":"Stress–strain curve","domain":"newtonian-mechanics"},
    {"id":"aperi21:work-by-variable-force","title":"Work done by a varying force","domain":"energy-momentum"},
    {"id":"aperi21:kinetic-energy","title":"Kinetic energy","domain":"energy-momentum"},
    {"id":"aperi21:work-energy-theorem","title":"Work-energy theorem","domain":"energy-momentum"},
    {"id":"aperi21:gravitational-potential-energy","title":"Gravitational potential energy","domain":"energy-momentum"},
    {"id":"aperi21:elastic-potential-energy","title":"Elastic potential energy","domain":"energy-momentum"},
    {"id":"aperi21:conservative-force","title":"Conservative force","domain":"energy-momentum"},
    {"id":"aperi21:non-conservative-force","title":"Non-conservative force","domain":"energy-momentum"},
    {"id":"aperi21:conservation-of-mechanical-energy","title":"Conservation of mechanical energy","domain":"energy-momentum"},
    {"id":"aperi21:energy-dissipation","title":"Energy dissipation","domain":"energy-momentum"},
    {"id":"aperi21:potential-energy-curve","title":"Potential energy curve","domain":"energy-momentum"},
    {"id":"aperi21:equilibrium-points","title":"Equilibrium points","domain":"energy-momentum"},
    {"id":"aperi21:efficiency","title":"Efficiency","domain":"energy-momentum"},
    {"id":"aperi21:impulse-momentum-theorem","title":"Impulse–momentum theorem","domain":"energy-momentum"},
    {"id":"aperi21:conservation-of-momentum","title":"Conservation of momentum","domain":"energy-momentum"},
    {"id":"aperi21:elastic-collision","title":"Elastic collision","domain":"energy-momentum"},
    {"id":"aperi21:inelastic-collision","title":"Inelastic collision","domain":"energy-momentum"},
    {"id":"aperi21:perfectly-inelastic-collision","title":"Perfectly inelastic collision","domain":"energy-momentum"},
    {"id":"aperi21:two-dimensional-collision","title":"Two-dimensional collision","domain":"energy-momentum"},
    {"id":"aperi21:center-of-mass-motion","title":"Motion of the centre of mass","domain":"energy-momentum"},
    {"id":"aperi21:explosion-and-recoil","title":"Explosion and recoil","domain":"energy-momentum"},
    {"id":"aperi21:rocket-equation","title":"The rocket equation","domain":"energy-momentum"},
    {"id":"aperi21:ballistic-pendulum","title":"Ballistic pendulum","domain":"energy-momentum"},
    {"id":"aperi21:energy-in-collision","title":"Energy in collisions","domain":"energy-momentum"},
    {"id":"aperi21:energy-flow-diagram","title":"Energy flow diagram","domain":"energy-momentum"},
    {"id":"aperi21:torque","title":"Torque","domain":"rotation-oscillation"},
    {"id":"aperi21:moment-of-inertia","title":"Moment of inertia","domain":"rotation-oscillation"},
    {"id":"aperi21:parallel-axis-theorem","title":"Parallel axis theorem","domain":"rotation-oscillation"},
    {"id":"aperi21:rotational-kinetic-energy","title":"Rotational kinetic energy","domain":"rotation-oscillation"},
    {"id":"aperi21:angular-momentum","title":"Angular momentum","domain":"rotation-oscillation"},
    {"id":"aperi21:conservation-of-angular-momentum","title":"Conservation of angular momentum","domain":"rotation-oscillation"},
    {"id":"aperi21:rolling-without-slipping","title":"Rolling without slipping","domain":"rotation-oscillation"},
    {"id":"aperi21:rolling-race","title":"Rolling race","domain":"rotation-oscillation"},
    {"id":"aperi21:static-equilibrium","title":"Static equilibrium","domain":"rotation-oscillation"},
    {"id":"aperi21:center-of-gravity","title":"Center of gravity","domain":"rotation-oscillation"},
    {"id":"aperi21:gyroscopic-precession","title":"Gyroscopic precession","domain":"rotation-oscillation"},
    {"id":"aperi21:angular-momentum-vector","title":"Direction of angular momentum","domain":"rotation-oscillation"},
    {"id":"aperi21:simple-harmonic-motion","title":"Simple harmonic motion","domain":"rotation-oscillation"},
    {"id":"aperi21:shm-energy","title":"Energy in simple harmonic motion","domain":"rotation-oscillation"},
    {"id":"aperi21:mass-spring-system","title":"Mass on a spring","domain":"rotation-oscillation"},
    {"id":"aperi21:simple-pendulum","title":"Simple pendulum","domain":"rotation-oscillation"},
    {"id":"aperi21:physical-pendulum","title":"Physical pendulum","domain":"rotation-oscillation"},
    {"id":"aperi21:pendulum-amplitude-dependence","title":"Isochronism of the pendulum","domain":"rotation-oscillation"},
    {"id":"aperi21:damped-oscillation","title":"Damped oscillation","domain":"rotation-oscillation"},
    {"id":"aperi21:damping-regimes","title":"Three regimes of damping","domain":"rotation-oscillation"},
    {"id":"aperi21:driven-oscillation","title":"Driven oscillation","domain":"rotation-oscillation"},
    {"id":"aperi21:resonance","title":"Resonance","domain":"rotation-oscillation"},
    {"id":"aperi21:quality-factor","title":"Quality factor","domain":"rotation-oscillation"},
    {"id":"aperi21:coupled-oscillators","title":"Coupled oscillators","domain":"rotation-oscillation"},
    {"id":"aperi21:normal-modes","title":"Normal modes","domain":"rotation-oscillation"},
    {"id":"aperi21:beats-in-oscillation","title":"Beats in oscillation","domain":"rotation-oscillation"},
    {"id":"aperi21:phase-space","title":"Phase space","domain":"rotation-oscillation"},
    {"id":"aperi21:nonlinear-oscillation","title":"Nonlinear oscillation","domain":"rotation-oscillation"},
    {"id":"aperi21:gears","title":"Gears","domain":"rotation-oscillation"},
    {"id":"aperi21:newtons-law-of-gravitation","title":"Newton's law of gravitation","domain":"gravitation"},
    {"id":"aperi21:gravitational-field","title":"Gravitational field","domain":"gravitation"},
    {"id":"aperi21:range-and-surface-gravity","title":"Gravity and range","domain":"gravitation"},
    {"id":"aperi21:shell-theorem","title":"Shell theorem","domain":"gravitation"},
    {"id":"aperi21:gravity-inside-earth","title":"Gravity inside the Earth","domain":"gravitation"},
    {"id":"aperi21:gravitational-potential-energy-general","title":"Gravitational potential energy (general)","domain":"gravitation"},
    {"id":"aperi21:escape-velocity","title":"Escape velocity","domain":"gravitation"},
    {"id":"aperi21:orbital-velocity","title":"Orbital velocity","domain":"gravitation"},
    {"id":"aperi21:circular-orbit","title":"Circular orbit","domain":"gravitation"},
    {"id":"aperi21:elliptical-orbit","title":"Elliptical orbit","domain":"gravitation"},
    {"id":"aperi21:keplers-first-law","title":"Kepler's first law","domain":"gravitation"},
    {"id":"aperi21:keplers-second-law","title":"Kepler's second law","domain":"gravitation"},
    {"id":"aperi21:keplers-third-law","title":"Kepler's third law","domain":"gravitation"},
    {"id":"aperi21:two-body-problem","title":"Two-body problem","domain":"gravitation"},
    {"id":"aperi21:tidal-force","title":"Tidal force","domain":"gravitation"},
    {"id":"aperi21:roche-limit","title":"Roche limit","domain":"gravitation"},
    {"id":"aperi21:weightlessness","title":"Weightlessness","domain":"gravitation"},
    {"id":"aperi21:geostationary-orbit","title":"Geostationary orbit","domain":"gravitation"},
    {"id":"aperi21:gravitational-slingshot","title":"Gravity assist","domain":"gravitation"},
    {"id":"aperi21:lagrange-points","title":"Lagrange points","domain":"gravitation"},
    {"id":"aperi21:orbital-transfer","title":"Orbital transfer","domain":"gravitation"},
    {"id":"aperi21:black-hole-horizon","title":"Event horizon","domain":"gravitation"},
    {"id":"aperi21:diurnal-motion","title":"Diurnal motion","domain":"gravitation"},
    {"id":"aperi21:earth-rotation-day-night","title":"Earth’s rotation, day and night","domain":"gravitation"},
    {"id":"aperi21:earth-revolution-constellations","title":"Earth’s orbit and the constellations","domain":"gravitation"},
    {"id":"aperi21:solar-altitude-shadow","title":"Solar altitude and shadows","domain":"gravitation"},
    {"id":"aperi21:seasonal-sun-path","title":"The Sun’s path through the seasons","domain":"gravitation"},
    {"id":"aperi21:axial-tilt-seasons","title":"Axial tilt and the seasons","domain":"gravitation"},
    {"id":"aperi21:moon-phases","title":"Phases of the Moon","domain":"gravitation"},
    {"id":"aperi21:eclipse","title":"Solar and lunar eclipses","domain":"gravitation"},
    {"id":"aperi21:stellar-parallax","title":"Stellar parallax","domain":"gravitation"},
    {"id":"aperi21:apparent-brightness","title":"Apparent brightness","domain":"gravitation"},
    {"id":"aperi21:magnitude-scale","title":"Stellar magnitude","domain":"gravitation"},
    {"id":"aperi21:star-color-temperature","title":"Star color and surface temperature","domain":"gravitation"},
    {"id":"aperi21:expanding-universe","title":"The expanding universe","domain":"gravitation"},
    {"id":"aperi21:stellar-luminosity","title":"Luminosity","domain":"gravitation"},
    {"id":"aperi21:hr-diagram","title":"HR diagram","domain":"gravitation"},
    {"id":"aperi21:star-radiation-gravity-balance","title":"Radiation pressure and gravity in balance","domain":"gravitation"},
    {"id":"aperi21:orbital-decay","title":"Orbital decay","domain":"gravitation"},
    {"id":"aperi21:inverse-square-law","title":"Inverse-square law","domain":"gravitation"},
    {"id":"aperi21:stellar-nucleosynthesis","title":"Stellar nucleosynthesis","domain":"gravitation"},
    {"id":"aperi21:star-life-cycle","title":"Life cycle of a star","domain":"gravitation"},
    {"id":"aperi21:stellar-spectral-class","title":"Stellar spectral classes","domain":"gravitation"},
    {"id":"aperi21:supernova-and-neutron-star","title":"Supernova and neutron star","domain":"gravitation"},
    {"id":"aperi21:exoplanet-detection","title":"Detecting exoplanets","domain":"gravitation"},
    {"id":"aperi21:projectile-in-wind","title":"Wind and range","domain":"fluids"},
    {"id":"aperi21:pressure-isotropy","title":"Pressure isotropy","domain":"fluids"},
    {"id":"aperi21:hydrostatic-pressure","title":"Hydrostatic pressure","domain":"fluids"},
    {"id":"aperi21:pressure-and-container-shape","title":"Container shape and bottom pressure","domain":"fluids"},
    {"id":"aperi21:atmospheric-pressure","title":"Atmospheric pressure","domain":"fluids"},
    {"id":"aperi21:barometer","title":"Barometer","domain":"fluids"},
    {"id":"aperi21:manometer","title":"Manometer","domain":"fluids"},
    {"id":"aperi21:pascals-principle","title":"Pascal's principle","domain":"fluids"},
    {"id":"aperi21:buoyancy","title":"Buoyancy","domain":"fluids"},
    {"id":"aperi21:archimedes-principle","title":"Archimedes principle — the size of the buoyant force","domain":"fluids"},
    {"id":"aperi21:floating-and-draft","title":"How deep a floating body sits","domain":"fluids"},
    {"id":"aperi21:stability-of-floating-body","title":"Stability of a floating body","domain":"fluids"},
    {"id":"aperi21:continuity-equation","title":"Continuity equation","domain":"fluids"},
    {"id":"aperi21:bernoullis-principle","title":"Bernoulli's principle","domain":"fluids"},
    {"id":"aperi21:venturi-effect","title":"Venturi effect","domain":"fluids"},
    {"id":"aperi21:torricellis-law","title":"Torricelli's law","domain":"fluids"},
    {"id":"aperi21:lift-force","title":"Lift","domain":"fluids"},
    {"id":"aperi21:viscosity","title":"Viscosity","domain":"fluids"},
    {"id":"aperi21:poiseuille-flow","title":"Laminar flow in a pipe","domain":"fluids"},
    {"id":"aperi21:stokes-drag","title":"Stokes drag","domain":"fluids"},
    {"id":"aperi21:laminar-vs-turbulent","title":"Laminar and turbulent flow","domain":"fluids"},
    {"id":"aperi21:reynolds-number","title":"Reynolds number","domain":"fluids"},
    {"id":"aperi21:boundary-layer","title":"Boundary layer","domain":"fluids"},
    {"id":"aperi21:surface-tension","title":"Surface tension","domain":"fluids"},
    {"id":"aperi21:laplace-pressure","title":"Laplace pressure","domain":"fluids"},
    {"id":"aperi21:capillary-action","title":"Capillary action","domain":"fluids"},
    {"id":"aperi21:wetting-and-contact-angle","title":"Wetting and contact angle","domain":"fluids"},
    {"id":"aperi21:drag-in-fluid","title":"Drag in a fluid","domain":"fluids"},
    {"id":"aperi21:thermal-equilibrium","title":"Thermal equilibrium","domain":"thermodynamics"},
    {"id":"aperi21:specific-heat","title":"Specific heat","domain":"thermodynamics"},
    {"id":"aperi21:calorimetry","title":"Calorimetry","domain":"thermodynamics"},
    {"id":"aperi21:latent-heat","title":"Latent heat","domain":"thermodynamics"},
    {"id":"aperi21:phase-diagram","title":"Phase diagram","domain":"thermodynamics"},
    {"id":"aperi21:triple-point","title":"Triple point","domain":"thermodynamics"},
    {"id":"aperi21:thermal-conduction","title":"Heat conduction","domain":"thermodynamics"},
    {"id":"aperi21:thermal-convection","title":"Convection","domain":"thermodynamics"},
    {"id":"aperi21:thermal-radiation","title":"Thermal radiation","domain":"thermodynamics"},
    {"id":"aperi21:stefan-boltzmann-law","title":"Stefan–Boltzmann law","domain":"thermodynamics"},
    {"id":"aperi21:thermal-expansion","title":"Thermal expansion","domain":"thermodynamics"},
    {"id":"aperi21:bimetal","title":"Bimetallic strip","domain":"thermodynamics"},
    {"id":"aperi21:ideal-gas-law","title":"Ideal gas law","domain":"thermodynamics"},
    {"id":"aperi21:boyles-law","title":"Boyle's law","domain":"thermodynamics"},
    {"id":"aperi21:charles-law","title":"Charles's law","domain":"thermodynamics"},
    {"id":"aperi21:gas-pressure","title":"Molecules and pressure","domain":"thermodynamics"},
    {"id":"aperi21:pressure-from-collisions","title":"Pressure from collisions","domain":"thermodynamics"},
    {"id":"aperi21:maxwell-boltzmann-distribution","title":"Maxwell–Boltzmann distribution","domain":"thermodynamics"},
    {"id":"aperi21:mean-free-path","title":"Mean free path","domain":"thermodynamics"},
    {"id":"aperi21:first-law-of-thermodynamics","title":"First law of thermodynamics","domain":"thermodynamics"},
    {"id":"aperi21:pv-diagram","title":"PV diagram","domain":"thermodynamics"},
    {"id":"aperi21:isothermal-process","title":"Isothermal process","domain":"thermodynamics"},
    {"id":"aperi21:adiabatic-process","title":"Adiabatic process","domain":"thermodynamics"},
    {"id":"aperi21:isobaric-isochoric","title":"Isobaric and isochoric processes","domain":"thermodynamics"},
    {"id":"aperi21:cyclic-process","title":"Cyclic process","domain":"thermodynamics"},
    {"id":"aperi21:second-law-of-thermodynamics","title":"Second law of thermodynamics","domain":"thermodynamics"},
    {"id":"aperi21:irreversibility","title":"Entropy and irreversibility","domain":"thermodynamics"},
    {"id":"aperi21:heat-engine","title":"Heat engine","domain":"thermodynamics"},
    {"id":"aperi21:carnot-cycle","title":"Carnot cycle","domain":"thermodynamics"},
    {"id":"aperi21:refrigerator-heat-pump","title":"Refrigerators and heat pumps","domain":"thermodynamics"},
    {"id":"aperi21:brownian-motion","title":"Brownian motion","domain":"thermodynamics"},
    {"id":"aperi21:diffusion","title":"Diffusion","domain":"thermodynamics"},
    {"id":"aperi21:random-walk","title":"Random walk","domain":"thermodynamics"},
    {"id":"aperi21:statistical-fluctuation","title":"Statistical fluctuation","domain":"thermodynamics"},
    {"id":"aperi21:maxwells-demon","title":"Maxwell's demon","domain":"thermodynamics"},
    {"id":"aperi21:insulation","title":"Insulation","domain":"thermodynamics"},
    {"id":"aperi21:albedo","title":"Albedo","domain":"thermodynamics"},
    {"id":"aperi21:radiative-equilibrium","title":"Radiative equilibrium","domain":"thermodynamics"},
    {"id":"aperi21:greenhouse-effect","title":"Greenhouse effect","domain":"thermodynamics"},
    {"id":"aperi21:wave-basics","title":"Basic quantities of a wave","domain":"waves-acoustics"},
    {"id":"aperi21:wave-vs-particle-transport","title":"What a wave carries","domain":"waves-acoustics"},
    {"id":"aperi21:transverse-wave","title":"Transverse wave","domain":"waves-acoustics"},
    {"id":"aperi21:longitudinal-wave","title":"Longitudinal wave","domain":"waves-acoustics"},
    {"id":"aperi21:wave-speed-in-medium","title":"Wave speed and the medium","domain":"waves-acoustics"},
    {"id":"aperi21:wavefront-and-ray","title":"Wavefronts and rays","domain":"waves-acoustics"},
    {"id":"aperi21:huygens-principle","title":"Huygens' principle","domain":"waves-acoustics"},
    {"id":"aperi21:superposition","title":"Superposition","domain":"waves-acoustics"},
    {"id":"aperi21:constructive-destructive","title":"Constructive and destructive interference","domain":"waves-acoustics"},
    {"id":"aperi21:interference","title":"Interference","domain":"waves-acoustics"},
    {"id":"aperi21:standing-wave","title":"Standing wave","domain":"waves-acoustics"},
    {"id":"aperi21:harmonics","title":"Harmonics","domain":"waves-acoustics"},
    {"id":"aperi21:string-vibration","title":"Vibrating string","domain":"waves-acoustics"},
    {"id":"aperi21:air-column-resonance","title":"Air-column resonance","domain":"waves-acoustics"},
    {"id":"aperi21:beats","title":"Beats","domain":"waves-acoustics"},
    {"id":"aperi21:doppler-effect","title":"Doppler effect","domain":"waves-acoustics"},
    {"id":"aperi21:doppler-source-vs-observer","title":"Moving source vs. moving observer","domain":"waves-acoustics"},
    {"id":"aperi21:shock-wave","title":"Shock wave","domain":"waves-acoustics"},
    {"id":"aperi21:sound-intensity","title":"Sound intensity","domain":"waves-acoustics"},
    {"id":"aperi21:reflection-of-waves","title":"Reflection of waves","domain":"waves-acoustics"},
    {"id":"aperi21:refraction-of-waves","title":"Refraction of waves","domain":"waves-acoustics"},
    {"id":"aperi21:diffraction","title":"Diffraction","domain":"waves-acoustics"},
    {"id":"aperi21:slit-width-and-diffraction","title":"Slit Width and Diffraction","domain":"waves-acoustics"},
    {"id":"aperi21:wave-energy","title":"Energy of a wave","domain":"waves-acoustics"},
    {"id":"aperi21:wave-attenuation","title":"Attenuation of a wave","domain":"waves-acoustics"},
    {"id":"aperi21:impedance-mismatch","title":"Impedance mismatch","domain":"waves-acoustics"},
    {"id":"aperi21:noise-cancellation","title":"Active noise cancellation","domain":"waves-acoustics"},
    {"id":"aperi21:sound-source-vibration","title":"Sound and vibration","domain":"waves-acoustics"},
    {"id":"aperi21:sound-through-materials","title":"Sound through materials","domain":"waves-acoustics"},
    {"id":"aperi21:digital-vs-analog-signal","title":"Digital and analog signals","domain":"waves-acoustics"},
    {"id":"aperi21:seismic-waves","title":"Seismic waves","domain":"waves-acoustics"},
    {"id":"aperi21:rectilinear-propagation","title":"Light travels in straight lines","domain":"optics"},
    {"id":"aperi21:shadow-umbra-penumbra","title":"Umbra and penumbra","domain":"optics"},
    {"id":"aperi21:pinhole-camera","title":"Pinhole camera","domain":"optics"},
    {"id":"aperi21:law-of-reflection","title":"Law of reflection","domain":"optics"},
    {"id":"aperi21:specular-diffuse-reflection","title":"Specular and diffuse reflection","domain":"optics"},
    {"id":"aperi21:plane-mirror-image","title":"Image in a plane mirror","domain":"optics"},
    {"id":"aperi21:multiple-mirror-images","title":"Images in two mirrors","domain":"optics"},
    {"id":"aperi21:concave-mirror","title":"Concave mirror","domain":"optics"},
    {"id":"aperi21:convex-mirror","title":"Convex mirror","domain":"optics"},
    {"id":"aperi21:snells-law","title":"Snell's law","domain":"optics"},
    {"id":"aperi21:apparent-depth","title":"Apparent depth","domain":"optics"},
    {"id":"aperi21:total-internal-reflection","title":"Total internal reflection","domain":"optics"},
    {"id":"aperi21:optical-fiber","title":"Optical fiber","domain":"optics"},
    {"id":"aperi21:mirage","title":"Mirage","domain":"optics"},
    {"id":"aperi21:dispersion","title":"Dispersion","domain":"optics"},
    {"id":"aperi21:prism","title":"Prism","domain":"optics"},
    {"id":"aperi21:rainbow","title":"Rainbow","domain":"optics"},
    {"id":"aperi21:thin-lens","title":"Thin lens","domain":"optics"},
    {"id":"aperi21:converging-diverging-lens","title":"Converging and diverging lenses","domain":"optics"},
    {"id":"aperi21:magnification","title":"Magnification","domain":"optics"},
    {"id":"aperi21:focal-length","title":"Focal length","domain":"optics"},
    {"id":"aperi21:real-vs-virtual-image","title":"Real and virtual images","domain":"optics"},
    {"id":"aperi21:lens-combination","title":"Combining lenses","domain":"optics"},
    {"id":"aperi21:spherical-aberration","title":"Spherical aberration","domain":"optics"},
    {"id":"aperi21:chromatic-aberration","title":"Chromatic aberration","domain":"optics"},
    {"id":"aperi21:human-eye-accommodation","title":"Accommodation of the eye","domain":"optics"},
    {"id":"aperi21:myopia-hyperopia","title":"Nearsightedness and farsightedness","domain":"optics"},
    {"id":"aperi21:magnifying-glass","title":"Magnifying glass","domain":"optics"},
    {"id":"aperi21:microscope","title":"Microscope","domain":"optics"},
    {"id":"aperi21:telescope","title":"Telescope","domain":"optics"},
    {"id":"aperi21:youngs-double-slit","title":"Young's double slit","domain":"optics"},
    {"id":"aperi21:single-slit-diffraction","title":"Single-slit diffraction","domain":"optics"},
    {"id":"aperi21:diffraction-grating","title":"Diffraction grating","domain":"optics"},
    {"id":"aperi21:thin-film-interference","title":"Thin-film interference","domain":"optics"},
    {"id":"aperi21:newtons-rings","title":"Newton's rings","domain":"optics"},
    {"id":"aperi21:resolving-power","title":"Resolving power","domain":"optics"},
    {"id":"aperi21:polarization","title":"Polarization","domain":"optics"},
    {"id":"aperi21:malus-law","title":"Malus's law","domain":"optics"},
    {"id":"aperi21:brewster-angle","title":"Brewster's angle","domain":"optics"},
    {"id":"aperi21:birefringence","title":"Birefringence","domain":"optics"},
    {"id":"aperi21:scattering","title":"Scattering","domain":"optics"},
    {"id":"aperi21:rayleigh-scattering","title":"Rayleigh scattering","domain":"optics"},
    {"id":"aperi21:seeing-requires-light","title":"Seeing needs light","domain":"optics"},
    {"id":"aperi21:color-addition","title":"Adding light","domain":"optics"},
    {"id":"aperi21:object-color","title":"The colour of an object","domain":"optics"},
    {"id":"aperi21:light-through-materials","title":"Light and materials","domain":"optics"},
    {"id":"aperi21:electric-charge","title":"Electric charge","domain":"electromagnetism"},
    {"id":"aperi21:charging-methods","title":"Charging methods","domain":"electromagnetism"},
    {"id":"aperi21:coulombs-law","title":"Coulomb's law","domain":"electromagnetism"},
    {"id":"aperi21:superposition-of-forces","title":"Superposition of electric forces","domain":"electromagnetism"},
    {"id":"aperi21:electric-field","title":"Electric field","domain":"electromagnetism"},
    {"id":"aperi21:field-lines","title":"Electric field lines","domain":"electromagnetism"},
    {"id":"aperi21:field-of-dipole","title":"Electric field of a dipole","domain":"electromagnetism"},
    {"id":"aperi21:uniform-field","title":"Uniform electric field","domain":"electromagnetism"},
    {"id":"aperi21:charge-in-uniform-field","title":"A charge in a uniform field","domain":"electromagnetism"},
    {"id":"aperi21:gausss-law","title":"Gauss’s law","domain":"electromagnetism"},
    {"id":"aperi21:field-of-charged-sphere","title":"Field of a charged sphere","domain":"electromagnetism"},
    {"id":"aperi21:equipotential-surface","title":"Equipotential surfaces","domain":"electromagnetism"},
    {"id":"aperi21:potential-vs-field","title":"Potential and electric field","domain":"electromagnetism"},
    {"id":"aperi21:electrostatic-shielding","title":"Electrostatic shielding","domain":"electromagnetism"},
    {"id":"aperi21:charge-on-conductor-surface","title":"Charge on a conductor surface","domain":"electromagnetism"},
    {"id":"aperi21:dielectric","title":"Dielectric","domain":"electromagnetism"},
    {"id":"aperi21:parallel-plate-capacitor","title":"Parallel-plate capacitor","domain":"electromagnetism"},
    {"id":"aperi21:capacitors-in-circuit","title":"Connecting capacitors","domain":"electromagnetism"},
    {"id":"aperi21:energy-in-capacitor","title":"Energy in a capacitor","domain":"electromagnetism"},
    {"id":"aperi21:electric-current","title":"Electric current","domain":"electromagnetism"},
    {"id":"aperi21:drift-velocity","title":"Drift velocity","domain":"electromagnetism"},
    {"id":"aperi21:ohms-law","title":"Ohm's law","domain":"electromagnetism"},
    {"id":"aperi21:resistance-and-geometry","title":"Resistance and shape","domain":"electromagnetism"},
    {"id":"aperi21:temperature-and-resistance","title":"Temperature and resistance","domain":"electromagnetism"},
    {"id":"aperi21:series-parallel-resistors","title":"Resistors in series and parallel","domain":"electromagnetism"},
    {"id":"aperi21:emf-and-internal-resistance","title":"EMF and internal resistance","domain":"electromagnetism"},
    {"id":"aperi21:kirchhoffs-current-law","title":"Kirchhoff's current law","domain":"electromagnetism"},
    {"id":"aperi21:kirchhoffs-voltage-law","title":"Kirchhoff's voltage law","domain":"electromagnetism"},
    {"id":"aperi21:wheatstone-bridge","title":"Wheatstone bridge","domain":"electromagnetism"},
    {"id":"aperi21:joule-heating","title":"Joule heating","domain":"electromagnetism"},
    {"id":"aperi21:rc-circuit","title":"RC circuit","domain":"electromagnetism"},
    {"id":"aperi21:magnetic-field","title":"Magnetic field","domain":"electromagnetism"},
    {"id":"aperi21:magnetic-field-lines","title":"Magnetic field lines","domain":"electromagnetism"},
    {"id":"aperi21:lorentz-force","title":"Lorentz force","domain":"electromagnetism"},
    {"id":"aperi21:charged-particle-in-magnetic-field","title":"Charges circling in a magnetic field","domain":"electromagnetism"},
    {"id":"aperi21:velocity-selector","title":"Velocity selector","domain":"electromagnetism"},
    {"id":"aperi21:mass-spectrometer","title":"Mass spectrometer","domain":"electromagnetism"},
    {"id":"aperi21:force-on-current-wire","title":"Force on a current-carrying wire","domain":"electromagnetism"},
    {"id":"aperi21:biot-savart-law","title":"Biot–Savart law","domain":"electromagnetism"},
    {"id":"aperi21:field-of-straight-wire","title":"The field a current makes","domain":"electromagnetism"},
    {"id":"aperi21:field-of-loop-and-solenoid","title":"Loop and solenoid","domain":"electromagnetism"},
    {"id":"aperi21:amperes-law","title":"Ampère’s law","domain":"electromagnetism"},
    {"id":"aperi21:force-between-wires","title":"Force between parallel wires","domain":"electromagnetism"},
    {"id":"aperi21:magnetic-dipole","title":"Magnetic dipole","domain":"electromagnetism"},
    {"id":"aperi21:magnetic-materials","title":"Magnetic materials","domain":"electromagnetism"},
    {"id":"aperi21:faradays-law","title":"Faraday's law","domain":"electromagnetism"},
    {"id":"aperi21:lenzs-law","title":"Lenz's law","domain":"electromagnetism"},
    {"id":"aperi21:motional-emf","title":"Motional EMF","domain":"electromagnetism"},
    {"id":"aperi21:eddy-current","title":"Eddy currents","domain":"electromagnetism"},
    {"id":"aperi21:self-inductance","title":"Self-inductance","domain":"electromagnetism"},
    {"id":"aperi21:mutual-inductance","title":"Mutual inductance","domain":"electromagnetism"},
    {"id":"aperi21:energy-in-inductor","title":"Energy in an inductor","domain":"electromagnetism"},
    {"id":"aperi21:rl-circuit","title":"RL circuit","domain":"electromagnetism"},
    {"id":"aperi21:lc-oscillation","title":"LC oscillation","domain":"electromagnetism"},
    {"id":"aperi21:ac-generation","title":"Generating alternating current","domain":"electromagnetism"},
    {"id":"aperi21:reactance","title":"Reactance and impedance","domain":"electromagnetism"},
    {"id":"aperi21:phase-in-ac-circuit","title":"Phase difference in AC circuits","domain":"electromagnetism"},
    {"id":"aperi21:series-rlc-resonance","title":"RLC resonance","domain":"electromagnetism"},
    {"id":"aperi21:transformer","title":"Transformer","domain":"electromagnetism"},
    {"id":"aperi21:motor","title":"Electric motor","domain":"electromagnetism"},
    {"id":"aperi21:generator","title":"Generator","domain":"electromagnetism"},
    {"id":"aperi21:displacement-current","title":"Displacement current","domain":"electromagnetism"},
    {"id":"aperi21:maxwells-equations","title":"Maxwell's equations","domain":"electromagnetism"},
    {"id":"aperi21:electromagnetic-wave","title":"Electromagnetic waves","domain":"electromagnetism"},
    {"id":"aperi21:poynting-vector","title":"Poynting vector","domain":"electromagnetism"},
    {"id":"aperi21:radiation-pressure","title":"Radiation pressure","domain":"electromagnetism"},
    {"id":"aperi21:antenna-radiation","title":"Antenna radiation","domain":"electromagnetism"},
    {"id":"aperi21:magnet-attraction","title":"What sticks to a magnet","domain":"electromagnetism"},
    {"id":"aperi21:magnetic-poles","title":"The two poles of a magnet","domain":"electromagnetism"},
    {"id":"aperi21:simple-circuit","title":"Building an electric circuit","domain":"electromagnetism"},
    {"id":"aperi21:electromagnet","title":"Electromagnet","domain":"electromagnetism"},
    {"id":"aperi21:iv-characteristic","title":"I–V characteristic curves","domain":"electromagnetism"},
    {"id":"aperi21:thermistor-and-ldr","title":"Thermistor and LDR","domain":"electromagnetism"},
    {"id":"aperi21:potential-divider","title":"Potential divider","domain":"electromagnetism"},
    {"id":"aperi21:millikan-experiment","title":"Millikan oil-drop experiment","domain":"electromagnetism"},
    {"id":"aperi21:power-transmission","title":"Power transmission","domain":"electromagnetism"},
    {"id":"aperi21:loudspeaker-and-microphone","title":"Loudspeaker and microphone","domain":"electromagnetism"},
    {"id":"aperi21:michelson-morley","title":"Michelson–Morley experiment","domain":"modern-physics"},
    {"id":"aperi21:relativity-of-simultaneity","title":"Relativity of simultaneity","domain":"modern-physics"},
    {"id":"aperi21:time-dilation","title":"Time dilation","domain":"modern-physics"},
    {"id":"aperi21:light-clock","title":"Light clock","domain":"modern-physics"},
    {"id":"aperi21:length-contraction","title":"Length contraction","domain":"modern-physics"},
    {"id":"aperi21:muon-decay-evidence","title":"Muons reaching the ground","domain":"modern-physics"},
    {"id":"aperi21:relativistic-velocity-addition","title":"Relativistic velocity addition","domain":"modern-physics"},
    {"id":"aperi21:twin-paradox","title":"Twin paradox","domain":"modern-physics"},
    {"id":"aperi21:spacetime-diagram","title":"Spacetime diagram","domain":"modern-physics"},
    {"id":"aperi21:light-cone","title":"Light cone","domain":"modern-physics"},
    {"id":"aperi21:relativistic-momentum","title":"Relativistic momentum","domain":"modern-physics"},
    {"id":"aperi21:relativistic-doppler","title":"Relativistic Doppler effect","domain":"modern-physics"},
    {"id":"aperi21:equivalence-principle","title":"Equivalence principle","domain":"modern-physics"},
    {"id":"aperi21:gravitational-time-dilation","title":"Gravitational time dilation","domain":"modern-physics"},
    {"id":"aperi21:gravitational-redshift","title":"Gravitational redshift","domain":"modern-physics"},
    {"id":"aperi21:light-bending-by-gravity","title":"Bending of light","domain":"modern-physics"},
    {"id":"aperi21:blackbody-radiation","title":"Blackbody radiation","domain":"modern-physics"},
    {"id":"aperi21:wien-displacement-law","title":"Wien's displacement law","domain":"modern-physics"},
    {"id":"aperi21:photoelectric-effect","title":"Photoelectric effect","domain":"modern-physics"},
    {"id":"aperi21:work-function-and-threshold","title":"Work function and threshold frequency","domain":"modern-physics"},
    {"id":"aperi21:compton-scattering","title":"Compton scattering","domain":"modern-physics"},
    {"id":"aperi21:pair-production","title":"Pair production","domain":"modern-physics"},
    {"id":"aperi21:de-broglie-wavelength","title":"de Broglie wavelength","domain":"modern-physics"},
    {"id":"aperi21:electron-diffraction","title":"Electron diffraction","domain":"modern-physics"},
    {"id":"aperi21:double-slit-with-electrons","title":"Double slit with electrons","domain":"modern-physics"},
    {"id":"aperi21:uncertainty-principle","title":"Uncertainty principle","domain":"modern-physics"},
    {"id":"aperi21:wave-function","title":"Wave function","domain":"modern-physics"},
    {"id":"aperi21:superposition-quantum","title":"Quantum superposition","domain":"modern-physics"},
    {"id":"aperi21:measurement-collapse","title":"Measurement and collapse","domain":"modern-physics"},
    {"id":"aperi21:particle-in-a-box","title":"Infinite square well","domain":"modern-physics"},
    {"id":"aperi21:finite-well","title":"Finite square well","domain":"modern-physics"},
    {"id":"aperi21:quantum-tunneling","title":"Quantum tunneling","domain":"modern-physics"},
    {"id":"aperi21:scanning-tunneling-microscope","title":"Scanning tunneling microscope","domain":"modern-physics"},
    {"id":"aperi21:quantum-harmonic-oscillator","title":"Quantum harmonic oscillator","domain":"modern-physics"},
    {"id":"aperi21:hydrogen-spectrum","title":"Hydrogen spectrum","domain":"modern-physics"},
    {"id":"aperi21:bohr-model","title":"Bohr model","domain":"modern-physics"},
    {"id":"aperi21:atomic-orbital","title":"Atomic orbital","domain":"modern-physics"},
    {"id":"aperi21:pauli-exclusion","title":"Pauli exclusion principle","domain":"modern-physics"},
    {"id":"aperi21:electron-configuration","title":"Electron configuration","domain":"modern-physics"},
    {"id":"aperi21:spin","title":"Spin","domain":"modern-physics"},
    {"id":"aperi21:stern-gerlach","title":"Stern–Gerlach experiment","domain":"modern-physics"},
    {"id":"aperi21:zeeman-effect","title":"Zeeman effect","domain":"modern-physics"},
    {"id":"aperi21:laser-and-stimulated-emission","title":"Lasers and stimulated emission","domain":"modern-physics"},
    {"id":"aperi21:nuclear-structure","title":"What a nucleus is made of","domain":"modern-physics"},
    {"id":"aperi21:binding-energy-curve","title":"Binding energy curve","domain":"modern-physics"},
    {"id":"aperi21:radioactive-decay","title":"Radioactive decay","domain":"modern-physics"},
    {"id":"aperi21:decay-types","title":"Types of decay radiation","domain":"modern-physics"},
    {"id":"aperi21:radiometric-dating","title":"Radiometric dating","domain":"modern-physics"},
    {"id":"aperi21:nuclear-fission","title":"Nuclear fission","domain":"modern-physics"},
    {"id":"aperi21:chain-reaction","title":"Chain reaction","domain":"modern-physics"},
    {"id":"aperi21:nuclear-fusion","title":"Nuclear fusion","domain":"modern-physics"},
    {"id":"aperi21:antimatter","title":"Antimatter","domain":"modern-physics"},
    {"id":"aperi21:band-theory","title":"Band theory","domain":"modern-physics"},
    {"id":"aperi21:fermi-level","title":"Fermi level","domain":"modern-physics"},
    {"id":"aperi21:semiconductor-doping","title":"Doping","domain":"modern-physics"},
    {"id":"aperi21:pn-junction","title":"p–n junction","domain":"modern-physics"},
    {"id":"aperi21:diode-and-led","title":"Diodes and LEDs","domain":"modern-physics"},
    {"id":"aperi21:transistor-principle","title":"Transistor","domain":"modern-physics"},
    {"id":"aperi21:photovoltaic-effect","title":"Photovoltaic effect","domain":"modern-physics"},
    {"id":"aperi21:superconductivity","title":"Superconductivity","domain":"modern-physics"},
    {"id":"aperi21:meissner-effect","title":"Meissner effect","domain":"modern-physics"},
    {"id":"aperi21:bose-einstein-condensate","title":"Bose–Einstein condensation","domain":"modern-physics"},
    {"id":"aperi21:scale-of-universe","title":"The scale of the universe","domain":"modern-physics"},
    {"id":"aperi21:rutherford-scattering","title":"Rutherford scattering","domain":"modern-physics"},
    {"id":"aperi21:ionizing-radiation","title":"Ionizing radiation","domain":"modern-physics"},
    {"id":"aperi21:exchange-particles","title":"Exchange particles","domain":"modern-physics"},
  ],
};
