/**
 * 자동 생성 파일 — 직접 편집하지 말 것.
 *
 * 생성: pnpm catalog:gen  (scripts/gen-aperi21-catalog.mts)
 * 출처: 각 sim 의 schema(label/description — description 의 원본은 topics.yaml desc) + docs/topics/topics.yaml(분야).
 */

import type { Aperi21Catalog } from '../catalog-types.js';

export const CATALOG: Aperi21Catalog = {
  locale: "es",
  domains: [
    {"id":"kinematics","name":"Cinemática"},
    {"id":"newtonian-mechanics","name":"Mecánica newtoniana"},
    {"id":"energy-momentum","name":"Trabajo, energía y momento lineal"},
    {"id":"rotation-oscillation","name":"Rotación y oscilación"},
    {"id":"gravitation","name":"Gravitación y astronomía"},
    {"id":"fluids","name":"Fluidos"},
    {"id":"thermodynamics","name":"Física térmica y estadística"},
    {"id":"waves-acoustics","name":"Ondas y acústica"},
    {"id":"optics","name":"Óptica"},
    {"id":"electromagnetism","name":"Electromagnetismo"},
    {"id":"modern-physics","name":"Física moderna"},
  ],
  entries: [
    {"id":"aperi21:reference-frame","title":"Sistema de referencia","description":"Cómo la descripción del movimiento depende del observador","domain":"kinematics"},
    {"id":"aperi21:coordinate-choice","title":"Elección de los ejes","description":"Cómo la elección de los ejes cambia las ecuaciones","domain":"kinematics"},
    {"id":"aperi21:average-velocity","title":"Velocidad media","description":"Una sola velocidad que representa todo un intervalo","domain":"kinematics"},
    {"id":"aperi21:average-acceleration","title":"Aceleración media","description":"Tasa de cambio de la velocidad","domain":"kinematics"},
    {"id":"aperi21:direction-of-acceleration","title":"Dirección de la aceleración","description":"Si apunta a favor o en contra de la velocidad","domain":"kinematics"},
    {"id":"aperi21:uniform-motion","title":"Movimiento uniforme","description":"Movimiento cuya velocidad no cambia","domain":"kinematics"},
    {"id":"aperi21:uniformly-accelerated-motion","title":"Movimiento uniformemente acelerado","description":"Movimiento en que la distancia recorrida en cada intervalo igual crece en una cantidad fija","domain":"kinematics"},
    {"id":"aperi21:position-time-graph","title":"Gráfica posición-tiempo","description":"Una representación cuya pendiente es la velocidad","domain":"kinematics"},
    {"id":"aperi21:velocity-time-graph","title":"Gráfica velocidad-tiempo","description":"Una representación en la que el área bajo la curva se lee como la distancia recorrida","domain":"kinematics"},
    {"id":"aperi21:acceleration-time-graph","title":"Gráfica aceleración-tiempo","description":"El área bajo la gráfica es el cambio de velocidad","domain":"kinematics"},
    {"id":"aperi21:free-fall","title":"Caída libre","description":"Movimiento vertical bajo la sola acción de la gravedad","domain":"kinematics"},
    {"id":"aperi21:vertical-throw","title":"Lanzamiento vertical","description":"La simetría entre subir y bajar","domain":"kinematics"},
    {"id":"aperi21:gravitational-acceleration","title":"Aceleración de la gravedad","description":"Una aceleración que no se detiene ni cuando la velocidad es cero","domain":"kinematics"},
    {"id":"aperi21:terminal-velocity","title":"Velocidad terminal","description":"La rapidez a la que el arrastre y la gravedad se equilibran","domain":"kinematics"},
    {"id":"aperi21:vector-decomposition","title":"Componentes de un vector","description":"Dividir un vector según las direcciones de los ejes","domain":"kinematics"},
    {"id":"aperi21:vector-addition","title":"Suma de vectores","description":"Una suma que une la cola con la punta","domain":"kinematics"},
    {"id":"aperi21:relative-velocity","title":"Velocidad relativa","description":"Conversión de la velocidad entre sistemas de referencia","domain":"kinematics"},
    {"id":"aperi21:river-crossing","title":"Cruzar un río","description":"La trayectoria que resulta de combinar dos velocidades","domain":"kinematics"},
    {"id":"aperi21:projectile-motion","title":"Movimiento de proyectiles","description":"La independencia de las componentes horizontal y vertical","domain":"kinematics"},
    {"id":"aperi21:projectile-range","title":"Alcance y ángulo de lanzamiento","description":"Cómo el ángulo de lanzamiento cambia lo lejos que llega","domain":"kinematics"},
    {"id":"aperi21:trajectory-equation","title":"Ecuación de la trayectoria","description":"La relación entre distancia horizontal y altura que queda al eliminar el tiempo","domain":"kinematics"},
    {"id":"aperi21:uniform-circular-motion","title":"Movimiento circular uniforme","description":"Una trayectoria circular con rapidez constante","domain":"kinematics"},
    {"id":"aperi21:centripetal-acceleration","title":"Aceleración centrípeta","description":"Hacia dónde apunta el cambio de velocidad cuando la rapidez no cambia","domain":"kinematics"},
    {"id":"aperi21:angular-acceleration","title":"Aceleración angular","description":"La tasa de cambio de la velocidad angular","domain":"kinematics"},
    {"id":"aperi21:tangential-normal-acceleration","title":"Aceleración tangencial y normal","description":"Separar el cambio de rapidez del cambio de dirección","domain":"kinematics"},
    {"id":"aperi21:radius-of-curvature","title":"Radio de curvatura","description":"La circunferencia a la que se parece localmente una curva","domain":"kinematics"},
    {"id":"aperi21:stopping-distance","title":"Distancia de detención","description":"La suma de la distancia de reacción y la distancia de frenado","domain":"kinematics"},
    {"id":"aperi21:newtons-first-law","title":"Sistema de referencia inercial","description":"El estado de movimiento cuando no hay fuerza neta","domain":"newtonian-mechanics"},
    {"id":"aperi21:newtons-second-law","title":"Segunda ley de Newton","description":"Fuerza neta, masa y aceleración","domain":"newtonian-mechanics"},
    {"id":"aperi21:newtons-third-law","title":"Acción y reacción","description":"Un par de fuerzas que actúan sobre cuerpos distintos","domain":"newtonian-mechanics"},
    {"id":"aperi21:net-force","title":"Fuerza neta","description":"Suma vectorial de varias fuerzas","domain":"newtonian-mechanics"},
    {"id":"aperi21:free-body-diagram","title":"Diagrama de cuerpo libre","description":"Aislar las fuerzas sobre un solo cuerpo","domain":"newtonian-mechanics"},
    {"id":"aperi21:inertial-vs-gravitational-mass","title":"Masa inercial y masa gravitatoria","description":"Dos definiciones distintas dan el mismo valor","domain":"newtonian-mechanics"},
    {"id":"aperi21:normal-force","title":"Fuerza normal","description":"El empuje perpendicular de una superficie de contacto","domain":"newtonian-mechanics"},
    {"id":"aperi21:apparent-weight","title":"Peso aparente","description":"Una báscula en un ascensor que acelera","domain":"newtonian-mechanics"},
    {"id":"aperi21:static-friction","title":"Rozamiento estático","description":"La fuerza que resiste hasta que el objeto se mueve","domain":"newtonian-mechanics"},
    {"id":"aperi21:kinetic-friction","title":"Rozamiento cinético","description":"Rozamiento mientras desliza","domain":"newtonian-mechanics"},
    {"id":"aperi21:angle-of-friction","title":"Ángulo de rozamiento","description":"La inclinación a la que empieza el deslizamiento","domain":"newtonian-mechanics"},
    {"id":"aperi21:inclined-plane","title":"Plano inclinado","description":"Descomponer la gravedad paralela y perpendicular a la pendiente","domain":"newtonian-mechanics"},
    {"id":"aperi21:tension","title":"Tensión","description":"Cómo una cuerda transmite un tirón","domain":"newtonian-mechanics"},
    {"id":"aperi21:pulley-system","title":"Poleas","description":"Un dispositivo que cambia la dirección y la magnitud de una fuerza","domain":"newtonian-mechanics"},
    {"id":"aperi21:connected-bodies","title":"Cuerpos enlazados","description":"Aceleración de cuerpos que se mueven juntos","domain":"newtonian-mechanics"},
    {"id":"aperi21:spring-force","title":"Fuerza elástica","description":"Fuerza restauradora proporcional al estiramiento","domain":"newtonian-mechanics"},
    {"id":"aperi21:centripetal-force","title":"Fuerza centrípeta","description":"La fuerza hacia dentro que sostiene el movimiento circular, y el camino que se toma cuando desaparece","domain":"newtonian-mechanics"},
    {"id":"aperi21:conical-pendulum","title":"Péndulo cónico","description":"Movimiento circular por la tensión y la gravedad","domain":"newtonian-mechanics"},
    {"id":"aperi21:banked-curve","title":"Curva peraltada","description":"El ángulo de peralte que hace girar un coche sin rozamiento","domain":"newtonian-mechanics"},
    {"id":"aperi21:vertical-loop","title":"Rizo vertical","description":"El punto donde un cuerpo deja el riel cuando no tiene rapidez suficiente para dar la vuelta al rizo","domain":"newtonian-mechanics"},
    {"id":"aperi21:drag-force","title":"Resistencia del aire","description":"Una resistencia proporcional a la primera y la segunda potencia de la rapidez","domain":"newtonian-mechanics"},
    {"id":"aperi21:buoyant-force-as-force","title":"El empuje como fuerza","description":"El empuje hacia arriba de un fluido","domain":"newtonian-mechanics"},
    {"id":"aperi21:non-inertial-frame","title":"Sistema de referencia no inercial","description":"El movimiento visto desde un sistema de referencia acelerado","domain":"newtonian-mechanics"},
    {"id":"aperi21:fictitious-force","title":"Fuerza ficticia","description":"La fuerza aparente de un sistema de referencia no inercial","domain":"newtonian-mechanics"},
    {"id":"aperi21:coriolis-effect","title":"Efecto Coriolis","description":"Una trayectoria que se curva en un sistema de referencia en rotación","domain":"newtonian-mechanics"},
    {"id":"aperi21:impulse-force-relation","title":"Fuerza e impulso","description":"Una fuerza breve y grande y otra larga y pequeña","domain":"newtonian-mechanics"},
    {"id":"aperi21:equilibrium-of-forces","title":"Equilibrio de fuerzas","description":"Fuerza neta nula","domain":"newtonian-mechanics"},
    {"id":"aperi21:atwood-machine","title":"Máquina de Atwood","description":"Un sistema de dos pesas unidas por una polea","domain":"newtonian-mechanics"},
    {"id":"aperi21:balance-scale","title":"Equilibrar una balanza","description":"Equilibrio fijado a la vez por la longitud del brazo y el peso","domain":"newtonian-mechanics"},
    {"id":"aperi21:mechanical-advantage","title":"Ventaja mecánica","description":"Cómo las palancas y las rampas reducen la fuerza necesaria","domain":"newtonian-mechanics"},
    {"id":"aperi21:youngs-modulus","title":"Módulo de Young","description":"Una rigidez que pertenece al material, no a un solo hilo","domain":"newtonian-mechanics"},
    {"id":"aperi21:stress-strain-curve","title":"Curva esfuerzo–deformación","description":"Cómo responde un material al estirarlo","domain":"newtonian-mechanics"},
    {"id":"aperi21:work-by-variable-force","title":"Trabajo realizado por una fuerza variable","description":"El área bajo la gráfica fuerza–desplazamiento","domain":"energy-momentum"},
    {"id":"aperi21:kinetic-energy","title":"Energía cinética","description":"La energía que lleva la rapidez","domain":"energy-momentum"},
    {"id":"aperi21:work-energy-theorem","title":"Teorema del trabajo y la energía","description":"Se repartan como se repartan la fuerza y la distancia, el mismo trabajo da la misma rapidez final","domain":"energy-momentum"},
    {"id":"aperi21:gravitational-potential-energy","title":"Energía potencial gravitatoria","description":"Energía almacenada en la altura","domain":"energy-momentum"},
    {"id":"aperi21:elastic-potential-energy","title":"Energía potencial elástica","description":"La energía almacenada en una deformación","domain":"energy-momentum"},
    {"id":"aperi21:conservative-force","title":"Fuerza conservativa","description":"Una fuerza que realiza el mismo trabajo sea cual sea el camino","domain":"energy-momentum"},
    {"id":"aperi21:non-conservative-force","title":"Fuerza no conservativa","description":"Trabajo que depende de la trayectoria","domain":"energy-momentum"},
    {"id":"aperi21:conservation-of-mechanical-energy","title":"Conservación de la energía mecánica","description":"La parte guardada en la posición y la parte guardada en el movimiento intercambian lugares mientras su suma se mantiene","domain":"energy-momentum"},
    {"id":"aperi21:energy-dissipation","title":"Disipación de energía","description":"La parte que se lleva el rozamiento, y adónde va","domain":"energy-momentum"},
    {"id":"aperi21:potential-energy-curve","title":"Curva de energía potencial","description":"Cómo la forma de la curva decide el movimiento","domain":"energy-momentum"},
    {"id":"aperi21:equilibrium-points","title":"Puntos de equilibrio","description":"Equilibrio estable, inestable e indiferente","domain":"energy-momentum"},
    {"id":"aperi21:efficiency","title":"Eficiencia","description":"La razón entre lo que sale y lo que entra","domain":"energy-momentum"},
    {"id":"aperi21:impulse-momentum-theorem","title":"Teorema del impulso y el momento lineal","description":"El impulso es igual al cambio del momento lineal","domain":"energy-momentum"},
    {"id":"aperi21:conservation-of-momentum","title":"Conservación del momento lineal","description":"Momento lineal total cuando no actúa ninguna fuerza externa","domain":"energy-momentum"},
    {"id":"aperi21:elastic-collision","title":"Choque elástico","description":"Un choque tras el cual nada pierde rapidez","domain":"energy-momentum"},
    {"id":"aperi21:inelastic-collision","title":"Choque inelástico","description":"Un choque en el que una parte no se recupera","domain":"energy-momentum"},
    {"id":"aperi21:perfectly-inelastic-collision","title":"Choque perfectamente inelástico","description":"Cuando los dos se mueven juntos, pegados","domain":"energy-momentum"},
    {"id":"aperi21:two-dimensional-collision","title":"Choque en dos dimensiones","description":"Una conservación que se cumple por separado en cada componente","domain":"energy-momentum"},
    {"id":"aperi21:center-of-mass-motion","title":"Movimiento del centro de masa","description":"El movimiento que las fuerzas internas no pueden cambiar","domain":"energy-momentum"},
    {"id":"aperi21:explosion-and-recoil","title":"Explosión y retroceso","description":"Cuando un sistema en reposo se separa","domain":"energy-momentum"},
    {"id":"aperi21:rocket-equation","title":"La ecuación del cohete","description":"Rapidez obtenida al expulsar combustible","domain":"energy-momentum"},
    {"id":"aperi21:ballistic-pendulum","title":"Péndulo balístico","description":"La medición que une un choque con la conservación de la energía","domain":"energy-momentum"},
    {"id":"aperi21:energy-in-collision","title":"La energía en los choques","description":"Distinguir lo que se conserva de lo que no","domain":"energy-momentum"},
    {"id":"aperi21:energy-flow-diagram","title":"Diagrama de flujo de energía","description":"Adónde va la energía, según el grosor de las ramas","domain":"energy-momentum"},
    {"id":"aperi21:torque","title":"Torque","description":"Lo que hace girar las cosas, y la longitud del brazo de palanca","domain":"rotation-oscillation"},
    {"id":"aperi21:moment-of-inertia","title":"Momento de inercia","description":"Cómo la distribución de la masa determina la resistencia a girar","domain":"rotation-oscillation"},
    {"id":"aperi21:parallel-axis-theorem","title":"Teorema de los ejes paralelos","description":"Momento de inercia al desplazar el eje","domain":"rotation-oscillation"},
    {"id":"aperi21:rotational-kinetic-energy","title":"Energía cinética de rotación","description":"La energía que lleva el giro","domain":"rotation-oscillation"},
    {"id":"aperi21:angular-momentum","title":"Momento angular","description":"La magnitud que hace que lo que gira mantenga su eje","domain":"rotation-oscillation"},
    {"id":"aperi21:conservation-of-angular-momentum","title":"Conservación del momento angular","description":"Por qué recoger los brazos te hace girar más rápido","domain":"rotation-oscillation"},
    {"id":"aperi21:rolling-without-slipping","title":"Rodadura sin deslizamiento","description":"La ligadura que une la traslación con la rotación","domain":"rotation-oscillation"},
    {"id":"aperi21:rolling-race","title":"Carrera de objetos rodantes","description":"Orden de llegada fijado por la distribución de masa","domain":"rotation-oscillation"},
    {"id":"aperi21:static-equilibrium","title":"Equilibrio estático","description":"Tanto la fuerza neta como el torque neto son cero","domain":"rotation-oscillation"},
    {"id":"aperi21:center-of-gravity","title":"Centro de gravedad","description":"El punto que decide cuándo algo se vuelca","domain":"rotation-oscillation"},
    {"id":"aperi21:gyroscopic-precession","title":"Precesión giroscópica","description":"El torque hace girar la dirección del momento angular","domain":"rotation-oscillation"},
    {"id":"aperi21:angular-momentum-vector","title":"Dirección del momento angular","description":"La regla de la mano derecha y el eje de rotación","domain":"rotation-oscillation"},
    {"id":"aperi21:simple-harmonic-motion","title":"Movimiento armónico simple","description":"Movimiento bajo una fuerza restauradora proporcional al desplazamiento","domain":"rotation-oscillation"},
    {"id":"aperi21:shm-energy","title":"Energía en el movimiento armónico simple","description":"Las energías cinética y potencial se intercambian","domain":"rotation-oscillation"},
    {"id":"aperi21:mass-spring-system","title":"Masa en un resorte","description":"El periodo que fijan la masa y la constante del resorte","domain":"rotation-oscillation"},
    {"id":"aperi21:simple-pendulum","title":"Péndulo simple","description":"El periodo con amplitud pequeña","domain":"rotation-oscillation"},
    {"id":"aperi21:physical-pendulum","title":"Péndulo físico","description":"Oscilación de un cuerpo extenso","domain":"rotation-oscillation"},
    {"id":"aperi21:pendulum-amplitude-dependence","title":"Amplitud y periodo","description":"El isocronismo que se rompe con amplitudes grandes","domain":"rotation-oscillation"},
    {"id":"aperi21:damped-oscillation","title":"Oscilación amortiguada","description":"Una oscilación que pierde energía","domain":"rotation-oscillation"},
    {"id":"aperi21:damping-regimes","title":"Tres regímenes de amortiguamiento","description":"Movimiento subamortiguado, críticamente amortiguado y sobreamortiguado","domain":"rotation-oscillation"},
    {"id":"aperi21:driven-oscillation","title":"Oscilación forzada","description":"La respuesta a un forzamiento externo","domain":"rotation-oscillation"},
    {"id":"aperi21:resonance","title":"Resonancia","description":"Cuando la frecuencia de excitación coincide con la frecuencia natural","domain":"rotation-oscillation"},
    {"id":"aperi21:quality-factor","title":"Factor de calidad","description":"Qué tan aguda es una resonancia","domain":"rotation-oscillation"},
    {"id":"aperi21:coupled-oscillators","title":"Osciladores acoplados","description":"Dos osciladores que intercambian energía","domain":"rotation-oscillation"},
    {"id":"aperi21:normal-modes","title":"Modos normales","description":"Las formas propias en que vibra un sistema","domain":"rotation-oscillation"},
    {"id":"aperi21:beats-in-oscillation","title":"Pulsaciones en la oscilación","description":"La suma de dos frecuencias cercanas","domain":"rotation-oscillation"},
    {"id":"aperi21:phase-space","title":"Espacio de fases","description":"El movimiento visto en el plano posición–velocidad","domain":"rotation-oscillation"},
    {"id":"aperi21:nonlinear-oscillation","title":"Oscilación no lineal","description":"Cuando la fuerza restauradora deja de ser proporcional","domain":"rotation-oscillation"},
    {"id":"aperi21:gears","title":"Engranajes","description":"Cómo el número de dientes cambia giro por fuerza","domain":"rotation-oscillation"},
    {"id":"aperi21:newtons-law-of-gravitation","title":"Ley de la gravitación universal de Newton","description":"Una fuerza que disminuye con el cuadrado de la distancia","domain":"gravitation"},
    {"id":"aperi21:gravitational-field","title":"Campo gravitatorio","description":"La intensidad de la gravedad repartida por el espacio","domain":"gravitation"},
    {"id":"aperi21:range-and-surface-gravity","title":"Gravedad y alcance","description":"Cómo un mismo lanzamiento llega más lejos donde la gravedad es más débil","domain":"gravitation"},
    {"id":"aperi21:shell-theorem","title":"Teorema de la cáscara","description":"Gravedad dentro y fuera de una cáscara esférica","domain":"gravitation"},
    {"id":"aperi21:gravity-inside-earth","title":"Gravedad en el interior de la Tierra","description":"Gravedad que disminuye con la profundidad","domain":"gravitation"},
    {"id":"aperi21:gravitational-potential-energy-general","title":"Energía potencial gravitatoria (general)","description":"Una energía negativa medida desde el infinito","domain":"gravitation"},
    {"id":"aperi21:escape-velocity","title":"Velocidad de escape","description":"La rapidez mínima para escapar de la gravedad","domain":"gravitation"},
    {"id":"aperi21:orbital-velocity","title":"Velocidad orbital","description":"La rapidez que mantiene circular una órbita","domain":"gravitation"},
    {"id":"aperi21:circular-orbit","title":"Órbita circular","description":"Movimiento en el que la gravedad es la fuerza centrípeta","domain":"gravitation"},
    {"id":"aperi21:elliptical-orbit","title":"Órbita elíptica","description":"El cuerpo central está en un foco","domain":"gravitation"},
    {"id":"aperi21:keplers-first-law","title":"Primera ley de Kepler","description":"Las órbitas son elipses","domain":"gravitation"},
    {"id":"aperi21:keplers-second-law","title":"Segunda ley de Kepler","description":"Áreas iguales en tiempos iguales","domain":"gravitation"},
    {"id":"aperi21:keplers-third-law","title":"Tercera ley de Kepler","description":"La relación entre el radio de la órbita y el tiempo de una vuelta","domain":"gravitation"},
    {"id":"aperi21:two-body-problem","title":"Problema de los dos cuerpos","description":"Dos cuerpos que orbitan su centro de masa común","domain":"gravitation"},
    {"id":"aperi21:tidal-force","title":"Fuerza de marea","description":"Estiramiento causado por una diferencia de gravedad","domain":"gravitation"},
    {"id":"aperi21:roche-limit","title":"Límite de Roche","description":"La distancia a la que las mareas despedazan un cuerpo","domain":"gravitation"},
    {"id":"aperi21:weightlessness","title":"Ingravidez","description":"Peso aparente en caída libre","domain":"gravitation"},
    {"id":"aperi21:geostationary-orbit","title":"Órbita geoestacionaria","description":"Una órbita que dura lo mismo que una vuelta de la Tierra","domain":"gravitation"},
    {"id":"aperi21:gravitational-slingshot","title":"Asistencia gravitatoria","description":"Cambiar de rapidez al pasar junto a un planeta","domain":"gravitation"},
    {"id":"aperi21:lagrange-points","title":"Puntos de Lagrange","description":"Cinco lugares que siguen el paso de dos cuerpos que orbitan juntos","domain":"gravitation"},
    {"id":"aperi21:orbital-transfer","title":"Transferencia orbital","description":"La transferencia de Hohmann de una órbita baja a una más alta","domain":"gravitation"},
    {"id":"aperi21:black-hole-horizon","title":"Horizonte de sucesos","description":"El radio en que la velocidad de escape alcanza la de la luz","domain":"gravitation"},
    {"id":"aperi21:diurnal-motion","title":"Movimiento diurno","description":"El camino por el que todo el cielo nocturno gira en torno a un punto a lo largo del día","domain":"gravitation"},
    {"id":"aperi21:earth-rotation-day-night","title":"La rotación de la Tierra, el día y la noche","description":"Por qué el día y la noche se alternan en una Tierra que gira","domain":"gravitation"},
    {"id":"aperi21:earth-revolution-constellations","title":"La órbita de la Tierra y las constelaciones","description":"Por qué las constelaciones que vemos cambian con las estaciones","domain":"gravitation"},
    {"id":"aperi21:solar-altitude-shadow","title":"Altura del Sol y sombras","description":"Cuando cambia la altura, la longitud de la sombra y el área sobre la que se reparte la luz solar cambian juntas","domain":"gravitation"},
    {"id":"aperi21:seasonal-sun-path","title":"La trayectoria del Sol a lo largo de las estaciones","description":"Cómo cambian juntas la altura del Sol al mediodía y la duración del día","domain":"gravitation"},
    {"id":"aperi21:axial-tilt-seasons","title":"La inclinación del eje y las estaciones","description":"Las estaciones que produce una Tierra que orbita inclinada","domain":"gravitation"},
    {"id":"aperi21:moon-phases","title":"Fases de la Luna","description":"Qué parte de la Luna iluminada por el Sol mira hacia nosotros","domain":"gravitation"},
    {"id":"aperi21:eclipse","title":"Eclipses solares y lunares","description":"Cuando el Sol, la Tierra y la Luna se alinean","domain":"gravitation"},
    {"id":"aperi21:stellar-parallax","title":"Paralaje estelar","description":"El ángulo que se desplaza una estrella cercana mientras la Tierra orbita el Sol","domain":"gravitation"},
    {"id":"aperi21:apparent-brightness","title":"Brillo aparente","description":"Cómo una misma estrella parece más o menos brillante según la distancia","domain":"gravitation"},
    {"id":"aperi21:magnitude-scale","title":"Magnitud estelar","description":"Cómo se expresa el brillo en magnitudes","domain":"gravitation"},
    {"id":"aperi21:star-color-temperature","title":"Color de las estrellas y temperatura superficial","description":"Cómo la temperatura superficial fija el color de la luz estelar","domain":"gravitation"},
    {"id":"aperi21:expanding-universe","title":"La expansión del universo","description":"Galaxias que se alejan en todas direcciones","domain":"gravitation"},
    {"id":"aperi21:stellar-luminosity","title":"Luminosidad","description":"Cuánta luz emite realmente una estrella","domain":"gravitation"},
    {"id":"aperi21:hr-diagram","title":"Diagrama HR","description":"Un diagrama que ordena las estrellas por temperatura y luminosidad","domain":"gravitation"},
    {"id":"aperi21:star-radiation-gravity-balance","title":"Equilibrio entre presión de radiación y gravedad","description":"Por qué una estrella ni colapsa ni se dispersa","domain":"gravitation"},
    {"id":"aperi21:orbital-decay","title":"Decaimiento orbital","description":"Una órbita frenada por el aire tenue","domain":"gravitation"},
    {"id":"aperi21:inverse-square-law","title":"Ley del inverso del cuadrado","description":"Se diluye a medida que se extiende","domain":"gravitation"},
    {"id":"aperi21:stellar-nucleosynthesis","title":"Nucleosíntesis estelar","description":"Cómo se forman los elementos más pesados dentro de las estrellas","domain":"gravitation"},
    {"id":"aperi21:star-life-cycle","title":"Ciclo de vida de una estrella","description":"Cómo la masa decide el camino de una estrella","domain":"gravitation"},
    {"id":"aperi21:stellar-spectral-class","title":"Clases espectrales estelares","description":"Patrones de líneas de absorción fijados por la temperatura","domain":"gravitation"},
    {"id":"aperi21:supernova-and-neutron-star","title":"Supernova y estrella de neutrones","description":"Un colapso final y un rebote","domain":"gravitation"},
    {"id":"aperi21:exoplanet-detection","title":"Detección de exoplanetas","description":"Las huellas que deja un planeta","domain":"gravitation"},
    {"id":"aperi21:projectile-in-wind","title":"Viento y alcance","description":"Cómo el viento desplaza el punto de caída de un mismo lanzamiento","domain":"fluids"},
    {"id":"aperi21:pressure-isotropy","title":"Isotropía de la presión","description":"La misma magnitud sea cual sea la dirección","domain":"fluids"},
    {"id":"aperi21:hydrostatic-pressure","title":"Presión hidrostática","description":"Presión que crece con la profundidad","domain":"fluids"},
    {"id":"aperi21:pressure-and-container-shape","title":"Forma del recipiente y presión en el fondo","description":"Cómo la presión en el fondo no depende de la forma","domain":"fluids"},
    {"id":"aperi21:atmospheric-pressure","title":"Presión atmosférica","description":"El peso de la columna de aire","domain":"fluids"},
    {"id":"aperi21:barometer","title":"Barómetro","description":"La altura de una columna de mercurio","domain":"fluids"},
    {"id":"aperi21:manometer","title":"Manómetro","description":"Leer la presión en una columna de líquido","domain":"fluids"},
    {"id":"aperi21:pascals-principle","title":"Principio de Pascal","description":"La presión transmitida y la prensa hidráulica","domain":"fluids"},
    {"id":"aperi21:buoyancy","title":"Empuje","description":"La fuerza hacia arriba que queda porque la cara inferior es empujada con más fuerza","domain":"fluids"},
    {"id":"aperi21:archimedes-principle","title":"Principio de Arquímedes — la magnitud del empuje","description":"La fuerza recibida es igual al peso del fluido desplazado","domain":"fluids"},
    {"id":"aperi21:floating-and-draft","title":"Cuánto se hunde un cuerpo que flota","description":"Qué determina el volumen sumergido","domain":"fluids"},
    {"id":"aperi21:stability-of-floating-body","title":"Estabilidad de un cuerpo flotante","description":"La relación entre el centro de gravedad y el centro de empuje","domain":"fluids"},
    {"id":"aperi21:continuity-equation","title":"Ecuación de continuidad","description":"Sección transversal y rapidez del flujo se compensan","domain":"fluids"},
    {"id":"aperi21:bernoullis-principle","title":"Principio de Bernoulli","description":"El intercambio entre rapidez y presión","domain":"fluids"},
    {"id":"aperi21:venturi-effect","title":"Efecto Venturi","description":"Menor presión donde el tubo se estrecha","domain":"fluids"},
    {"id":"aperi21:torricellis-law","title":"Ley de Torricelli","description":"La rapidez del flujo que sale por un orificio","domain":"fluids"},
    {"id":"aperi21:lift-force","title":"Sustentación","description":"Cómo fluye el aire por encima y por debajo de un ala","domain":"fluids"},
    {"id":"aperi21:viscosity","title":"Viscosidad","description":"Rozamiento entre capas","domain":"fluids"},
    {"id":"aperi21:poiseuille-flow","title":"Flujo laminar en un tubo","description":"El caudal crece con la cuarta potencia del radio","domain":"fluids"},
    {"id":"aperi21:stokes-drag","title":"Arrastre de Stokes","description":"Lo que, en un flujo lento, fija con qué rapidez se hunde un tamaño","domain":"fluids"},
    {"id":"aperi21:laminar-vs-turbulent","title":"Flujo laminar y turbulento","description":"Dos regímenes de flujo","domain":"fluids"},
    {"id":"aperi21:reynolds-number","title":"Número de Reynolds","description":"El número adimensional que fija el carácter de un flujo","domain":"fluids"},
    {"id":"aperi21:boundary-layer","title":"Capa límite","description":"La capa junto a una pared donde el flujo se frena hasta cero","domain":"fluids"},
    {"id":"aperi21:surface-tension","title":"Tensión superficial","description":"La tracción de la superficie del agua que cambia de dirección para sostener una carga","domain":"fluids"},
    {"id":"aperi21:laplace-pressure","title":"Presión de Laplace","description":"El salto de presión que crea una superficie curva","domain":"fluids"},
    {"id":"aperi21:capillary-action","title":"Capilaridad","description":"Ascenso y descenso en tubos estrechos","domain":"fluids"},
    {"id":"aperi21:wetting-and-contact-angle","title":"Mojado y ángulo de contacto","description":"Cuánto se extiende un líquido sobre un sólido","domain":"fluids"},
    {"id":"aperi21:drag-in-fluid","title":"Arrastre en un fluido","description":"La resistencia en un flujo rápido que fija la forma de la parte trasera","domain":"fluids"},
    {"id":"aperi21:thermal-equilibrium","title":"Equilibrio térmico","description":"El estado que alcanzan dos sistemas en contacto","domain":"thermodynamics"},
    {"id":"aperi21:specific-heat","title":"Calor específico","description":"Cuánto cambia la temperatura, material por material","domain":"thermodynamics"},
    {"id":"aperi21:calorimetry","title":"Calorimetría","description":"La temperatura final de una mezcla","domain":"thermodynamics"},
    {"id":"aperi21:latent-heat","title":"Calor latente","description":"Por qué la temperatura se detiene durante un cambio de estado","domain":"thermodynamics"},
    {"id":"aperi21:phase-diagram","title":"Diagrama de fases","description":"La fase que fijan la presión y la temperatura","domain":"thermodynamics"},
    {"id":"aperi21:triple-point","title":"Punto triple","description":"La condición en que coexisten tres fases","domain":"thermodynamics"},
    {"id":"aperi21:thermal-conduction","title":"Conducción del calor","description":"Transferencia por contacto","domain":"thermodynamics"},
    {"id":"aperi21:thermal-convection","title":"Convección","description":"Calor transportado por un fluido en movimiento","domain":"thermodynamics"},
    {"id":"aperi21:thermal-radiation","title":"Radiación térmica","description":"Calor que viaja sin un medio","domain":"thermodynamics"},
    {"id":"aperi21:stefan-boltzmann-law","title":"Ley de Stefan–Boltzmann","description":"Radiación que crece con la cuarta potencia de la temperatura","domain":"thermodynamics"},
    {"id":"aperi21:thermal-expansion","title":"Dilatación térmica","description":"El cambio de longitud de un sólido con la temperatura","domain":"thermodynamics"},
    {"id":"aperi21:bimetal","title":"Lámina bimetálica","description":"Flexión por una dilatación desigual","domain":"thermodynamics"},
    {"id":"aperi21:ideal-gas-law","title":"Ley de los gases ideales","description":"Cómo se relacionan presión, volumen y temperatura","domain":"thermodynamics"},
    {"id":"aperi21:boyles-law","title":"Ley de Boyle","description":"Presión y volumen a temperatura constante","domain":"thermodynamics"},
    {"id":"aperi21:charles-law","title":"Ley de Charles","description":"Volumen y temperatura a presión constante","domain":"thermodynamics"},
    {"id":"aperi21:gas-pressure","title":"Moléculas y presión","description":"Cómo al subir la temperatura las moléculas golpean la pared más a menudo y con más fuerza, y la presión sube","domain":"thermodynamics"},
    {"id":"aperi21:pressure-from-collisions","title":"Presión debida a los choques","description":"El momento lineal que las moléculas llevan a la pared","domain":"thermodynamics"},
    {"id":"aperi21:maxwell-boltzmann-distribution","title":"Distribución de Maxwell–Boltzmann","description":"La distribución de las rapideces moleculares","domain":"thermodynamics"},
    {"id":"aperi21:mean-free-path","title":"Recorrido libre medio","description":"La distancia entre choques","domain":"thermodynamics"},
    {"id":"aperi21:first-law-of-thermodynamics","title":"Primera ley de la termodinámica","description":"Cómo se relacionan la energía interna, el trabajo y el calor","domain":"thermodynamics"},
    {"id":"aperi21:pv-diagram","title":"Diagrama PV","description":"Donde el área es trabajo","domain":"thermodynamics"},
    {"id":"aperi21:isothermal-process","title":"Proceso isotérmico","description":"Un cambio que mantiene fija la temperatura","domain":"thermodynamics"},
    {"id":"aperi21:adiabatic-process","title":"Proceso adiabático","description":"Un cambio sin entrada ni salida de calor","domain":"thermodynamics"},
    {"id":"aperi21:isobaric-isochoric","title":"Procesos isobárico e isocórico","description":"Cambios a presión fija o a volumen fijo","domain":"thermodynamics"},
    {"id":"aperi21:cyclic-process","title":"Proceso cíclico","description":"Un cambio que vuelve a donde empezó","domain":"thermodynamics"},
    {"id":"aperi21:second-law-of-thermodynamics","title":"Segunda ley de la termodinámica","description":"Un cambio que va en un solo sentido","domain":"thermodynamics"},
    {"id":"aperi21:irreversibility","title":"Entropía e irreversibilidad","description":"Por qué no se puede deshacer","domain":"thermodynamics"},
    {"id":"aperi21:heat-engine","title":"Máquina térmica","description":"Un ciclo que convierte calor en trabajo","domain":"thermodynamics"},
    {"id":"aperi21:carnot-cycle","title":"Ciclo de Carnot","description":"La eficiencia máxima teórica","domain":"thermodynamics"},
    {"id":"aperi21:refrigerator-heat-pump","title":"Refrigeradores y bombas de calor","description":"Mover calor aportando trabajo","domain":"thermodynamics"},
    {"id":"aperi21:brownian-motion","title":"Movimiento browniano","description":"Movimiento aleatorio impulsado por choques moleculares","domain":"thermodynamics"},
    {"id":"aperi21:diffusion","title":"Difusión","description":"Flujo impulsado por una diferencia de concentración","domain":"thermodynamics"},
    {"id":"aperi21:random-walk","title":"Camino aleatorio","description":"Una distancia que crece como una raíz cuadrada","domain":"thermodynamics"},
    {"id":"aperi21:statistical-fluctuation","title":"Fluctuación estadística","description":"La oscilación que crece cuando hay pocas partículas","domain":"thermodynamics"},
    {"id":"aperi21:maxwells-demon","title":"El demonio de Maxwell","description":"Un gas que se separa solo en la medida en que se observa","domain":"thermodynamics"},
    {"id":"aperi21:insulation","title":"Aislamiento térmico","description":"Frenar el flujo de calor","domain":"thermodynamics"},
    {"id":"aperi21:albedo","title":"Albedo","description":"La fracción de luz devuelta","domain":"thermodynamics"},
    {"id":"aperi21:radiative-equilibrium","title":"Equilibrio radiativo","description":"La temperatura que se fija cuando lo que sale iguala a lo que entra","domain":"thermodynamics"},
    {"id":"aperi21:greenhouse-effect","title":"Efecto invernadero","description":"Una capa que devuelve el infrarrojo hacia abajo calienta el suelo","domain":"thermodynamics"},
    {"id":"aperi21:wave-basics","title":"Magnitudes básicas de una onda","description":"Longitud de onda, frecuencia, rapidez y amplitud","domain":"waves-acoustics"},
    {"id":"aperi21:wave-vs-particle-transport","title":"Lo que transporta una onda","description":"El medio se queda en su sitio, la energía avanza","domain":"waves-acoustics"},
    {"id":"aperi21:transverse-wave","title":"Onda transversal","description":"El medio vibra en ángulo recto con la dirección en que viaja la onda","domain":"waves-acoustics"},
    {"id":"aperi21:longitudinal-wave","title":"Onda longitudinal","description":"Vibración paralela a la dirección de propagación","domain":"waves-acoustics"},
    {"id":"aperi21:wave-speed-in-medium","title":"La rapidez de onda y el medio","description":"La rapidez fijada por la tensión y la densidad lineal","domain":"waves-acoustics"},
    {"id":"aperi21:wavefront-and-ray","title":"Frentes de onda y rayos","description":"Superficies de igual fase y las líneas normales a ellas","domain":"waves-acoustics"},
    {"id":"aperi21:huygens-principle","title":"Principio de Huygens","description":"Cada punto de un frente de onda se convierte en una nueva fuente","domain":"waves-acoustics"},
    {"id":"aperi21:superposition","title":"Superposición","description":"Qué ocurre cuando las ondas se superponen","domain":"waves-acoustics"},
    {"id":"aperi21:constructive-destructive","title":"Interferencia constructiva y destructiva","description":"Cómo la diferencia de fase fija el tamaño de la suma","domain":"waves-acoustics"},
    {"id":"aperi21:interference","title":"Interferencia","description":"El patrón que forman dos fuentes","domain":"waves-acoustics"},
    {"id":"aperi21:standing-wave","title":"Onda estacionaria","description":"Una onda cuyos nodos y vientres quedan fijos","domain":"waves-acoustics"},
    {"id":"aperi21:harmonics","title":"Armónicos","description":"Frecuencias fijadas por la frontera","domain":"waves-acoustics"},
    {"id":"aperi21:string-vibration","title":"Cuerda que vibra","description":"La altura del sonido fijada por la longitud que vibra","domain":"waves-acoustics"},
    {"id":"aperi21:air-column-resonance","title":"Resonancia en columnas de aire","description":"Tubo abierto frente a tubo cerrado","domain":"waves-acoustics"},
    {"id":"aperi21:beats","title":"Pulsaciones","description":"La suma de dos frecuencias cercanas","domain":"waves-acoustics"},
    {"id":"aperi21:doppler-effect","title":"Efecto Doppler","description":"Cómo una fuente en movimiento separa el espaciado de los frentes de onda por delante y por detrás","domain":"waves-acoustics"},
    {"id":"aperi21:doppler-source-vs-observer","title":"Fuente en movimiento frente a observador en movimiento","description":"La asimetría según quién se mueve","domain":"waves-acoustics"},
    {"id":"aperi21:shock-wave","title":"Onda de choque","description":"El cono que se forma al superar la rapidez del sonido","domain":"waves-acoustics"},
    {"id":"aperi21:sound-intensity","title":"Intensidad del sonido","description":"Disminución con el cuadrado de la distancia","domain":"waves-acoustics"},
    {"id":"aperi21:reflection-of-waves","title":"Reflexión de ondas","description":"Fase en un extremo fijo y en un extremo libre","domain":"waves-acoustics"},
    {"id":"aperi21:refraction-of-waves","title":"Refracción de las ondas","description":"Un cambio de rapidez desvía la dirección","domain":"waves-acoustics"},
    {"id":"aperi21:diffraction","title":"Difracción","description":"Ondas que rodean los obstáculos","domain":"waves-acoustics"},
    {"id":"aperi21:slit-width-and-diffraction","title":"Ancho de la rendija y difracción","description":"Cómo la razón entre abertura y longitud de onda fija cuánto se abren las ondas","domain":"waves-acoustics"},
    {"id":"aperi21:wave-energy","title":"Energía de una onda","description":"La energía crece con el cuadrado de la amplitud","domain":"waves-acoustics"},
    {"id":"aperi21:wave-attenuation","title":"Atenuación de una onda","description":"Una amplitud que baja en la misma proporción en cada distancia igual","domain":"waves-acoustics"},
    {"id":"aperi21:impedance-mismatch","title":"Desacoplamiento de impedancias","description":"Cuánto se refleja en una frontera","domain":"waves-acoustics"},
    {"id":"aperi21:noise-cancellation","title":"Cancelación activa de ruido","description":"Superposición de una onda invertida","domain":"waves-acoustics"},
    {"id":"aperi21:sound-source-vibration","title":"Sonido y vibración","description":"Un objeto que suena vibra, y cuando la vibración se detiene, también el sonido","domain":"waves-acoustics"},
    {"id":"aperi21:sound-through-materials","title":"El sonido a través de los materiales","description":"La rapidez del sonido y su paso, fijados por el medio","domain":"waves-acoustics"},
    {"id":"aperi21:digital-vs-analog-signal","title":"Señales digitales y analógicas","description":"Dos maneras de resistir el ruido","domain":"waves-acoustics"},
    {"id":"aperi21:seismic-waves","title":"Ondas sísmicas","description":"Ondas P y S que atraviesan la Tierra","domain":"waves-acoustics"},
    {"id":"aperi21:rectilinear-propagation","title":"La luz viaja en línea recta","description":"Las sombras y el modelo de rayos","domain":"optics"},
    {"id":"aperi21:shadow-umbra-penumbra","title":"Umbra y penumbra","description":"Cómo el tamaño de una fuente de luz da forma al borde de una sombra","domain":"optics"},
    {"id":"aperi21:pinhole-camera","title":"Cámara estenopeica","description":"La imagen que forma un solo orificio","domain":"optics"},
    {"id":"aperi21:law-of-reflection","title":"Ley de la reflexión","description":"Ángulo de incidencia y ángulo de reflexión","domain":"optics"},
    {"id":"aperi21:specular-diffuse-reflection","title":"Reflexión especular y difusa","description":"Una reflexión determinada por la rugosidad de la superficie","domain":"optics"},
    {"id":"aperi21:plane-mirror-image","title":"Imagen en un espejo plano","description":"La imagen virtual detrás del espejo, donde se cruza la luz prolongada hacia atrás","domain":"optics"},
    {"id":"aperi21:multiple-mirror-images","title":"Imágenes en dos espejos","description":"Cómo el ángulo entre dos espejos determina el número de imágenes","domain":"optics"},
    {"id":"aperi21:concave-mirror","title":"Espejo cóncavo","description":"El foco y la imagen real","domain":"optics"},
    {"id":"aperi21:convex-mirror","title":"Espejo convexo","description":"Un campo de visión más amplio y una imagen virtual","domain":"optics"},
    {"id":"aperi21:snells-law","title":"Ley de Snell","description":"Cómo se desvía la trayectoria según el medio","domain":"optics"},
    {"id":"aperi21:apparent-depth","title":"Profundidad aparente","description":"Por qué los objetos bajo el agua parecen elevados","domain":"optics"},
    {"id":"aperi21:total-internal-reflection","title":"Reflexión total interna","description":"El ángulo crítico y su condición","domain":"optics"},
    {"id":"aperi21:optical-fiber","title":"Fibra óptica","description":"Luz atrapada por reflexión total interna","domain":"optics"},
    {"id":"aperi21:mirage","title":"Espejismo","description":"Luz curvada por un gradiente de densidad","domain":"optics"},
    {"id":"aperi21:dispersion","title":"Dispersión","description":"Índice de refracción que depende de la longitud de onda","domain":"optics"},
    {"id":"aperi21:prism","title":"Prisma","description":"Un espectro que se abre por dispersión","domain":"optics"},
    {"id":"aperi21:rainbow","title":"Arcoíris","description":"Refracción y reflexión dentro de las gotas de lluvia","domain":"optics"},
    {"id":"aperi21:thin-lens","title":"Lente delgada","description":"Focos y formación de imágenes","domain":"optics"},
    {"id":"aperi21:converging-diverging-lens","title":"Lentes convergentes y divergentes","description":"Una lente que concentra la luz y otra que la esparce","domain":"optics"},
    {"id":"aperi21:magnification","title":"Aumento","description":"El tamaño de la imagen y el tamaño del objeto","domain":"optics"},
    {"id":"aperi21:focal-length","title":"Distancia focal","description":"Cómo la distancia focal decide dónde se forma la imagen","domain":"optics"},
    {"id":"aperi21:real-vs-virtual-image","title":"Imágenes reales y virtuales","description":"¿La luz se junta de verdad?","domain":"optics"},
    {"id":"aperi21:lens-combination","title":"Combinación de lentes","description":"El foco combinado de dos lentes","domain":"optics"},
    {"id":"aperi21:spherical-aberration","title":"Aberración esférica","description":"Los rayos del borde se enfocan en otro lugar","domain":"optics"},
    {"id":"aperi21:chromatic-aberration","title":"Aberración cromática","description":"Un foco distinto para cada longitud de onda","domain":"optics"},
    {"id":"aperi21:human-eye-accommodation","title":"Acomodación del ojo","description":"Cómo el cristalino enfoca las cosas","domain":"optics"},
    {"id":"aperi21:myopia-hyperopia","title":"Miopía e hipermetropía","description":"Dónde se forma la imagen y cómo la corrigen las gafas","domain":"optics"},
    {"id":"aperi21:magnifying-glass","title":"Lupa","description":"Un objeto dentro del foco cercano","domain":"optics"},
    {"id":"aperi21:microscope","title":"Microscopio","description":"Los aumentos del objetivo y del ocular se multiplican","domain":"optics"},
    {"id":"aperi21:telescope","title":"Telescopio","description":"Aumento fijado por la razón entre las distancias focales","domain":"optics"},
    {"id":"aperi21:youngs-double-slit","title":"Doble rendija de Young","description":"Prueba de que la luz es una onda","domain":"optics"},
    {"id":"aperi21:single-slit-diffraction","title":"Difracción por una rendija","description":"El patrón que crea un ancho","domain":"optics"},
    {"id":"aperi21:diffraction-grating","title":"Red de difracción","description":"Máximos nítidos creados por muchas rendijas","domain":"optics"},
    {"id":"aperi21:thin-film-interference","title":"Interferencia en películas delgadas","description":"Color creado por el espesor","domain":"optics"},
    {"id":"aperi21:newtons-rings","title":"Anillos de Newton","description":"Interferencia entre una superficie curva y una plana","domain":"optics"},
    {"id":"aperi21:resolving-power","title":"Poder de resolución","description":"El límite para distinguir dos puntos","domain":"optics"},
    {"id":"aperi21:polarization","title":"Polarización","description":"Selección del plano de vibración","domain":"optics"},
    {"id":"aperi21:malus-law","title":"Ley de Malus","description":"Intensidad a través de un polarizador","domain":"optics"},
    {"id":"aperi21:brewster-angle","title":"Ángulo de Brewster","description":"El ángulo en que la luz reflejada queda totalmente polarizada","domain":"optics"},
    {"id":"aperi21:birefringence","title":"Birrefringencia","description":"Índice de refracción que depende de la dirección","domain":"optics"},
    {"id":"aperi21:scattering","title":"Dispersión","description":"El tamaño de partícula que separa el cielo azul de las nubes blancas","domain":"optics"},
    {"id":"aperi21:rayleigh-scattering","title":"Dispersión de Rayleigh","description":"Una dispersión que crece bruscamente cuanto más corta es la longitud de onda","domain":"optics"},
    {"id":"aperi21:seeing-requires-light","title":"Para ver hace falta luz","description":"Sin luz, un objeto no se puede ver","domain":"optics"},
    {"id":"aperi21:color-addition","title":"Suma de luces","description":"El color que forman tres luces donde se superponen","domain":"optics"},
    {"id":"aperi21:object-color","title":"El color de un objeto","description":"El color que fija la luz que un objeto devuelve","domain":"optics"},
    {"id":"aperi21:light-through-materials","title":"La luz y los materiales","description":"Cómo pasa la luz depende del material","domain":"optics"},
    {"id":"aperi21:electric-charge","title":"Carga eléctrica","description":"La carga, que solo es de dos clases","domain":"electromagnetism"},
    {"id":"aperi21:charging-methods","title":"Métodos de electrización","description":"Frotamiento, contacto e inducción","domain":"electromagnetism"},
    {"id":"aperi21:coulombs-law","title":"Ley de Coulomb","description":"La fuerza entre cargas, que se debilita con el cuadrado de cuántas veces se alejan","domain":"electromagnetism"},
    {"id":"aperi21:superposition-of-forces","title":"Superposición de fuerzas eléctricas","description":"Sumar las fuerzas de varias cargas","domain":"electromagnetism"},
    {"id":"aperi21:electric-field","title":"Campo eléctrico","description":"La fuerza sobre una carga unitaria","domain":"electromagnetism"},
    {"id":"aperi21:field-lines","title":"Líneas de campo eléctrico","description":"La convención para dibujar un campo y su significado","domain":"electromagnetism"},
    {"id":"aperi21:field-of-dipole","title":"Campo eléctrico de un dipolo","description":"Dos cargas opuestas cercanas","domain":"electromagnetism"},
    {"id":"aperi21:uniform-field","title":"Campo eléctrico uniforme","description":"El campo entre placas paralelas","domain":"electromagnetism"},
    {"id":"aperi21:charge-in-uniform-field","title":"Una carga en un campo uniforme","description":"Igual que un proyectil","domain":"electromagnetism"},
    {"id":"aperi21:gausss-law","title":"Ley de Gauss","description":"Flujo eléctrico a través de una superficie cerrada","domain":"electromagnetism"},
    {"id":"aperi21:field-of-charged-sphere","title":"Campo de una esfera cargada","description":"Por qué difieren el interior y el exterior","domain":"electromagnetism"},
    {"id":"aperi21:equipotential-surface","title":"Superficies equipotenciales","description":"Superficies perpendiculares al campo","domain":"electromagnetism"},
    {"id":"aperi21:potential-vs-field","title":"Potencial y campo eléctrico","description":"La relación de la pendiente","domain":"electromagnetism"},
    {"id":"aperi21:electrostatic-shielding","title":"Blindaje electrostático","description":"Por qué el campo dentro de un conductor es cero","domain":"electromagnetism"},
    {"id":"aperi21:charge-on-conductor-surface","title":"Carga en la superficie de un conductor","description":"La carga se amontona en el extremo puntiagudo","domain":"electromagnetism"},
    {"id":"aperi21:dielectric","title":"Dieléctrico","description":"La polarización debilita el campo","domain":"electromagnetism"},
    {"id":"aperi21:parallel-plate-capacitor","title":"Condensador de placas paralelas","description":"Capacidad fijada por el área y la separación","domain":"electromagnetism"},
    {"id":"aperi21:capacitors-in-circuit","title":"Conexión de condensadores","description":"Combinación en serie y en paralelo","domain":"electromagnetism"},
    {"id":"aperi21:energy-in-capacitor","title":"Energía en un condensador","description":"El trabajo invertido en mover la carga","domain":"electromagnetism"},
    {"id":"aperi21:electric-current","title":"Corriente eléctrica","description":"El flujo de carga y su convenio de signo","domain":"electromagnetism"},
    {"id":"aperi21:drift-velocity","title":"Velocidad de deriva","description":"La rapidez con que se arrastran los electrones dentro de un cable","domain":"electromagnetism"},
    {"id":"aperi21:ohms-law","title":"Ley de Ohm","description":"Voltaje, corriente y resistencia","domain":"electromagnetism"},
    {"id":"aperi21:resistance-and-geometry","title":"Resistencia y forma","description":"Cómo influyen la longitud y la sección transversal","domain":"electromagnetism"},
    {"id":"aperi21:temperature-and-resistance","title":"Temperatura y resistencia","description":"Metales y semiconductores van en sentidos opuestos","domain":"electromagnetism"},
    {"id":"aperi21:series-parallel-resistors","title":"Resistencias en serie y en paralelo","description":"Cómo la conexión cambia la corriente que entrega una batería","domain":"electromagnetism"},
    {"id":"aperi21:emf-and-internal-resistance","title":"Fem y resistencia interna","description":"Por qué baja el voltaje en los bornes","domain":"electromagnetism"},
    {"id":"aperi21:kirchhoffs-current-law","title":"Ley de corrientes de Kirchhoff","description":"Conservación de la carga en un nudo","domain":"electromagnetism"},
    {"id":"aperi21:kirchhoffs-voltage-law","title":"Ley de voltajes de Kirchhoff","description":"Conservación de la energía en una malla","domain":"electromagnetism"},
    {"id":"aperi21:wheatstone-bridge","title":"Puente de Wheatstone","description":"Medir una resistencia por equilibrio","domain":"electromagnetism"},
    {"id":"aperi21:joule-heating","title":"Efecto Joule","description":"El calor que produce la resistencia","domain":"electromagnetism"},
    {"id":"aperi21:rc-circuit","title":"Circuito RC","description":"La constante de tiempo de la carga y la descarga","domain":"electromagnetism"},
    {"id":"aperi21:magnetic-field","title":"Campo magnético","description":"Cómo se reparte la fuerza magnética alrededor de un imán","domain":"electromagnetism"},
    {"id":"aperi21:magnetic-field-lines","title":"Líneas de campo magnético","description":"Líneas que nunca se cortan y siempre se cierran","domain":"electromagnetism"},
    {"id":"aperi21:lorentz-force","title":"Fuerza de Lorentz","description":"La fuerza sobre una carga que se mueve en un campo magnético","domain":"electromagnetism"},
    {"id":"aperi21:charged-particle-in-magnetic-field","title":"Cargas girando en un campo magnético","description":"El mismo tiempo por vuelta sea cual sea la rapidez","domain":"electromagnetism"},
    {"id":"aperi21:velocity-selector","title":"Selector de velocidades","description":"Equilibrio entre las fuerzas eléctrica y magnética","domain":"electromagnetism"},
    {"id":"aperi21:mass-spectrometer","title":"Espectrómetro de masas","description":"Separar masas por el radio","domain":"electromagnetism"},
    {"id":"aperi21:force-on-current-wire","title":"Fuerza sobre un hilo con corriente","description":"La fuerza magnética sobre un hilo que lleva corriente","domain":"electromagnetism"},
    {"id":"aperi21:biot-savart-law","title":"Ley de Biot–Savart","description":"El campo magnético de los elementos de corriente","domain":"electromagnetism"},
    {"id":"aperi21:field-of-straight-wire","title":"El campo magnético de una corriente","description":"Una intensidad que disminuye con la distancia","domain":"electromagnetism"},
    {"id":"aperi21:field-of-loop-and-solenoid","title":"Espira y solenoide","description":"El campo magnético a lo largo del eje","domain":"electromagnetism"},
    {"id":"aperi21:amperes-law","title":"Ley de Ampère","description":"Circulación del campo magnético alrededor de una corriente","domain":"electromagnetism"},
    {"id":"aperi21:force-between-wires","title":"Fuerza entre hilos paralelos","description":"Dos corrientes paralelas se atraen o se repelen","domain":"electromagnetism"},
    {"id":"aperi21:magnetic-dipole","title":"Dipolo magnético","description":"Una espira de corriente y un imán son lo mismo","domain":"electromagnetism"},
    {"id":"aperi21:magnetic-materials","title":"Materiales magnéticos","description":"Ferromagnetismo, paramagnetismo y diamagnetismo","domain":"electromagnetism"},
    {"id":"aperi21:faradays-law","title":"Ley de Faraday","description":"La fem producida por un flujo variable","domain":"electromagnetism"},
    {"id":"aperi21:lenzs-law","title":"Ley de Lenz","description":"Una corriente inducida que se opone al cambio","domain":"electromagnetism"},
    {"id":"aperi21:motional-emf","title":"Fem de movimiento","description":"El voltaje que produce un hilo en movimiento","domain":"electromagnetism"},
    {"id":"aperi21:eddy-current","title":"Corrientes de Foucault","description":"Corrientes inducidas dentro de un conductor macizo","domain":"electromagnetism"},
    {"id":"aperi21:self-inductance","title":"Autoinductancia","description":"Una bobina que se opone a los cambios de su propio flujo","domain":"electromagnetism"},
    {"id":"aperi21:mutual-inductance","title":"Inductancia mutua","description":"Una fem inducida en un circuito vecino","domain":"electromagnetism"},
    {"id":"aperi21:energy-in-inductor","title":"Energía en un inductor","description":"Energía almacenada en el campo magnético","domain":"electromagnetism"},
    {"id":"aperi21:rl-circuit","title":"Circuito RL","description":"Por qué la corriente sube despacio","domain":"electromagnetism"},
    {"id":"aperi21:lc-oscillation","title":"Oscilación LC","description":"La energía eléctrica y la magnética se intercambian","domain":"electromagnetism"},
    {"id":"aperi21:ac-generation","title":"Generación de corriente alterna","description":"Una bobina que gira y una onda sinusoidal","domain":"electromagnetism"},
    {"id":"aperi21:reactance","title":"Reactancia e impedancia","description":"Una resistencia que depende de la frecuencia","domain":"electromagnetism"},
    {"id":"aperi21:phase-in-ac-circuit","title":"Diferencia de fase en circuitos de CA","description":"Voltaje y corriente que se desfasan","domain":"electromagnetism"},
    {"id":"aperi21:series-rlc-resonance","title":"Resonancia RLC","description":"La frecuencia en la que la impedancia es mínima","domain":"electromagnetism"},
    {"id":"aperi21:transformer","title":"Transformador","description":"Las espiras y la razón de voltajes","domain":"electromagnetism"},
    {"id":"aperi21:motor","title":"Motor eléctrico","description":"Girar gracias a la fuerza sobre una corriente","domain":"electromagnetism"},
    {"id":"aperi21:generator","title":"Generador","description":"Enciende la bombilla y la manivela se vuelve más pesada","domain":"electromagnetism"},
    {"id":"aperi21:displacement-current","title":"Corriente de desplazamiento","description":"El término que salva el hueco del condensador","domain":"electromagnetism"},
    {"id":"aperi21:maxwells-equations","title":"Ecuaciones de Maxwell","description":"La cadena en la que la electricidad y el magnetismo se generan mutuamente","domain":"electromagnetism"},
    {"id":"aperi21:electromagnetic-wave","title":"Ondas electromagnéticas","description":"Campos eléctricos y magnéticos que se propagan solos","domain":"electromagnetism"},
    {"id":"aperi21:poynting-vector","title":"Vector de Poynting","description":"La energía que atraviesa el espacio alrededor de un cable","domain":"electromagnetism"},
    {"id":"aperi21:radiation-pressure","title":"Presión de radiación","description":"El empuje de la luz","domain":"electromagnetism"},
    {"id":"aperi21:antenna-radiation","title":"Radiación de una antena","description":"Las ondas que emite una carga acelerada","domain":"electromagnetism"},
    {"id":"aperi21:magnet-attraction","title":"Lo que se pega a un imán","description":"Cosas que un imán atrae y cosas que no","domain":"electromagnetism"},
    {"id":"aperi21:magnetic-poles","title":"Los dos polos de un imán","description":"Polos iguales se repelen, polos opuestos se atraen","domain":"electromagnetism"},
    {"id":"aperi21:simple-circuit","title":"Armar un circuito eléctrico","description":"Solo circula si está unido; si se corta, la bombilla se apaga","domain":"electromagnetism"},
    {"id":"aperi21:electromagnet","title":"Electroimán","description":"Un imán solo mientras circula corriente","domain":"electromagnetism"},
    {"id":"aperi21:iv-characteristic","title":"Curvas características I–V","description":"Componentes cuya corriente no sigue al voltaje en línea recta","domain":"electromagnetism"},
    {"id":"aperi21:thermistor-and-ldr","title":"Termistor y LDR","description":"Una resistencia que cambia con la temperatura y la luz","domain":"electromagnetism"},
    {"id":"aperi21:potential-divider","title":"Divisor de tensión","description":"Repartir un voltaje con resistencias","domain":"electromagnetism"},
    {"id":"aperi21:millikan-experiment","title":"Experimento de la gota de aceite de Millikan","description":"Prueba de que la carga viene en porciones","domain":"electromagnetism"},
    {"id":"aperi21:power-transmission","title":"Transmisión de energía eléctrica","description":"Subir el voltaje para reducir la pérdida","domain":"electromagnetism"},
    {"id":"aperi21:loudspeaker-and-microphone","title":"Altavoz y micrófono","description":"Convertir la corriente en vibración y de vuelta","domain":"electromagnetism"},
    {"id":"aperi21:michelson-morley","title":"Experimento de Michelson y Morley","description":"Prueba de que no existe el éter","domain":"modern-physics"},
    {"id":"aperi21:relativity-of-simultaneity","title":"Relatividad de la simultaneidad","description":"Un «al mismo tiempo» que cambia de un sistema de referencia a otro","domain":"modern-physics"},
    {"id":"aperi21:time-dilation","title":"Dilatación del tiempo","description":"Un reloj en movimiento se atrasa","domain":"modern-physics"},
    {"id":"aperi21:light-clock","title":"Reloj de luz","description":"El experimento mental detrás de la dilatación del tiempo","domain":"modern-physics"},
    {"id":"aperi21:length-contraction","title":"Contracción de la longitud","description":"Contracción en la dirección del movimiento","domain":"modern-physics"},
    {"id":"aperi21:muon-decay-evidence","title":"Muones que llegan al suelo","description":"Prueba observacional de la dilatación del tiempo","domain":"modern-physics"},
    {"id":"aperi21:relativistic-velocity-addition","title":"Suma relativista de velocidades","description":"Una composición que nunca supera la velocidad de la luz","domain":"modern-physics"},
    {"id":"aperi21:twin-paradox","title":"Paradoja de los gemelos","description":"La media vuelta que crea la asimetría","domain":"modern-physics"},
    {"id":"aperi21:spacetime-diagram","title":"Diagrama espaciotemporal","description":"Línea de universo y línea de simultaneidad","domain":"modern-physics"},
    {"id":"aperi21:light-cone","title":"Cono de luz","description":"Hasta dónde llega una causa","domain":"modern-physics"},
    {"id":"aperi21:relativistic-momentum","title":"Momento lineal relativista","description":"El momento lineal diverge al crecer la rapidez","domain":"modern-physics"},
    {"id":"aperi21:relativistic-doppler","title":"Efecto Doppler relativista","description":"Cambio de frecuencia con la dilatación del tiempo añadida","domain":"modern-physics"},
    {"id":"aperi21:equivalence-principle","title":"Principio de equivalencia","description":"La aceleración y la gravedad son indistinguibles","domain":"modern-physics"},
    {"id":"aperi21:gravitational-time-dilation","title":"Dilatación gravitacional del tiempo","description":"Los relojes marchan a ritmos distintos en potenciales distintos","domain":"modern-physics"},
    {"id":"aperi21:gravitational-redshift","title":"Corrimiento al rojo gravitacional","description":"La luz que enrojece al salir","domain":"modern-physics"},
    {"id":"aperi21:light-bending-by-gravity","title":"Curvatura de la luz","description":"La trayectoria de la luz se curva cerca de una masa","domain":"modern-physics"},
    {"id":"aperi21:blackbody-radiation","title":"Radiación de cuerpo negro","description":"Donde la teoría clásica falla","domain":"modern-physics"},
    {"id":"aperi21:wien-displacement-law","title":"Ley de desplazamiento de Wien","description":"Temperatura y longitud de onda del pico","domain":"modern-physics"},
    {"id":"aperi21:photoelectric-effect","title":"Efecto fotoeléctrico","description":"Prueba de que la luz llega en partículas","domain":"modern-physics"},
    {"id":"aperi21:work-function-and-threshold","title":"Función de trabajo y frecuencia umbral","description":"Un umbral distinto para cada metal, con la misma pendiente para todos","domain":"modern-physics"},
    {"id":"aperi21:compton-scattering","title":"Dispersión Compton","description":"Prueba de que un fotón tiene momento lineal","domain":"modern-physics"},
    {"id":"aperi21:pair-production","title":"Producción de pares","description":"Energía que se convierte en materia","domain":"modern-physics"},
    {"id":"aperi21:de-broglie-wavelength","title":"Longitud de onda de De Broglie","description":"La longitud de onda de la materia, fijada por su rapidez","domain":"modern-physics"},
    {"id":"aperi21:electron-diffraction","title":"Difracción de electrones","description":"Ver las ondas de materia","domain":"modern-physics"},
    {"id":"aperi21:double-slit-with-electrons","title":"Doble rendija con electrones","description":"Un patrón que se forma electrón a electrón","domain":"modern-physics"},
    {"id":"aperi21:uncertainty-principle","title":"Principio de incertidumbre","description":"Con qué precisión pueden fijarse a la vez dos magnitudes conjugadas","domain":"modern-physics"},
    {"id":"aperi21:wave-function","title":"Función de onda","description":"La amplitud de probabilidad y lo que significa","domain":"modern-physics"},
    {"id":"aperi21:superposition-quantum","title":"Superposición cuántica","description":"Ser una suma de varios estados","domain":"modern-physics"},
    {"id":"aperi21:measurement-collapse","title":"Medición y colapso","description":"Cómo la observación fija el estado","domain":"modern-physics"},
    {"id":"aperi21:particle-in-a-box","title":"Pozo cuadrado infinito","description":"Cuantización de la energía producida por las paredes","domain":"modern-physics"},
    {"id":"aperi21:finite-well","title":"Pozo cuadrado finito","description":"Una función de onda que se filtra más allá de las paredes","domain":"modern-physics"},
    {"id":"aperi21:quantum-tunneling","title":"Efecto túnel cuántico","description":"La probabilidad de atravesar una barrera","domain":"modern-physics"},
    {"id":"aperi21:scanning-tunneling-microscope","title":"Microscopio de efecto túnel","description":"Dibujar una superficie con corriente túnel","domain":"modern-physics"},
    {"id":"aperi21:quantum-harmonic-oscillator","title":"Oscilador armónico cuántico","description":"Niveles equiespaciados y energía del punto cero","domain":"modern-physics"},
    {"id":"aperi21:hydrogen-spectrum","title":"Espectro del hidrógeno","description":"Un espectro de líneas discreto","domain":"modern-physics"},
    {"id":"aperi21:bohr-model","title":"Modelo de Bohr","description":"Órbitas cuantizadas","domain":"modern-physics"},
    {"id":"aperi21:atomic-orbital","title":"Orbital atómico","description":"El electrón como distribución de probabilidad","domain":"modern-physics"},
    {"id":"aperi21:pauli-exclusion","title":"Principio de exclusión de Pauli","description":"Nunca dos en el mismo estado","domain":"modern-physics"},
    {"id":"aperi21:electron-configuration","title":"Configuración electrónica","description":"Cómo surge la tabla periódica","domain":"modern-physics"},
    {"id":"aperi21:spin","title":"Espín","description":"Momento angular sin análogo clásico","domain":"modern-physics"},
    {"id":"aperi21:stern-gerlach","title":"Experimento de Stern–Gerlach","description":"Un haz atómico que se divide","domain":"modern-physics"},
    {"id":"aperi21:zeeman-effect","title":"Efecto Zeeman","description":"Niveles de energía divididos por un campo magnético","domain":"modern-physics"},
    {"id":"aperi21:laser-and-stimulated-emission","title":"Láseres y emisión estimulada","description":"Amplificar la luz en fase","domain":"modern-physics"},
    {"id":"aperi21:nuclear-structure","title":"De qué está hecho un núcleo","description":"Protones y neutrones","domain":"modern-physics"},
    {"id":"aperi21:binding-energy-curve","title":"Curva de energía de enlace","description":"Por qué alcanza su máximo en el hierro","domain":"modern-physics"},
    {"id":"aperi21:radioactive-decay","title":"Desintegración radiactiva","description":"Semivida y decaimiento exponencial","domain":"modern-physics"},
    {"id":"aperi21:decay-types","title":"Tipos de radiación de desintegración","description":"Alfa, beta, gamma","domain":"modern-physics"},
    {"id":"aperi21:radiometric-dating","title":"Datación radiométrica","description":"Medir el tiempo por lo que queda","domain":"modern-physics"},
    {"id":"aperi21:nuclear-fission","title":"Fisión nuclear","description":"La energía liberada cuando un núcleo pesado se divide","domain":"modern-physics"},
    {"id":"aperi21:chain-reaction","title":"Reacción en cadena","description":"Fisión sostenida por neutrones","domain":"modern-physics"},
    {"id":"aperi21:nuclear-fusion","title":"Fusión nuclear","description":"Energía liberada cuando se unen núcleos ligeros","domain":"modern-physics"},
    {"id":"aperi21:antimatter","title":"Antimateria","description":"Una pareja con la carga opuesta","domain":"modern-physics"},
    {"id":"aperi21:band-theory","title":"Teoría de bandas","description":"Qué separa a conductores, aislantes y semiconductores","domain":"modern-physics"},
    {"id":"aperi21:fermi-level","title":"Nivel de Fermi","description":"Hasta qué altura llenan los electrones","domain":"modern-physics"},
    {"id":"aperi21:semiconductor-doping","title":"Dopaje","description":"Cómo las impurezas crean el tipo n y el tipo p","domain":"modern-physics"},
    {"id":"aperi21:pn-junction","title":"Unión p–n","description":"Capa de agotamiento y rectificación","domain":"modern-physics"},
    {"id":"aperi21:diode-and-led","title":"Diodos y LED","description":"Corriente en un solo sentido y emisión de luz","domain":"modern-physics"},
    {"id":"aperi21:transistor-principle","title":"Transistor","description":"Una señal pequeña controla una corriente grande","domain":"modern-physics"},
    {"id":"aperi21:photovoltaic-effect","title":"Efecto fotovoltaico","description":"Un voltaje creado por la luz","domain":"modern-physics"},
    {"id":"aperi21:superconductivity","title":"Superconductividad","description":"El estado en que la resistencia desaparece","domain":"modern-physics"},
    {"id":"aperi21:meissner-effect","title":"Efecto Meissner","description":"Un superconductor expulsa el campo magnético","domain":"modern-physics"},
    {"id":"aperi21:bose-einstein-condensate","title":"Condensación de Bose–Einstein","description":"Partículas frías que se agolpan en un solo estado","domain":"modern-physics"},
    {"id":"aperi21:scale-of-universe","title":"La escala del universo","description":"Tamaños del átomo al universo, unidos por potencias de diez","domain":"modern-physics"},
    {"id":"aperi21:rutherford-scattering","title":"Dispersión de Rutherford","description":"El experimento en que la mayoría atravesó y unas pocas rebotaron","domain":"modern-physics"},
    {"id":"aperi21:ionizing-radiation","title":"Radiación ionizante","description":"Energía de fotón suficiente para romper enlaces","domain":"modern-physics"},
    {"id":"aperi21:exchange-particles","title":"Partículas de intercambio","description":"Fotones entre electrones, gluones entre quarks","domain":"modern-physics"},
  ],
};
