/**
 * 자동 생성 파일 — 직접 편집하지 말 것.
 *
 * 생성: pnpm catalog:gen  (scripts/gen-aperi21-catalog.mts)
 * 출처: 각 sim 의 schema(label/operation) + docs/topics/topics.yaml(분야).
 */

import type { Aperi21Catalog } from '../catalog-types.js';

export const CATALOG: Aperi21Catalog = {
  locale: "fr",
  domains: [
    {"id":"kinematics","name":"Cinématique"},
    {"id":"newtonian-mechanics","name":"Mécanique newtonienne"},
    {"id":"energy-momentum","name":"Travail, énergie et quantité de mouvement"},
    {"id":"rotation-oscillation","name":"Rotation et oscillations"},
    {"id":"gravitation","name":"Gravitation et astronomie"},
    {"id":"fluids","name":"Fluides"},
    {"id":"thermodynamics","name":"Physique thermique et statistique"},
    {"id":"waves-acoustics","name":"Ondes et acoustique"},
    {"id":"optics","name":"Optique"},
    {"id":"electromagnetism","name":"Électromagnétisme"},
    {"id":"modern-physics","name":"Physique moderne"},
  ],
  entries: [
    {"id":"aperi21:reference-frame","title":"Référentiel","description":"Comment la description du mouvement dépend de l’observateur","domain":"kinematics"},
    {"id":"aperi21:coordinate-choice","title":"Choix des axes","description":"Comment le choix des axes change les équations","domain":"kinematics"},
    {"id":"aperi21:average-velocity","title":"Vitesse moyenne","description":"Une seule vitesse pour tout un intervalle","domain":"kinematics"},
    {"id":"aperi21:average-acceleration","title":"Accélération moyenne","description":"Taux de variation de la vitesse","domain":"kinematics"},
    {"id":"aperi21:direction-of-acceleration","title":"Direction de l’accélération","description":"S’il pointe dans le sens de la vitesse ou en sens inverse","domain":"kinematics"},
    {"id":"aperi21:uniform-motion","title":"Mouvement uniforme","description":"Des intervalles égaux en des temps égaux","domain":"kinematics"},
    {"id":"aperi21:uniformly-accelerated-motion","title":"Mouvement uniformément accéléré","description":"La distance parcourue en des durées égales augmente de quantités égales","domain":"kinematics"},
    {"id":"aperi21:position-time-graph","title":"Graphique position-temps","description":"Plus il monte vite, plus la ligne qu’il laisse est raide","domain":"kinematics"},
    {"id":"aperi21:velocity-time-graph","title":"Graphique vitesse-temps","description":"L’aire sous le graphique est la distance parcourue","domain":"kinematics"},
    {"id":"aperi21:acceleration-time-graph","title":"Graphique accélération-temps","description":"L’aire sous le graphique est la variation de vitesse","domain":"kinematics"},
    {"id":"aperi21:free-fall","title":"Chute libre","description":"Quel que soit l’écart de poids, les deux balles tombent ensemble et touchent le sol ensemble","domain":"kinematics"},
    {"id":"aperi21:vertical-throw","title":"Lancer vertical","description":"La symétrie de la montée et de la descente","domain":"kinematics"},
    {"id":"aperi21:gravitational-acceleration","title":"Accélération de la pesanteur","description":"Une accélération qui ne s’arrête pas, même quand la vitesse est nulle","domain":"kinematics"},
    {"id":"aperi21:terminal-velocity","title":"Vitesse limite","description":"Il cesse d’accélérer dès que la résistance de l’air rattrape la pesanteur","domain":"kinematics"},
    {"id":"aperi21:vector-decomposition","title":"Composantes d’un vecteur","description":"Descendez tout droit de la pointe vers chaque axe : c’est là que finit chaque composante","domain":"kinematics"},
    {"id":"aperi21:vector-addition","title":"Addition de vecteurs","description":"Glissez b jusqu’à la pointe de a, parcourez les deux : l’extrémité finale est la somme","domain":"kinematics"},
    {"id":"aperi21:relative-velocity","title":"Vitesse relative","description":"Changez d’observateur et le chemin laissé par le bateau s’incline","domain":"kinematics"},
    {"id":"aperi21:river-crossing","title":"Traverser une rivière","description":"Pointé droit vers l’autre rive, le bateau est poussé vers l’aval par le courant","domain":"kinematics"},
    {"id":"aperi21:projectile-motion","title":"Mouvement des projectiles","description":"L’horizontal et le vertical avancent sans s’influencer","domain":"kinematics"},
    {"id":"aperi21:projectile-range","title":"Portée et angle de tir","description":"Comment l’angle de tir change la distance parcourue","domain":"kinematics"},
    {"id":"aperi21:trajectory-equation","title":"Équation de la trajectoire","description":"La trajectoire qui reste quand on élimine le temps","domain":"kinematics"},
    {"id":"aperi21:uniform-circular-motion","title":"Mouvement circulaire uniforme","description":"La flèche de vitesse garde sa longueur et ne fait que tourner","domain":"kinematics"},
    {"id":"aperi21:centripetal-acceleration","title":"Accélération centripète","description":"La variation de vitesse est toujours tournée vers le centre","domain":"kinematics"},
    {"id":"aperi21:angular-acceleration","title":"Accélération angulaire","description":"Chaque demi-seconde balaie un angle plus grand que la précédente","domain":"kinematics"},
    {"id":"aperi21:tangential-normal-acceleration","title":"Accélération tangentielle et normale","description":"Séparer la variation de vitesse de la variation de direction","domain":"kinematics"},
    {"id":"aperi21:radius-of-curvature","title":"Rayon de courbure","description":"Un cercle épousant la courbure glisse le long du chemin","domain":"kinematics"},
    {"id":"aperi21:stopping-distance","title":"Distance d’arrêt","description":"La réaction croît linéairement, le freinage comme le carré","domain":"kinematics"},
    {"id":"aperi21:newtons-first-law","title":"Référentiel inertiel","description":"Seul le bus ralentit ; le passager continue","domain":"newtonian-mechanics"},
    {"id":"aperi21:newtons-second-law","title":"Deuxième loi de Newton","description":"Force résultante, masse et accélération","domain":"newtonian-mechanics"},
    {"id":"aperi21:newtons-third-law","title":"Action et réaction","description":"Une paire de forces s’exerçant sur des corps différents","domain":"newtonian-mechanics"},
    {"id":"aperi21:net-force","title":"Force résultante","description":"Somme vectorielle de plusieurs forces","domain":"newtonian-mechanics"},
    {"id":"aperi21:free-body-diagram","title":"Diagramme de corps libre","description":"Isoler les forces qui s’exercent sur un seul corps","domain":"newtonian-mechanics"},
    {"id":"aperi21:inertial-vs-gravitational-mass","title":"Masse inertielle et masse gravitationnelle","description":"Deux définitions différentes donnent la même valeur","domain":"newtonian-mechanics"},
    {"id":"aperi21:normal-force","title":"Force normale","description":"La poussée perpendiculaire d’une surface de contact","domain":"newtonian-mechanics"},
    {"id":"aperi21:apparent-weight","title":"Poids apparent","description":"Une balance dans un ascenseur qui accélère","domain":"newtonian-mechanics"},
    {"id":"aperi21:static-friction","title":"Frottement statique","description":"La force qui tient jusqu’à ce que l’objet bouge","domain":"newtonian-mechanics"},
    {"id":"aperi21:kinetic-friction","title":"Frottement cinétique","description":"Le frottement pendant le glissement","domain":"newtonian-mechanics"},
    {"id":"aperi21:angle-of-friction","title":"Angle de frottement","description":"La pente à laquelle le glissement commence","domain":"newtonian-mechanics"},
    {"id":"aperi21:inclined-plane","title":"Plan incliné","description":"Décomposer la pesanteur parallèlement et perpendiculairement à la pente","domain":"newtonian-mechanics"},
    {"id":"aperi21:tension","title":"Tension","description":"Comment une corde transmet une traction","domain":"newtonian-mechanics"},
    {"id":"aperi21:pulley-system","title":"Poulies","description":"Un dispositif qui change la direction et l’intensité d’une force","domain":"newtonian-mechanics"},
    {"id":"aperi21:connected-bodies","title":"Corps reliés","description":"Accélération de corps qui se déplacent ensemble","domain":"newtonian-mechanics"},
    {"id":"aperi21:spring-force","title":"Force élastique","description":"Force de rappel proportionnelle à l’allongement","domain":"newtonian-mechanics"},
    {"id":"aperi21:centripetal-force","title":"Force centripète","description":"Ce qui maintient un corps sur un cercle","domain":"newtonian-mechanics"},
    {"id":"aperi21:conical-pendulum","title":"Pendule conique","description":"Mouvement circulaire dû à la tension et à la pesanteur","domain":"newtonian-mechanics"},
    {"id":"aperi21:banked-curve","title":"Virage relevé","description":"L’angle de relèvement qui fait tourner une voiture sans frottement","domain":"newtonian-mechanics"},
    {"id":"aperi21:vertical-loop","title":"Looping vertical","description":"La vitesse minimale qui maintient une bille sur la boucle au sommet","domain":"newtonian-mechanics"},
    {"id":"aperi21:drag-force","title":"Résistance de l’air","description":"Plus il va vite, plus la part de la traînée proportionnelle au carré de la vitesse croît fortement","domain":"newtonian-mechanics"},
    {"id":"aperi21:buoyant-force-as-force","title":"La poussée d’Archimède en tant que force","description":"La poussée vers le haut d’un fluide","domain":"newtonian-mechanics"},
    {"id":"aperi21:non-inertial-frame","title":"Référentiel non inertiel","description":"Le mouvement vu depuis un référentiel accéléré","domain":"newtonian-mechanics"},
    {"id":"aperi21:fictitious-force","title":"Force fictive","description":"La force apparente d’un référentiel non inertiel","domain":"newtonian-mechanics"},
    {"id":"aperi21:coriolis-effect","title":"Effet Coriolis","description":"Une trajectoire qui s’incurve dans un référentiel tournant","domain":"newtonian-mechanics"},
    {"id":"aperi21:impulse-force-relation","title":"Force et impulsion","description":"Une force brève et grande, et une autre longue et faible","domain":"newtonian-mechanics"},
    {"id":"aperi21:equilibrium-of-forces","title":"Équilibre des forces","description":"Force résultante nulle","domain":"newtonian-mechanics"},
    {"id":"aperi21:atwood-machine","title":"Machine d’Atwood","description":"À masse totale égale, c’est la différence qui fixe l’accélération","domain":"newtonian-mechanics"},
    {"id":"aperi21:balance-scale","title":"Équilibrer une balance","description":"Un équilibre fixé à la fois par la longueur du bras et le poids","domain":"newtonian-mechanics"},
    {"id":"aperi21:mechanical-advantage","title":"Avantage mécanique","description":"Comment leviers et plans inclinés réduisent la force nécessaire","domain":"newtonian-mechanics"},
    {"id":"aperi21:youngs-modulus","title":"Module de Young","description":"L’allongement d’un fil dépend de son matériau, pas de sa longueur","domain":"newtonian-mechanics"},
    {"id":"aperi21:stress-strain-curve","title":"Courbe contrainte–déformation","description":"Comment un matériau réagit quand on le tire","domain":"newtonian-mechanics"},
    {"id":"aperi21:work-by-variable-force","title":"Travail d’une force variable","description":"L’aire sous le graphique force–déplacement","domain":"energy-momentum"},
    {"id":"aperi21:kinetic-energy","title":"Énergie cinétique","description":"L’énergie que porte la vitesse","domain":"energy-momentum"},
    {"id":"aperi21:work-energy-theorem","title":"Théorème de l’énergie cinétique","description":"Le travail total est égal à la variation d’énergie cinétique","domain":"energy-momentum"},
    {"id":"aperi21:gravitational-potential-energy","title":"Énergie potentielle de pesanteur","description":"Énergie stockée dans la hauteur","domain":"energy-momentum"},
    {"id":"aperi21:elastic-potential-energy","title":"Énergie potentielle élastique","description":"L’énergie stockée dans une déformation","domain":"energy-momentum"},
    {"id":"aperi21:conservative-force","title":"Force conservative","description":"Une force dont le travail ne dépend pas du chemin — et le potentiel qu’elle permet","domain":"energy-momentum"},
    {"id":"aperi21:non-conservative-force","title":"Force non conservative","description":"Un travail qui dépend du chemin","domain":"energy-momentum"},
    {"id":"aperi21:conservation-of-mechanical-energy","title":"Conservation de l’énergie mécanique","description":"La somme qui tient pendant que hauteur et mouvement échangent leurs places","domain":"energy-momentum"},
    {"id":"aperi21:energy-dissipation","title":"Dissipation d’énergie","description":"La part que prend le frottement, et où elle va","domain":"energy-momentum"},
    {"id":"aperi21:potential-energy-curve","title":"Courbe d’énergie potentielle","description":"Comment la forme de la courbe décide du mouvement","domain":"energy-momentum"},
    {"id":"aperi21:equilibrium-points","title":"Points d’équilibre","description":"Équilibre stable, instable et indifférent","domain":"energy-momentum"},
    {"id":"aperi21:efficiency","title":"Rendement","description":"Le rapport entre ce qui sort et ce qui entre","domain":"energy-momentum"},
    {"id":"aperi21:impulse-momentum-theorem","title":"Théorème impulsion–quantité de mouvement","description":"L’impulsion est égale à la variation de la quantité de mouvement","domain":"energy-momentum"},
    {"id":"aperi21:conservation-of-momentum","title":"Conservation de la quantité de mouvement","description":"Quantité de mouvement totale en l’absence de force extérieure","domain":"energy-momentum"},
    {"id":"aperi21:elastic-collision","title":"Collision élastique","description":"Une collision qui conserve même l’énergie cinétique","domain":"energy-momentum"},
    {"id":"aperi21:inelastic-collision","title":"Collision inélastique","description":"Une collision qui perd de l’énergie","domain":"energy-momentum"},
    {"id":"aperi21:perfectly-inelastic-collision","title":"Collision parfaitement inélastique","description":"Quand les deux avancent ensemble, collés","domain":"energy-momentum"},
    {"id":"aperi21:two-dimensional-collision","title":"Collision à deux dimensions","description":"Une conservation qui vaut séparément pour chaque composante","domain":"energy-momentum"},
    {"id":"aperi21:center-of-mass-motion","title":"Mouvement du centre de masse","description":"Le mouvement que les forces internes ne peuvent pas changer","domain":"energy-momentum"},
    {"id":"aperi21:explosion-and-recoil","title":"Explosion et recul","description":"Quand un système au repos se sépare","domain":"energy-momentum"},
    {"id":"aperi21:rocket-equation","title":"L’équation de la fusée","description":"Vitesse gagnée en rejetant du carburant","domain":"energy-momentum"},
    {"id":"aperi21:ballistic-pendulum","title":"Pendule balistique","description":"La mesure qui relie une collision à la conservation de l’énergie","domain":"energy-momentum"},
    {"id":"aperi21:energy-in-collision","title":"L’énergie dans les collisions","description":"Distinguer ce qui se conserve de ce qui ne se conserve pas","domain":"energy-momentum"},
    {"id":"aperi21:energy-flow-diagram","title":"Diagramme des flux d’énergie","description":"Où va l’énergie, montré par l’épaisseur des branches","domain":"energy-momentum"},
    {"id":"aperi21:torque","title":"Couple","description":"Ce qui fait tourner les objets, et la longueur du bras de levier","domain":"rotation-oscillation"},
    {"id":"aperi21:moment-of-inertia","title":"Moment d’inertie","description":"Comment la répartition de la masse fixe la résistance à la rotation","domain":"rotation-oscillation"},
    {"id":"aperi21:parallel-axis-theorem","title":"Théorème des axes parallèles","description":"Moment d’inertie quand on déplace l’axe","domain":"rotation-oscillation"},
    {"id":"aperi21:rotational-kinetic-energy","title":"Énergie cinétique de rotation","description":"L’énergie que porte la rotation","domain":"rotation-oscillation"},
    {"id":"aperi21:angular-momentum","title":"Moment cinétique","description":"L’équivalent de la quantité de mouvement pour la rotation","domain":"rotation-oscillation"},
    {"id":"aperi21:conservation-of-angular-momentum","title":"Conservation du moment cinétique","description":"Pourquoi ramener les bras fait tourner plus vite","domain":"rotation-oscillation"},
    {"id":"aperi21:rolling-without-slipping","title":"Roulement sans glissement","description":"La contrainte qui lie la translation à la rotation","domain":"rotation-oscillation"},
    {"id":"aperi21:rolling-race","title":"Course d’objets qui roulent","description":"Ordre d’arrivée fixé par la répartition de la masse","domain":"rotation-oscillation"},
    {"id":"aperi21:static-equilibrium","title":"Équilibre statique","description":"La force résultante et le couple résultant sont tous deux nuls","domain":"rotation-oscillation"},
    {"id":"aperi21:center-of-gravity","title":"Centre de gravité","description":"Le point qui décide quand un objet bascule","domain":"rotation-oscillation"},
    {"id":"aperi21:gyroscopic-precession","title":"Précession gyroscopique","description":"Le couple fait tourner la direction du moment cinétique","domain":"rotation-oscillation"},
    {"id":"aperi21:angular-momentum-vector","title":"Direction du moment cinétique","description":"La règle de la main droite et l’axe de rotation","domain":"rotation-oscillation"},
    {"id":"aperi21:simple-harmonic-motion","title":"Mouvement harmonique simple","description":"Mouvement sous une force de rappel proportionnelle au déplacement","domain":"rotation-oscillation"},
    {"id":"aperi21:shm-energy","title":"Énergie dans le mouvement harmonique simple","description":"L’énergie cinétique et l’énergie potentielle s’échangent","domain":"rotation-oscillation"},
    {"id":"aperi21:mass-spring-system","title":"Masse suspendue à un ressort","description":"La période fixée par la masse et la raideur du ressort","domain":"rotation-oscillation"},
    {"id":"aperi21:simple-pendulum","title":"Pendule simple","description":"La période aux petites amplitudes","domain":"rotation-oscillation"},
    {"id":"aperi21:physical-pendulum","title":"Pendule pesant","description":"Oscillation d’un corps étendu","domain":"rotation-oscillation"},
    {"id":"aperi21:pendulum-amplitude-dependence","title":"Isochronisme du pendule","description":"Faites glisser l’ampleur du balancement pour élargir les cinq ensemble","domain":"rotation-oscillation"},
    {"id":"aperi21:damped-oscillation","title":"Oscillation amortie","description":"Une oscillation qui perd de l’énergie","domain":"rotation-oscillation"},
    {"id":"aperi21:damping-regimes","title":"Trois régimes d’amortissement","description":"Mouvement sous-amorti, à amortissement critique et suramorti","domain":"rotation-oscillation"},
    {"id":"aperi21:driven-oscillation","title":"Oscillations forcées","description":"La réponse à une excitation extérieure","domain":"rotation-oscillation"},
    {"id":"aperi21:resonance","title":"Résonance","description":"Quand la fréquence d’excitation égale la fréquence propre","domain":"rotation-oscillation"},
    {"id":"aperi21:quality-factor","title":"Facteur de qualité","description":"L’acuité d’une résonance","domain":"rotation-oscillation"},
    {"id":"aperi21:coupled-oscillators","title":"Oscillateurs couplés","description":"Deux oscillateurs qui s’échangent de l’énergie","domain":"rotation-oscillation"},
    {"id":"aperi21:normal-modes","title":"Modes propres","description":"Les formes propres selon lesquelles un système vibre","domain":"rotation-oscillation"},
    {"id":"aperi21:beats-in-oscillation","title":"Battements dans une oscillation","description":"La somme de deux fréquences voisines","domain":"rotation-oscillation"},
    {"id":"aperi21:phase-space","title":"Espace des phases","description":"Le mouvement vu dans le plan position–vitesse","domain":"rotation-oscillation"},
    {"id":"aperi21:nonlinear-oscillation","title":"Oscillation non linéaire","description":"Quand la force de rappel cesse d’être proportionnelle","domain":"rotation-oscillation"},
    {"id":"aperi21:gears","title":"Engrenages","description":"Comment le nombre de dents échange la rotation contre la force","domain":"rotation-oscillation"},
    {"id":"aperi21:newtons-law-of-gravitation","title":"Loi de la gravitation universelle de Newton","description":"Une force qui décroît avec le carré de la distance","domain":"gravitation"},
    {"id":"aperi21:gravitational-field","title":"Champ gravitationnel","description":"L’intensité de la gravité répartie dans l’espace","domain":"gravitation"},
    {"id":"aperi21:range-and-surface-gravity","title":"Gravité et portée","description":"Même lancer, gravité différente","domain":"gravitation"},
    {"id":"aperi21:shell-theorem","title":"Théorème de la coquille","description":"La gravité à l’intérieur et à l’extérieur d’une coquille sphérique","domain":"gravitation"},
    {"id":"aperi21:gravity-inside-earth","title":"Gravité à l’intérieur de la Terre","description":"Une gravité qui faiblit avec la profondeur","domain":"gravitation"},
    {"id":"aperi21:gravitational-potential-energy-general","title":"Énergie potentielle gravitationnelle (cas général)","description":"Une énergie négative mesurée depuis l’infini","domain":"gravitation"},
    {"id":"aperi21:escape-velocity","title":"Vitesse de libération","description":"La vitesse minimale pour échapper à la gravité","domain":"gravitation"},
    {"id":"aperi21:orbital-velocity","title":"Vitesse orbitale","description":"La vitesse qui garde une orbite circulaire","domain":"gravitation"},
    {"id":"aperi21:circular-orbit","title":"Orbite circulaire","description":"Mouvement où la gravité joue le rôle de force centripète","domain":"gravitation"},
    {"id":"aperi21:elliptical-orbit","title":"Orbite elliptique","description":"Le corps central occupe un foyer","domain":"gravitation"},
    {"id":"aperi21:keplers-first-law","title":"Première loi de Kepler","description":"Les orbites sont des ellipses","domain":"gravitation"},
    {"id":"aperi21:keplers-second-law","title":"Deuxième loi de Kepler","description":"Aires égales en des temps égaux","domain":"gravitation"},
    {"id":"aperi21:keplers-third-law","title":"Troisième loi de Kepler","description":"Comment la période dépend du demi-grand axe","domain":"gravitation"},
    {"id":"aperi21:two-body-problem","title":"Problème à deux corps","description":"Deux corps en orbite autour de leur centre de masse commun","domain":"gravitation"},
    {"id":"aperi21:tidal-force","title":"Force de marée","description":"Un étirement créé par une différence de gravité","domain":"gravitation"},
    {"id":"aperi21:roche-limit","title":"Limite de Roche","description":"La distance à laquelle les marées disloquent un corps","domain":"gravitation"},
    {"id":"aperi21:weightlessness","title":"Impesanteur","description":"Poids apparent en chute libre","domain":"gravitation"},
    {"id":"aperi21:geostationary-orbit","title":"Orbite géostationnaire","description":"Une orbite qui dure autant qu’un tour de la Terre","domain":"gravitation"},
    {"id":"aperi21:gravitational-slingshot","title":"Assistance gravitationnelle","description":"Changer de vitesse en passant près d’une planète","domain":"gravitation"},
    {"id":"aperi21:lagrange-points","title":"Points de Lagrange","description":"S’éloigner des cols, tourner autour des sommets","domain":"gravitation"},
    {"id":"aperi21:orbital-transfer","title":"Transfert orbital","description":"Le transfert de Hohmann et ce qu’il coûte","domain":"gravitation"},
    {"id":"aperi21:black-hole-horizon","title":"Horizon des événements","description":"Le rayon où la vitesse de libération atteint celle de la lumière","domain":"gravitation"},
    {"id":"aperi21:diurnal-motion","title":"Mouvement diurne","description":"Les trajectoires que le Soleil et les étoiles tracent dans le ciel en une journée","domain":"gravitation"},
    {"id":"aperi21:earth-rotation-day-night","title":"La rotation de la Terre, le jour et la nuit","description":"Pourquoi le jour et la nuit alternent sur une Terre qui tourne","domain":"gravitation"},
    {"id":"aperi21:earth-revolution-constellations","title":"L’orbite de la Terre et les constellations","description":"Pourquoi les constellations visibles changent avec les saisons","domain":"gravitation"},
    {"id":"aperi21:solar-altitude-shadow","title":"Hauteur du Soleil et ombres","description":"Quand la hauteur du Soleil change, la longueur de l’ombre et la chaleur changent ensemble","domain":"gravitation"},
    {"id":"aperi21:seasonal-sun-path","title":"La course du Soleil au fil des saisons","description":"Comment la hauteur du Soleil à midi et la durée du jour changent ensemble","domain":"gravitation"},
    {"id":"aperi21:axial-tilt-seasons","title":"L’inclinaison de l’axe et les saisons","description":"Les saisons d’une Terre qui orbite inclinée","domain":"gravitation"},
    {"id":"aperi21:moon-phases","title":"Phases de la Lune","description":"Quelle partie de la Lune éclairée par le Soleil est tournée vers nous","domain":"gravitation"},
    {"id":"aperi21:eclipse","title":"Éclipses de Soleil et de Lune","description":"Quand le Soleil, la Terre et la Lune s’alignent","domain":"gravitation"},
    {"id":"aperi21:stellar-parallax","title":"Parallaxe stellaire","description":"L’angle dont se décale une étoile proche quand la Terre tourne autour du Soleil","domain":"gravitation"},
    {"id":"aperi21:apparent-brightness","title":"Éclat apparent","description":"La même lumière se répartit sur une surface plus grande","domain":"gravitation"},
    {"id":"aperi21:magnitude-scale","title":"Magnitude stellaire","description":"Comment l’éclat s’exprime en magnitude","domain":"gravitation"},
    {"id":"aperi21:star-color-temperature","title":"Couleur des étoiles et température de surface","description":"Comment la température de surface fixe la couleur de la lumière des étoiles","domain":"gravitation"},
    {"id":"aperi21:expanding-universe","title":"L’univers en expansion","description":"Des galaxies qui s’éloignent dans toutes les directions","domain":"gravitation"},
    {"id":"aperi21:stellar-luminosity","title":"Luminosité","description":"La quantité de lumière qu’une étoile émet réellement","domain":"gravitation"},
    {"id":"aperi21:hr-diagram","title":"Diagramme HR","description":"Les étoiles les plus lourdes quittent la séquence principale en premier","domain":"gravitation"},
    {"id":"aperi21:star-radiation-gravity-balance","title":"Équilibre entre pression de radiation et gravité","description":"Pourquoi une étoile ne s’effondre ni ne se disperse","domain":"gravitation"},
    {"id":"aperi21:orbital-decay","title":"Décroissance orbitale","description":"Une orbite freinée par l’air raréfié","domain":"gravitation"},
    {"id":"aperi21:inverse-square-law","title":"Loi de l’inverse du carré","description":"Se diluer en s’étalant","domain":"gravitation"},
    {"id":"aperi21:stellar-nucleosynthesis","title":"Nucléosynthèse stellaire","description":"Comment les éléments plus lourds se forment à l’intérieur des étoiles","domain":"gravitation"},
    {"id":"aperi21:star-life-cycle","title":"Cycle de vie d’une étoile","description":"Comment la masse décide du parcours d’une étoile","domain":"gravitation"},
    {"id":"aperi21:stellar-spectral-class","title":"Types spectraux des étoiles","description":"Motifs de raies d’absorption fixés par la température","domain":"gravitation"},
    {"id":"aperi21:supernova-and-neutron-star","title":"Supernova et étoile à neutrons","description":"Un effondrement final et un rebond","domain":"gravitation"},
    {"id":"aperi21:exoplanet-detection","title":"Détecter les exoplanètes","description":"Les traces que laisse une planète","domain":"gravitation"},
    {"id":"aperi21:projectile-in-wind","title":"Vent et portée","description":"Même lancer, vent différent","domain":"fluids"},
    {"id":"aperi21:pressure-isotropy","title":"Isotropie de la pression","description":"la plaque fait un demi-tour pour refermer la trace en cercle, puis le lecteur la tourne à la main","domain":"fluids"},
    {"id":"aperi21:hydrostatic-pressure","title":"Pression hydrostatique","description":"Une pression qui croît avec la profondeur","domain":"fluids"},
    {"id":"aperi21:pressure-and-container-shape","title":"Forme du récipient et pression au fond","description":"Déplace le niveau de l’eau et remplis à nouveau les trois","domain":"fluids"},
    {"id":"aperi21:atmospheric-pressure","title":"Pression atmosphérique","description":"Le poids de la colonne d’air","domain":"fluids"},
    {"id":"aperi21:barometer","title":"Baromètre","description":"La hauteur d’une colonne de mercure","domain":"fluids"},
    {"id":"aperi21:manometer","title":"Manomètre","description":"Lire la pression sur une colonne de liquide","domain":"fluids"},
    {"id":"aperi21:pascals-principle","title":"Principe de Pascal","description":"La pression transmise et la presse hydraulique","domain":"fluids"},
    {"id":"aperi21:buoyancy","title":"Poussée d’Archimède","description":"Autant que le poids du fluide déplacé","domain":"fluids"},
    {"id":"aperi21:archimedes-principle","title":"Principe d’Archimède — l’intensité de la poussée d’Archimède","description":"Un objet de 2.0 kg et 1.0 L est descendu dans un vase rempli jusqu’au bec. L’eau déplacée s’écoule dans le gobelet, et la balance qui reçoit l’eau gagne exactement ce que perd la balance qui tient l’objet.","domain":"fluids"},
    {"id":"aperi21:floating-and-draft","title":"À quelle profondeur s’enfonce un corps flottant","description":"Ce qui fixe le volume immergé","domain":"fluids"},
    {"id":"aperi21:stability-of-floating-body","title":"Stabilité d’un corps flottant","description":"Quand un bateau gîte, son centre de poussée se déplace et le redresse","domain":"fluids"},
    {"id":"aperi21:continuity-equation","title":"Équation de continuité","description":"Section et vitesse d’écoulement se compensent","domain":"fluids"},
    {"id":"aperi21:bernoullis-principle","title":"Principe de Bernoulli","description":"Là où l’eau accélère, sa pression baisse","domain":"fluids"},
    {"id":"aperi21:venturi-effect","title":"Effet Venturi","description":"Une pression plus basse là où le tube se rétrécit","domain":"fluids"},
    {"id":"aperi21:torricellis-law","title":"Loi de Torricelli","description":"Plus le trou est profond, plus le jet est rapide","domain":"fluids"},
    {"id":"aperi21:lift-force","title":"Portance","description":"Comment l’air s’écoule au-dessus et au-dessous d’une aile","domain":"fluids"},
    {"id":"aperi21:viscosity","title":"Viscosité","description":"Frottement entre les couches","domain":"fluids"},
    {"id":"aperi21:poiseuille-flow","title":"Écoulement laminaire dans un tuyau","description":"Le débit croît comme la puissance quatrième du rayon","domain":"fluids"},
    {"id":"aperi21:stokes-drag","title":"Traînée de Stokes","description":"Traînée dans un écoulement lent et visqueux","domain":"fluids"},
    {"id":"aperi21:laminar-vs-turbulent","title":"Écoulement laminaire et turbulent","description":"Là où l’écoulement se désorganise soudain","domain":"fluids"},
    {"id":"aperi21:reynolds-number","title":"Nombre de Reynolds","description":"Le nombre sans dimension qui décide de la transition","domain":"fluids"},
    {"id":"aperi21:boundary-layer","title":"Couche limite","description":"La couche près d’une paroi où l’écoulement ralentit jusqu’à zéro","domain":"fluids"},
    {"id":"aperi21:surface-tension","title":"Tension superficielle","description":"La traction qui contracte une surface","domain":"fluids"},
    {"id":"aperi21:laplace-pressure","title":"Pression de Laplace","description":"Le saut de pression créé par une surface courbe","domain":"fluids"},
    {"id":"aperi21:capillary-action","title":"Capillarité","description":"Montée et descente dans des tubes étroits","domain":"fluids"},
    {"id":"aperi21:wetting-and-contact-angle","title":"Mouillage et angle de contact","description":"Jusqu’où un liquide s’étale sur un solide","domain":"fluids"},
    {"id":"aperi21:drag-in-fluid","title":"Traînée dans un fluide","description":"Traînée fixée par la forme et la vitesse","domain":"fluids"},
    {"id":"aperi21:thermal-equilibrium","title":"Équilibre thermique","description":"L’état qu’atteignent deux systèmes en contact","domain":"thermodynamics"},
    {"id":"aperi21:specific-heat","title":"Capacité thermique massique","description":"De combien la température change, matériau par matériau","domain":"thermodynamics"},
    {"id":"aperi21:calorimetry","title":"Calorimétrie","description":"La température finale d’un mélange","domain":"thermodynamics"},
    {"id":"aperi21:latent-heat","title":"Chaleur latente","description":"Pourquoi la température s’arrête pendant un changement d’état","domain":"thermodynamics"},
    {"id":"aperi21:phase-diagram","title":"Diagramme de phases","description":"Sous le point triple, le domaine liquide est sauté","domain":"thermodynamics"},
    {"id":"aperi21:triple-point","title":"Point triple","description":"La condition où trois phases coexistent","domain":"thermodynamics"},
    {"id":"aperi21:thermal-conduction","title":"Conduction thermique","description":"Elle se propage dans l’acier et reste dans le bois","domain":"thermodynamics"},
    {"id":"aperi21:thermal-convection","title":"Convection","description":"Chaleur transportée par un fluide en mouvement","domain":"thermodynamics"},
    {"id":"aperi21:thermal-radiation","title":"Rayonnement thermique","description":"De la chaleur qui se propage sans milieu","domain":"thermodynamics"},
    {"id":"aperi21:stefan-boltzmann-law","title":"Loi de Stefan–Boltzmann","description":"Un rayonnement qui croît comme la puissance quatrième de la température","domain":"thermodynamics"},
    {"id":"aperi21:thermal-expansion","title":"Dilatation thermique","description":"Comment la longueur et le volume changent avec la température","domain":"thermodynamics"},
    {"id":"aperi21:bimetal","title":"Bilame","description":"Courbure due à une dilatation inégale","domain":"thermodynamics"},
    {"id":"aperi21:ideal-gas-law","title":"Loi des gaz parfaits","description":"Comment pression, volume et température sont liés","domain":"thermodynamics"},
    {"id":"aperi21:boyles-law","title":"Loi de Boyle","description":"Pression et volume à température constante","domain":"thermodynamics"},
    {"id":"aperi21:charles-law","title":"Loi de Charles","description":"Volume et température à pression constante","domain":"thermodynamics"},
    {"id":"aperi21:gas-pressure","title":"Molécules et pression","description":"La pression est la somme des chocs","domain":"thermodynamics"},
    {"id":"aperi21:pressure-from-collisions","title":"La pression due aux collisions","description":"La quantité de mouvement que les molécules apportent à la paroi","domain":"thermodynamics"},
    {"id":"aperi21:maxwell-boltzmann-distribution","title":"Distribution de Maxwell–Boltzmann","description":"Chauffer étale la distribution des vitesses et abaisse son pic","domain":"thermodynamics"},
    {"id":"aperi21:mean-free-path","title":"Libre parcours moyen","description":"La distance entre les collisions","domain":"thermodynamics"},
    {"id":"aperi21:first-law-of-thermodynamics","title":"Premier principe de la thermodynamique","description":"Comment l’énergie interne, le travail et la chaleur sont liés","domain":"thermodynamics"},
    {"id":"aperi21:pv-diagram","title":"Diagramme PV","description":"Là où l’aire est un travail","domain":"thermodynamics"},
    {"id":"aperi21:isothermal-process","title":"Transformation isotherme","description":"Une transformation qui garde la température fixe","domain":"thermodynamics"},
    {"id":"aperi21:adiabatic-process","title":"Transformation adiabatique","description":"Une transformation sans chaleur qui entre ni qui sort","domain":"thermodynamics"},
    {"id":"aperi21:isobaric-isochoric","title":"Transformations isobare et isochore","description":"Transformations à pression fixe ou à volume fixe","domain":"thermodynamics"},
    {"id":"aperi21:cyclic-process","title":"Transformation cyclique","description":"Une transformation qui revient à son point de départ","domain":"thermodynamics"},
    {"id":"aperi21:second-law-of-thermodynamics","title":"Deuxième principe de la thermodynamique","description":"Un changement à sens unique","domain":"thermodynamics"},
    {"id":"aperi21:irreversibility","title":"Entropie et irréversibilité","description":"Pourquoi on ne peut pas revenir en arrière","domain":"thermodynamics"},
    {"id":"aperi21:heat-engine","title":"Moteur thermique","description":"Un cycle qui transforme la chaleur en travail","domain":"thermodynamics"},
    {"id":"aperi21:carnot-cycle","title":"Cycle de Carnot","description":"Le rendement maximal théorique","domain":"thermodynamics"},
    {"id":"aperi21:refrigerator-heat-pump","title":"Réfrigérateurs et pompes à chaleur","description":"Déplacer de la chaleur en fournissant du travail","domain":"thermodynamics"},
    {"id":"aperi21:brownian-motion","title":"Mouvement brownien","description":"Mouvement aléatoire provoqué par les collisions moléculaires","domain":"thermodynamics"},
    {"id":"aperi21:diffusion","title":"Diffusion","description":"Un flux engendré par une différence de concentration","domain":"thermodynamics"},
    {"id":"aperi21:random-walk","title":"Marche aléatoire","description":"Une distance qui croît comme une racine carrée","domain":"thermodynamics"},
    {"id":"aperi21:statistical-fluctuation","title":"Fluctuation statistique","description":"L’oscillation qui grandit quand les particules sont peu nombreuses","domain":"thermodynamics"},
    {"id":"aperi21:maxwells-demon","title":"Le démon de Maxwell","description":"Information et entropie","domain":"thermodynamics"},
    {"id":"aperi21:insulation","title":"Isolation thermique","description":"Ralentir le flux de chaleur","domain":"thermodynamics"},
    {"id":"aperi21:albedo","title":"Albédo","description":"La part de lumière renvoyée","domain":"thermodynamics"},
    {"id":"aperi21:radiative-equilibrium","title":"Équilibre radiatif","description":"La température fixée quand ce qui sort égale ce qui entre","domain":"thermodynamics"},
    {"id":"aperi21:greenhouse-effect","title":"Effet de serre","description":"Une couche qui renvoie l’infrarouge vers le bas réchauffe le sol","domain":"thermodynamics"},
    {"id":"aperi21:wave-basics","title":"Grandeurs fondamentales d’une onde","description":"Longueur d’onde, fréquence, vitesse et amplitude","domain":"waves-acoustics"},
    {"id":"aperi21:wave-vs-particle-transport","title":"Ce que transporte une onde","description":"Le milieu reste sur place, l’énergie avance","domain":"waves-acoustics"},
    {"id":"aperi21:transverse-wave","title":"Onde transversale","description":"Le milieu vibre perpendiculairement à la direction de propagation de l’onde","domain":"waves-acoustics"},
    {"id":"aperi21:longitudinal-wave","title":"Onde longitudinale","description":"Les particules oscillent sur place tandis que les zones serrées avancent","domain":"waves-acoustics"},
    {"id":"aperi21:wave-speed-in-medium","title":"La vitesse d’une onde et le milieu","description":"Vitesse fixée par la tension et la densité","domain":"waves-acoustics"},
    {"id":"aperi21:wavefront-and-ray","title":"Fronts d’onde et rayons","description":"Surfaces d’égale phase et les lignes qui leur sont normales","domain":"waves-acoustics"},
    {"id":"aperi21:huygens-principle","title":"Principe de Huygens","description":"Les ondelettes circulaires issues des points d’un front d’onde se superposent en un front rectiligne","domain":"waves-acoustics"},
    {"id":"aperi21:superposition","title":"Superposition","description":"Ce qui se passe quand des ondes se superposent","domain":"waves-acoustics"},
    {"id":"aperi21:constructive-destructive","title":"Interférences constructives et destructives","description":"Comment le déphasage fixe l’ampleur de la somme","domain":"waves-acoustics"},
    {"id":"aperi21:interference","title":"Interférences","description":"Deux séries de rides s’annulent et laissent des lignes calmes","domain":"waves-acoustics"},
    {"id":"aperi21:standing-wave","title":"Onde stationnaire","description":"Deux ondes allant en sens opposés figent les nœuds sur place","domain":"waves-acoustics"},
    {"id":"aperi21:harmonics","title":"Harmoniques","description":"Fréquences fixées par les conditions aux limites","domain":"waves-acoustics"},
    {"id":"aperi21:string-vibration","title":"Corde vibrante","description":"Modes d’une corde fixée aux deux extrémités","domain":"waves-acoustics"},
    {"id":"aperi21:air-column-resonance","title":"Résonance d’une colonne d’air","description":"Tuyau ouvert ou tuyau fermé","domain":"waves-acoustics"},
    {"id":"aperi21:beats","title":"Battements","description":"La somme s’annule à mesure que les deux se décalent","domain":"waves-acoustics"},
    {"id":"aperi21:doppler-effect","title":"Effet Doppler","description":"La source entraîne ses points d’émission et resserre l’avant","domain":"waves-acoustics"},
    {"id":"aperi21:doppler-source-vs-observer","title":"Source en mouvement ou observateur en mouvement","description":"L’asymétrie selon qui se déplace","domain":"waves-acoustics"},
    {"id":"aperi21:shock-wave","title":"Onde de choc","description":"Le cône qui se forme au-delà de la vitesse du son","domain":"waves-acoustics"},
    {"id":"aperi21:sound-intensity","title":"Intensité sonore","description":"Décroissance avec le carré de la distance","domain":"waves-acoustics"},
    {"id":"aperi21:reflection-of-waves","title":"Réflexion des ondes","description":"Phase à une extrémité fixe et à une extrémité libre","domain":"waves-acoustics"},
    {"id":"aperi21:refraction-of-waves","title":"Réfraction des ondes","description":"Un changement de vitesse fait tourner la direction","domain":"waves-acoustics"},
    {"id":"aperi21:diffraction","title":"Diffraction","description":"Des ondes qui contournent les obstacles","domain":"waves-acoustics"},
    {"id":"aperi21:slit-width-and-diffraction","title":"Largeur de la fente et diffraction","description":"Comment le rapport ouverture/longueur d’onde fixe l’étalement","domain":"waves-acoustics"},
    {"id":"aperi21:wave-energy","title":"Énergie d’une onde","description":"L’énergie croît avec le carré de l’amplitude","domain":"waves-acoustics"},
    {"id":"aperi21:wave-attenuation","title":"Atténuation d’une onde","description":"Énergie absorbée par le milieu","domain":"waves-acoustics"},
    {"id":"aperi21:impedance-mismatch","title":"Désadaptation d’impédance","description":"Quelle part se réfléchit à une frontière","domain":"waves-acoustics"},
    {"id":"aperi21:noise-cancellation","title":"Réduction active du bruit","description":"Superposition d’une onde inversée","domain":"waves-acoustics"},
    {"id":"aperi21:sound-source-vibration","title":"Son et vibration","description":"Un objet qui émet un son vibre, et quand la vibration cesse, le son cesse aussi","domain":"waves-acoustics"},
    {"id":"aperi21:sound-through-materials","title":"Le son à travers les matériaux","description":"Comment le son se propage différemment selon les matériaux","domain":"waves-acoustics"},
    {"id":"aperi21:digital-vs-analog-signal","title":"Signaux numériques et analogiques","description":"Deux façons de résister au bruit","domain":"waves-acoustics"},
    {"id":"aperi21:seismic-waves","title":"Ondes sismiques","description":"Ondes P et S qui traversent la Terre","domain":"waves-acoustics"},
    {"id":"aperi21:rectilinear-propagation","title":"La lumière se propage en ligne droite","description":"Les ombres et le modèle du rayon lumineux","domain":"optics"},
    {"id":"aperi21:shadow-umbra-penumbra","title":"Ombre et pénombre","description":"Comment la taille d’une source lumineuse façonne le bord d’une ombre","domain":"optics"},
    {"id":"aperi21:pinhole-camera","title":"Sténopé","description":"L’image formée par un seul trou","domain":"optics"},
    {"id":"aperi21:law-of-reflection","title":"Loi de la réflexion","description":"Angle d’incidence et angle de réflexion","domain":"optics"},
    {"id":"aperi21:specular-diffuse-reflection","title":"Réflexion spéculaire et diffuse","description":"Une réflexion fixée par la rugosité de la surface","domain":"optics"},
    {"id":"aperi21:plane-mirror-image","title":"Image dans un miroir plan","description":"Où se forme l’image virtuelle, et pourquoi elle paraît inversée","domain":"optics"},
    {"id":"aperi21:multiple-mirror-images","title":"Images dans deux miroirs","description":"Comment l’angle entre deux miroirs fixe le nombre d’images","domain":"optics"},
    {"id":"aperi21:concave-mirror","title":"Miroir concave","description":"Le foyer et l’image réelle","domain":"optics"},
    {"id":"aperi21:convex-mirror","title":"Miroir convexe","description":"Un champ de vision plus large et une image virtuelle","domain":"optics"},
    {"id":"aperi21:snells-law","title":"Loi de Snell-Descartes","description":"Comment le trajet dévie selon le milieu","domain":"optics"},
    {"id":"aperi21:apparent-depth","title":"Profondeur apparente","description":"Pourquoi les objets sous l’eau semblent surélevés","domain":"optics"},
    {"id":"aperi21:total-internal-reflection","title":"Réflexion totale interne","description":"L’angle critique et sa condition","domain":"optics"},
    {"id":"aperi21:optical-fiber","title":"Fibre optique","description":"Lumière piégée par réflexion totale interne","domain":"optics"},
    {"id":"aperi21:mirage","title":"Mirage","description":"La lumière courbée par un gradient de masse volumique","domain":"optics"},
    {"id":"aperi21:dispersion","title":"Dispersion","description":"Indice de réfraction qui dépend de la longueur d’onde","domain":"optics"},
    {"id":"aperi21:prism","title":"Prisme","description":"Un spectre étalé par la dispersion","domain":"optics"},
    {"id":"aperi21:rainbow","title":"Arc-en-ciel","description":"Réfraction et réflexion dans les gouttes de pluie","domain":"optics"},
    {"id":"aperi21:thin-lens","title":"Lentille mince","description":"Trouver l’image avec trois rayons","domain":"optics"},
    {"id":"aperi21:converging-diverging-lens","title":"Lentilles convergentes et divergentes","description":"Une lentille qui rassemble la lumière et une lentille qui l’étale","domain":"optics"},
    {"id":"aperi21:magnification","title":"Grandissement","description":"La taille de l’image et la taille de l’objet","domain":"optics"},
    {"id":"aperi21:focal-length","title":"Distance focale","description":"Ce qui décide où se forme l’image","domain":"optics"},
    {"id":"aperi21:real-vs-virtual-image","title":"Images réelles et virtuelles","description":"La lumière se rejoint-elle vraiment ?","domain":"optics"},
    {"id":"aperi21:lens-combination","title":"Association de lentilles","description":"Le foyer combiné de deux lentilles","domain":"optics"},
    {"id":"aperi21:spherical-aberration","title":"Aberration sphérique","description":"Les rayons du bord convergent à un autre endroit","domain":"optics"},
    {"id":"aperi21:chromatic-aberration","title":"Aberration chromatique","description":"Un foyer différent pour chaque longueur d’onde","domain":"optics"},
    {"id":"aperi21:human-eye-accommodation","title":"Accommodation de l’œil","description":"Comment le cristallin fait la mise au point","domain":"optics"},
    {"id":"aperi21:myopia-hyperopia","title":"Myopie et hypermétropie","description":"Où se forme l’image, et comment les lunettes la corrigent","domain":"optics"},
    {"id":"aperi21:magnifying-glass","title":"Loupe","description":"Un objet en deçà du foyer proche","domain":"optics"},
    {"id":"aperi21:microscope","title":"Microscope","description":"Les grossissements de l’objectif et de l’oculaire se multiplient","domain":"optics"},
    {"id":"aperi21:telescope","title":"Lunette astronomique","description":"Grossissement fixé par le rapport des distances focales","domain":"optics"},
    {"id":"aperi21:youngs-double-slit","title":"Fentes de Young","description":"La preuve que la lumière est une onde","domain":"optics"},
    {"id":"aperi21:single-slit-diffraction","title":"Diffraction par une fente","description":"Le motif que crée une largeur","domain":"optics"},
    {"id":"aperi21:diffraction-grating","title":"Réseau de diffraction","description":"Des maxima nets créés par de nombreuses fentes","domain":"optics"},
    {"id":"aperi21:thin-film-interference","title":"Interférences en lame mince","description":"La couleur créée par l’épaisseur","domain":"optics"},
    {"id":"aperi21:newtons-rings","title":"Anneaux de Newton","description":"Interférences entre une surface courbe et une surface plane","domain":"optics"},
    {"id":"aperi21:resolving-power","title":"Pouvoir de résolution","description":"La limite pour distinguer deux points","domain":"optics"},
    {"id":"aperi21:polarization","title":"Polarisation","description":"Sélection du plan de vibration","domain":"optics"},
    {"id":"aperi21:malus-law","title":"Loi de Malus","description":"Intensité à travers un polariseur","domain":"optics"},
    {"id":"aperi21:brewster-angle","title":"Angle de Brewster","description":"L’angle où la lumière réfléchie est totalement polarisée","domain":"optics"},
    {"id":"aperi21:birefringence","title":"Biréfringence","description":"Indice de réfraction qui dépend de la direction","domain":"optics"},
    {"id":"aperi21:scattering","title":"Diffusion","description":"Les couleurs du ciel et du coucher de soleil","domain":"optics"},
    {"id":"aperi21:rayleigh-scattering","title":"Diffusion de Rayleigh","description":"Diffusion qui décroît comme la puissance quatrième de la longueur d’onde","domain":"optics"},
    {"id":"aperi21:seeing-requires-light","title":"Voir exige de la lumière","description":"Sans lumière, on ne peut pas voir un objet","domain":"optics"},
    {"id":"aperi21:color-addition","title":"Addition de lumières","description":"La couleur que forment trois lumières là où elles se superposent","domain":"optics"},
    {"id":"aperi21:object-color","title":"La couleur d’un objet","description":"La couleur fixée par la lumière qu’un objet renvoie","domain":"optics"},
    {"id":"aperi21:light-through-materials","title":"La lumière et les matériaux","description":"Le passage de la lumière dépend du matériau","domain":"optics"},
    {"id":"aperi21:electric-charge","title":"Charge électrique","description":"Deux sortes de charge et leur conservation","domain":"electromagnetism"},
    {"id":"aperi21:charging-methods","title":"Modes d’électrisation","description":"Frottement, contact et influence","domain":"electromagnetism"},
    {"id":"aperi21:coulombs-law","title":"Loi de Coulomb","description":"La force entre des charges","domain":"electromagnetism"},
    {"id":"aperi21:superposition-of-forces","title":"Superposition des forces électriques","description":"Additionner les forces de plusieurs charges","domain":"electromagnetism"},
    {"id":"aperi21:electric-field","title":"Champ électrique","description":"La force sur une charge unité","domain":"electromagnetism"},
    {"id":"aperi21:field-lines","title":"Lignes de champ électrique","description":"Là où les lignes se resserrent, le champ est intense","domain":"electromagnetism"},
    {"id":"aperi21:field-of-dipole","title":"Champ électrique d’un dipôle","description":"Deux charges opposées proches","domain":"electromagnetism"},
    {"id":"aperi21:uniform-field","title":"Champ électrique uniforme","description":"Le champ entre des plaques parallèles","domain":"electromagnetism"},
    {"id":"aperi21:charge-in-uniform-field","title":"Une charge dans un champ uniforme","description":"Comme un projectile","domain":"electromagnetism"},
    {"id":"aperi21:gausss-law","title":"Théorème de Gauss","description":"Flux électrique à travers une surface fermée","domain":"electromagnetism"},
    {"id":"aperi21:field-of-charged-sphere","title":"Champ d’une sphère chargée","description":"Pourquoi l’intérieur et l’extérieur diffèrent","domain":"electromagnetism"},
    {"id":"aperi21:equipotential-surface","title":"Surfaces équipotentielles","description":"Surfaces perpendiculaires au champ","domain":"electromagnetism"},
    {"id":"aperi21:potential-vs-field","title":"Potentiel et champ électrique","description":"La relation de pente","domain":"electromagnetism"},
    {"id":"aperi21:electrostatic-shielding","title":"Blindage électrostatique","description":"Pourquoi le champ à l’intérieur d’un conducteur est nul","domain":"electromagnetism"},
    {"id":"aperi21:charge-on-conductor-surface","title":"Charge à la surface d’un conducteur","description":"La charge s’accumule au bout pointu","domain":"electromagnetism"},
    {"id":"aperi21:dielectric","title":"Diélectrique","description":"La polarisation affaiblit le champ","domain":"electromagnetism"},
    {"id":"aperi21:parallel-plate-capacitor","title":"Condensateur plan","description":"Capacité fixée par la surface et l’écartement","domain":"electromagnetism"},
    {"id":"aperi21:capacitors-in-circuit","title":"Association de condensateurs","description":"Association en série et en parallèle","domain":"electromagnetism"},
    {"id":"aperi21:energy-in-capacitor","title":"Énergie d’un condensateur","description":"Énergie stockée dans le champ électrique","domain":"electromagnetism"},
    {"id":"aperi21:electric-current","title":"Courant électrique","description":"Le flux de charge et sa convention de sens","domain":"electromagnetism"},
    {"id":"aperi21:drift-velocity","title":"Vitesse de dérive","description":"Électrons lents, signal rapide","domain":"electromagnetism"},
    {"id":"aperi21:ohms-law","title":"Loi d’Ohm","description":"Tension, courant et résistance","domain":"electromagnetism"},
    {"id":"aperi21:resistance-and-geometry","title":"Résistance et forme","description":"L’influence de la longueur et de la section","domain":"electromagnetism"},
    {"id":"aperi21:temperature-and-resistance","title":"Température et résistance","description":"Métaux et semi-conducteurs évoluent en sens inverse","domain":"electromagnetism"},
    {"id":"aperi21:series-parallel-resistors","title":"Résistances en série et en parallèle","description":"Comment le branchement change le courant que fournit une pile","domain":"electromagnetism"},
    {"id":"aperi21:emf-and-internal-resistance","title":"F.é.m. et résistance interne","description":"Pourquoi la tension aux bornes baisse","domain":"electromagnetism"},
    {"id":"aperi21:kirchhoffs-current-law","title":"Loi des nœuds de Kirchhoff","description":"Conservation de la charge en un nœud","domain":"electromagnetism"},
    {"id":"aperi21:kirchhoffs-voltage-law","title":"Loi des mailles de Kirchhoff","description":"Conservation de l’énergie le long d’une maille","domain":"electromagnetism"},
    {"id":"aperi21:wheatstone-bridge","title":"Pont de Wheatstone","description":"Mesurer une résistance par l’équilibre","domain":"electromagnetism"},
    {"id":"aperi21:joule-heating","title":"Effet Joule","description":"La chaleur produite par une résistance","domain":"electromagnetism"},
    {"id":"aperi21:rc-circuit","title":"Circuit RC","description":"L’écart restant diminue du même facteur à chaque τ","domain":"electromagnetism"},
    {"id":"aperi21:magnetic-field","title":"Champ magnétique","description":"Comment la force magnétique se répartit autour d’un aimant","domain":"electromagnetism"},
    {"id":"aperi21:magnetic-field-lines","title":"Lignes de champ magnétique","description":"Des lignes qui ne se rompent jamais et se referment toujours","domain":"electromagnetism"},
    {"id":"aperi21:lorentz-force","title":"Force de Lorentz","description":"La force sur une charge en mouvement dans un champ magnétique","domain":"electromagnetism"},
    {"id":"aperi21:charged-particle-in-magnetic-field","title":"Des charges qui tournent dans un champ magnétique","description":"Une charge plus rapide met le même temps par tour","domain":"electromagnetism"},
    {"id":"aperi21:velocity-selector","title":"Sélecteur de vitesse","description":"Équilibre des forces électrique et magnétique","domain":"electromagnetism"},
    {"id":"aperi21:mass-spectrometer","title":"Spectromètre de masse","description":"Trier les masses par le rayon","domain":"electromagnetism"},
    {"id":"aperi21:force-on-current-wire","title":"Force sur un fil parcouru par un courant","description":"La force magnétique sur un fil parcouru par un courant","domain":"electromagnetism"},
    {"id":"aperi21:biot-savart-law","title":"Loi de Biot–Savart","description":"Le champ magnétique des éléments de courant","domain":"electromagnetism"},
    {"id":"aperi21:field-of-straight-wire","title":"Le champ magnétique d’un courant","description":"Les aiguilles tournent le long de la boucle, et moins loin du fil","domain":"electromagnetism"},
    {"id":"aperi21:field-of-loop-and-solenoid","title":"Spire et solénoïde","description":"Le champ magnétique le long de l’axe","domain":"electromagnetism"},
    {"id":"aperi21:amperes-law","title":"Théorème d’Ampère","description":"Circulation du champ magnétique autour d’un courant","domain":"electromagnetism"},
    {"id":"aperi21:force-between-wires","title":"Force entre fils parallèles","description":"Deux courants parallèles s’attirent ou se repoussent","domain":"electromagnetism"},
    {"id":"aperi21:magnetic-dipole","title":"Dipôle magnétique","description":"Une boucle de courant et un aimant, c’est la même chose","domain":"electromagnetism"},
    {"id":"aperi21:magnetic-materials","title":"Matériaux magnétiques","description":"Ferromagnétique, paramagnétique et diamagnétique","domain":"electromagnetism"},
    {"id":"aperi21:faradays-law","title":"Loi de Faraday","description":"La f.é.m. créée par un flux variable","domain":"electromagnetism"},
    {"id":"aperi21:lenzs-law","title":"Loi de Lenz","description":"Le courant s’inverse, la force jamais","domain":"electromagnetism"},
    {"id":"aperi21:motional-emf","title":"F.é.m. de mouvement","description":"La tension créée par un fil en mouvement","domain":"electromagnetism"},
    {"id":"aperi21:eddy-current","title":"Courants de Foucault","description":"Courants induits dans un conducteur massif","domain":"electromagnetism"},
    {"id":"aperi21:self-inductance","title":"Auto-inductance","description":"Une bobine qui s’oppose aux variations de son propre flux","domain":"electromagnetism"},
    {"id":"aperi21:mutual-inductance","title":"Inductance mutuelle","description":"Une f.é.m. induite dans un circuit voisin","domain":"electromagnetism"},
    {"id":"aperi21:energy-in-inductor","title":"Énergie d’une bobine","description":"Énergie stockée dans le champ magnétique","domain":"electromagnetism"},
    {"id":"aperi21:rl-circuit","title":"Circuit RL","description":"Pourquoi le courant monte lentement","domain":"electromagnetism"},
    {"id":"aperi21:lc-oscillation","title":"Oscillations LC","description":"Les énergies électrique et magnétique s’échangent","domain":"electromagnetism"},
    {"id":"aperi21:ac-generation","title":"Production d’un courant alternatif","description":"Une bobine qui tourne et une sinusoïde","domain":"electromagnetism"},
    {"id":"aperi21:reactance","title":"Réactance et impédance","description":"Une opposition au courant qui dépend de la fréquence","domain":"electromagnetism"},
    {"id":"aperi21:phase-in-ac-circuit","title":"Déphasage dans les circuits en courant alternatif","description":"Tension et courant qui se décalent","domain":"electromagnetism"},
    {"id":"aperi21:series-rlc-resonance","title":"Résonance RLC","description":"La fréquence où l’impédance est minimale","domain":"electromagnetism"},
    {"id":"aperi21:transformer","title":"Transformateur","description":"Les spires et le rapport des tensions","domain":"electromagnetism"},
    {"id":"aperi21:motor","title":"Moteur électrique","description":"Tourner grâce à la force sur un courant","domain":"electromagnetism"},
    {"id":"aperi21:generator","title":"Générateur","description":"La f.é.m. produite par la rotation","domain":"electromagnetism"},
    {"id":"aperi21:displacement-current","title":"Courant de déplacement","description":"Le terme qui franchit l’espace du condensateur","domain":"electromagnetism"},
    {"id":"aperi21:maxwells-equations","title":"Équations de Maxwell","description":"Quatre équations qui unissent l’électromagnétisme","domain":"electromagnetism"},
    {"id":"aperi21:electromagnetic-wave","title":"Ondes électromagnétiques","description":"Des champs électrique et magnétique qui se propagent d’eux-mêmes","domain":"electromagnetism"},
    {"id":"aperi21:poynting-vector","title":"Vecteur de Poynting","description":"Le flux d’énergie transporté par les ondes électromagnétiques","domain":"electromagnetism"},
    {"id":"aperi21:radiation-pressure","title":"Pression de radiation","description":"La poussée de la lumière","domain":"electromagnetism"},
    {"id":"aperi21:antenna-radiation","title":"Rayonnement d’une antenne","description":"Les ondes qu’émet une charge accélérée","domain":"electromagnetism"},
    {"id":"aperi21:magnet-attraction","title":"Ce qui colle à un aimant","description":"Ce qu’un aimant attire et ce qu’il n’attire pas","domain":"electromagnetism"},
    {"id":"aperi21:magnetic-poles","title":"Les deux pôles d’un aimant","description":"Des pôles de même nom se repoussent, des pôles de noms contraires s’attirent","domain":"electromagnetism"},
    {"id":"aperi21:simple-circuit","title":"Construire un circuit électrique","description":"Le courant ne passe que si tout est relié ; coupez et l’ampoule s’éteint","domain":"electromagnetism"},
    {"id":"aperi21:electromagnet","title":"Électroaimant","description":"Un aimant seulement tant que le courant passe","domain":"electromagnetism"},
    {"id":"aperi21:iv-characteristic","title":"Courbes caractéristiques I–V","description":"Des composants dont le courant ne suit pas la tension en ligne droite","domain":"electromagnetism"},
    {"id":"aperi21:thermistor-and-ldr","title":"Thermistance et LDR","description":"Une résistance qui varie avec la température et la lumière","domain":"electromagnetism"},
    {"id":"aperi21:potential-divider","title":"Diviseur de tension","description":"Partager une tension avec des résistances","domain":"electromagnetism"},
    {"id":"aperi21:millikan-experiment","title":"Expérience de la goutte d’huile de Millikan","description":"La preuve que la charge vient par paquets","domain":"electromagnetism"},
    {"id":"aperi21:power-transmission","title":"Transport de l’électricité","description":"Élever la tension pour réduire les pertes","domain":"electromagnetism"},
    {"id":"aperi21:loudspeaker-and-microphone","title":"Haut-parleur et microphone","description":"Transformer le courant en vibration, et inversement","domain":"electromagnetism"},
    {"id":"aperi21:michelson-morley","title":"Expérience de Michelson et Morley","description":"La preuve qu’il n’y a pas d’éther","domain":"modern-physics"},
    {"id":"aperi21:relativity-of-simultaneity","title":"Relativité de la simultanéité","description":"Chaque référentiel a son propre « en même temps »","domain":"modern-physics"},
    {"id":"aperi21:time-dilation","title":"Dilatation du temps","description":"Une horloge en mouvement retarde","domain":"modern-physics"},
    {"id":"aperi21:light-clock","title":"Horloge de lumière","description":"L’expérience de pensée derrière la dilatation du temps","domain":"modern-physics"},
    {"id":"aperi21:length-contraction","title":"Contraction des longueurs","description":"Contraction dans la direction du mouvement","domain":"modern-physics"},
    {"id":"aperi21:muon-decay-evidence","title":"Des muons qui atteignent le sol","description":"Preuve observationnelle de la dilatation du temps","domain":"modern-physics"},
    {"id":"aperi21:relativistic-velocity-addition","title":"Composition relativiste des vitesses","description":"Une composition qui ne dépasse jamais la vitesse de la lumière","domain":"modern-physics"},
    {"id":"aperi21:twin-paradox","title":"Paradoxe des jumeaux","description":"L’accélération qui brise la symétrie","domain":"modern-physics"},
    {"id":"aperi21:spacetime-diagram","title":"Diagramme d’espace-temps","description":"Ligne d’univers et ligne de simultanéité","domain":"modern-physics"},
    {"id":"aperi21:light-cone","title":"Cône de lumière","description":"Là où une cause peut porter","domain":"modern-physics"},
    {"id":"aperi21:relativistic-momentum","title":"Quantité de mouvement relativiste","description":"La quantité de mouvement diverge quand la vitesse augmente","domain":"modern-physics"},
    {"id":"aperi21:relativistic-doppler","title":"Effet Doppler relativiste","description":"Décalage de fréquence augmenté de la dilatation du temps","domain":"modern-physics"},
    {"id":"aperi21:equivalence-principle","title":"Principe d’équivalence","description":"Accélération et pesanteur sont indiscernables","domain":"modern-physics"},
    {"id":"aperi21:gravitational-time-dilation","title":"Dilatation gravitationnelle du temps","description":"Les horloges battent à des rythmes différents selon le potentiel","domain":"modern-physics"},
    {"id":"aperi21:gravitational-redshift","title":"Décalage vers le rouge gravitationnel","description":"Énergie perdue en sortant d’un puits de gravité","domain":"modern-physics"},
    {"id":"aperi21:light-bending-by-gravity","title":"Déviation de la lumière","description":"Le trajet de la lumière s’incurve près d’une masse","domain":"modern-physics"},
    {"id":"aperi21:blackbody-radiation","title":"Rayonnement du corps noir","description":"Là où la théorie classique s’effondre","domain":"modern-physics"},
    {"id":"aperi21:wien-displacement-law","title":"Loi du déplacement de Wien","description":"Température et longueur d’onde du pic","domain":"modern-physics"},
    {"id":"aperi21:photoelectric-effect","title":"Effet photoélectrique","description":"Preuve que la lumière arrive par particules","domain":"modern-physics"},
    {"id":"aperi21:work-function-and-threshold","title":"Travail de sortie et fréquence seuil","description":"Fixé par la fréquence, pas par l’intensité","domain":"modern-physics"},
    {"id":"aperi21:compton-scattering","title":"Diffusion Compton","description":"Preuve qu’un photon porte une quantité de mouvement","domain":"modern-physics"},
    {"id":"aperi21:pair-production","title":"Création de paires","description":"De l’énergie qui devient matière","domain":"modern-physics"},
    {"id":"aperi21:de-broglie-wavelength","title":"Longueur d’onde de de Broglie","description":"La nature ondulatoire de la matière","domain":"modern-physics"},
    {"id":"aperi21:electron-diffraction","title":"Diffraction des électrons","description":"Voir les ondes de matière","domain":"modern-physics"},
    {"id":"aperi21:double-slit-with-electrons","title":"Double fente avec des électrons","description":"Une figure qui se forme un électron à la fois","domain":"modern-physics"},
    {"id":"aperi21:uncertainty-principle","title":"Principe d’incertitude","description":"Avec quelle précision fixer à la fois deux grandeurs conjuguées","domain":"modern-physics"},
    {"id":"aperi21:wave-function","title":"Fonction d’onde","description":"L’amplitude de probabilité et ce qu’elle signifie","domain":"modern-physics"},
    {"id":"aperi21:superposition-quantum","title":"Superposition quantique","description":"Être une somme de plusieurs états","domain":"modern-physics"},
    {"id":"aperi21:measurement-collapse","title":"Mesure et effondrement","description":"Comment l’observation fixe l’état","domain":"modern-physics"},
    {"id":"aperi21:particle-in-a-box","title":"Puits carré infini","description":"Quantification de l’énergie imposée par les parois","domain":"modern-physics"},
    {"id":"aperi21:finite-well","title":"Puits carré fini","description":"Une fonction d’onde qui fuit au-delà des parois","domain":"modern-physics"},
    {"id":"aperi21:quantum-tunneling","title":"Effet tunnel quantique","description":"La probabilité de traverser une barrière","domain":"modern-physics"},
    {"id":"aperi21:scanning-tunneling-microscope","title":"Microscope à effet tunnel","description":"Dessiner une surface avec le courant tunnel","domain":"modern-physics"},
    {"id":"aperi21:quantum-harmonic-oscillator","title":"Oscillateur harmonique quantique","description":"Niveaux équidistants et énergie de point zéro","domain":"modern-physics"},
    {"id":"aperi21:hydrogen-spectrum","title":"Spectre de l’hydrogène","description":"Un spectre de raies discret","domain":"modern-physics"},
    {"id":"aperi21:bohr-model","title":"Modèle de Bohr","description":"Orbites quantifiées","domain":"modern-physics"},
    {"id":"aperi21:atomic-orbital","title":"Orbitale atomique","description":"L’électron comme distribution de probabilité","domain":"modern-physics"},
    {"id":"aperi21:pauli-exclusion","title":"Principe d’exclusion de Pauli","description":"Jamais deux dans le même état","domain":"modern-physics"},
    {"id":"aperi21:electron-configuration","title":"Configuration électronique","description":"Comment naît le tableau périodique","domain":"modern-physics"},
    {"id":"aperi21:spin","title":"Spin","description":"Moment cinétique sans équivalent classique","domain":"modern-physics"},
    {"id":"aperi21:stern-gerlach","title":"Expérience de Stern–Gerlach","description":"Un faisceau atomique qui se divise","domain":"modern-physics"},
    {"id":"aperi21:zeeman-effect","title":"Effet Zeeman","description":"Niveaux d’énergie séparés par un champ magnétique","domain":"modern-physics"},
    {"id":"aperi21:laser-and-stimulated-emission","title":"Lasers et émission stimulée","description":"Amplifier la lumière en phase","domain":"modern-physics"},
    {"id":"aperi21:nuclear-structure","title":"De quoi est fait un noyau","description":"Protons et neutrons","domain":"modern-physics"},
    {"id":"aperi21:binding-energy-curve","title":"Courbe de l’énergie de liaison","description":"Pourquoi elle culmine au fer","domain":"modern-physics"},
    {"id":"aperi21:radioactive-decay","title":"Désintégration radioactive","description":"Demi-vie et décroissance exponentielle","domain":"modern-physics"},
    {"id":"aperi21:decay-types","title":"Types de rayonnement de désintégration","description":"Alpha, bêta, gamma","domain":"modern-physics"},
    {"id":"aperi21:radiometric-dating","title":"Datation radiométrique","description":"Mesurer le temps par ce qui reste","domain":"modern-physics"},
    {"id":"aperi21:nuclear-fission","title":"Fission nucléaire","description":"L’énergie libérée quand un noyau lourd se scinde","domain":"modern-physics"},
    {"id":"aperi21:chain-reaction","title":"Réaction en chaîne","description":"Une fission entretenue par les neutrons","domain":"modern-physics"},
    {"id":"aperi21:nuclear-fusion","title":"Fusion nucléaire","description":"L’énergie libérée quand des noyaux légers s’unissent","domain":"modern-physics"},
    {"id":"aperi21:antimatter","title":"Antimatière","description":"Un partenaire de charge opposée","domain":"modern-physics"},
    {"id":"aperi21:band-theory","title":"Théorie des bandes","description":"Ce qui distingue conducteurs, isolants et semi-conducteurs","domain":"modern-physics"},
    {"id":"aperi21:fermi-level","title":"Niveau de Fermi","description":"Hauteur de remplissage des électrons","domain":"modern-physics"},
    {"id":"aperi21:semiconductor-doping","title":"Dopage","description":"Comment les impuretés créent le type n et le type p","domain":"modern-physics"},
    {"id":"aperi21:pn-junction","title":"Jonction p–n","description":"Zone de déplétion et redressement","domain":"modern-physics"},
    {"id":"aperi21:diode-and-led","title":"Diodes et LED","description":"Courant à sens unique et émission de lumière","domain":"modern-physics"},
    {"id":"aperi21:transistor-principle","title":"Transistor","description":"Un petit signal commande un grand courant","domain":"modern-physics"},
    {"id":"aperi21:photovoltaic-effect","title":"Effet photovoltaïque","description":"Une tension créée par la lumière","domain":"modern-physics"},
    {"id":"aperi21:superconductivity","title":"Supraconductivité","description":"L’état dans lequel la résistance s’annule","domain":"modern-physics"},
    {"id":"aperi21:meissner-effect","title":"Effet Meissner","description":"Un supraconducteur expulse le champ magnétique","domain":"modern-physics"},
    {"id":"aperi21:bose-einstein-condensate","title":"Condensation de Bose–Einstein","description":"Des particules froides qui s’entassent dans un seul état","domain":"modern-physics"},
    {"id":"aperi21:scale-of-universe","title":"L’échelle de l’univers","description":"Des tailles de l’atome à l’univers, reliées par des puissances de dix","domain":"modern-physics"},
    {"id":"aperi21:rutherford-scattering","title":"Diffusion de Rutherford","description":"L’expérience où la plupart sont passées et quelques-unes ont rebondi","domain":"modern-physics"},
    {"id":"aperi21:ionizing-radiation","title":"Rayonnement ionisant","description":"Une énergie de photon assez grande pour rompre des liaisons","domain":"modern-physics"},
    {"id":"aperi21:exchange-particles","title":"Particules d’échange","description":"Particules qui transmettent une force","domain":"modern-physics"},
  ],
};
