/**
 * 자동 생성 파일 — 직접 편집하지 말 것.
 *
 * 생성: pnpm catalog:gen  (scripts/gen-aperi21-catalog.mts)
 * 출처: 각 sim 의 schema(label/operation) + docs/topics/topics.yaml(분야).
 */

import type { Aperi21Catalog } from '../catalog-types.js';

export const CATALOG: Aperi21Catalog = {
  locale: "hi",
  domains: [
    {"id":"kinematics","name":"गतिकी"},
    {"id":"newtonian-mechanics","name":"न्यूटनी यांत्रिकी"},
    {"id":"energy-momentum","name":"कार्य, ऊर्जा और संवेग"},
    {"id":"rotation-oscillation","name":"घूर्णन और दोलन"},
    {"id":"gravitation","name":"गुरुत्वाकर्षण और खगोलिकी"},
    {"id":"fluids","name":"तरल"},
    {"id":"thermodynamics","name":"ऊष्मीय और सांख्यिकीय भौतिकी"},
    {"id":"waves-acoustics","name":"तरंगें और ध्वनिकी"},
    {"id":"optics","name":"प्रकाशिकी"},
    {"id":"electromagnetism","name":"विद्युतचुंबकत्व"},
    {"id":"modern-physics","name":"आधुनिक भौतिकी"},
  ],
  entries: [
    {"id":"aperi21:reference-frame","title":"निर्देश तंत्र","description":"गति का वर्णन प्रेक्षक पर कैसे निर्भर करता है","domain":"kinematics"},
    {"id":"aperi21:coordinate-choice","title":"अक्षों का चयन","description":"अक्षों का चयन समीकरणों को कैसे बदलता है","domain":"kinematics"},
    {"id":"aperi21:average-velocity","title":"औसत वेग","description":"पूरे अंतराल का प्रतिनिधित्व करने वाला एक वेग","domain":"kinematics"},
    {"id":"aperi21:average-acceleration","title":"औसत त्वरण","description":"वेग परिवर्तन की दर","domain":"kinematics"},
    {"id":"aperi21:direction-of-acceleration","title":"त्वरण की दिशा","description":"वह वेग की दिशा में है या उसके विपरीत","domain":"kinematics"},
    {"id":"aperi21:uniform-motion","title":"एकसमान गति","description":"समान समय में समान अंतराल","domain":"kinematics"},
    {"id":"aperi21:uniformly-accelerated-motion","title":"एकसमान त्वरित गति","description":"समान समय में तय दूरी हर बार समान मात्रा से बढ़ती है","domain":"kinematics"},
    {"id":"aperi21:position-time-graph","title":"स्थिति-समय ग्राफ़","description":"जितनी तेज़ी से ऊपर चढ़े, छोड़ी गई रेखा उतनी ही खड़ी","domain":"kinematics"},
    {"id":"aperi21:velocity-time-graph","title":"वेग-समय ग्राफ़","description":"ग्राफ़ के नीचे का क्षेत्रफल ही तय की गई दूरी है","domain":"kinematics"},
    {"id":"aperi21:acceleration-time-graph","title":"त्वरण-समय ग्राफ़","description":"ग्राफ़ के नीचे का क्षेत्रफल वेग में परिवर्तन है","domain":"kinematics"},
    {"id":"aperi21:free-fall","title":"मुक्त पतन","description":"भार कितना भी अलग हो, दोनों गेंदें साथ-साथ गिरती हैं और साथ-साथ ज़मीन पर पहुँचती हैं","domain":"kinematics"},
    {"id":"aperi21:vertical-throw","title":"ऊर्ध्वाधर प्रक्षेप","description":"ऊपर जाने और नीचे आने की सममिति","domain":"kinematics"},
    {"id":"aperi21:gravitational-acceleration","title":"गुरुत्वीय त्वरण","description":"ऐसा त्वरण जो वेग शून्य होने पर भी नहीं रुकता","domain":"kinematics"},
    {"id":"aperi21:terminal-velocity","title":"सीमांत वेग","description":"जिस क्षण वायु प्रतिरोध गुरुत्व के बराबर पहुँचता है, उसी क्षण से यह और तेज़ नहीं होता","domain":"kinematics"},
    {"id":"aperi21:vector-decomposition","title":"सदिश के घटक","description":"शीर्ष से हर अक्ष पर सीधा लंब गिराएँ — वहीं हर घटक समाप्त होता है","domain":"kinematics"},
    {"id":"aperi21:vector-addition","title":"सदिशों का योग","description":"b को a के शीर्ष पर खिसकाएँ, दोनों पर चलें — अंतिम सिरा ही योग है","domain":"kinematics"},
    {"id":"aperi21:relative-velocity","title":"आपेक्षिक वेग","description":"देखने वाला बदलो तो नाव का छोड़ा हुआ पथ झुक जाता है","domain":"kinematics"},
    {"id":"aperi21:river-crossing","title":"नदी पार करना","description":"सीधे उस पार साधी गई नाव को भी धारा बहाव की दिशा में धकेल देती है","domain":"kinematics"},
    {"id":"aperi21:projectile-motion","title":"प्रक्षेप्य गति","description":"क्षैतिज और ऊर्ध्वाधर एक-दूसरे को प्रभावित किए बिना चलते हैं","domain":"kinematics"},
    {"id":"aperi21:projectile-range","title":"परास और प्रक्षेपण कोण","description":"प्रक्षेपण कोण उड़ान की दूरी को कैसे बदलता है","domain":"kinematics"},
    {"id":"aperi21:trajectory-equation","title":"प्रक्षेप-पथ समीकरण","description":"समय को विलोपित करने पर बचा पथ","domain":"kinematics"},
    {"id":"aperi21:uniform-circular-motion","title":"एकसमान वृत्तीय गति","description":"वेग-तीर की लंबाई वही रहती है, वह केवल मुड़ता है","domain":"kinematics"},
    {"id":"aperi21:centripetal-acceleration","title":"अभिकेंद्र त्वरण","description":"वेग में परिवर्तन सदा केंद्र की ओर मुड़ता है","domain":"kinematics"},
    {"id":"aperi21:angular-acceleration","title":"कोणीय त्वरण","description":"हर आधा सेकंड पिछले से बड़ा कोण घूमता है","domain":"kinematics"},
    {"id":"aperi21:tangential-normal-acceleration","title":"स्पर्शरेखीय और अभिलंब त्वरण","description":"चाल के परिवर्तन को दिशा के परिवर्तन से अलग करना","domain":"kinematics"},
    {"id":"aperi21:radius-of-curvature","title":"वक्रता त्रिज्या","description":"मोड़ से मेल खाता वृत्त पथ पर सवार होकर चलता है","domain":"kinematics"},
    {"id":"aperi21:stopping-distance","title":"रुकने की दूरी","description":"प्रतिक्रिया दूरी रैखिक रूप से बढ़ती है, ब्रेकिंग दूरी वर्ग के अनुसार","domain":"kinematics"},
    {"id":"aperi21:newtons-first-law","title":"जड़त्वीय निर्देश तंत्र","description":"केवल बस धीमी होती है; यात्री चलता रहता है","domain":"newtonian-mechanics"},
    {"id":"aperi21:newtons-second-law","title":"न्यूटन का गति का दूसरा नियम","description":"परिणामी बल, द्रव्यमान और त्वरण","domain":"newtonian-mechanics"},
    {"id":"aperi21:newtons-third-law","title":"क्रिया और प्रतिक्रिया","description":"भिन्न पिंडों पर लगने वाला बल-युग्म","domain":"newtonian-mechanics"},
    {"id":"aperi21:net-force","title":"परिणामी बल","description":"कई बलों का सदिश योग","domain":"newtonian-mechanics"},
    {"id":"aperi21:free-body-diagram","title":"मुक्त पिंड आरेख","description":"एक ही पिंड पर लगने वाले बलों को अलग करना","domain":"newtonian-mechanics"},
    {"id":"aperi21:inertial-vs-gravitational-mass","title":"जड़त्वीय द्रव्यमान और गुरुत्वीय द्रव्यमान","description":"दो अलग परिभाषाएँ एक ही मान देती हैं","domain":"newtonian-mechanics"},
    {"id":"aperi21:normal-force","title":"अभिलंब बल","description":"संपर्क सतह का लंबवत धक्का","domain":"newtonian-mechanics"},
    {"id":"aperi21:apparent-weight","title":"आभासी भार","description":"त्वरित होती लिफ़्ट में तराज़ू","domain":"newtonian-mechanics"},
    {"id":"aperi21:static-friction","title":"स्थैतिक घर्षण","description":"वह बल जो वस्तु के चलने तक टिका रहता है","domain":"newtonian-mechanics"},
    {"id":"aperi21:kinetic-friction","title":"गतिज घर्षण","description":"फिसलते समय का घर्षण","domain":"newtonian-mechanics"},
    {"id":"aperi21:angle-of-friction","title":"घर्षण कोण","description":"वह ढलान जिस पर फिसलना शुरू होता है","domain":"newtonian-mechanics"},
    {"id":"aperi21:inclined-plane","title":"आनत तल","description":"गुरुत्व को ढलान के अनुदिश और उसके लंबवत बाँटना","domain":"newtonian-mechanics"},
    {"id":"aperi21:tension","title":"तनाव","description":"रस्सी खिंचाव को कैसे आगे पहुँचाती है","domain":"newtonian-mechanics"},
    {"id":"aperi21:pulley-system","title":"घिरनियाँ","description":"एक युक्ति जो बल की दिशा और परिमाण बदलती है","domain":"newtonian-mechanics"},
    {"id":"aperi21:connected-bodies","title":"जुड़े हुए पिंड","description":"साथ-साथ चलते पिंडों का त्वरण","domain":"newtonian-mechanics"},
    {"id":"aperi21:spring-force","title":"स्प्रिंग बल","description":"खिंचाव के समानुपाती प्रत्यानयन बल","domain":"newtonian-mechanics"},
    {"id":"aperi21:centripetal-force","title":"अभिकेंद्र बल","description":"किसी वस्तु को वृत्त में घुमाए रखने वाली चीज़","domain":"newtonian-mechanics"},
    {"id":"aperi21:conical-pendulum","title":"शंक्वाकार लोलक","description":"तनाव और गुरुत्व से वृत्तीय गति","domain":"newtonian-mechanics"},
    {"id":"aperi21:banked-curve","title":"ढालू मोड़","description":"वह ढाल कोण जो बिना घर्षण के कार को मोड़ देता है","domain":"newtonian-mechanics"},
    {"id":"aperi21:vertical-loop","title":"ऊर्ध्वाधर लूप","description":"वह न्यूनतम चाल जो शीर्ष पर गेंद को लूप पर बनाए रखती है","domain":"newtonian-mechanics"},
    {"id":"aperi21:drag-force","title":"वायु प्रतिरोध","description":"चाल जितनी अधिक, कर्षण का चाल के वर्ग के समानुपाती भाग उतनी ही तेज़ी से बढ़ता है","domain":"newtonian-mechanics"},
    {"id":"aperi21:buoyant-force-as-force","title":"बल के रूप में उत्प्लावन बल","description":"तरल का ऊपर की ओर धक्का","domain":"newtonian-mechanics"},
    {"id":"aperi21:non-inertial-frame","title":"अजड़त्वीय निर्देश तंत्र","description":"त्वरित निर्देश तंत्र से देखी गई गति","domain":"newtonian-mechanics"},
    {"id":"aperi21:fictitious-force","title":"छद्म बल","description":"अजड़त्वीय निर्देश तंत्र का आभासी बल","domain":"newtonian-mechanics"},
    {"id":"aperi21:coriolis-effect","title":"कोरिओलिस प्रभाव","description":"घूर्णी निर्देश तंत्र में मुड़ने वाला पथ","domain":"newtonian-mechanics"},
    {"id":"aperi21:impulse-force-relation","title":"बल और आवेग","description":"कम समय का बड़ा बल और लंबे समय का छोटा बल","domain":"newtonian-mechanics"},
    {"id":"aperi21:equilibrium-of-forces","title":"बलों का संतुलन","description":"शून्य परिणामी बल","domain":"newtonian-mechanics"},
    {"id":"aperi21:atwood-machine","title":"एटवुड मशीन","description":"कुल द्रव्यमान समान हो तो अंतर त्वरण तय करता है","domain":"newtonian-mechanics"},
    {"id":"aperi21:balance-scale","title":"तराज़ू को संतुलित करना","description":"भुजा की लंबाई और भार दोनों से तय होने वाला संतुलन","domain":"newtonian-mechanics"},
    {"id":"aperi21:mechanical-advantage","title":"यांत्रिक लाभ","description":"उत्तोलक और आनत तल आवश्यक बल को कैसे घटाते हैं","domain":"newtonian-mechanics"},
    {"id":"aperi21:youngs-modulus","title":"यंग प्रत्यास्थता गुणांक","description":"तार कितना खिंचता है, यह उसकी लंबाई नहीं बल्कि उसका पदार्थ तय करता है","domain":"newtonian-mechanics"},
    {"id":"aperi21:stress-strain-curve","title":"प्रतिबल–विकृति वक्र","description":"खींचने पर पदार्थ कैसे प्रतिक्रिया करता है","domain":"newtonian-mechanics"},
    {"id":"aperi21:work-by-variable-force","title":"परिवर्ती बल द्वारा किया गया कार्य","description":"बल–विस्थापन ग्राफ़ के नीचे का क्षेत्रफल","domain":"energy-momentum"},
    {"id":"aperi21:kinetic-energy","title":"गतिज ऊर्जा","description":"चाल में निहित ऊर्जा","domain":"energy-momentum"},
    {"id":"aperi21:work-energy-theorem","title":"कार्य-ऊर्जा प्रमेय","description":"कुल कार्य गतिज ऊर्जा में परिवर्तन के बराबर होता है","domain":"energy-momentum"},
    {"id":"aperi21:gravitational-potential-energy","title":"गुरुत्वीय स्थितिज ऊर्जा","description":"ऊँचाई में संचित ऊर्जा","domain":"energy-momentum"},
    {"id":"aperi21:elastic-potential-energy","title":"प्रत्यास्थ स्थितिज ऊर्जा","description":"विरूपण में संचित ऊर्जा","domain":"energy-momentum"},
    {"id":"aperi21:conservative-force","title":"संरक्षी बल","description":"ऐसा बल जिसका कार्य पथ पर निर्भर नहीं करता — और वह स्थितिज ऊर्जा जिसे यह संभव बनाता है","domain":"energy-momentum"},
    {"id":"aperi21:non-conservative-force","title":"असंरक्षी बल","description":"पथ पर निर्भर करने वाला कार्य","domain":"energy-momentum"},
    {"id":"aperi21:conservation-of-mechanical-energy","title":"यांत्रिक ऊर्जा संरक्षण","description":"वह योग जो ऊँचाई और गति के स्थान बदलते समय भी बना रहता है","domain":"energy-momentum"},
    {"id":"aperi21:energy-dissipation","title":"ऊर्जा का क्षय","description":"घर्षण जो हिस्सा ले जाता है, और वह कहाँ जाता है","domain":"energy-momentum"},
    {"id":"aperi21:potential-energy-curve","title":"स्थितिज ऊर्जा वक्र","description":"वक्र का आकार गति को कैसे तय करता है","domain":"energy-momentum"},
    {"id":"aperi21:equilibrium-points","title":"संतुलन बिंदु","description":"स्थायी, अस्थायी और उदासीन संतुलन","domain":"energy-momentum"},
    {"id":"aperi21:efficiency","title":"दक्षता","description":"जो निकलता है और जो डाला जाता है, उनका अनुपात","domain":"energy-momentum"},
    {"id":"aperi21:impulse-momentum-theorem","title":"आवेग–संवेग प्रमेय","description":"आवेग संवेग में परिवर्तन के बराबर है","domain":"energy-momentum"},
    {"id":"aperi21:conservation-of-momentum","title":"संवेग संरक्षण","description":"कोई बाह्य बल न लगने पर कुल संवेग","domain":"energy-momentum"},
    {"id":"aperi21:elastic-collision","title":"प्रत्यास्थ टक्कर","description":"ऐसी टक्कर जिसमें गतिज ऊर्जा भी संरक्षित रहती है","domain":"energy-momentum"},
    {"id":"aperi21:inelastic-collision","title":"अप्रत्यास्थ टक्कर","description":"ऐसी टक्कर जिसमें ऊर्जा खोती है","domain":"energy-momentum"},
    {"id":"aperi21:perfectly-inelastic-collision","title":"पूर्णतः अप्रत्यास्थ टक्कर","description":"जब दोनों चिपककर साथ चलते हैं","domain":"energy-momentum"},
    {"id":"aperi21:two-dimensional-collision","title":"द्वि-विमीय टक्कर","description":"हर घटक के लिए अलग-अलग लागू होने वाला संरक्षण","domain":"energy-momentum"},
    {"id":"aperi21:center-of-mass-motion","title":"द्रव्यमान केंद्र की गति","description":"वह गति जिसे आंतरिक बल बदल नहीं सकते","domain":"energy-momentum"},
    {"id":"aperi21:explosion-and-recoil","title":"विस्फोट और प्रतिक्षेप","description":"जब विराम में स्थित निकाय टूटकर अलग होता है","domain":"energy-momentum"},
    {"id":"aperi21:rocket-equation","title":"रॉकेट समीकरण","description":"ईंधन फेंककर पाई गई चाल","domain":"energy-momentum"},
    {"id":"aperi21:ballistic-pendulum","title":"प्राक्षेपिक लोलक","description":"वह माप जो टक्कर को ऊर्जा संरक्षण से जोड़ता है","domain":"energy-momentum"},
    {"id":"aperi21:energy-in-collision","title":"टक्कर में ऊर्जा","description":"क्या संरक्षित रहता है और क्या नहीं, इसमें भेद","domain":"energy-momentum"},
    {"id":"aperi21:energy-flow-diagram","title":"ऊर्जा प्रवाह आरेख","description":"ऊर्जा कहाँ जाती है, शाखाओं की मोटाई से दिखाया गया","domain":"energy-momentum"},
    {"id":"aperi21:torque","title":"बल-आघूर्ण","description":"वस्तुओं को घुमाने वाली राशि, और बल-भुजा की लंबाई","domain":"rotation-oscillation"},
    {"id":"aperi21:moment-of-inertia","title":"जड़त्व आघूर्ण","description":"द्रव्यमान का वितरण घूर्णन के प्रतिरोध को कैसे तय करता है","domain":"rotation-oscillation"},
    {"id":"aperi21:parallel-axis-theorem","title":"समांतर अक्ष प्रमेय","description":"अक्ष खिसकाने पर जड़त्व आघूर्ण","domain":"rotation-oscillation"},
    {"id":"aperi21:rotational-kinetic-energy","title":"घूर्णी गतिज ऊर्जा","description":"घूर्णन में निहित ऊर्जा","domain":"rotation-oscillation"},
    {"id":"aperi21:angular-momentum","title":"कोणीय संवेग","description":"घूर्णन में संवेग के समतुल्य राशि","domain":"rotation-oscillation"},
    {"id":"aperi21:conservation-of-angular-momentum","title":"कोणीय संवेग संरक्षण","description":"बाँहें सिकोड़ने से घूमना तेज़ क्यों हो जाता है","domain":"rotation-oscillation"},
    {"id":"aperi21:rolling-without-slipping","title":"बिना फिसले लुढ़कना","description":"स्थानांतरण को घूर्णन से जोड़ने वाली बाध्यता","domain":"rotation-oscillation"},
    {"id":"aperi21:rolling-race","title":"लुढ़कती वस्तुओं की दौड़","description":"द्रव्यमान वितरण से तय होता पहुँचने का क्रम","domain":"rotation-oscillation"},
    {"id":"aperi21:static-equilibrium","title":"स्थैतिक संतुलन","description":"परिणामी बल और परिणामी बल-आघूर्ण दोनों शून्य हैं","domain":"rotation-oscillation"},
    {"id":"aperi21:center-of-gravity","title":"गुरुत्व केंद्र","description":"वह बिंदु जो तय करता है कि चीज़ें कब पलटती हैं","domain":"rotation-oscillation"},
    {"id":"aperi21:gyroscopic-precession","title":"जाइरोस्कोपिक पुरस्सरण","description":"बल-आघूर्ण कोणीय संवेग की दिशा को घुमाता है","domain":"rotation-oscillation"},
    {"id":"aperi21:angular-momentum-vector","title":"कोणीय संवेग की दिशा","description":"दाएँ हाथ का नियम और घूर्णन अक्ष","domain":"rotation-oscillation"},
    {"id":"aperi21:simple-harmonic-motion","title":"सरल आवर्त गति","description":"विस्थापन के समानुपाती प्रत्यानयन बल के अधीन गति","domain":"rotation-oscillation"},
    {"id":"aperi21:shm-energy","title":"सरल आवर्त गति में ऊर्जा","description":"गतिज और स्थितिज ऊर्जा आपस में जगह बदलती हैं","domain":"rotation-oscillation"},
    {"id":"aperi21:mass-spring-system","title":"स्प्रिंग से लटका पिंड","description":"द्रव्यमान और स्प्रिंग नियतांक से तय होने वाला आवर्तकाल","domain":"rotation-oscillation"},
    {"id":"aperi21:simple-pendulum","title":"सरल लोलक","description":"छोटे आयाम पर आवर्तकाल","domain":"rotation-oscillation"},
    {"id":"aperi21:physical-pendulum","title":"भौतिक लोलक","description":"विस्तारित पिंड का दोलन","domain":"rotation-oscillation"},
    {"id":"aperi21:pendulum-amplitude-dependence","title":"आयाम और आवर्तकाल","description":"छोटे झूलों में आयाम अलग होने पर भी सब साथ लौटते हैं; चौड़े झूलों में पीछे छूट जाते हैं","domain":"rotation-oscillation"},
    {"id":"aperi21:damped-oscillation","title":"अवमंदित दोलन","description":"ऊर्जा खोता दोलन","domain":"rotation-oscillation"},
    {"id":"aperi21:damping-regimes","title":"अवमंदन की तीन अवस्थाएँ","description":"अल्प-अवमंदित, क्रांतिक अवमंदित और अति-अवमंदित गति","domain":"rotation-oscillation"},
    {"id":"aperi21:driven-oscillation","title":"प्रणोदित दोलन","description":"बाहरी प्रणोदन के प्रति अनुक्रिया","domain":"rotation-oscillation"},
    {"id":"aperi21:resonance","title":"अनुनाद","description":"जब चालक आवृत्ति प्राकृतिक आवृत्ति के बराबर हो","domain":"rotation-oscillation"},
    {"id":"aperi21:quality-factor","title":"गुणता कारक","description":"अनुनाद कितना तीक्ष्ण है","domain":"rotation-oscillation"},
    {"id":"aperi21:coupled-oscillators","title":"युग्मित दोलित्र","description":"ऊर्जा का आदान-प्रदान करते दो दोलित्र","domain":"rotation-oscillation"},
    {"id":"aperi21:normal-modes","title":"प्रसामान्य विधाएँ","description":"वे प्राकृतिक आकृतियाँ जिनमें कोई निकाय कंपन करता है","domain":"rotation-oscillation"},
    {"id":"aperi21:beats-in-oscillation","title":"दोलन में विस्पंद","description":"दो निकट आवृत्तियों का योग","domain":"rotation-oscillation"},
    {"id":"aperi21:phase-space","title":"कला समष्टि","description":"स्थिति–वेग तल पर देखी गई गति","domain":"rotation-oscillation"},
    {"id":"aperi21:nonlinear-oscillation","title":"अरैखिक दोलन","description":"जब प्रत्यानयन बल समानुपाती नहीं रहता","domain":"rotation-oscillation"},
    {"id":"aperi21:gears","title":"गियर","description":"दाँतों की संख्या घुमाव के बदले बल कैसे देती है","domain":"rotation-oscillation"},
    {"id":"aperi21:newtons-law-of-gravitation","title":"न्यूटन का गुरुत्वाकर्षण नियम","description":"दूरी के वर्ग के साथ घटने वाला बल","domain":"gravitation"},
    {"id":"aperi21:gravitational-field","title":"गुरुत्वीय क्षेत्र","description":"स्थान में फैली गुरुत्व की तीव्रता","domain":"gravitation"},
    {"id":"aperi21:range-and-surface-gravity","title":"गुरुत्व और परास","description":"एक जैसा प्रक्षेपण, अलग गुरुत्व","domain":"gravitation"},
    {"id":"aperi21:shell-theorem","title":"कोश प्रमेय","description":"गोलीय कोश के अंदर और बाहर गुरुत्व","domain":"gravitation"},
    {"id":"aperi21:gravity-inside-earth","title":"पृथ्वी के अंदर गुरुत्व","description":"गहराई के साथ घटता गुरुत्व","domain":"gravitation"},
    {"id":"aperi21:gravitational-potential-energy-general","title":"गुरुत्वीय स्थितिज ऊर्जा (व्यापक)","description":"अनंत से मापी गई ऋणात्मक ऊर्जा","domain":"gravitation"},
    {"id":"aperi21:escape-velocity","title":"पलायन वेग","description":"गुरुत्व से मुक्त होने की न्यूनतम चाल","domain":"gravitation"},
    {"id":"aperi21:orbital-velocity","title":"कक्षीय वेग","description":"वह चाल जो कक्षा को वृत्ताकार बनाए रखती है","domain":"gravitation"},
    {"id":"aperi21:circular-orbit","title":"वृत्ताकार कक्षा","description":"वह गति जिसमें गुरुत्व ही अभिकेंद्र बल है","domain":"gravitation"},
    {"id":"aperi21:elliptical-orbit","title":"दीर्घवृत्ताकार कक्षा","description":"केंद्रीय पिंड एक नाभि पर स्थित है","domain":"gravitation"},
    {"id":"aperi21:keplers-first-law","title":"केप्लर का पहला नियम","description":"कक्षाएँ दीर्घवृत्त होती हैं","domain":"gravitation"},
    {"id":"aperi21:keplers-second-law","title":"केप्लर का दूसरा नियम","description":"समान समय में समान क्षेत्रफल","domain":"gravitation"},
    {"id":"aperi21:keplers-third-law","title":"केप्लर का तीसरा नियम","description":"आवर्तकाल अर्ध-दीर्घ अक्ष पर कैसे निर्भर करता है","domain":"gravitation"},
    {"id":"aperi21:two-body-problem","title":"द्वि-पिंड समस्या","description":"अपने साझा द्रव्यमान केंद्र की परिक्रमा करते दो पिंड","domain":"gravitation"},
    {"id":"aperi21:tidal-force","title":"ज्वारीय बल","description":"गुरुत्व के अंतर से होने वाला खिंचाव","domain":"gravitation"},
    {"id":"aperi21:roche-limit","title":"रोश सीमा","description":"वह दूरी जिस पर ज्वारीय बल किसी पिंड को चीर देता है","domain":"gravitation"},
    {"id":"aperi21:weightlessness","title":"भारहीनता","description":"मुक्त पतन में आभासी भार","domain":"gravitation"},
    {"id":"aperi21:geostationary-orbit","title":"भूस्थिर कक्षा","description":"पृथ्वी के एक घूर्णन जितनी लंबी कक्षा","domain":"gravitation"},
    {"id":"aperi21:gravitational-slingshot","title":"गुरुत्वीय सहायता","description":"किसी ग्रह के पास से गुज़रकर चाल बदलना","domain":"gravitation"},
    {"id":"aperi21:lagrange-points","title":"लाग्रांज बिंदु","description":"काठियों से दूर बहना, शिखरों के चारों ओर घूमना","domain":"gravitation"},
    {"id":"aperi21:orbital-transfer","title":"कक्षीय स्थानांतरण","description":"होमान स्थानांतरण और उसकी लागत","domain":"gravitation"},
    {"id":"aperi21:black-hole-horizon","title":"घटना क्षितिज","description":"वह त्रिज्या जहाँ पलायन वेग प्रकाश की चाल तक पहुँचता है","domain":"gravitation"},
    {"id":"aperi21:diurnal-motion","title":"दैनिक गति","description":"एक दिन में सूर्य और तारे आकाश में जो पथ बनाते हैं","domain":"gravitation"},
    {"id":"aperi21:earth-rotation-day-night","title":"पृथ्वी का घूर्णन, दिन और रात","description":"घूमती पृथ्वी पर दिन और रात बारी-बारी से क्यों आते हैं","domain":"gravitation"},
    {"id":"aperi21:earth-revolution-constellations","title":"पृथ्वी की कक्षा और तारामंडल","description":"हमें दिखने वाले तारामंडल ऋतुओं के साथ क्यों बदलते हैं","domain":"gravitation"},
    {"id":"aperi21:solar-altitude-shadow","title":"सूर्य की ऊँचाई और छायाएँ","description":"सूर्य की ऊँचाई बदलने पर छाया की लंबाई और गर्माहट साथ-साथ बदलती हैं","domain":"gravitation"},
    {"id":"aperi21:seasonal-sun-path","title":"ऋतुओं के साथ सूर्य का पथ","description":"दोपहर की ऊँचाई और दिन की लंबाई एक साथ कैसे बदलती हैं","domain":"gravitation"},
    {"id":"aperi21:axial-tilt-seasons","title":"अक्षीय झुकाव और ऋतुएँ","description":"झुकी हुई अवस्था में परिक्रमा करती पृथ्वी से बनी ऋतुएँ","domain":"gravitation"},
    {"id":"aperi21:moon-phases","title":"चंद्रमा की कलाएँ","description":"धूप से प्रकाशित चंद्रमा का कौन-सा भाग हमारी ओर होता है","domain":"gravitation"},
    {"id":"aperi21:eclipse","title":"सूर्य ग्रहण और चंद्र ग्रहण","description":"जब सूर्य, पृथ्वी और चंद्रमा एक सीध में आते हैं","domain":"gravitation"},
    {"id":"aperi21:stellar-parallax","title":"तारकीय लंबन","description":"वह कोण जिससे पृथ्वी के सूर्य की परिक्रमा करते समय पास का तारा खिसकता दिखता है","domain":"gravitation"},
    {"id":"aperi21:apparent-brightness","title":"आभासी चमक","description":"वही प्रकाश अधिक बड़े क्षेत्र पर बँट जाता है","domain":"gravitation"},
    {"id":"aperi21:magnitude-scale","title":"तारकीय कांतिमान","description":"चमक को कांतिमान में कैसे लिखा जाता है","domain":"gravitation"},
    {"id":"aperi21:star-color-temperature","title":"तारे का रंग और सतह का ताप","description":"सतह का ताप तारे के प्रकाश का रंग कैसे तय करता है","domain":"gravitation"},
    {"id":"aperi21:expanding-universe","title":"फैलता हुआ ब्रह्मांड","description":"हर दिशा में दूर जाती आकाशगंगाएँ","domain":"gravitation"},
    {"id":"aperi21:stellar-luminosity","title":"दीप्ति","description":"कोई तारा वास्तव में कितना प्रकाश देता है","domain":"gravitation"},
    {"id":"aperi21:hr-diagram","title":"HR आरेख","description":"सबसे भारी तारे सबसे पहले मुख्य अनुक्रम छोड़ते हैं","domain":"gravitation"},
    {"id":"aperi21:star-radiation-gravity-balance","title":"विकिरण दाब और गुरुत्व का संतुलन","description":"तारा क्यों न ढहता है, न बिखरता है","domain":"gravitation"},
    {"id":"aperi21:orbital-decay","title":"कक्षीय क्षय","description":"विरल हवा से खिंचती कक्षा","domain":"gravitation"},
    {"id":"aperi21:inverse-square-law","title":"व्युत्क्रम वर्ग नियम","description":"फैलने के साथ विरल होता","domain":"gravitation"},
    {"id":"aperi21:stellar-nucleosynthesis","title":"तारकीय नाभिकीय संश्लेषण","description":"भारी तत्व तारों के भीतर कैसे बनते हैं","domain":"gravitation"},
    {"id":"aperi21:star-life-cycle","title":"तारे का जीवन चक्र","description":"द्रव्यमान तारे का मार्ग कैसे तय करता है","domain":"gravitation"},
    {"id":"aperi21:stellar-spectral-class","title":"तारों के स्पेक्ट्रमी वर्ग","description":"ताप द्वारा तय अवशोषण-रेखाओं के प्रतिरूप","domain":"gravitation"},
    {"id":"aperi21:supernova-and-neutron-star","title":"सुपरनोवा और न्यूट्रॉन तारा","description":"अंतिम पतन और पलटाव","domain":"gravitation"},
    {"id":"aperi21:exoplanet-detection","title":"बाह्यग्रहों का पता लगाना","description":"ग्रह द्वारा छोड़े गए निशान","domain":"gravitation"},
    {"id":"aperi21:projectile-in-wind","title":"हवा और परास","description":"एक-सा प्रक्षेपण, अलग हवा","domain":"fluids"},
    {"id":"aperi21:pressure-isotropy","title":"दाब की समदैशिकता","description":"प्लेट आधा चक्कर घूमकर पथ को वृत्त में बंद करती है, फिर पाठक उसे हाथ से घुमाता है","domain":"fluids"},
    {"id":"aperi21:hydrostatic-pressure","title":"द्रवस्थैतिक दाब","description":"गहराई के साथ बढ़ता दाब","domain":"fluids"},
    {"id":"aperi21:pressure-and-container-shape","title":"बर्तन का आकार और तली पर दाब","description":"जल-स्तर बदलो और तीनों को फिर से भरो","domain":"fluids"},
    {"id":"aperi21:atmospheric-pressure","title":"वायुमंडलीय दाब","description":"वायु-स्तंभ का भार","domain":"fluids"},
    {"id":"aperi21:barometer","title":"वायुदाबमापी","description":"पारे के स्तंभ की ऊँचाई","domain":"fluids"},
    {"id":"aperi21:manometer","title":"मैनोमीटर","description":"द्रव-स्तंभ से दाब पढ़ना","domain":"fluids"},
    {"id":"aperi21:pascals-principle","title":"पास्कल का नियम","description":"दाब का संचरण और हाइड्रॉलिक प्रेस","domain":"fluids"},
    {"id":"aperi21:buoyancy","title":"उत्प्लावन बल","description":"हटाए गए तरल के भार जितना","domain":"fluids"},
    {"id":"aperi21:archimedes-principle","title":"आर्किमिडीज़ का सिद्धांत — उत्प्लावन बल का परिमाण","description":"2.0 kg और 1.0 L की एक वस्तु को टोंटी तक भरे बर्तन में उतारा जाता है। विस्थापित पानी टोंटी से कप में गिरता है, और पानी वाले तराज़ू पर ठीक उतना बढ़ता है जितना वस्तु वाले तराज़ू पर घटता है।","domain":"fluids"},
    {"id":"aperi21:floating-and-draft","title":"तैरती वस्तु कितनी गहराई तक डूबती है","description":"डूबे आयतन को क्या तय करता है","domain":"fluids"},
    {"id":"aperi21:stability-of-floating-body","title":"प्लवमान पिंड का स्थायित्व","description":"जब नाव झुकती है, उसका उत्प्लावन केंद्र खिसककर उसे सीधा कर देता है","domain":"fluids"},
    {"id":"aperi21:continuity-equation","title":"सांतत्य समीकरण","description":"अनुप्रस्थ काट और प्रवाह की चाल एक-दूसरे की भरपाई करते हैं","domain":"fluids"},
    {"id":"aperi21:bernoullis-principle","title":"बर्नूली का सिद्धांत","description":"जहाँ पानी तेज़ होता है, वहाँ उसका दाब घटता है","domain":"fluids"},
    {"id":"aperi21:venturi-effect","title":"वेंचुरी प्रभाव","description":"जहाँ नली संकरी होती है, वहाँ कम दाब","domain":"fluids"},
    {"id":"aperi21:torricellis-law","title":"टॉरिसेली का नियम","description":"छेद जितना गहरा, धार उतनी तेज़","domain":"fluids"},
    {"id":"aperi21:lift-force","title":"उत्थापक बल","description":"पंख के ऊपर और नीचे हवा कैसे बहती है","domain":"fluids"},
    {"id":"aperi21:viscosity","title":"श्यानता","description":"परतों के बीच घर्षण","domain":"fluids"},
    {"id":"aperi21:poiseuille-flow","title":"नली में स्तरीय प्रवाह","description":"प्रवाह दर त्रिज्या की चौथी घात के अनुपात में बढ़ती है","domain":"fluids"},
    {"id":"aperi21:stokes-drag","title":"स्टोक्स कर्षण","description":"धीमे, श्यान प्रवाह में कर्षण","domain":"fluids"},
    {"id":"aperi21:laminar-vs-turbulent","title":"स्तरीय और विक्षुब्ध प्रवाह","description":"जहाँ प्रवाह अचानक बिखर जाता है","domain":"fluids"},
    {"id":"aperi21:reynolds-number","title":"रेनॉल्ड्स संख्या","description":"वह विमाहीन संख्या जो संक्रमण तय करती है","domain":"fluids"},
    {"id":"aperi21:boundary-layer","title":"परिसीमा परत","description":"दीवार के पास की वह परत जहाँ प्रवाह धीमा होकर शून्य हो जाता है","domain":"fluids"},
    {"id":"aperi21:surface-tension","title":"पृष्ठ तनाव","description":"सतह को सिकोड़ने वाला खिंचाव","domain":"fluids"},
    {"id":"aperi21:laplace-pressure","title":"लाप्लास दाब","description":"वक्र पृष्ठ से बनने वाला दाब का अंतर","domain":"fluids"},
    {"id":"aperi21:capillary-action","title":"केशिका क्रिया","description":"पतली नलियों में चढ़ाव और उतार","domain":"fluids"},
    {"id":"aperi21:wetting-and-contact-angle","title":"गीलापन और संपर्क कोण","description":"कोई द्रव ठोस पर कितना फैलता है","domain":"fluids"},
    {"id":"aperi21:drag-in-fluid","title":"तरल में कर्षण","description":"आकार और चाल से तय होने वाला कर्षण","domain":"fluids"},
    {"id":"aperi21:thermal-equilibrium","title":"ऊष्मीय संतुलन","description":"संपर्क में रखे दो निकायों द्वारा प्राप्त अवस्था","domain":"thermodynamics"},
    {"id":"aperi21:specific-heat","title":"विशिष्ट ऊष्मा","description":"हर पदार्थ में ताप कितना बदलता है","domain":"thermodynamics"},
    {"id":"aperi21:calorimetry","title":"ऊष्मामिति","description":"मिश्रण का अंतिम ताप","domain":"thermodynamics"},
    {"id":"aperi21:latent-heat","title":"गुप्त ऊष्मा","description":"अवस्था परिवर्तन के दौरान ताप क्यों रुक जाता है","domain":"thermodynamics"},
    {"id":"aperi21:phase-diagram","title":"प्रावस्था आरेख","description":"त्रिक बिंदु से नीचे, द्रव का क्षेत्र छूट जाता है","domain":"thermodynamics"},
    {"id":"aperi21:triple-point","title":"त्रिक बिंदु","description":"वह स्थिति जहाँ तीन प्रावस्थाएँ साथ रहती हैं","domain":"thermodynamics"},
    {"id":"aperi21:thermal-conduction","title":"ऊष्मा चालन","description":"इस्पात में फैलती है, लकड़ी में टिकी रहती है","domain":"thermodynamics"},
    {"id":"aperi21:thermal-convection","title":"संवहन","description":"गतिशील तरल द्वारा ले जाई गई ऊष्मा","domain":"thermodynamics"},
    {"id":"aperi21:thermal-radiation","title":"ऊष्मीय विकिरण","description":"बिना माध्यम के चलने वाली ऊष्मा","domain":"thermodynamics"},
    {"id":"aperi21:stefan-boltzmann-law","title":"स्टीफ़न–बोल्ट्ज़मान नियम","description":"ताप की चौथी घात के अनुपात में बढ़ने वाला विकिरण","domain":"thermodynamics"},
    {"id":"aperi21:thermal-expansion","title":"ऊष्मीय प्रसार","description":"ताप के साथ लंबाई और आयतन कैसे बदलते हैं","domain":"thermodynamics"},
    {"id":"aperi21:bimetal","title":"द्विधात्विक पट्टी","description":"असमान प्रसार से होने वाला मुड़ाव","domain":"thermodynamics"},
    {"id":"aperi21:ideal-gas-law","title":"आदर्श गैस नियम","description":"दाब, आयतन और ताप का संबंध","domain":"thermodynamics"},
    {"id":"aperi21:boyles-law","title":"बॉयल का नियम","description":"स्थिर ताप पर दाब और आयतन","domain":"thermodynamics"},
    {"id":"aperi21:charles-law","title":"चार्ल्स का नियम","description":"स्थिर दाब पर आयतन और ताप","domain":"thermodynamics"},
    {"id":"aperi21:gas-pressure","title":"अणु और दाब","description":"दाब टक्करों का योग है","domain":"thermodynamics"},
    {"id":"aperi21:pressure-from-collisions","title":"टक्करों से बनने वाला दाब","description":"अणुओं द्वारा दीवार तक लाया गया संवेग","domain":"thermodynamics"},
    {"id":"aperi21:maxwell-boltzmann-distribution","title":"मैक्सवेल–बोल्ट्ज़मान वितरण","description":"गर्म करने पर चाल वितरण फैलता है और उसका शिखर नीचे आता है","domain":"thermodynamics"},
    {"id":"aperi21:mean-free-path","title":"माध्य मुक्त पथ","description":"टक्करों के बीच की दूरी","domain":"thermodynamics"},
    {"id":"aperi21:first-law-of-thermodynamics","title":"ऊष्मागतिकी का प्रथम नियम","description":"आंतरिक ऊर्जा, कार्य और ऊष्मा का संबंध","domain":"thermodynamics"},
    {"id":"aperi21:pv-diagram","title":"PV आरेख","description":"जहाँ क्षेत्रफल ही कार्य है","domain":"thermodynamics"},
    {"id":"aperi21:isothermal-process","title":"समतापी प्रक्रम","description":"ऐसा परिवर्तन जो ताप को स्थिर रखता है","domain":"thermodynamics"},
    {"id":"aperi21:adiabatic-process","title":"रुद्धोष्म प्रक्रम","description":"ऐसा परिवर्तन जिसमें ऊष्मा न अंदर आती है न बाहर जाती है","domain":"thermodynamics"},
    {"id":"aperi21:isobaric-isochoric","title":"समदाबी और समआयतनी प्रक्रम","description":"स्थिर दाब या स्थिर आयतन पर परिवर्तन","domain":"thermodynamics"},
    {"id":"aperi21:cyclic-process","title":"चक्रीय प्रक्रम","description":"ऐसा परिवर्तन जो वहीं लौट आता है जहाँ से शुरू हुआ था","domain":"thermodynamics"},
    {"id":"aperi21:second-law-of-thermodynamics","title":"ऊष्मागतिकी का द्वितीय नियम","description":"एक ही दिशा में चलने वाला परिवर्तन","domain":"thermodynamics"},
    {"id":"aperi21:irreversibility","title":"एन्ट्रॉपी और अनुत्क्रमणीयता","description":"इसे वापस क्यों नहीं किया जा सकता","domain":"thermodynamics"},
    {"id":"aperi21:heat-engine","title":"ऊष्मा इंजन","description":"ऊष्मा को कार्य में बदलने वाला चक्र","domain":"thermodynamics"},
    {"id":"aperi21:carnot-cycle","title":"कार्नो चक्र","description":"सैद्धांतिक अधिकतम दक्षता","domain":"thermodynamics"},
    {"id":"aperi21:refrigerator-heat-pump","title":"रेफ्रिजरेटर और ऊष्मा पंप","description":"कार्य लगाकर ऊष्मा को स्थानांतरित करना","domain":"thermodynamics"},
    {"id":"aperi21:brownian-motion","title":"ब्राउनी गति","description":"आण्विक टक्करों से होने वाली यादृच्छिक गति","domain":"thermodynamics"},
    {"id":"aperi21:diffusion","title":"विसरण","description":"सांद्रता के अंतर से चलने वाला प्रवाह","domain":"thermodynamics"},
    {"id":"aperi21:random-walk","title":"यादृच्छिक भ्रमण","description":"वर्गमूल की तरह बढ़ने वाली दूरी","domain":"thermodynamics"},
    {"id":"aperi21:statistical-fluctuation","title":"सांख्यिकीय उतार-चढ़ाव","description":"कण कम हों तो बढ़ने वाला उतार-चढ़ाव","domain":"thermodynamics"},
    {"id":"aperi21:maxwells-demon","title":"मैक्सवेल का दानव","description":"सूचना और एन्ट्रॉपी","domain":"thermodynamics"},
    {"id":"aperi21:insulation","title":"ऊष्मारोधन","description":"ऊष्मा के प्रवाह को धीमा करना","domain":"thermodynamics"},
    {"id":"aperi21:albedo","title":"ऐल्बिडो","description":"वापस भेजे गए प्रकाश का हिस्सा","domain":"thermodynamics"},
    {"id":"aperi21:radiative-equilibrium","title":"विकिरण संतुलन","description":"वह ताप जो तब तय होता है जब बाहर जाने वाला अंदर आने वाले के बराबर हो","domain":"thermodynamics"},
    {"id":"aperi21:greenhouse-effect","title":"ग्रीनहाउस प्रभाव","description":"अवरक्त को नीचे लौटाने वाली परत ज़मीन को गर्म करती है","domain":"thermodynamics"},
    {"id":"aperi21:wave-basics","title":"तरंग की मूल राशियाँ","description":"तरंगदैर्घ्य, आवृत्ति, चाल और आयाम","domain":"waves-acoustics"},
    {"id":"aperi21:wave-vs-particle-transport","title":"तरंग क्या ले जाती है","description":"माध्यम अपनी जगह रहता है, ऊर्जा आगे बढ़ती है","domain":"waves-acoustics"},
    {"id":"aperi21:transverse-wave","title":"अनुप्रस्थ तरंग","description":"माध्यम तरंग के चलने की दिशा के लंबवत कंपन करता है","domain":"waves-acoustics"},
    {"id":"aperi21:longitudinal-wave","title":"अनुदैर्ध्य तरंग","description":"कण अपनी जगह डोलते हैं, जबकि घने स्थान आगे बढ़ते जाते हैं","domain":"waves-acoustics"},
    {"id":"aperi21:wave-speed-in-medium","title":"तरंग की चाल और माध्यम","description":"तनाव और घनत्व से तय होने वाली चाल","domain":"waves-acoustics"},
    {"id":"aperi21:wavefront-and-ray","title":"तरंगाग्र और किरणें","description":"समान कला वाले पृष्ठ और उन पर अभिलंब रेखाएँ","domain":"waves-acoustics"},
    {"id":"aperi21:huygens-principle","title":"हाइगेंस का सिद्धांत","description":"तरंगाग्र के बिंदुओं से निकली वृत्ताकार द्वितीयक तरंगिकाएँ मिलकर एक सीधा तरंगाग्र बनाती हैं","domain":"waves-acoustics"},
    {"id":"aperi21:superposition","title":"अध्यारोपण","description":"तरंगें एक-दूसरे पर पड़ें तो क्या होता है","domain":"waves-acoustics"},
    {"id":"aperi21:constructive-destructive","title":"संपोषी और विनाशी व्यतिकरण","description":"कलांतर योग का आकार कैसे तय करता है","domain":"waves-acoustics"},
    {"id":"aperi21:interference","title":"व्यतिकरण","description":"लहरों के दो समूह एक-दूसरे को रद्द कर शांत रेखाएँ छोड़ते हैं","domain":"waves-acoustics"},
    {"id":"aperi21:standing-wave","title":"अप्रगामी तरंग","description":"विपरीत दिशाओं में चलती दो तरंगें निस्पंदों को अपनी जगह स्थिर कर देती हैं","domain":"waves-acoustics"},
    {"id":"aperi21:harmonics","title":"संनादी","description":"सीमा द्वारा निर्धारित आवृत्तियाँ","domain":"waves-acoustics"},
    {"id":"aperi21:string-vibration","title":"कंपन करती डोरी","description":"दोनों सिरों पर बँधी डोरी की विधाएँ","domain":"waves-acoustics"},
    {"id":"aperi21:air-column-resonance","title":"वायु स्तंभ में अनुनाद","description":"खुला पाइप बनाम बंद पाइप","domain":"waves-acoustics"},
    {"id":"aperi21:beats","title":"विस्पंद","description":"दोनों के खिसकने के साथ योग मिटता जाता है","domain":"waves-acoustics"},
    {"id":"aperi21:doppler-effect","title":"डॉप्लर प्रभाव","description":"स्रोत अपने उत्सर्जन बिंदुओं को साथ खींचता है, जिससे आगे का भाग घना हो जाता है","domain":"waves-acoustics"},
    {"id":"aperi21:doppler-source-vs-observer","title":"गतिशील स्रोत बनाम गतिशील प्रेक्षक","description":"कौन गति कर रहा है, इससे उपजी असममिति","domain":"waves-acoustics"},
    {"id":"aperi21:shock-wave","title":"आघात तरंग","description":"ध्वनि की चाल पार करने पर बनने वाला शंकु","domain":"waves-acoustics"},
    {"id":"aperi21:sound-intensity","title":"ध्वनि की तीव्रता","description":"दूरी के वर्ग के साथ घटना","domain":"waves-acoustics"},
    {"id":"aperi21:reflection-of-waves","title":"तरंगों का परावर्तन","description":"स्थिर सिरे और मुक्त सिरे पर कला","domain":"waves-acoustics"},
    {"id":"aperi21:refraction-of-waves","title":"तरंगों का अपवर्तन","description":"चाल में बदलाव दिशा मोड़ देता है","domain":"waves-acoustics"},
    {"id":"aperi21:diffraction","title":"विवर्तन","description":"अवरोधों के चारों ओर मुड़ती तरंगें","domain":"waves-acoustics"},
    {"id":"aperi21:slit-width-and-diffraction","title":"झिरी की चौड़ाई और विवर्तन","description":"छिद्र और तरंगदैर्घ्य का अनुपात फैलाव कैसे तय करता है","domain":"waves-acoustics"},
    {"id":"aperi21:wave-energy","title":"तरंग की ऊर्जा","description":"ऊर्जा आयाम के वर्ग के साथ बढ़ती है","domain":"waves-acoustics"},
    {"id":"aperi21:wave-attenuation","title":"तरंग का क्षीणन","description":"माध्यम द्वारा अवशोषित ऊर्जा","domain":"waves-acoustics"},
    {"id":"aperi21:impedance-mismatch","title":"प्रतिबाधा बेमेल","description":"सीमा पर कितना परावर्तित होता है","domain":"waves-acoustics"},
    {"id":"aperi21:noise-cancellation","title":"सक्रिय शोर निरसन","description":"उल्टी तरंग का अध्यारोपण","domain":"waves-acoustics"},
    {"id":"aperi21:sound-source-vibration","title":"ध्वनि और कंपन","description":"ध्वनि करती वस्तु कंपन करती है, और कंपन रुकने पर ध्वनि भी रुक जाती है","domain":"waves-acoustics"},
    {"id":"aperi21:sound-through-materials","title":"पदार्थों से होकर ध्वनि","description":"ध्वनि अलग-अलग पदार्थों में अलग ढंग से कैसे चलती है","domain":"waves-acoustics"},
    {"id":"aperi21:digital-vs-analog-signal","title":"डिजिटल और एनालॉग संकेत","description":"शोर का सामना करने के दो तरीके","domain":"waves-acoustics"},
    {"id":"aperi21:seismic-waves","title":"भूकंपीय तरंगें","description":"पृथ्वी के भीतर से गुज़रती P और S तरंगें","domain":"waves-acoustics"},
    {"id":"aperi21:rectilinear-propagation","title":"प्रकाश सीधी रेखा में चलता है","description":"छाया और किरण मॉडल","domain":"optics"},
    {"id":"aperi21:shadow-umbra-penumbra","title":"प्रच्छाया और उपच्छाया","description":"प्रकाश स्रोत का आकार छाया के किनारे को कैसे गढ़ता है","domain":"optics"},
    {"id":"aperi21:pinhole-camera","title":"सूचिछिद्र कैमरा","description":"एक ही छिद्र से बना प्रतिबिंब","domain":"optics"},
    {"id":"aperi21:law-of-reflection","title":"परावर्तन का नियम","description":"आपतन कोण और परावर्तन कोण","domain":"optics"},
    {"id":"aperi21:specular-diffuse-reflection","title":"नियमित और विसरित परावर्तन","description":"सतह के खुरदरेपन से तय होने वाला परावर्तन","domain":"optics"},
    {"id":"aperi21:plane-mirror-image","title":"समतल दर्पण में प्रतिबिंब","description":"आभासी प्रतिबिंब कहाँ बनता है, और वह उलटा क्यों दिखता है","domain":"optics"},
    {"id":"aperi21:multiple-mirror-images","title":"दो दर्पणों में प्रतिबिंब","description":"दो दर्पणों के बीच का कोण प्रतिबिंबों की संख्या कैसे तय करता है","domain":"optics"},
    {"id":"aperi21:concave-mirror","title":"अवतल दर्पण","description":"फोकस और वास्तविक प्रतिबिंब","domain":"optics"},
    {"id":"aperi21:convex-mirror","title":"उत्तल दर्पण","description":"अधिक चौड़ा दृष्टि-क्षेत्र और आभासी प्रतिबिंब","domain":"optics"},
    {"id":"aperi21:snells-law","title":"स्नेल का नियम","description":"माध्यम के साथ पथ कैसे मुड़ता है","domain":"optics"},
    {"id":"aperi21:apparent-depth","title":"आभासी गहराई","description":"पानी के नीचे की वस्तुएँ ऊपर उठी हुई क्यों दिखती हैं","domain":"optics"},
    {"id":"aperi21:total-internal-reflection","title":"पूर्ण आंतरिक परावर्तन","description":"क्रांतिक कोण और उसकी शर्त","domain":"optics"},
    {"id":"aperi21:optical-fiber","title":"प्रकाशीय तंतु","description":"पूर्ण आंतरिक परावर्तन से बँधा प्रकाश","domain":"optics"},
    {"id":"aperi21:mirage","title":"मृगमरीचिका","description":"घनत्व प्रवणता से मुड़ता प्रकाश","domain":"optics"},
    {"id":"aperi21:dispersion","title":"वर्ण-विक्षेपण","description":"तरंगदैर्घ्य पर निर्भर अपवर्तनांक","domain":"optics"},
    {"id":"aperi21:prism","title":"प्रिज़्म","description":"वर्ण-विक्षेपण से फैला स्पेक्ट्रम","domain":"optics"},
    {"id":"aperi21:rainbow","title":"इंद्रधनुष","description":"वर्षा की बूँदों के भीतर अपवर्तन और परावर्तन","domain":"optics"},
    {"id":"aperi21:thin-lens","title":"पतला लेंस","description":"तीन किरणों से प्रतिबिंब ढूँढना","domain":"optics"},
    {"id":"aperi21:converging-diverging-lens","title":"अभिसारी और अपसारी लेंस","description":"प्रकाश को इकट्ठा करने वाला लेंस और उसे फैलाने वाला लेंस","domain":"optics"},
    {"id":"aperi21:magnification","title":"आवर्धन","description":"प्रतिबिंब का आकार और वस्तु का आकार","domain":"optics"},
    {"id":"aperi21:focal-length","title":"फोकस दूरी","description":"जो तय करता है कि प्रतिबिंब कहाँ बनता है","domain":"optics"},
    {"id":"aperi21:real-vs-virtual-image","title":"वास्तविक और आभासी प्रतिबिंब","description":"क्या प्रकाश सचमुच मिलता है?","domain":"optics"},
    {"id":"aperi21:lens-combination","title":"लेंसों का संयोजन","description":"दो लेंसों का संयुक्त फोकस","domain":"optics"},
    {"id":"aperi21:spherical-aberration","title":"गोलीय विपथन","description":"किनारे की किरणें किसी दूसरी जगह फोकस होती हैं","domain":"optics"},
    {"id":"aperi21:chromatic-aberration","title":"वर्ण विपथन","description":"हर तरंगदैर्घ्य के लिए अलग फोकस","domain":"optics"},
    {"id":"aperi21:human-eye-accommodation","title":"नेत्र की समंजन क्षमता","description":"नेत्र लेंस वस्तुओं को कैसे फोकस करता है","domain":"optics"},
    {"id":"aperi21:myopia-hyperopia","title":"निकट दृष्टि दोष और दूर दृष्टि दोष","description":"प्रतिबिंब कहाँ बनता है, और चश्मा उसे कैसे ठीक करता है","domain":"optics"},
    {"id":"aperi21:magnifying-glass","title":"आवर्धक लेंस","description":"निकट फोकस बिंदु के भीतर रखी वस्तु","domain":"optics"},
    {"id":"aperi21:microscope","title":"सूक्ष्मदर्शी","description":"अभिदृश्यक और नेत्रिका के आवर्धन गुणा होते हैं","domain":"optics"},
    {"id":"aperi21:telescope","title":"दूरदर्शी","description":"फोकस दूरियों के अनुपात से तय होने वाला आवर्धन","domain":"optics"},
    {"id":"aperi21:youngs-double-slit","title":"यंग की द्वि-झिरी","description":"इस बात का प्रमाण कि प्रकाश एक तरंग है","domain":"optics"},
    {"id":"aperi21:single-slit-diffraction","title":"एकल झिरी विवर्तन","description":"चौड़ाई से बनने वाला प्रतिरूप","domain":"optics"},
    {"id":"aperi21:diffraction-grating","title":"विवर्तन ग्रेटिंग","description":"अनेक झिरियों से बनने वाले तीक्ष्ण उच्चिष्ठ","domain":"optics"},
    {"id":"aperi21:thin-film-interference","title":"पतली फ़िल्म में व्यतिकरण","description":"मोटाई से बनने वाला रंग","domain":"optics"},
    {"id":"aperi21:newtons-rings","title":"न्यूटन वलय","description":"वक्र और समतल पृष्ठ के बीच व्यतिकरण","domain":"optics"},
    {"id":"aperi21:resolving-power","title":"विभेदन क्षमता","description":"दो बिंदुओं को अलग पहचानने की सीमा","domain":"optics"},
    {"id":"aperi21:polarization","title":"ध्रुवण","description":"कंपन-तल का चयन","domain":"optics"},
    {"id":"aperi21:malus-law","title":"मैलस का नियम","description":"ध्रुवक से होकर गई तीव्रता","domain":"optics"},
    {"id":"aperi21:brewster-angle","title":"ब्रूस्टर कोण","description":"वह कोण जिस पर परावर्तित प्रकाश पूर्णतः ध्रुवित होता है","domain":"optics"},
    {"id":"aperi21:birefringence","title":"द्विअपवर्तन","description":"दिशा पर निर्भर अपवर्तनांक","domain":"optics"},
    {"id":"aperi21:scattering","title":"प्रकीर्णन","description":"आकाश और सूर्यास्त के रंग","domain":"optics"},
    {"id":"aperi21:rayleigh-scattering","title":"रेले प्रकीर्णन","description":"तरंगदैर्घ्य की चौथी घात के साथ घटने वाला प्रकीर्णन","domain":"optics"},
    {"id":"aperi21:seeing-requires-light","title":"देखने के लिए प्रकाश चाहिए","description":"प्रकाश के बिना कोई वस्तु नहीं दिखती","domain":"optics"},
    {"id":"aperi21:color-addition","title":"प्रकाश का योग","description":"तीन प्रकाश जहाँ एक-दूसरे पर पड़ते हैं वहाँ बनने वाला रंग","domain":"optics"},
    {"id":"aperi21:object-color","title":"किसी वस्तु का रंग","description":"वस्तु द्वारा लौटाए गए प्रकाश से तय होने वाला रंग","domain":"optics"},
    {"id":"aperi21:light-through-materials","title":"प्रकाश और पदार्थ","description":"प्रकाश का पार जाना पदार्थ पर निर्भर करता है","domain":"optics"},
    {"id":"aperi21:electric-charge","title":"विद्युत आवेश","description":"दो प्रकार के आवेश और उनका संरक्षण","domain":"electromagnetism"},
    {"id":"aperi21:charging-methods","title":"आवेशित करने की विधियाँ","description":"घर्षण, संपर्क और प्रेरण","domain":"electromagnetism"},
    {"id":"aperi21:coulombs-law","title":"कूलॉम का नियम","description":"आवेशों के बीच बल","domain":"electromagnetism"},
    {"id":"aperi21:superposition-of-forces","title":"विद्युत बलों का अध्यारोपण","description":"कई आवेशों से लगने वाले बलों को जोड़ना","domain":"electromagnetism"},
    {"id":"aperi21:electric-field","title":"विद्युत क्षेत्र","description":"एकांक आवेश पर लगने वाला बल","domain":"electromagnetism"},
    {"id":"aperi21:field-lines","title":"विद्युत क्षेत्र रेखाएँ","description":"जहाँ रेखाएँ घनी होती हैं, वहाँ क्षेत्र प्रबल होता है","domain":"electromagnetism"},
    {"id":"aperi21:field-of-dipole","title":"द्विध्रुव का विद्युत क्षेत्र","description":"दो पास-पास के विपरीत आवेश","domain":"electromagnetism"},
    {"id":"aperi21:uniform-field","title":"एकसमान विद्युत क्षेत्र","description":"समांतर प्लेटों के बीच का क्षेत्र","domain":"electromagnetism"},
    {"id":"aperi21:charge-in-uniform-field","title":"एकसमान क्षेत्र में एक आवेश","description":"बिल्कुल एक प्रक्षेप्य की तरह","domain":"electromagnetism"},
    {"id":"aperi21:gausss-law","title":"गाउस का नियम","description":"बंद पृष्ठ से होकर विद्युत फ्लक्स","domain":"electromagnetism"},
    {"id":"aperi21:field-of-charged-sphere","title":"आवेशित गोले का क्षेत्र","description":"अंदर और बाहर अलग क्यों हैं","domain":"electromagnetism"},
    {"id":"aperi21:equipotential-surface","title":"समविभव पृष्ठ","description":"क्षेत्र के लंबवत पृष्ठ","domain":"electromagnetism"},
    {"id":"aperi21:potential-vs-field","title":"विभव और विद्युत क्षेत्र","description":"ढाल का संबंध","domain":"electromagnetism"},
    {"id":"aperi21:electrostatic-shielding","title":"स्थिरवैद्युत परिरक्षण","description":"चालक के भीतर क्षेत्र शून्य क्यों होता है","domain":"electromagnetism"},
    {"id":"aperi21:charge-on-conductor-surface","title":"चालक की सतह पर आवेश","description":"नुकीले सिरे पर जमा होता आवेश","domain":"electromagnetism"},
    {"id":"aperi21:dielectric","title":"परावैद्युत","description":"ध्रुवण क्षेत्र को कमज़ोर करता है","domain":"electromagnetism"},
    {"id":"aperi21:parallel-plate-capacitor","title":"समांतर प्लेट संधारित्र","description":"क्षेत्रफल और अंतराल से तय होने वाली धारिता","domain":"electromagnetism"},
    {"id":"aperi21:capacitors-in-circuit","title":"संधारित्रों का संयोजन","description":"श्रेणीक्रम और पार्श्वक्रम में संयोजन","domain":"electromagnetism"},
    {"id":"aperi21:energy-in-capacitor","title":"संधारित्र में ऊर्जा","description":"विद्युत क्षेत्र में संचित ऊर्जा","domain":"electromagnetism"},
    {"id":"aperi21:electric-current","title":"विद्युत धारा","description":"आवेश का प्रवाह और उसकी दिशा की परिपाटी","domain":"electromagnetism"},
    {"id":"aperi21:drift-velocity","title":"अपवाह वेग","description":"धीमे इलेक्ट्रॉन, तेज़ संकेत","domain":"electromagnetism"},
    {"id":"aperi21:ohms-law","title":"ओम का नियम","description":"वोल्टता, धारा और प्रतिरोध","domain":"electromagnetism"},
    {"id":"aperi21:resistance-and-geometry","title":"प्रतिरोध और आकृति","description":"लंबाई और अनुप्रस्थ काट का प्रभाव","domain":"electromagnetism"},
    {"id":"aperi21:temperature-and-resistance","title":"ताप और प्रतिरोध","description":"धातुएँ और अर्धचालक विपरीत दिशाओं में जाते हैं","domain":"electromagnetism"},
    {"id":"aperi21:series-parallel-resistors","title":"प्रतिरोधों का श्रेणीक्रम और पार्श्वक्रम संयोजन","description":"संयोजन बदलने से एक ही बैटरी की दी हुई धारा कैसे बदलती है","domain":"electromagnetism"},
    {"id":"aperi21:emf-and-internal-resistance","title":"विद्युत वाहक बल और आंतरिक प्रतिरोध","description":"टर्मिनल वोल्टता क्यों घटती है","domain":"electromagnetism"},
    {"id":"aperi21:kirchhoffs-current-law","title":"किरखॉफ का धारा नियम","description":"संधि पर आवेश का संरक्षण","domain":"electromagnetism"},
    {"id":"aperi21:kirchhoffs-voltage-law","title":"किरखॉफ का वोल्टता नियम","description":"बंद पाश में ऊर्जा का संरक्षण","domain":"electromagnetism"},
    {"id":"aperi21:wheatstone-bridge","title":"व्हीटस्टोन सेतु","description":"संतुलन से प्रतिरोध मापना","domain":"electromagnetism"},
    {"id":"aperi21:joule-heating","title":"जूल तापन","description":"प्रतिरोध से उत्पन्न ऊष्मा","domain":"electromagnetism"},
    {"id":"aperi21:rc-circuit","title":"RC परिपथ","description":"बचा हुआ अंतर हर τ में समान अनुपात से घटता है","domain":"electromagnetism"},
    {"id":"aperi21:magnetic-field","title":"चुंबकीय क्षेत्र","description":"चुंबक के चारों ओर चुंबकीय बल कैसे फैला होता है","domain":"electromagnetism"},
    {"id":"aperi21:magnetic-field-lines","title":"चुंबकीय क्षेत्र रेखाएँ","description":"रेखाएँ जो कभी टूटती नहीं और सदा बंद होती हैं","domain":"electromagnetism"},
    {"id":"aperi21:lorentz-force","title":"लोरेंत्ज़ बल","description":"चुंबकीय क्षेत्र में गतिमान आवेश पर बल","domain":"electromagnetism"},
    {"id":"aperi21:charged-particle-in-magnetic-field","title":"चुंबकीय क्षेत्र में वृत्ताकार घूमते आवेश","description":"तेज़ आवेश भी एक चक्कर में उतना ही समय लेता है","domain":"electromagnetism"},
    {"id":"aperi21:velocity-selector","title":"वेग चयनक","description":"विद्युत बल और चुंबकीय बल का संतुलन","domain":"electromagnetism"},
    {"id":"aperi21:mass-spectrometer","title":"द्रव्यमान स्पेक्ट्रोमीटर","description":"त्रिज्या से द्रव्यमानों को अलग करना","domain":"electromagnetism"},
    {"id":"aperi21:force-on-current-wire","title":"धारावाही तार पर बल","description":"धारा ले जाते तार पर चुंबकीय बल","domain":"electromagnetism"},
    {"id":"aperi21:biot-savart-law","title":"बायो–सावर्ट नियम","description":"धारा अवयवों का चुंबकीय क्षेत्र","domain":"electromagnetism"},
    {"id":"aperi21:field-of-straight-wire","title":"धारा से बनने वाला चुंबकीय क्षेत्र","description":"सुइयाँ लूप की दिशा में घूमती हैं, और दूर जाने पर कम","domain":"electromagnetism"},
    {"id":"aperi21:field-of-loop-and-solenoid","title":"लूप और परिनालिका","description":"अक्ष के अनुदिश चुंबकीय क्षेत्र","domain":"electromagnetism"},
    {"id":"aperi21:amperes-law","title":"ऐम्पियर का नियम","description":"धारा के चारों ओर चुंबकीय क्षेत्र का परिसंचरण","domain":"electromagnetism"},
    {"id":"aperi21:force-between-wires","title":"समांतर तारों के बीच बल","description":"दो समांतर धाराएँ आकर्षित या प्रतिकर्षित करती हैं","domain":"electromagnetism"},
    {"id":"aperi21:magnetic-dipole","title":"चुंबकीय द्विध्रुव","description":"धारा लूप और चुंबक एक ही हैं","domain":"electromagnetism"},
    {"id":"aperi21:magnetic-materials","title":"चुंबकीय पदार्थ","description":"लौहचुंबकीय, अनुचुंबकीय और प्रतिचुंबकीय","domain":"electromagnetism"},
    {"id":"aperi21:faradays-law","title":"फैराडे का नियम","description":"बदलते फ्लक्स से उत्पन्न विद्युत वाहक बल","domain":"electromagnetism"},
    {"id":"aperi21:lenzs-law","title":"लेन्ज़ का नियम","description":"धारा पलटती है, बल कभी नहीं","domain":"electromagnetism"},
    {"id":"aperi21:motional-emf","title":"गतिक विद्युत वाहक बल","description":"गतिमान तार से उत्पन्न वोल्टता","domain":"electromagnetism"},
    {"id":"aperi21:eddy-current","title":"भँवर धाराएँ","description":"ठोस चालक के भीतर प्रेरित धाराएँ","domain":"electromagnetism"},
    {"id":"aperi21:self-inductance","title":"स्व-प्रेरकत्व","description":"अपने ही फ्लक्स में परिवर्तन का विरोध करती कुंडली","domain":"electromagnetism"},
    {"id":"aperi21:mutual-inductance","title":"अन्योन्य प्रेरकत्व","description":"पास के परिपथ में प्रेरित विद्युत वाहक बल","domain":"electromagnetism"},
    {"id":"aperi21:energy-in-inductor","title":"प्रेरक में ऊर्जा","description":"चुंबकीय क्षेत्र में संचित ऊर्जा","domain":"electromagnetism"},
    {"id":"aperi21:rl-circuit","title":"RL परिपथ","description":"धारा धीरे-धीरे क्यों बढ़ती है","domain":"electromagnetism"},
    {"id":"aperi21:lc-oscillation","title":"LC दोलन","description":"विद्युत और चुंबकीय ऊर्जा आपस में जगह बदलती हैं","domain":"electromagnetism"},
    {"id":"aperi21:ac-generation","title":"प्रत्यावर्ती धारा का उत्पादन","description":"घूमती कुंडली और ज्या तरंग","domain":"electromagnetism"},
    {"id":"aperi21:reactance","title":"प्रतिघात और प्रतिबाधा","description":"आवृत्ति पर निर्भर धारा का विरोध","domain":"electromagnetism"},
    {"id":"aperi21:phase-in-ac-circuit","title":"प्रत्यावर्ती धारा परिपथों में कलांतर","description":"वोल्टता और धारा का एक-दूसरे से आगे-पीछे होना","domain":"electromagnetism"},
    {"id":"aperi21:series-rlc-resonance","title":"RLC अनुनाद","description":"वह आवृत्ति जिस पर प्रतिबाधा न्यूनतम होती है","domain":"electromagnetism"},
    {"id":"aperi21:transformer","title":"ट्रांसफ़ॉर्मर","description":"फेरे और वोल्टता अनुपात","domain":"electromagnetism"},
    {"id":"aperi21:motor","title":"विद्युत मोटर","description":"धारा पर लगने वाले बल से घूमना","domain":"electromagnetism"},
    {"id":"aperi21:generator","title":"विद्युत जनित्र","description":"घुमाने से उत्पन्न विद्युत वाहक बल","domain":"electromagnetism"},
    {"id":"aperi21:displacement-current","title":"विस्थापन धारा","description":"वह पद जो संधारित्र के अंतराल को पाटता है","domain":"electromagnetism"},
    {"id":"aperi21:maxwells-equations","title":"मैक्सवेल के समीकरण","description":"विद्युत चुंबकत्व को बाँधने वाले चार समीकरण","domain":"electromagnetism"},
    {"id":"aperi21:electromagnetic-wave","title":"विद्युत चुंबकीय तरंगें","description":"स्वयं संचरित होने वाले विद्युत और चुंबकीय क्षेत्र","domain":"electromagnetism"},
    {"id":"aperi21:poynting-vector","title":"पॉइंटिंग सदिश","description":"विद्युत चुंबकीय तरंगों द्वारा ले जाया गया ऊर्जा प्रवाह","domain":"electromagnetism"},
    {"id":"aperi21:radiation-pressure","title":"विकिरण दाब","description":"प्रकाश का धक्का","domain":"electromagnetism"},
    {"id":"aperi21:antenna-radiation","title":"ऐंटेना से विकिरण","description":"त्वरित आवेश द्वारा भेजी गई तरंगें","domain":"electromagnetism"},
    {"id":"aperi21:magnet-attraction","title":"चुंबक से क्या चिपकता है","description":"वे चीज़ें जिन्हें चुंबक खींचता है और जिन्हें नहीं","domain":"electromagnetism"},
    {"id":"aperi21:magnetic-poles","title":"चुंबक के दो ध्रुव","description":"समान ध्रुव प्रतिकर्षित करते हैं, असमान ध्रुव आकर्षित करते हैं","domain":"electromagnetism"},
    {"id":"aperi21:simple-circuit","title":"विद्युत परिपथ बनाना","description":"जुड़ा हो तभी धारा बहती है; तोड़ो तो बल्ब बुझ जाता है","domain":"electromagnetism"},
    {"id":"aperi21:electromagnet","title":"विद्युत चुंबक","description":"केवल धारा बहते समय बनने वाला चुंबक","domain":"electromagnetism"},
    {"id":"aperi21:iv-characteristic","title":"I–V अभिलाक्षणिक वक्र","description":"ऐसे अवयव जिनकी धारा वोल्टता के साथ सरल रेखा में नहीं बदलती","domain":"electromagnetism"},
    {"id":"aperi21:thermistor-and-ldr","title":"थर्मिस्टर और LDR","description":"ताप और प्रकाश के साथ बदलता प्रतिरोध","domain":"electromagnetism"},
    {"id":"aperi21:potential-divider","title":"विभव विभाजक","description":"प्रतिरोधों से वोल्टता बाँटना","domain":"electromagnetism"},
    {"id":"aperi21:millikan-experiment","title":"मिलिकन का तेल-बूँद प्रयोग","description":"प्रमाण कि आवेश टुकड़ों में आता है","domain":"electromagnetism"},
    {"id":"aperi21:power-transmission","title":"विद्युत पारेषण","description":"वोल्टता बढ़ाकर हानि घटाना","domain":"electromagnetism"},
    {"id":"aperi21:loudspeaker-and-microphone","title":"लाउडस्पीकर और माइक्रोफ़ोन","description":"धारा को कंपन में बदलना और फिर वापस","domain":"electromagnetism"},
    {"id":"aperi21:michelson-morley","title":"माइकलसन–मॉर्ले प्रयोग","description":"ईथर के न होने का प्रमाण","domain":"modern-physics"},
    {"id":"aperi21:relativity-of-simultaneity","title":"समकालिकता की आपेक्षिकता","description":"हर निर्देश तंत्र का अपना “एक ही समय”","domain":"modern-physics"},
    {"id":"aperi21:time-dilation","title":"काल विस्तारण","description":"गतिमान घड़ी धीमी चलती है","domain":"modern-physics"},
    {"id":"aperi21:light-clock","title":"प्रकाश घड़ी","description":"काल विस्तारण के पीछे का विचार प्रयोग","domain":"modern-physics"},
    {"id":"aperi21:length-contraction","title":"लंबाई संकुचन","description":"गति की दिशा में संकुचन","domain":"modern-physics"},
    {"id":"aperi21:muon-decay-evidence","title":"ज़मीन तक पहुँचते म्यूऑन","description":"काल विस्तारण का प्रेक्षणात्मक प्रमाण","domain":"modern-physics"},
    {"id":"aperi21:relativistic-velocity-addition","title":"वेगों का आपेक्षिक योग","description":"ऐसा संयोजन जो प्रकाश की चाल कभी पार नहीं करता","domain":"modern-physics"},
    {"id":"aperi21:twin-paradox","title":"जुड़वाँ विरोधाभास","description":"सममिति तोड़ने वाला त्वरण","domain":"modern-physics"},
    {"id":"aperi21:spacetime-diagram","title":"दिक्काल आरेख","description":"विश्व रेखा और समकालिकता रेखा","domain":"modern-physics"},
    {"id":"aperi21:light-cone","title":"प्रकाश शंकु","description":"जहाँ तक कोई कारण पहुँच सकता है","domain":"modern-physics"},
    {"id":"aperi21:relativistic-momentum","title":"आपेक्षिक संवेग","description":"चाल बढ़ने पर संवेग असीमित रूप से बढ़ता है","domain":"modern-physics"},
    {"id":"aperi21:relativistic-doppler","title":"आपेक्षिक डॉप्लर प्रभाव","description":"काल विस्तारण जुड़ने से आवृत्ति में परिवर्तन","domain":"modern-physics"},
    {"id":"aperi21:equivalence-principle","title":"तुल्यता सिद्धांत","description":"त्वरण और गुरुत्व में भेद नहीं किया जा सकता","domain":"modern-physics"},
    {"id":"aperi21:gravitational-time-dilation","title":"गुरुत्वीय काल विस्तारण","description":"भिन्न विभवों पर घड़ियाँ भिन्न दरों से चलती हैं","domain":"modern-physics"},
    {"id":"aperi21:gravitational-redshift","title":"गुरुत्वीय अभिरक्त विस्थापन","description":"गुरुत्व कूप से बाहर चढ़ते हुए खोई ऊर्जा","domain":"modern-physics"},
    {"id":"aperi21:light-bending-by-gravity","title":"प्रकाश का मुड़ना","description":"द्रव्यमान के पास प्रकाश का पथ मुड़ जाता है","domain":"modern-physics"},
    {"id":"aperi21:blackbody-radiation","title":"कृष्णिका विकिरण","description":"जहाँ चिरसम्मत सिद्धांत विफल होता है","domain":"modern-physics"},
    {"id":"aperi21:wien-displacement-law","title":"वीन का विस्थापन नियम","description":"ताप और शिखर तरंगदैर्घ्य","domain":"modern-physics"},
    {"id":"aperi21:photoelectric-effect","title":"प्रकाश-विद्युत प्रभाव","description":"इस बात का प्रमाण कि प्रकाश कणों के रूप में आता है","domain":"modern-physics"},
    {"id":"aperi21:work-function-and-threshold","title":"कार्य फलन और देहली आवृत्ति","description":"तीव्रता नहीं, आवृत्ति तय करती है","domain":"modern-physics"},
    {"id":"aperi21:compton-scattering","title":"कॉम्पटन प्रकीर्णन","description":"इस बात का प्रमाण कि फोटॉन में संवेग होता है","domain":"modern-physics"},
    {"id":"aperi21:pair-production","title":"युग्म उत्पादन","description":"ऊर्जा का द्रव्य में बदलना","domain":"modern-physics"},
    {"id":"aperi21:de-broglie-wavelength","title":"दे ब्रॉग्ली तरंगदैर्घ्य","description":"द्रव्य की तरंग प्रकृति","domain":"modern-physics"},
    {"id":"aperi21:electron-diffraction","title":"इलेक्ट्रॉन विवर्तन","description":"द्रव्य तरंगों को देखना","domain":"modern-physics"},
    {"id":"aperi21:double-slit-with-electrons","title":"इलेक्ट्रॉनों के साथ द्वि-झिरी","description":"एक-एक इलेक्ट्रॉन से बनने वाला पैटर्न","domain":"modern-physics"},
    {"id":"aperi21:uncertainty-principle","title":"अनिश्चितता सिद्धांत","description":"दो संयुग्मी राशियाँ एक साथ कितनी सटीकता से तय हो सकती हैं","domain":"modern-physics"},
    {"id":"aperi21:wave-function","title":"तरंग फलन","description":"प्रायिकता आयाम और उसका अर्थ","domain":"modern-physics"},
    {"id":"aperi21:superposition-quantum","title":"क्वांटम अध्यारोपण","description":"कई अवस्थाओं का योग होना","domain":"modern-physics"},
    {"id":"aperi21:measurement-collapse","title":"मापन और निपात","description":"प्रेक्षण अवस्था को कैसे तय करता है","domain":"modern-physics"},
    {"id":"aperi21:particle-in-a-box","title":"अनंत वर्ग कूप","description":"दीवारों से बना ऊर्जा का क्वांटीकरण","domain":"modern-physics"},
    {"id":"aperi21:finite-well","title":"परिमित वर्ग विभव कूप","description":"दीवारों के पार रिसता तरंग फलन","domain":"modern-physics"},
    {"id":"aperi21:quantum-tunneling","title":"क्वांटम सुरंगन","description":"अवरोध के पार जाने की प्रायिकता","domain":"modern-physics"},
    {"id":"aperi21:scanning-tunneling-microscope","title":"क्रमवीक्षण सुरंगन सूक्ष्मदर्शी","description":"सुरंगन धारा से सतह का चित्रण","domain":"modern-physics"},
    {"id":"aperi21:quantum-harmonic-oscillator","title":"क्वांटम सरल आवर्ती दोलित्र","description":"समान अंतराल वाले स्तर और शून्य-बिंदु ऊर्जा","domain":"modern-physics"},
    {"id":"aperi21:hydrogen-spectrum","title":"हाइड्रोजन स्पेक्ट्रम","description":"एक असतत रेखा स्पेक्ट्रम","domain":"modern-physics"},
    {"id":"aperi21:bohr-model","title":"बोर मॉडल","description":"क्वांटीकृत कक्षाएँ","domain":"modern-physics"},
    {"id":"aperi21:atomic-orbital","title":"परमाणु कक्षक","description":"प्रायिकता बंटन के रूप में इलेक्ट्रॉन","domain":"modern-physics"},
    {"id":"aperi21:pauli-exclusion","title":"पाउली अपवर्जन सिद्धांत","description":"एक ही अवस्था में दो नहीं","domain":"modern-physics"},
    {"id":"aperi21:electron-configuration","title":"इलेक्ट्रॉनिक विन्यास","description":"आवर्त सारणी कैसे बनती है","domain":"modern-physics"},
    {"id":"aperi21:spin","title":"प्रचक्रण","description":"ऐसा कोणीय संवेग जिसका कोई चिरसम्मत प्रतिरूप नहीं","domain":"modern-physics"},
    {"id":"aperi21:stern-gerlach","title":"स्टर्न–गर्लाक प्रयोग","description":"विभाजित होने वाला परमाणु पुंज","domain":"modern-physics"},
    {"id":"aperi21:zeeman-effect","title":"ज़ीमान प्रभाव","description":"चुंबकीय क्षेत्र द्वारा विभाजित ऊर्जा स्तर","domain":"modern-physics"},
    {"id":"aperi21:laser-and-stimulated-emission","title":"लेज़र और उद्दीपित उत्सर्जन","description":"कला में मेल खाते प्रकाश का प्रवर्धन","domain":"modern-physics"},
    {"id":"aperi21:nuclear-structure","title":"नाभिक किससे बना है","description":"प्रोटॉन और न्यूट्रॉन","domain":"modern-physics"},
    {"id":"aperi21:binding-energy-curve","title":"बंधन ऊर्जा वक्र","description":"यह लोहे पर शिखर पर क्यों पहुँचता है","domain":"modern-physics"},
    {"id":"aperi21:radioactive-decay","title":"रेडियोधर्मी क्षय","description":"अर्ध-आयु और चरघातांकी क्षय","domain":"modern-physics"},
    {"id":"aperi21:decay-types","title":"क्षय विकिरण के प्रकार","description":"अल्फ़ा, बीटा, गामा","domain":"modern-physics"},
    {"id":"aperi21:radiometric-dating","title":"रेडियोमितीय काल-निर्धारण","description":"जो बचा है उससे समय जानना","domain":"modern-physics"},
    {"id":"aperi21:nuclear-fission","title":"नाभिकीय विखंडन","description":"भारी नाभिक के टूटने पर मुक्त होने वाली ऊर्जा","domain":"modern-physics"},
    {"id":"aperi21:chain-reaction","title":"श्रृंखला अभिक्रिया","description":"न्यूट्रॉनों द्वारा आगे बढ़ता विखंडन","domain":"modern-physics"},
    {"id":"aperi21:nuclear-fusion","title":"नाभिकीय संलयन","description":"हल्के नाभिकों के जुड़ने पर मुक्त होने वाली ऊर्जा","domain":"modern-physics"},
    {"id":"aperi21:antimatter","title":"प्रतिद्रव्य","description":"विपरीत आवेश वाला साथी","domain":"modern-physics"},
    {"id":"aperi21:band-theory","title":"बैंड सिद्धांत","description":"चालकों, विद्युतरोधियों और अर्धचालकों को क्या अलग करता है","domain":"modern-physics"},
    {"id":"aperi21:fermi-level","title":"फर्मी स्तर","description":"इलेक्ट्रॉन कितनी ऊँचाई तक भरते हैं","domain":"modern-physics"},
    {"id":"aperi21:semiconductor-doping","title":"अपमिश्रण","description":"अशुद्धियाँ n-प्रकार और p-प्रकार कैसे बनाती हैं","domain":"modern-physics"},
    {"id":"aperi21:pn-junction","title":"p–n संधि","description":"अवक्षय परत और दिष्टकरण","domain":"modern-physics"},
    {"id":"aperi21:diode-and-led","title":"डायोड और LED","description":"एकदिशीय धारा और प्रकाश का उत्सर्जन","domain":"modern-physics"},
    {"id":"aperi21:transistor-principle","title":"ट्रांज़िस्टर","description":"छोटा संकेत बड़ी धारा को नियंत्रित करता है","domain":"modern-physics"},
    {"id":"aperi21:photovoltaic-effect","title":"प्रकाश-वोल्टीय प्रभाव","description":"प्रकाश से बनी वोल्टता","domain":"modern-physics"},
    {"id":"aperi21:superconductivity","title":"अतिचालकता","description":"वह अवस्था जिसमें प्रतिरोध लुप्त हो जाता है","domain":"modern-physics"},
    {"id":"aperi21:meissner-effect","title":"माइस्नर प्रभाव","description":"अतिचालक चुंबकीय क्षेत्र को बाहर धकेल देता है","domain":"modern-physics"},
    {"id":"aperi21:bose-einstein-condensate","title":"बोस–आइंस्टाइन संघनन","description":"एक ही अवस्था में सिमटते ठंडे कण","domain":"modern-physics"},
    {"id":"aperi21:scale-of-universe","title":"ब्रह्मांड का पैमाना","description":"परमाणु से ब्रह्मांड तक के आकार, दस की घातों से जुड़े","domain":"modern-physics"},
    {"id":"aperi21:rutherford-scattering","title":"रदरफ़ोर्ड प्रकीर्णन","description":"वह प्रयोग जिसमें अधिकांश पार निकल गए और कुछ वापस उछल आए","domain":"modern-physics"},
    {"id":"aperi21:ionizing-radiation","title":"आयनकारी विकिरण","description":"बंधों को तोड़ने लायक बड़ी फोटॉन ऊर्जा","domain":"modern-physics"},
    {"id":"aperi21:exchange-particles","title":"विनिमय कण","description":"बल वहन करने वाले कण","domain":"modern-physics"},
  ],
};
