/**
 * 자동 생성 파일 — 직접 편집하지 말 것.
 *
 * 생성: pnpm catalog:gen  (scripts/gen-aperi21-catalog.mts)
 * 출처: 각 sim 의 schema(label/description — description 의 원본은 topics.yaml desc) + docs/topics/topics.yaml(분야).
 */

import type { Aperi21Catalog } from '../catalog-types.js';

export const CATALOG: Aperi21Catalog = {
  locale: "id",
  domains: [
    {"id":"kinematics","name":"Kinematika"},
    {"id":"newtonian-mechanics","name":"Mekanika Newton"},
    {"id":"energy-momentum","name":"Usaha, Energi, dan Momentum"},
    {"id":"rotation-oscillation","name":"Rotasi dan Osilasi"},
    {"id":"gravitation","name":"Gravitasi dan Astronomi"},
    {"id":"fluids","name":"Fluida"},
    {"id":"thermodynamics","name":"Fisika Termal dan Statistik"},
    {"id":"waves-acoustics","name":"Gelombang dan Akustik"},
    {"id":"optics","name":"Optika"},
    {"id":"electromagnetism","name":"Elektromagnetisme"},
    {"id":"modern-physics","name":"Fisika Modern"},
  ],
  entries: [
    {"id":"aperi21:reference-frame","title":"Kerangka acuan","description":"Bagaimana deskripsi gerak bergantung pada pengamat","domain":"kinematics"},
    {"id":"aperi21:coordinate-choice","title":"Memilih sumbu","description":"Bagaimana pilihan sumbu mengubah persamaan","domain":"kinematics"},
    {"id":"aperi21:average-velocity","title":"Kecepatan rata-rata","description":"Satu kecepatan yang mewakili seluruh selang","domain":"kinematics"},
    {"id":"aperi21:average-acceleration","title":"Percepatan rata-rata","description":"Laju perubahan kecepatan selama suatu selang, yang hanya ditentukan oleh kecepatan di awal dan akhirnya","domain":"kinematics"},
    {"id":"aperi21:direction-of-acceleration","title":"Arah percepatan","description":"Searah kecepatan membuat benda makin cepat; berlawanan arah membuatnya melambat","domain":"kinematics"},
    {"id":"aperi21:uniform-motion","title":"Gerak lurus beraturan","description":"Gerak yang kecepatannya tidak berubah","domain":"kinematics"},
    {"id":"aperi21:uniformly-accelerated-motion","title":"Gerak lurus berubah beraturan","description":"Gerak yang jarak tempuhnya pada setiap selang waktu yang sama bertambah dengan jumlah tetap","domain":"kinematics"},
    {"id":"aperi21:position-time-graph","title":"Grafik posisi-waktu","description":"Representasi yang kemiringannya adalah kecepatan","domain":"kinematics"},
    {"id":"aperi21:velocity-time-graph","title":"Grafik kecepatan-waktu","description":"Representasi yang luas di bawah kurvanya terbaca sebagai jarak tempuh","domain":"kinematics"},
    {"id":"aperi21:acceleration-time-graph","title":"Grafik percepatan-waktu","description":"Luas di bawah grafik adalah perubahan kecepatan","domain":"kinematics"},
    {"id":"aperi21:free-fall","title":"Jatuh bebas","description":"Gerak di bawah gravitasi saja, benda berat dan ringan jatuh berdampingan","domain":"kinematics"},
    {"id":"aperi21:vertical-throw","title":"Gerak vertikal ke atas","description":"Simetri gerak naik dan turun","domain":"kinematics"},
    {"id":"aperi21:gravitational-acceleration","title":"Percepatan gravitasi","description":"Percepatan yang tidak berhenti bahkan saat kecepatannya nol","domain":"kinematics"},
    {"id":"aperi21:terminal-velocity","title":"Kecepatan terminal","description":"Kelajuan saat gaya hambat dan gravitasi mencapai keseimbangan","domain":"kinematics"},
    {"id":"aperi21:vector-decomposition","title":"Komponen vektor","description":"Menguraikan satu vektor menurut arah sumbu","domain":"kinematics"},
    {"id":"aperi21:vector-addition","title":"Penjumlahan vektor","description":"Penjumlahan yang menyambung ekor ke kepala","domain":"kinematics"},
    {"id":"aperi21:relative-velocity","title":"Kecepatan relatif","description":"Konversi kecepatan antarkerangka acuan","domain":"kinematics"},
    {"id":"aperi21:river-crossing","title":"Menyeberangi sungai","description":"Lintasan yang terbentuk dari perpaduan dua kecepatan","domain":"kinematics"},
    {"id":"aperi21:projectile-motion","title":"Gerak parabola","description":"Kebebasan komponen horizontal dan vertikal","domain":"kinematics"},
    {"id":"aperi21:projectile-range","title":"Jangkauan dan sudut lemparan","description":"Bagaimana sudut lemparan mengubah seberapa jauh benda terbang","domain":"kinematics"},
    {"id":"aperi21:trajectory-equation","title":"Persamaan lintasan","description":"Hubungan antara jarak mendatar dan ketinggian yang tersisa setelah waktu dihilangkan","domain":"kinematics"},
    {"id":"aperi21:uniform-circular-motion","title":"Gerak melingkar beraturan","description":"Lintasan melingkar dengan kelajuan tetap","domain":"kinematics"},
    {"id":"aperi21:centripetal-acceleration","title":"Percepatan sentripetal","description":"Ke mana perubahan kecepatan mengarah ketika kelajuannya tetap","domain":"kinematics"},
    {"id":"aperi21:angular-acceleration","title":"Percepatan sudut","description":"Laju perubahan kecepatan sudut","domain":"kinematics"},
    {"id":"aperi21:tangential-normal-acceleration","title":"Percepatan tangensial dan normal","description":"Memisahkan perubahan kelajuan dari perubahan arah","domain":"kinematics"},
    {"id":"aperi21:radius-of-curvature","title":"Jari-jari kelengkungan","description":"Lingkaran yang secara lokal menyerupai sebuah kurva","domain":"kinematics"},
    {"id":"aperi21:stopping-distance","title":"Jarak henti","description":"Jumlah jarak reaksi dan jarak pengereman","domain":"kinematics"},
    {"id":"aperi21:newtons-first-law","title":"Hukum I Newton","description":"Keadaan gerak saat tidak ada gaya total","domain":"newtonian-mechanics"},
    {"id":"aperi21:newtons-second-law","title":"Hukum II Newton","description":"Gaya total, massa, dan percepatan","domain":"newtonian-mechanics"},
    {"id":"aperi21:newtons-third-law","title":"Aksi dan reaksi","description":"Pasangan gaya yang bekerja pada benda berbeda","domain":"newtonian-mechanics"},
    {"id":"aperi21:net-force","title":"Gaya total","description":"Jumlah vektor beberapa gaya","domain":"newtonian-mechanics"},
    {"id":"aperi21:free-body-diagram","title":"Diagram benda bebas","description":"Memisahkan gaya-gaya pada satu benda","domain":"newtonian-mechanics"},
    {"id":"aperi21:inertial-vs-gravitational-mass","title":"Massa inersia dan massa gravitasi","description":"Dua definisi berbeda memberi nilai yang sama","domain":"newtonian-mechanics"},
    {"id":"aperi21:normal-force","title":"Gaya normal","description":"Dorongan tegak lurus dari permukaan kontak","domain":"newtonian-mechanics"},
    {"id":"aperi21:apparent-weight","title":"Berat semu","description":"Timbangan di dalam lift yang dipercepat","domain":"newtonian-mechanics"},
    {"id":"aperi21:static-friction","title":"Gaya gesek statis","description":"Gaya yang bertahan sampai benda bergerak","domain":"newtonian-mechanics"},
    {"id":"aperi21:kinetic-friction","title":"Gaya gesek kinetis","description":"Gesekan selama meluncur","domain":"newtonian-mechanics"},
    {"id":"aperi21:angle-of-friction","title":"Sudut gesek","description":"Kemiringan saat mulai tergelincir","domain":"newtonian-mechanics"},
    {"id":"aperi21:inclined-plane","title":"Bidang miring","description":"Menguraikan gravitasi sejajar dan tegak lurus bidang miring","domain":"newtonian-mechanics"},
    {"id":"aperi21:tension","title":"Tegangan tali","description":"Bagaimana tali meneruskan tarikan","domain":"newtonian-mechanics"},
    {"id":"aperi21:pulley-system","title":"Katrol","description":"Alat yang makin banyak utas talinya makin kecil tarikannya dan makin panjang tali yang ditarik","domain":"newtonian-mechanics"},
    {"id":"aperi21:connected-bodies","title":"Benda-benda terhubung","description":"Percepatan benda-benda yang bergerak bersama","domain":"newtonian-mechanics"},
    {"id":"aperi21:spring-force","title":"Gaya pegas","description":"Gaya pemulih yang sebanding dengan pertambahan panjang","domain":"newtonian-mechanics"},
    {"id":"aperi21:centripetal-force","title":"Gaya sentripetal","description":"Gaya ke arah dalam yang menahan gerak melingkar, dan lintasan saat gaya itu hilang","domain":"newtonian-mechanics"},
    {"id":"aperi21:conical-pendulum","title":"Bandul kerucut","description":"Gerak melingkar dari tegangan tali dan gravitasi","domain":"newtonian-mechanics"},
    {"id":"aperi21:banked-curve","title":"Tikungan miring","description":"Sudut kemiringan yang membelokkan mobil tanpa gesekan","domain":"newtonian-mechanics"},
    {"id":"aperi21:vertical-loop","title":"Lintasan loop vertikal","description":"Titik tempat benda meninggalkan rel ketika kelajuannya tidak cukup untuk memutari lingkaran","domain":"newtonian-mechanics"},
    {"id":"aperi21:drag-force","title":"Hambatan udara","description":"Hambatan yang sebanding dengan pangkat satu dan pangkat dua kelajuan","domain":"newtonian-mechanics"},
    {"id":"aperi21:buoyant-force-as-force","title":"Gaya apung sebagai gaya","description":"Dorongan fluida ke atas","domain":"newtonian-mechanics"},
    {"id":"aperi21:non-inertial-frame","title":"Kerangka acuan non-inersial","description":"Gerak yang dilihat dari kerangka acuan yang dipercepat","domain":"newtonian-mechanics"},
    {"id":"aperi21:fictitious-force","title":"Gaya fiktif","description":"Gaya semu dalam kerangka acuan non-inersial","domain":"newtonian-mechanics"},
    {"id":"aperi21:coriolis-effect","title":"Efek Coriolis","description":"Lintasan yang melengkung dalam kerangka acuan berotasi","domain":"newtonian-mechanics"},
    {"id":"aperi21:impulse-force-relation","title":"Gaya dan impuls","description":"Gaya singkat yang besar dan gaya lama yang kecil","domain":"newtonian-mechanics"},
    {"id":"aperi21:equilibrium-of-forces","title":"Kesetimbangan gaya","description":"Gaya total nol","domain":"newtonian-mechanics"},
    {"id":"aperi21:atwood-machine","title":"Mesin Atwood","description":"Sistem dua beban yang dihubungkan melalui katrol","domain":"newtonian-mechanics"},
    {"id":"aperi21:balance-scale","title":"Menyeimbangkan timbangan","description":"Keseimbangan yang ditentukan oleh panjang lengan dan berat sekaligus","domain":"newtonian-mechanics"},
    {"id":"aperi21:mechanical-advantage","title":"Keuntungan mekanis","description":"Bagaimana tuas dan bidang miring menukar gaya yang lebih kecil dengan jarak yang lebih jauh","domain":"newtonian-mechanics"},
    {"id":"aperi21:youngs-modulus","title":"Modulus Young","description":"Kekakuan yang dimiliki bahan, bukan oleh satu helai kawat","domain":"newtonian-mechanics"},
    {"id":"aperi21:stress-strain-curve","title":"Kurva tegangan–regangan","description":"Bagaimana bahan merespons saat ditarik","domain":"newtonian-mechanics"},
    {"id":"aperi21:work-by-variable-force","title":"Usaha oleh gaya yang berubah","description":"Luas di bawah grafik gaya–perpindahan","domain":"energy-momentum"},
    {"id":"aperi21:kinetic-energy","title":"Energi kinetik","description":"Energi yang dibawa oleh kelajuan","domain":"energy-momentum"},
    {"id":"aperi21:work-energy-theorem","title":"Teorema usaha-energi","description":"Bagaimanapun gaya dan jarak dibagi, usaha yang sama menghasilkan kelajuan akhir yang sama","domain":"energy-momentum"},
    {"id":"aperi21:gravitational-potential-energy","title":"Energi potensial gravitasi","description":"Energi yang tersimpan dalam ketinggian","domain":"energy-momentum"},
    {"id":"aperi21:elastic-potential-energy","title":"Energi potensial elastis","description":"Energi yang tersimpan dalam deformasi","domain":"energy-momentum"},
    {"id":"aperi21:conservative-force","title":"Gaya konservatif","description":"Gaya yang melakukan usaha sama lewat jalur mana pun","domain":"energy-momentum"},
    {"id":"aperi21:non-conservative-force","title":"Gaya nonkonservatif","description":"Usaha yang bergantung pada lintasan","domain":"energy-momentum"},
    {"id":"aperi21:conservation-of-mechanical-energy","title":"Kekekalan energi mekanik","description":"Bagian yang tersimpan dalam posisi dan bagian yang tersimpan dalam gerak bertukar tempat sementara jumlahnya tetap","domain":"energy-momentum"},
    {"id":"aperi21:energy-dissipation","title":"Disipasi energi","description":"Bagian yang diambil gesekan, dan ke mana perginya","domain":"energy-momentum"},
    {"id":"aperi21:potential-energy-curve","title":"Kurva energi potensial","description":"Bagaimana bentuk kurva menentukan gerak","domain":"energy-momentum"},
    {"id":"aperi21:equilibrium-points","title":"Titik kesetimbangan","description":"Kesetimbangan stabil, labil, dan netral","domain":"energy-momentum"},
    {"id":"aperi21:efficiency","title":"Efisiensi","description":"Bagian dari masukan yang keluar sebagai keluaran berguna","domain":"energy-momentum"},
    {"id":"aperi21:impulse-momentum-theorem","title":"Teorema impuls–momentum","description":"Impuls sama dengan perubahan momentum","domain":"energy-momentum"},
    {"id":"aperi21:conservation-of-momentum","title":"Kekekalan momentum","description":"Momentum total ketika tidak ada gaya luar yang bekerja","domain":"energy-momentum"},
    {"id":"aperi21:elastic-collision","title":"Tumbukan lenting sempurna","description":"Tumbukan yang membuat benda saling bertukar kelajuan","domain":"energy-momentum"},
    {"id":"aperi21:inelastic-collision","title":"Tumbukan lenting sebagian","description":"Tumbukan yang menyisakan bagian yang tidak kembali","domain":"energy-momentum"},
    {"id":"aperi21:perfectly-inelastic-collision","title":"Tumbukan tidak lenting sama sekali","description":"Ketika keduanya menempel dan bergerak bersama","domain":"energy-momentum"},
    {"id":"aperi21:two-dimensional-collision","title":"Tumbukan dua dimensi","description":"Kekekalan yang berlaku terpisah untuk tiap komponen","domain":"energy-momentum"},
    {"id":"aperi21:center-of-mass-motion","title":"Gerak pusat massa","description":"Gerak yang tidak dapat diubah oleh gaya dalam","domain":"energy-momentum"},
    {"id":"aperi21:explosion-and-recoil","title":"Ledakan dan tolakan","description":"Saat sistem yang diam terpecah","domain":"energy-momentum"},
    {"id":"aperi21:rocket-equation","title":"Persamaan roket","description":"Kelajuan yang diperoleh dengan membuang bahan bakar","domain":"energy-momentum"},
    {"id":"aperi21:ballistic-pendulum","title":"Bandul balistik","description":"Pengukuran yang menghubungkan tumbukan dengan kekekalan energi","domain":"energy-momentum"},
    {"id":"aperi21:energy-in-collision","title":"Energi dalam tumbukan","description":"Membedakan yang kekal dari yang tidak","domain":"energy-momentum"},
    {"id":"aperi21:energy-flow-diagram","title":"Diagram aliran energi","description":"Ke mana energi pergi, ditunjukkan oleh tebal cabang","domain":"energy-momentum"},
    {"id":"aperi21:torque","title":"Torsi","description":"Yang membuat benda berputar, dan panjang lengan gaya","domain":"rotation-oscillation"},
    {"id":"aperi21:moment-of-inertia","title":"Momen inersia","description":"Bagaimana sebaran massa menentukan hambatan terhadap rotasi","domain":"rotation-oscillation"},
    {"id":"aperi21:parallel-axis-theorem","title":"Teorema sumbu sejajar","description":"Momen inersia saat sumbu digeser","domain":"rotation-oscillation"},
    {"id":"aperi21:rotational-kinetic-energy","title":"Energi kinetik rotasi","description":"Energi yang dibawa putaran","domain":"rotation-oscillation"},
    {"id":"aperi21:angular-momentum","title":"Momentum sudut","description":"Besaran yang membuat benda berputar mempertahankan porosnya","domain":"rotation-oscillation"},
    {"id":"aperi21:conservation-of-angular-momentum","title":"Kekekalan momentum sudut","description":"Mengapa menarik lengan ke dalam membuatmu berputar lebih cepat","domain":"rotation-oscillation"},
    {"id":"aperi21:rolling-without-slipping","title":"Menggelinding tanpa slip","description":"Kendala yang mengikat translasi dengan rotasi","domain":"rotation-oscillation"},
    {"id":"aperi21:rolling-race","title":"Balapan benda menggelinding","description":"Urutan tiba ditentukan oleh sebaran massa","domain":"rotation-oscillation"},
    {"id":"aperi21:static-equilibrium","title":"Kesetimbangan statis","description":"Gaya total dan torsi total sama-sama nol","domain":"rotation-oscillation"},
    {"id":"aperi21:center-of-gravity","title":"Titik berat","description":"Titik yang menentukan kapan benda terguling","domain":"rotation-oscillation"},
    {"id":"aperi21:gyroscopic-precession","title":"Presesi giroskopik","description":"Torsi memutar arah momentum sudut","domain":"rotation-oscillation"},
    {"id":"aperi21:angular-momentum-vector","title":"Arah momentum sudut","description":"Kaidah tangan kanan dan sumbu rotasi","domain":"rotation-oscillation"},
    {"id":"aperi21:simple-harmonic-motion","title":"Gerak harmonik sederhana","description":"Gerak di bawah gaya pemulih yang sebanding dengan simpangan","domain":"rotation-oscillation"},
    {"id":"aperi21:shm-energy","title":"Energi pada gerak harmonik sederhana","description":"Energi kinetik dan energi potensial bertukar tempat","domain":"rotation-oscillation"},
    {"id":"aperi21:mass-spring-system","title":"Beban pada pegas","description":"Periode yang ditentukan oleh massa dan konstanta pegas","domain":"rotation-oscillation"},
    {"id":"aperi21:simple-pendulum","title":"Bandul sederhana","description":"Periode pada amplitudo kecil","domain":"rotation-oscillation"},
    {"id":"aperi21:physical-pendulum","title":"Bandul fisis","description":"Osilasi benda berukuran","domain":"rotation-oscillation"},
    {"id":"aperi21:pendulum-amplitude-dependence","title":"Amplitudo dan periode","description":"Isokronisme yang runtuh pada amplitudo besar","domain":"rotation-oscillation"},
    {"id":"aperi21:damped-oscillation","title":"Osilasi teredam","description":"Osilasi yang kehilangan energi","domain":"rotation-oscillation"},
    {"id":"aperi21:damping-regimes","title":"Tiga rezim redaman","description":"Gerak teredam kurang, teredam kritis, dan teredam lebih","domain":"rotation-oscillation"},
    {"id":"aperi21:driven-oscillation","title":"Osilasi paksa","description":"Tanggapan terhadap penggerak luar","domain":"rotation-oscillation"},
    {"id":"aperi21:resonance","title":"Resonansi","description":"Saat frekuensi penggerak sama dengan frekuensi alami","domain":"rotation-oscillation"},
    {"id":"aperi21:quality-factor","title":"Faktor kualitas","description":"Makin tajam resonansinya, makin lama getarannya bertahan","domain":"rotation-oscillation"},
    {"id":"aperi21:coupled-oscillators","title":"Osilator tergandeng","description":"Dua osilator yang saling bertukar energi","domain":"rotation-oscillation"},
    {"id":"aperi21:normal-modes","title":"Mode normal","description":"Bentuk getaran alami sebuah sistem","domain":"rotation-oscillation"},
    {"id":"aperi21:beats-in-oscillation","title":"Pelayangan pada osilasi","description":"Jumlah dua frekuensi yang berdekatan","domain":"rotation-oscillation"},
    {"id":"aperi21:phase-space","title":"Ruang fase","description":"Gerak yang dilihat pada bidang posisi–kecepatan","domain":"rotation-oscillation"},
    {"id":"aperi21:nonlinear-oscillation","title":"Osilasi nonlinier","description":"Saat gaya pemulih tidak lagi sebanding","domain":"rotation-oscillation"},
    {"id":"aperi21:gears","title":"Roda gigi","description":"Bagaimana jumlah gigi menukar kelajuan putar dengan torsi","domain":"rotation-oscillation"},
    {"id":"aperi21:newtons-law-of-gravitation","title":"Hukum gravitasi Newton","description":"Gaya yang melemah sebanding kuadrat jarak","domain":"gravitation"},
    {"id":"aperi21:gravitational-field","title":"Medan gravitasi","description":"Kuat gravitasi yang tersebar di ruang","domain":"gravitation"},
    {"id":"aperi21:range-and-surface-gravity","title":"Gravitasi dan jangkauan","description":"Bagaimana peluncuran yang sama melaju lebih jauh di tempat gravitasi lebih lemah","domain":"gravitation"},
    {"id":"aperi21:shell-theorem","title":"Teorema kulit bola","description":"Gravitasi di dalam dan di luar kulit bola","domain":"gravitation"},
    {"id":"aperi21:gravity-inside-earth","title":"Gravitasi di dalam Bumi","description":"Gravitasi yang melemah seiring kedalaman","domain":"gravitation"},
    {"id":"aperi21:gravitational-potential-energy-general","title":"Energi potensial gravitasi (umum)","description":"Energi negatif yang diukur dari tak hingga","domain":"gravitation"},
    {"id":"aperi21:escape-velocity","title":"Kecepatan lepas","description":"Kelajuan terkecil untuk lepas dari gravitasi","domain":"gravitation"},
    {"id":"aperi21:orbital-velocity","title":"Kecepatan orbit","description":"Kelajuan yang membuat orbit tetap melingkar","domain":"gravitation"},
    {"id":"aperi21:circular-orbit","title":"Orbit melingkar","description":"Gerak dengan gravitasi sebagai gaya sentripetal","domain":"gravitation"},
    {"id":"aperi21:elliptical-orbit","title":"Orbit elips","description":"Benda pusat berada di salah satu fokus","domain":"gravitation"},
    {"id":"aperi21:keplers-first-law","title":"Hukum Pertama Kepler","description":"Orbit elips dengan Matahari di salah satu fokus","domain":"gravitation"},
    {"id":"aperi21:keplers-second-law","title":"Hukum Kedua Kepler","description":"Luas sama dalam waktu sama","domain":"gravitation"},
    {"id":"aperi21:keplers-third-law","title":"Hukum Ketiga Kepler","description":"Waktu satu putaran, yang bertambah jauh lebih cepat daripada jari-jari","domain":"gravitation"},
    {"id":"aperi21:two-body-problem","title":"Masalah dua benda","description":"Dua benda yang mengorbit pusat massa bersamanya","domain":"gravitation"},
    {"id":"aperi21:tidal-force","title":"Gaya pasang surut","description":"Peregangan akibat perbedaan gravitasi","domain":"gravitation"},
    {"id":"aperi21:roche-limit","title":"Batas Roche","description":"Jarak tempat gaya pasang surut mengoyak sebuah benda","domain":"gravitation"},
    {"id":"aperi21:weightlessness","title":"Keadaan tanpa bobot","description":"Berat semu saat jatuh bebas","domain":"gravitation"},
    {"id":"aperi21:geostationary-orbit","title":"Orbit geostasioner","description":"Orbit di atas khatulistiwa dengan periode yang sama dengan rotasi Bumi","domain":"gravitation"},
    {"id":"aperi21:gravitational-slingshot","title":"Asistensi gravitasi","description":"Mengubah kelajuan dengan melintasi planet","domain":"gravitation"},
    {"id":"aperi21:lagrange-points","title":"Titik Lagrange","description":"Lima tempat yang mengikuti langkah dua benda langit yang mengorbit bersama","domain":"gravitation"},
    {"id":"aperi21:orbital-transfer","title":"Transfer orbit","description":"Transfer Hohmann dari orbit rendah ke orbit yang lebih tinggi","domain":"gravitation"},
    {"id":"aperi21:black-hole-horizon","title":"Horizon peristiwa","description":"Jari-jari tempat kecepatan lepas mencapai kecepatan cahaya","domain":"gravitation"},
    {"id":"aperi21:diurnal-motion","title":"Gerak harian","description":"Lintasan seluruh langit malam yang berputar mengelilingi satu titik dalam sehari","domain":"gravitation"},
    {"id":"aperi21:earth-rotation-day-night","title":"Rotasi Bumi, siang dan malam","description":"Mengapa siang dan malam silih berganti di Bumi yang berputar","domain":"gravitation"},
    {"id":"aperi21:earth-revolution-constellations","title":"Orbit Bumi dan rasi bintang","description":"Mengapa rasi bintang yang kita lihat berubah mengikuti musim","domain":"gravitation"},
    {"id":"aperi21:solar-altitude-shadow","title":"Ketinggian Matahari dan bayang-bayang","description":"Ketika ketinggian berubah, panjang bayangan dan luas sebaran sinar matahari berubah bersama","domain":"gravitation"},
    {"id":"aperi21:seasonal-sun-path","title":"Lintasan Matahari sepanjang musim","description":"Bagaimana ketinggian Matahari saat tengah hari dan panjang siang berubah bersama","domain":"gravitation"},
    {"id":"aperi21:axial-tilt-seasons","title":"Kemiringan sumbu rotasi dan musim","description":"Musim yang dibuat oleh Bumi yang mengorbit dalam keadaan miring","domain":"gravitation"},
    {"id":"aperi21:moon-phases","title":"Fase-fase Bulan","description":"Bagian Bulan yang tersinari Matahari mana yang menghadap kita","domain":"gravitation"},
    {"id":"aperi21:eclipse","title":"Gerhana Matahari dan gerhana Bulan","description":"Ketika Matahari, Bumi, dan Bulan segaris","domain":"gravitation"},
    {"id":"aperi21:stellar-parallax","title":"Paralaks bintang","description":"Sudut pergeseran bintang dekat saat Bumi mengorbit Matahari","domain":"gravitation"},
    {"id":"aperi21:apparent-brightness","title":"Kecerahan semu","description":"Bagaimana bintang yang sama tampak berbeda terangnya menurut jaraknya","domain":"gravitation"},
    {"id":"aperi21:magnitude-scale","title":"Magnitudo bintang","description":"Cara kecerahan dinyatakan sebagai magnitudo","domain":"gravitation"},
    {"id":"aperi21:star-color-temperature","title":"Warna bintang dan suhu permukaan","description":"Bagaimana suhu permukaan menentukan warna cahaya bintang","domain":"gravitation"},
    {"id":"aperi21:expanding-universe","title":"Alam semesta yang mengembang","description":"Galaksi-galaksi yang menjauh ke segala arah","domain":"gravitation"},
    {"id":"aperi21:stellar-luminosity","title":"Luminositas","description":"Seberapa banyak cahaya yang sebenarnya dipancarkan bintang","domain":"gravitation"},
    {"id":"aperi21:hr-diagram","title":"Diagram HR","description":"Diagram suhu–luminositas sebuah gugus, tempat bintang terberat meninggalkan deret utama lebih dulu seiring bertambahnya usia","domain":"gravitation"},
    {"id":"aperi21:star-radiation-gravity-balance","title":"Keseimbangan tekanan dan gravitasi","description":"Mengapa bintang tidak runtuh dan tidak tercerai-berai","domain":"gravitation"},
    {"id":"aperi21:orbital-decay","title":"Peluruhan orbit","description":"Orbit yang dihambat udara tipis","domain":"gravitation"},
    {"id":"aperi21:inverse-square-law","title":"Hukum kuadrat terbalik","description":"Makin menyebar, makin tipis","domain":"gravitation"},
    {"id":"aperi21:stellar-nucleosynthesis","title":"Nukleosintesis bintang","description":"Fusi di inti bintang yang membentuk unsur lebih berat selangkah demi selangkah hingga besi","domain":"gravitation"},
    {"id":"aperi21:star-life-cycle","title":"Siklus hidup bintang","description":"Bagaimana massa menentukan jalan hidup bintang","domain":"gravitation"},
    {"id":"aperi21:stellar-spectral-class","title":"Kelas spektrum bintang","description":"Pola garis serapan yang ditentukan suhu","domain":"gravitation"},
    {"id":"aperi21:supernova-and-neutron-star","title":"Supernova dan bintang neutron","description":"Keruntuhan terakhir dan pantulan","domain":"gravitation"},
    {"id":"aperi21:exoplanet-detection","title":"Mendeteksi eksoplanet","description":"Jejak yang ditinggalkan planet","domain":"gravitation"},
    {"id":"aperi21:projectile-in-wind","title":"Angin dan jangkauan","description":"Bagaimana angin menggeser titik jatuh dari peluncuran yang sama","domain":"fluids"},
    {"id":"aperi21:pressure-isotropy","title":"Isotropi tekanan","description":"Besarnya sama ke arah mana pun","domain":"fluids"},
    {"id":"aperi21:hydrostatic-pressure","title":"Tekanan hidrostatis","description":"Tekanan yang bertambah seiring kedalaman","domain":"fluids"},
    {"id":"aperi21:pressure-and-container-shape","title":"Bentuk wadah dan tekanan di dasar","description":"Bagaimana tekanan di dasar tidak bergantung pada bentuk","domain":"fluids"},
    {"id":"aperi21:atmospheric-pressure","title":"Tekanan atmosfer","description":"Berat kolom udara","domain":"fluids"},
    {"id":"aperi21:barometer","title":"Barometer","description":"Tinggi kolom raksa","domain":"fluids"},
    {"id":"aperi21:manometer","title":"Manometer","description":"Membaca tekanan dari kolom cairan","domain":"fluids"},
    {"id":"aperi21:pascals-principle","title":"Hukum Pascal","description":"Tekanan yang diteruskan dan pres hidrolik","domain":"fluids"},
    {"id":"aperi21:buoyancy","title":"Gaya apung","description":"Gaya ke atas yang tersisa karena permukaan bawah terdorong lebih kuat","domain":"fluids"},
    {"id":"aperi21:archimedes-principle","title":"Prinsip Archimedes — besarnya gaya apung","description":"Gaya yang diterima sama dengan berat fluida yang dipindahkan","domain":"fluids"},
    {"id":"aperi21:floating-and-draft","title":"Seberapa dalam benda terapung tenggelam","description":"Apa yang menentukan volume yang tercelup","domain":"fluids"},
    {"id":"aperi21:stability-of-floating-body","title":"Kestabilan benda terapung","description":"Hubungan antara titik berat dan titik apung","domain":"fluids"},
    {"id":"aperi21:continuity-equation","title":"Persamaan kontinuitas","description":"Luas penampang dan kelajuan aliran saling mengimbangi","domain":"fluids"},
    {"id":"aperi21:bernoullis-principle","title":"Prinsip Bernoulli","description":"Pertukaran antara kelajuan dan tekanan","domain":"fluids"},
    {"id":"aperi21:venturi-effect","title":"Efek Venturi","description":"Tekanan lebih rendah di bagian pipa yang menyempit","domain":"fluids"},
    {"id":"aperi21:torricellis-law","title":"Hukum Torricelli","description":"Kelajuan aliran yang keluar dari lubang","domain":"fluids"},
    {"id":"aperi21:lift-force","title":"Gaya angkat","description":"Cara udara mengalir di atas dan di bawah sayap","domain":"fluids"},
    {"id":"aperi21:viscosity","title":"Viskositas","description":"Gesekan antarlapisan","domain":"fluids"},
    {"id":"aperi21:poiseuille-flow","title":"Aliran laminar dalam pipa","description":"Debit bertambah sebanding dengan pangkat empat jari-jari","domain":"fluids"},
    {"id":"aperi21:stokes-drag","title":"Gaya hambat Stokes","description":"Dalam aliran lambat, bola berjari-jari dua kali tenggelam empat kali lebih cepat","domain":"fluids"},
    {"id":"aperi21:laminar-vs-turbulent","title":"Aliran laminar dan turbulen","description":"Dua pola aliran","domain":"fluids"},
    {"id":"aperi21:reynolds-number","title":"Bilangan Reynolds","description":"Bilangan tak berdimensi yang menentukan corak aliran","domain":"fluids"},
    {"id":"aperi21:boundary-layer","title":"Lapisan batas","description":"Lapisan tipis tempat kelajuan aliran naik dari nol di dinding hingga kelajuan aliran luar","domain":"fluids"},
    {"id":"aperi21:surface-tension","title":"Tegangan permukaan","description":"Tarikan permukaan air yang berubah arah untuk menopang beban","domain":"fluids"},
    {"id":"aperi21:laplace-pressure","title":"Tekanan Laplace","description":"Lonjakan tekanan yang dibuat permukaan lengkung","domain":"fluids"},
    {"id":"aperi21:capillary-action","title":"Kapilaritas","description":"Naik dan turun di dalam pipa sempit","domain":"fluids"},
    {"id":"aperi21:wetting-and-contact-angle","title":"Pembasahan dan sudut kontak","description":"Seberapa jauh cairan menyebar di atas padatan","domain":"fluids"},
    {"id":"aperi21:drag-in-fluid","title":"Gaya hambat dalam fluida","description":"Hambatan dalam aliran cepat yang ditentukan oleh bentuk bagian belakang","domain":"fluids"},
    {"id":"aperi21:thermal-equilibrium","title":"Kesetimbangan termal","description":"Keadaan yang dicapai dua sistem yang bersentuhan","domain":"thermodynamics"},
    {"id":"aperi21:specific-heat","title":"Kalor jenis","description":"Seberapa besar suhu berubah, bahan demi bahan","domain":"thermodynamics"},
    {"id":"aperi21:calorimetry","title":"Kalorimetri","description":"Suhu akhir suatu campuran","domain":"thermodynamics"},
    {"id":"aperi21:latent-heat","title":"Kalor laten","description":"Mengapa suhu berhenti selama perubahan wujud","domain":"thermodynamics"},
    {"id":"aperi21:phase-diagram","title":"Diagram fase","description":"Fase yang ditentukan oleh tekanan dan suhu","domain":"thermodynamics"},
    {"id":"aperi21:triple-point","title":"Titik tripel","description":"Kondisi saat tiga fase berada bersama","domain":"thermodynamics"},
    {"id":"aperi21:thermal-conduction","title":"Konduksi kalor","description":"Kalor yang merambat melalui bahan, cepat pada baja dan lambat pada kayu","domain":"thermodynamics"},
    {"id":"aperi21:thermal-convection","title":"Konveksi","description":"Kalor yang dibawa fluida yang bergerak","domain":"thermodynamics"},
    {"id":"aperi21:thermal-radiation","title":"Radiasi termal","description":"Kalor yang merambat tanpa medium","domain":"thermodynamics"},
    {"id":"aperi21:stefan-boltzmann-law","title":"Hukum Stefan–Boltzmann","description":"Radiasi yang bertambah sebanding pangkat empat suhu","domain":"thermodynamics"},
    {"id":"aperi21:thermal-expansion","title":"Pemuaian termal","description":"Perubahan panjang zat padat terhadap suhu","domain":"thermodynamics"},
    {"id":"aperi21:bimetal","title":"Keping bimetal","description":"Pembengkokan akibat pemuaian yang tidak sama","domain":"thermodynamics"},
    {"id":"aperi21:ideal-gas-law","title":"Hukum gas ideal","description":"Hubungan tekanan, volume, dan suhu","domain":"thermodynamics"},
    {"id":"aperi21:boyles-law","title":"Hukum Boyle","description":"Tekanan dan volume pada suhu tetap","domain":"thermodynamics"},
    {"id":"aperi21:charles-law","title":"Hukum Charles","description":"Volume dan suhu pada tekanan tetap","domain":"thermodynamics"},
    {"id":"aperi21:gas-pressure","title":"Molekul dan tekanan","description":"Bagaimana menaikkan suhu membuat molekul menumbuk dinding lebih sering dan lebih keras sehingga tekanan naik","domain":"thermodynamics"},
    {"id":"aperi21:pressure-from-collisions","title":"Tekanan dari tumbukan","description":"Lebih keras dan lebih sering: tekanan dinding yang bertambah sebanding kuadrat kelajuan molekul","domain":"thermodynamics"},
    {"id":"aperi21:maxwell-boltzmann-distribution","title":"Distribusi Maxwell–Boltzmann","description":"Sebaran kelajuan molekul","domain":"thermodynamics"},
    {"id":"aperi21:mean-free-path","title":"Jalan bebas rata-rata","description":"Jarak antartumbukan","domain":"thermodynamics"},
    {"id":"aperi21:first-law-of-thermodynamics","title":"Hukum pertama termodinamika","description":"Hubungan energi dalam, usaha, dan kalor","domain":"thermodynamics"},
    {"id":"aperi21:pv-diagram","title":"Diagram PV","description":"Tempat luas adalah usaha","domain":"thermodynamics"},
    {"id":"aperi21:isothermal-process","title":"Proses isotermal","description":"Perubahan yang menjaga suhu tetap","domain":"thermodynamics"},
    {"id":"aperi21:adiabatic-process","title":"Proses adiabatik","description":"Perubahan tanpa kalor yang masuk atau keluar","domain":"thermodynamics"},
    {"id":"aperi21:isobaric-isochoric","title":"Proses isobarik dan isokhorik","description":"Perubahan pada tekanan tetap atau volume tetap","domain":"thermodynamics"},
    {"id":"aperi21:cyclic-process","title":"Proses siklus","description":"Perubahan yang kembali ke tempat ia bermula","domain":"thermodynamics"},
    {"id":"aperi21:second-law-of-thermodynamics","title":"Hukum kedua termodinamika","description":"Perubahan yang berjalan satu arah","domain":"thermodynamics"},
    {"id":"aperi21:irreversibility","title":"Entropi dan ketakterbalikan","description":"Mengapa tidak bisa dibalikkan","domain":"thermodynamics"},
    {"id":"aperi21:heat-engine","title":"Mesin kalor","description":"Siklus yang hanya mengubah sebagian kalornya menjadi usaha dan membuang sisanya ke sisi dingin","domain":"thermodynamics"},
    {"id":"aperi21:carnot-cycle","title":"Siklus Carnot","description":"Efisiensi maksimum teoretis","domain":"thermodynamics"},
    {"id":"aperi21:refrigerator-heat-pump","title":"Kulkas dan pompa kalor","description":"Memindahkan kalor dengan memberikan usaha","domain":"thermodynamics"},
    {"id":"aperi21:brownian-motion","title":"Gerak Brown","description":"Gerak acak yang digerakkan tumbukan molekul","domain":"thermodynamics"},
    {"id":"aperi21:diffusion","title":"Difusi","description":"Aliran yang digerakkan oleh perbedaan konsentrasi","domain":"thermodynamics"},
    {"id":"aperi21:random-walk","title":"Langkah acak","description":"Sebaran dari titik awal yang hanya bertambah sebesar akar kuadrat jumlah langkah","domain":"thermodynamics"},
    {"id":"aperi21:statistical-fluctuation","title":"Fluktuasi statistik","description":"Goyangan yang membesar saat partikel sedikit","domain":"thermodynamics"},
    {"id":"aperi21:maxwells-demon","title":"Iblis Maxwell","description":"Gas yang terpisah sebanyak yang diamati","domain":"thermodynamics"},
    {"id":"aperi21:insulation","title":"Insulasi termal","description":"Memperlambat aliran kalor","domain":"thermodynamics"},
    {"id":"aperi21:albedo","title":"Albedo","description":"Bagian cahaya yang dipantulkan kembali","domain":"thermodynamics"},
    {"id":"aperi21:radiative-equilibrium","title":"Kesetimbangan radiasi","description":"Suhu yang tercapai ketika yang keluar sama dengan yang masuk","domain":"thermodynamics"},
    {"id":"aperi21:greenhouse-effect","title":"Efek rumah kaca","description":"Lapisan yang mengirim inframerah kembali ke bawah menghangatkan tanah","domain":"thermodynamics"},
    {"id":"aperi21:wave-basics","title":"Besaran dasar gelombang","description":"Panjang gelombang, frekuensi, kelajuan, dan amplitudo","domain":"waves-acoustics"},
    {"id":"aperi21:wave-vs-particle-transport","title":"Apa yang dibawa gelombang","description":"Medium tetap di tempat, energi bergerak maju","domain":"waves-acoustics"},
    {"id":"aperi21:transverse-wave","title":"Gelombang transversal","description":"Medium bergetar tegak lurus terhadap arah rambat gelombang","domain":"waves-acoustics"},
    {"id":"aperi21:longitudinal-wave","title":"Gelombang longitudinal","description":"Getaran yang sejajar dengan arah rambat","domain":"waves-acoustics"},
    {"id":"aperi21:wave-speed-in-medium","title":"Kelajuan gelombang dan medium","description":"Kelajuan yang ditentukan oleh tegangan tali dan rapat massa linear","domain":"waves-acoustics"},
    {"id":"aperi21:wavefront-and-ray","title":"Muka gelombang dan sinar","description":"Permukaan sefase dan garis-garis yang tegak lurus padanya","domain":"waves-acoustics"},
    {"id":"aperi21:huygens-principle","title":"Prinsip Huygens","description":"Setiap titik pada muka gelombang menjadi sumber baru","domain":"waves-acoustics"},
    {"id":"aperi21:superposition","title":"Superposisi","description":"Apa yang terjadi ketika gelombang saling bertumpuk","domain":"waves-acoustics"},
    {"id":"aperi21:constructive-destructive","title":"Interferensi konstruktif dan destruktif","description":"Bagaimana beda fase menentukan besar jumlahnya","domain":"waves-acoustics"},
    {"id":"aperi21:interference","title":"Interferensi","description":"Pola yang dibentuk dua sumber","domain":"waves-acoustics"},
    {"id":"aperi21:standing-wave","title":"Gelombang stasioner","description":"Gelombang yang simpul dan perutnya tetap","domain":"waves-acoustics"},
    {"id":"aperi21:harmonics","title":"Harmonik","description":"Frekuensi yang ditentukan oleh batas","domain":"waves-acoustics"},
    {"id":"aperi21:string-vibration","title":"Tali yang bergetar","description":"Tinggi nada yang ditentukan oleh panjang yang bergetar","domain":"waves-acoustics"},
    {"id":"aperi21:air-column-resonance","title":"Resonansi kolom udara","description":"Pipa terbuka dan pipa tertutup","domain":"waves-acoustics"},
    {"id":"aperi21:beats","title":"Pelayangan","description":"Jumlah dua frekuensi yang berdekatan","domain":"waves-acoustics"},
    {"id":"aperi21:doppler-effect","title":"Efek Doppler","description":"Bagaimana sumber yang bergerak memisahkan jarak antarmuka gelombang di depan dan di belakang","domain":"waves-acoustics"},
    {"id":"aperi21:doppler-source-vs-observer","title":"Sumber bergerak vs. pengamat bergerak","description":"Asimetri menurut siapa yang bergerak","domain":"waves-acoustics"},
    {"id":"aperi21:shock-wave","title":"Gelombang kejut","description":"Kerucut yang terbentuk setelah melampaui kelajuan bunyi","domain":"waves-acoustics"},
    {"id":"aperi21:sound-intensity","title":"Intensitas bunyi","description":"Intensitas yang turun berbanding terbalik dengan kuadrat jarak, sementara taraf desibel hanya turun sedikit","domain":"waves-acoustics"},
    {"id":"aperi21:reflection-of-waves","title":"Pemantulan gelombang","description":"Fase di ujung terikat dan di ujung bebas","domain":"waves-acoustics"},
    {"id":"aperi21:refraction-of-waves","title":"Pembiasan gelombang","description":"Perubahan kelajuan membelokkan arah","domain":"waves-acoustics"},
    {"id":"aperi21:diffraction","title":"Difraksi","description":"Gelombang yang membelok di sekitar penghalang","domain":"waves-acoustics"},
    {"id":"aperi21:slit-width-and-diffraction","title":"Lebar Celah dan Difraksi","description":"Bagaimana perbandingan celah dan panjang gelombang menentukan penyebaran","domain":"waves-acoustics"},
    {"id":"aperi21:wave-energy","title":"Energi gelombang","description":"Energi bertambah sebanding dengan kuadrat amplitudo","domain":"waves-acoustics"},
    {"id":"aperi21:wave-attenuation","title":"Atenuasi gelombang","description":"Amplitudo yang turun dengan rasio sama pada setiap jarak yang sama","domain":"waves-acoustics"},
    {"id":"aperi21:impedance-mismatch","title":"Ketidakcocokan impedansi","description":"Seberapa banyak yang dipantulkan di batas","domain":"waves-acoustics"},
    {"id":"aperi21:noise-cancellation","title":"Peredam bising aktif","description":"Superposisi gelombang terbalik","domain":"waves-acoustics"},
    {"id":"aperi21:sound-source-vibration","title":"Bunyi dan getaran","description":"Benda yang berbunyi bergetar, dan saat getarannya berhenti, bunyinya pun berhenti","domain":"waves-acoustics"},
    {"id":"aperi21:sound-through-materials","title":"Bunyi melalui berbagai bahan","description":"Kelajuan bunyi dan perambatannya yang ditentukan oleh medium","domain":"waves-acoustics"},
    {"id":"aperi21:digital-vs-analog-signal","title":"Sinyal digital dan analog","description":"Dua cara bertahan terhadap derau","domain":"waves-acoustics"},
    {"id":"aperi21:seismic-waves","title":"Gelombang seismik","description":"Zona bayangan yang terbentuk saat inti luar cair menahan gelombang S dan membelokkan gelombang P","domain":"waves-acoustics"},
    {"id":"aperi21:rectilinear-propagation","title":"Cahaya merambat lurus","description":"Bayang-bayang dan model sinar","domain":"optics"},
    {"id":"aperi21:shadow-umbra-penumbra","title":"Umbra dan penumbra","description":"Bagaimana ukuran sumber cahaya membentuk tepi bayang-bayang","domain":"optics"},
    {"id":"aperi21:pinhole-camera","title":"Kamera lubang jarum","description":"Bayangan yang dibentuk oleh satu lubang","domain":"optics"},
    {"id":"aperi21:law-of-reflection","title":"Hukum pemantulan","description":"Sudut datang dan sudut pantul","domain":"optics"},
    {"id":"aperi21:specular-diffuse-reflection","title":"Pemantulan teratur dan pemantulan baur","description":"Pemantulan yang ditentukan kekasaran permukaan","domain":"optics"},
    {"id":"aperi21:plane-mirror-image","title":"Bayangan pada cermin datar","description":"Bayangan maya di balik cermin, tempat cahaya yang ditelusuri balik bertemu","domain":"optics"},
    {"id":"aperi21:multiple-mirror-images","title":"Bayangan pada dua cermin","description":"Bagaimana sudut antara dua cermin menentukan jumlah bayangan","domain":"optics"},
    {"id":"aperi21:concave-mirror","title":"Cermin cekung","description":"Bayangan nyata selama benda di luar titik fokus, bayangan maya begitu di dalamnya","domain":"optics"},
    {"id":"aperi21:convex-mirror","title":"Cermin cembung","description":"Bidang pandang lebih luas dan bayangan maya yang kecil dan tegak","domain":"optics"},
    {"id":"aperi21:snells-law","title":"Hukum Snellius","description":"Bagaimana lintasan membelok menurut medium","domain":"optics"},
    {"id":"aperi21:apparent-depth","title":"Kedalaman semu","description":"Mengapa benda di bawah air tampak terangkat","domain":"optics"},
    {"id":"aperi21:total-internal-reflection","title":"Pemantulan sempurna","description":"Sudut kritis dan syaratnya","domain":"optics"},
    {"id":"aperi21:optical-fiber","title":"Serat optik","description":"Cahaya yang terperangkap oleh pemantulan sempurna","domain":"optics"},
    {"id":"aperi21:mirage","title":"Fatamorgana","description":"Cahaya yang dibelokkan oleh gradien kerapatan","domain":"optics"},
    {"id":"aperi21:dispersion","title":"Dispersi","description":"Indeks bias yang bergantung pada panjang gelombang","domain":"optics"},
    {"id":"aperi21:prism","title":"Prisma","description":"Spektrum yang terurai oleh dispersi","domain":"optics"},
    {"id":"aperi21:rainbow","title":"Pelangi","description":"Pembiasan dan pemantulan di dalam tetes hujan","domain":"optics"},
    {"id":"aperi21:thin-lens","title":"Lensa tipis","description":"Titik fokus dan pembentukan bayangan","domain":"optics"},
    {"id":"aperi21:converging-diverging-lens","title":"Lensa konvergen dan lensa divergen","description":"Lensa yang mengumpulkan cahaya dan lensa yang menyebarkannya","domain":"optics"},
    {"id":"aperi21:magnification","title":"Perbesaran","description":"Ukuran bayangan dan ukuran benda","domain":"optics"},
    {"id":"aperi21:focal-length","title":"Jarak fokus","description":"Bagaimana jarak fokus menentukan tempat bayangan terbentuk","domain":"optics"},
    {"id":"aperi21:real-vs-virtual-image","title":"Bayangan nyata dan maya","description":"Apakah cahaya benar-benar bertemu?","domain":"optics"},
    {"id":"aperi21:lens-combination","title":"Kombinasi lensa","description":"Titik fokus gabungan dua lensa","domain":"optics"},
    {"id":"aperi21:spherical-aberration","title":"Aberasi sferis","description":"Sinar tepi terfokus di tempat lain","domain":"optics"},
    {"id":"aperi21:chromatic-aberration","title":"Aberasi kromatik","description":"Fokus berbeda untuk tiap panjang gelombang","domain":"optics"},
    {"id":"aperi21:human-eye-accommodation","title":"Akomodasi mata","description":"Cara lensa mata memfokuskan benda","domain":"optics"},
    {"id":"aperi21:myopia-hyperopia","title":"Rabun jauh dan rabun dekat","description":"Di mana bayangan terbentuk, dan bagaimana kacamata mengoreksinya","domain":"optics"},
    {"id":"aperi21:magnifying-glass","title":"Kaca pembesar","description":"Benda di dalam titik fokus yang terlihat sebagai bayangan maya yang besar dan tegak","domain":"optics"},
    {"id":"aperi21:microscope","title":"Mikroskop","description":"Perbesaran lensa objektif dan okuler dikalikan","domain":"optics"},
    {"id":"aperi21:telescope","title":"Teleskop","description":"Perbesaran yang ditentukan oleh perbandingan jarak fokus","domain":"optics"},
    {"id":"aperi21:youngs-double-slit","title":"Celah ganda Young","description":"Bukti bahwa cahaya adalah gelombang","domain":"optics"},
    {"id":"aperi21:single-slit-diffraction","title":"Difraksi celah tunggal","description":"Pita terang tengah yang melebar saat celah menyempit","domain":"optics"},
    {"id":"aperi21:diffraction-grating","title":"Kisi difraksi","description":"Maksimum tajam yang dibentuk banyak celah","domain":"optics"},
    {"id":"aperi21:thin-film-interference","title":"Interferensi lapisan tipis","description":"Warna yang dibentuk oleh ketebalan","domain":"optics"},
    {"id":"aperi21:newtons-rings","title":"Cincin Newton","description":"Interferensi antara permukaan lengkung dan permukaan datar","domain":"optics"},
    {"id":"aperi21:resolving-power","title":"Daya urai","description":"Batas untuk membedakan dua titik","domain":"optics"},
    {"id":"aperi21:polarization","title":"Polarisasi","description":"Memilih bidang getar","domain":"optics"},
    {"id":"aperi21:malus-law","title":"Hukum Malus","description":"Intensitas yang melewati polarisator","domain":"optics"},
    {"id":"aperi21:brewster-angle","title":"Sudut Brewster","description":"Sudut saat cahaya pantul terpolarisasi penuh","domain":"optics"},
    {"id":"aperi21:birefringence","title":"Birefringensi","description":"Cahaya yang terpecah menjadi dua berkas yang bergetar tegak lurus sehingga bayangan tampak ganda","domain":"optics"},
    {"id":"aperi21:scattering","title":"Hamburan","description":"Ukuran partikel yang membedakan langit biru dari awan putih","domain":"optics"},
    {"id":"aperi21:rayleigh-scattering","title":"Hamburan Rayleigh","description":"Hamburan yang naik tajam makin pendek panjang gelombangnya","domain":"optics"},
    {"id":"aperi21:seeing-requires-light","title":"Melihat butuh cahaya","description":"Tanpa cahaya, benda tidak dapat dilihat","domain":"optics"},
    {"id":"aperi21:color-addition","title":"Penjumlahan cahaya","description":"Warna yang dibentuk tiga cahaya di tempat mereka bertumpang tindih","domain":"optics"},
    {"id":"aperi21:object-color","title":"Warna suatu benda","description":"Warna yang ditentukan oleh cahaya yang dipantulkan benda","domain":"optics"},
    {"id":"aperi21:light-through-materials","title":"Cahaya dan bahan","description":"Cara cahaya menembus bergantung pada bahannya","domain":"optics"},
    {"id":"aperi21:electric-charge","title":"Muatan listrik","description":"Muatan yang hanya ada dua jenis","domain":"electromagnetism"},
    {"id":"aperi21:charging-methods","title":"Cara memberi muatan listrik","description":"Gesekan, sentuhan, dan induksi","domain":"electromagnetism"},
    {"id":"aperi21:coulombs-law","title":"Hukum Coulomb","description":"Gaya antarmuatan yang melemah sebesar kuadrat kelipatan jaraknya","domain":"electromagnetism"},
    {"id":"aperi21:superposition-of-forces","title":"Superposisi gaya listrik","description":"Menjumlahkan gaya dari beberapa muatan","domain":"electromagnetism"},
    {"id":"aperi21:electric-field","title":"Medan listrik","description":"Gaya pada muatan satuan","domain":"electromagnetism"},
    {"id":"aperi21:field-lines","title":"Garis medan listrik","description":"Konvensi menggambar medan dan maknanya","domain":"electromagnetism"},
    {"id":"aperi21:field-of-dipole","title":"Medan listrik dipol","description":"Dua muatan berlawanan yang berdekatan","domain":"electromagnetism"},
    {"id":"aperi21:uniform-field","title":"Medan listrik homogen","description":"Medan di antara keping sejajar","domain":"electromagnetism"},
    {"id":"aperi21:charge-in-uniform-field","title":"Muatan dalam medan homogen","description":"Persis seperti gerak parabola","domain":"electromagnetism"},
    {"id":"aperi21:gausss-law","title":"Hukum Gauss","description":"Fluks listrik melalui permukaan tertutup","domain":"electromagnetism"},
    {"id":"aperi21:field-of-charged-sphere","title":"Medan bola bermuatan","description":"Mengapa bagian dalam dan luar berbeda","domain":"electromagnetism"},
    {"id":"aperi21:equipotential-surface","title":"Permukaan ekuipotensial","description":"Permukaan yang tegak lurus medan","domain":"electromagnetism"},
    {"id":"aperi21:potential-vs-field","title":"Potensial dan medan listrik","description":"Hubungan kemiringan","domain":"electromagnetism"},
    {"id":"aperi21:electrostatic-shielding","title":"Perisai elektrostatik","description":"Mengapa medan di dalam konduktor bernilai nol","domain":"electromagnetism"},
    {"id":"aperi21:charge-on-conductor-surface","title":"Muatan di permukaan konduktor","description":"Muatan berkumpul di ujung runcing","domain":"electromagnetism"},
    {"id":"aperi21:dielectric","title":"Dielektrik","description":"Polarisasi melemahkan medan","domain":"electromagnetism"},
    {"id":"aperi21:parallel-plate-capacitor","title":"Kapasitor keping sejajar","description":"Kapasitas yang ditentukan oleh luas dan jarak keping","domain":"electromagnetism"},
    {"id":"aperi21:capacitors-in-circuit","title":"Rangkaian kapasitor","description":"Penggabungan seri dan paralel","domain":"electromagnetism"},
    {"id":"aperi21:energy-in-capacitor","title":"Energi pada kapasitor","description":"Usaha yang dikeluarkan untuk memindahkan muatan","domain":"electromagnetism"},
    {"id":"aperi21:electric-current","title":"Arus listrik","description":"Aliran muatan dan konvensi arahnya","domain":"electromagnetism"},
    {"id":"aperi21:drift-velocity","title":"Kecepatan hanyut","description":"Kelajuan elektron yang merayap di dalam kawat","domain":"electromagnetism"},
    {"id":"aperi21:ohms-law","title":"Hukum Ohm","description":"Tegangan, arus, dan hambatan","domain":"electromagnetism"},
    {"id":"aperi21:resistance-and-geometry","title":"Hambatan dan bentuk","description":"Pengaruh panjang dan luas penampang","domain":"electromagnetism"},
    {"id":"aperi21:temperature-and-resistance","title":"Suhu dan hambatan","description":"Logam dan semikonduktor berubah ke arah berlawanan","domain":"electromagnetism"},
    {"id":"aperi21:series-parallel-resistors","title":"Hambatan seri dan paralel","description":"Bagaimana cara penyambungan mengubah arus yang diberikan satu baterai","domain":"electromagnetism"},
    {"id":"aperi21:emf-and-internal-resistance","title":"GGL dan hambatan dalam","description":"Mengapa tegangan jepit turun","domain":"electromagnetism"},
    {"id":"aperi21:kirchhoffs-current-law","title":"Hukum arus Kirchhoff","description":"Kekekalan muatan di titik cabang","domain":"electromagnetism"},
    {"id":"aperi21:kirchhoffs-voltage-law","title":"Hukum tegangan Kirchhoff","description":"Kekekalan energi dalam satu loop","domain":"electromagnetism"},
    {"id":"aperi21:wheatstone-bridge","title":"Jembatan Wheatstone","description":"Mengukur hambatan dengan kesetimbangan","domain":"electromagnetism"},
    {"id":"aperi21:joule-heating","title":"Pemanasan Joule","description":"Kalor yang dihasilkan hambatan","domain":"electromagnetism"},
    {"id":"aperi21:rc-circuit","title":"Rangkaian RC","description":"Konstanta waktu pengisian dan pengosongan","domain":"electromagnetism"},
    {"id":"aperi21:magnetic-field","title":"Medan magnet","description":"Bagaimana gaya magnet tersebar di sekitar magnet","domain":"electromagnetism"},
    {"id":"aperi21:magnetic-field-lines","title":"Garis medan magnet","description":"Garis yang tak pernah putus dan selalu tertutup","domain":"electromagnetism"},
    {"id":"aperi21:lorentz-force","title":"Gaya Lorentz","description":"Gaya pada muatan yang bergerak dalam medan magnet","domain":"electromagnetism"},
    {"id":"aperi21:charged-particle-in-magnetic-field","title":"Muatan yang berputar dalam medan magnet","description":"Waktu satu putaran yang sama berapa pun kelajuannya","domain":"electromagnetism"},
    {"id":"aperi21:velocity-selector","title":"Pemilih kecepatan","description":"Menyeimbangkan gaya listrik dan gaya magnet","domain":"electromagnetism"},
    {"id":"aperi21:mass-spectrometer","title":"Spektrometer massa","description":"Memilah massa menurut jari-jari","domain":"electromagnetism"},
    {"id":"aperi21:force-on-current-wire","title":"Gaya pada kawat berarus","description":"Gaya magnet pada kawat yang dialiri arus","domain":"electromagnetism"},
    {"id":"aperi21:biot-savart-law","title":"Hukum Biot–Savart","description":"Medan magnet elemen-elemen arus","domain":"electromagnetism"},
    {"id":"aperi21:field-of-straight-wire","title":"Medan magnet yang dihasilkan arus","description":"Kuat medan yang melemah makin jauh jaraknya","domain":"electromagnetism"},
    {"id":"aperi21:field-of-loop-and-solenoid","title":"Kawat melingkar dan solenoida","description":"Medan magnet yang dibuat kawat melingkar bertumpuk seragam dan kuat di dalam serta lemah di luar","domain":"electromagnetism"},
    {"id":"aperi21:amperes-law","title":"Hukum Ampère","description":"Sirkulasi medan magnet di sekitar arus","domain":"electromagnetism"},
    {"id":"aperi21:force-between-wires","title":"Gaya antara kawat sejajar","description":"Dua arus sejajar saling tarik atau saling tolak","domain":"electromagnetism"},
    {"id":"aperi21:magnetic-dipole","title":"Dipol magnetik","description":"Kawat melingkar berarus dan magnet itu sama","domain":"electromagnetism"},
    {"id":"aperi21:magnetic-materials","title":"Bahan magnetik","description":"Feromagnetik, paramagnetik, dan diamagnetik","domain":"electromagnetism"},
    {"id":"aperi21:faradays-law","title":"Hukum Faraday","description":"GGL yang ditimbulkan oleh perubahan fluks","domain":"electromagnetism"},
    {"id":"aperi21:lenzs-law","title":"Hukum Lenz","description":"Arus induksi yang melawan perubahan","domain":"electromagnetism"},
    {"id":"aperi21:motional-emf","title":"GGL gerak","description":"Tegangan yang ditimbulkan kawat yang bergerak","domain":"electromagnetism"},
    {"id":"aperi21:eddy-current","title":"Arus pusar","description":"Arus induksi di dalam konduktor pejal","domain":"electromagnetism"},
    {"id":"aperi21:self-inductance","title":"Induktansi diri","description":"Kumparan yang melawan dengan tegangannya sendiri ketika arusnya berubah","domain":"electromagnetism"},
    {"id":"aperi21:mutual-inductance","title":"Induktansi bersama","description":"GGL yang terinduksi pada rangkaian di dekatnya","domain":"electromagnetism"},
    {"id":"aperi21:energy-in-inductor","title":"Energi pada induktor","description":"Energi yang tersimpan dalam medan magnet","domain":"electromagnetism"},
    {"id":"aperi21:rl-circuit","title":"Rangkaian RL","description":"Mengapa arus naik perlahan","domain":"electromagnetism"},
    {"id":"aperi21:lc-oscillation","title":"Osilasi LC","description":"Energi listrik dan energi magnet bertukar tempat","domain":"electromagnetism"},
    {"id":"aperi21:ac-generation","title":"Pembangkitan arus bolak-balik","description":"Kumparan yang berputar dan gelombang sinus","domain":"electromagnetism"},
    {"id":"aperi21:reactance","title":"Reaktansi dan impedansi","description":"Bagaimana kumparan makin menghambat arus bolak-balik dan kapasitor makin sedikit saat frekuensi naik","domain":"electromagnetism"},
    {"id":"aperi21:phase-in-ac-circuit","title":"Beda fase pada rangkaian AC","description":"Tegangan dan arus yang tidak lagi seirama","domain":"electromagnetism"},
    {"id":"aperi21:series-rlc-resonance","title":"Resonansi RLC","description":"Frekuensi saat impedansi paling kecil","domain":"electromagnetism"},
    {"id":"aperi21:transformer","title":"Transformator","description":"Jumlah lilitan dan perbandingan tegangan","domain":"electromagnetism"},
    {"id":"aperi21:motor","title":"Motor listrik","description":"Berputar oleh gaya pada arus","domain":"electromagnetism"},
    {"id":"aperi21:generator","title":"Generator","description":"Nyalakan bohlam dan engkol menjadi lebih berat","domain":"electromagnetism"},
    {"id":"aperi21:displacement-current","title":"Arus perpindahan","description":"Suku yang menjembatani celah kapasitor","domain":"electromagnetism"},
    {"id":"aperi21:maxwells-equations","title":"Persamaan Maxwell","description":"Rantai tempat listrik dan magnet saling membangkitkan","domain":"electromagnetism"},
    {"id":"aperi21:electromagnetic-wave","title":"Gelombang elektromagnetik","description":"Medan listrik dan magnet yang merambat sendiri","domain":"electromagnetism"},
    {"id":"aperi21:poynting-vector","title":"Vektor Poynting","description":"Energi yang melintasi ruang di sekitar kawat","domain":"electromagnetism"},
    {"id":"aperi21:radiation-pressure","title":"Tekanan radiasi","description":"Dorongan cahaya","domain":"electromagnetism"},
    {"id":"aperi21:antenna-radiation","title":"Radiasi antena","description":"Gelombang yang dipancarkan antena paling kuat ke samping dan sama sekali tidak searah sumbunya","domain":"electromagnetism"},
    {"id":"aperi21:magnet-attraction","title":"Yang menempel pada magnet","description":"Benda yang ditarik magnet dan yang tidak","domain":"electromagnetism"},
    {"id":"aperi21:magnetic-poles","title":"Dua kutub magnet","description":"Kutub sejenis tolak-menolak, kutub tak sejenis tarik-menarik","domain":"electromagnetism"},
    {"id":"aperi21:simple-circuit","title":"Merangkai rangkaian listrik","description":"Arus mengalir hanya bila tersambung; putuskan dan lampu padam","domain":"electromagnetism"},
    {"id":"aperi21:electromagnet","title":"Elektromagnet","description":"Magnet hanya selama arus mengalir","domain":"electromagnetism"},
    {"id":"aperi21:iv-characteristic","title":"Kurva karakteristik I–V","description":"Komponen yang arusnya tidak mengikuti tegangan secara garis lurus","domain":"electromagnetism"},
    {"id":"aperi21:thermistor-and-ldr","title":"Termistor dan LDR","description":"Hambatan yang berubah menurut suhu dan cahaya","domain":"electromagnetism"},
    {"id":"aperi21:potential-divider","title":"Pembagi tegangan","description":"Membagi tegangan dengan hambatan","domain":"electromagnetism"},
    {"id":"aperi21:millikan-experiment","title":"Percobaan tetes minyak Millikan","description":"Bukti bahwa muatan datang dalam paket-paket","domain":"electromagnetism"},
    {"id":"aperi21:power-transmission","title":"Transmisi daya listrik","description":"Menaikkan tegangan untuk mengurangi rugi daya","domain":"electromagnetism"},
    {"id":"aperi21:loudspeaker-and-microphone","title":"Pengeras suara dan mikrofon","description":"Mengubah arus menjadi getaran dan sebaliknya","domain":"electromagnetism"},
    {"id":"aperi21:michelson-morley","title":"Eksperimen Michelson–Morley","description":"Bukti bahwa eter tidak ada","domain":"modern-physics"},
    {"id":"aperi21:relativity-of-simultaneity","title":"Relativitas keserempakan","description":"‘Serentak’ yang berbeda di tiap kerangka acuan","domain":"modern-physics"},
    {"id":"aperi21:time-dilation","title":"Dilatasi waktu","description":"Jam yang bergerak berjalan lambat","domain":"modern-physics"},
    {"id":"aperi21:light-clock","title":"Jam cahaya","description":"Eksperimen pikiran di balik dilatasi waktu","domain":"modern-physics"},
    {"id":"aperi21:length-contraction","title":"Kontraksi panjang","description":"Kontraksi searah gerak","domain":"modern-physics"},
    {"id":"aperi21:muon-decay-evidence","title":"Muon yang mencapai tanah","description":"Bukti pengamatan dilatasi waktu","domain":"modern-physics"},
    {"id":"aperi21:relativistic-velocity-addition","title":"Penjumlahan kecepatan relativistik","description":"Komposisi yang tak pernah melampaui kecepatan cahaya","domain":"modern-physics"},
    {"id":"aperi21:twin-paradox","title":"Paradoks kembar","description":"Putar balik yang menciptakan ketidaksimetrisan","domain":"modern-physics"},
    {"id":"aperi21:spacetime-diagram","title":"Diagram ruang-waktu","description":"Garis dunia dan garis keserempakan","domain":"modern-physics"},
    {"id":"aperi21:light-cone","title":"Kerucut cahaya","description":"Sejauh mana sebab dapat menjangkau","domain":"modern-physics"},
    {"id":"aperi21:relativistic-momentum","title":"Momentum relativistik","description":"Momentum yang bertambah tanpa batas saat kelajuan mendekati kecepatan cahaya","domain":"modern-physics"},
    {"id":"aperi21:relativistic-doppler","title":"Efek Doppler relativistik","description":"Pergeseran frekuensi dengan tambahan dilatasi waktu","domain":"modern-physics"},
    {"id":"aperi21:equivalence-principle","title":"Prinsip ekuivalensi","description":"Percepatan dan gravitasi tak dapat dibedakan","domain":"modern-physics"},
    {"id":"aperi21:gravitational-time-dilation","title":"Dilatasi waktu gravitasi","description":"Jam berjalan dengan laju berbeda pada potensial berbeda","domain":"modern-physics"},
    {"id":"aperi21:gravitational-redshift","title":"Pergeseran merah gravitasi","description":"Cahaya yang memerah saat keluar","domain":"modern-physics"},
    {"id":"aperi21:light-bending-by-gravity","title":"Pembelokan cahaya","description":"Lintasan cahaya membelok di dekat massa","domain":"modern-physics"},
    {"id":"aperi21:blackbody-radiation","title":"Radiasi benda hitam","description":"Tempat teori klasik gagal","domain":"modern-physics"},
    {"id":"aperi21:wien-displacement-law","title":"Hukum pergeseran Wien","description":"Suhu dan panjang gelombang puncak","domain":"modern-physics"},
    {"id":"aperi21:photoelectric-effect","title":"Efek fotolistrik","description":"Bukti bahwa cahaya datang sebagai partikel","domain":"modern-physics"},
    {"id":"aperi21:work-function-and-threshold","title":"Fungsi kerja dan frekuensi ambang","description":"Ambang yang berbeda untuk tiap logam, dengan kemiringan yang sama untuk semuanya","domain":"modern-physics"},
    {"id":"aperi21:compton-scattering","title":"Hamburan Compton","description":"Bukti bahwa foton membawa momentum","domain":"modern-physics"},
    {"id":"aperi21:pair-production","title":"Produksi pasangan","description":"Energi yang berubah menjadi materi","domain":"modern-physics"},
    {"id":"aperi21:de-broglie-wavelength","title":"Panjang gelombang de Broglie","description":"Panjang gelombang materi yang ditentukan oleh kelajuannya","domain":"modern-physics"},
    {"id":"aperi21:electron-diffraction","title":"Difraksi elektron","description":"Melihat gelombang materi","domain":"modern-physics"},
    {"id":"aperi21:double-slit-with-electrons","title":"Celah ganda dengan elektron","description":"Pola yang terbentuk satu elektron demi satu","domain":"modern-physics"},
    {"id":"aperi21:uncertainty-principle","title":"Prinsip ketidakpastian","description":"Seberapa tajam dua besaran konjugat dapat ditetapkan sekaligus","domain":"modern-physics"},
    {"id":"aperi21:wave-function","title":"Fungsi gelombang","description":"Amplitudo probabilitas dan maknanya","domain":"modern-physics"},
    {"id":"aperi21:superposition-quantum","title":"Superposisi kuantum","description":"Berada sebagai jumlah beberapa keadaan","domain":"modern-physics"},
    {"id":"aperi21:measurement-collapse","title":"Pengukuran dan keruntuhan","description":"Bagaimana pengamatan menetapkan keadaan","domain":"modern-physics"},
    {"id":"aperi21:particle-in-a-box","title":"Sumur persegi tak berhingga","description":"Kuantisasi energi yang dibuat oleh dinding","domain":"modern-physics"},
    {"id":"aperi21:finite-well","title":"Sumur potensial persegi berhingga","description":"Tingkat energi yang lebih rendah karena fungsi gelombang merembes ke dalam dinding","domain":"modern-physics"},
    {"id":"aperi21:quantum-tunneling","title":"Penerowongan kuantum","description":"Probabilitas menembus penghalang","domain":"modern-physics"},
    {"id":"aperi21:scanning-tunneling-microscope","title":"Mikroskop penerowongan pemindai","description":"Menggambar permukaan dengan arus penerowongan","domain":"modern-physics"},
    {"id":"aperi21:quantum-harmonic-oscillator","title":"Osilator harmonik kuantum","description":"Tingkat energi berjarak sama dan energi titik nol","domain":"modern-physics"},
    {"id":"aperi21:hydrogen-spectrum","title":"Spektrum hidrogen","description":"Spektrum garis yang diskret","domain":"modern-physics"},
    {"id":"aperi21:bohr-model","title":"Model atom Bohr","description":"Orbit terkuantisasi","domain":"modern-physics"},
    {"id":"aperi21:atomic-orbital","title":"Orbital atom","description":"Elektron sebagai distribusi probabilitas","domain":"modern-physics"},
    {"id":"aperi21:pauli-exclusion","title":"Prinsip larangan Pauli","description":"Tak ada dua dalam keadaan yang sama","domain":"modern-physics"},
    {"id":"aperi21:electron-configuration","title":"Konfigurasi elektron","description":"Bagaimana tabel periodik terbentuk","domain":"modern-physics"},
    {"id":"aperi21:spin","title":"Spin","description":"Momentum sudut tanpa padanan klasik","domain":"modern-physics"},
    {"id":"aperi21:stern-gerlach","title":"Eksperimen Stern–Gerlach","description":"Berkas atom yang terbelah","domain":"modern-physics"},
    {"id":"aperi21:zeeman-effect","title":"Efek Zeeman","description":"Tingkat energi yang dipecah oleh medan magnet","domain":"modern-physics"},
    {"id":"aperi21:laser-and-stimulated-emission","title":"Laser dan emisi terstimulasi","description":"Menguatkan cahaya yang selaras","domain":"modern-physics"},
    {"id":"aperi21:nuclear-structure","title":"Terbuat dari apa inti atom","description":"Jumlah proton menentukan unsur; jumlah neutron menentukan isotop","domain":"modern-physics"},
    {"id":"aperi21:binding-energy-curve","title":"Kurva energi ikat","description":"Mengapa puncaknya di besi","domain":"modern-physics"},
    {"id":"aperi21:radioactive-decay","title":"Peluruhan radioaktif","description":"Waktu paruh dan peluruhan eksponensial","domain":"modern-physics"},
    {"id":"aperi21:decay-types","title":"Jenis radiasi peluruhan","description":"Alfa, beta, gama","domain":"modern-physics"},
    {"id":"aperi21:radiometric-dating","title":"Penanggalan radiometrik","description":"Mengukur waktu dari yang tersisa","domain":"modern-physics"},
    {"id":"aperi21:nuclear-fission","title":"Fisi nuklir","description":"Energi yang dilepaskan saat inti berat membelah","domain":"modern-physics"},
    {"id":"aperi21:chain-reaction","title":"Reaksi berantai","description":"Fisi yang diteruskan oleh neutron","domain":"modern-physics"},
    {"id":"aperi21:nuclear-fusion","title":"Fusi nuklir","description":"Energi yang dilepaskan saat inti ringan bergabung","domain":"modern-physics"},
    {"id":"aperi21:antimatter","title":"Antimateri","description":"Pasangan elektron yang lenyap bersamanya dan memancarkan dua foton ke arah berlawanan","domain":"modern-physics"},
    {"id":"aperi21:band-theory","title":"Teori pita","description":"Apa yang membedakan konduktor, isolator, dan semikonduktor","domain":"modern-physics"},
    {"id":"aperi21:fermi-level","title":"Tingkat Fermi","description":"Seberapa tinggi elektron terisi","domain":"modern-physics"},
    {"id":"aperi21:semiconductor-doping","title":"Doping","description":"Bagaimana pengotor membentuk tipe-n dan tipe-p","domain":"modern-physics"},
    {"id":"aperi21:pn-junction","title":"Sambungan p–n","description":"Lapisan deplesi dan penyearahan","domain":"modern-physics"},
    {"id":"aperi21:diode-and-led","title":"Dioda dan LED","description":"Arus satu arah dan pancaran cahaya","domain":"modern-physics"},
    {"id":"aperi21:transistor-principle","title":"Transistor","description":"Sinyal kecil mengendalikan arus besar","domain":"modern-physics"},
    {"id":"aperi21:photovoltaic-effect","title":"Efek fotovoltaik","description":"Tegangan yang dihasilkan cahaya","domain":"modern-physics"},
    {"id":"aperi21:superconductivity","title":"Superkonduktivitas","description":"Keadaan saat hambatan lenyap","domain":"modern-physics"},
    {"id":"aperi21:meissner-effect","title":"Efek Meissner","description":"Superkonduktor mendorong keluar medan magnet","domain":"modern-physics"},
    {"id":"aperi21:bose-einstein-condensate","title":"Kondensasi Bose–Einstein","description":"Partikel dingin yang berdesakan ke satu keadaan","domain":"modern-physics"},
    {"id":"aperi21:scale-of-universe","title":"Skala alam semesta","description":"Ukuran dari atom hingga alam semesta, dihubungkan oleh pangkat sepuluh","domain":"modern-physics"},
    {"id":"aperi21:rutherford-scattering","title":"Hamburan Rutherford","description":"Eksperimen ketika sebagian besar lewat dan sedikit terpantul balik","domain":"modern-physics"},
    {"id":"aperi21:photon-bond-threshold","title":"Foton yang memutus ikatan","description":"Ambang ultraungu tempat satu foton mulai memutus satu ikatan","domain":"modern-physics"},
    {"id":"aperi21:exchange-particles","title":"Partikel pertukaran","description":"Foton di antara elektron, gluon di antara kuark","domain":"modern-physics"},
  ],
};
