/**
 * 자동 생성 파일 — 직접 편집하지 말 것.
 *
 * 생성: pnpm catalog:gen  (scripts/gen-aperi21-catalog.mts)
 * 출처: 각 sim 의 schema(label/description — description 의 원본은 topics.yaml desc) + docs/topics/topics.yaml(분야).
 */

import type { Aperi21Catalog } from '../catalog-types.js';

export const CATALOG: Aperi21Catalog = {
  locale: "ko",
  domains: [
    {"id":"kinematics","name":"운동학"},
    {"id":"newtonian-mechanics","name":"뉴턴 역학"},
    {"id":"energy-momentum","name":"일·에너지·운동량"},
    {"id":"rotation-oscillation","name":"회전과 진동"},
    {"id":"gravitation","name":"중력과 천체"},
    {"id":"fluids","name":"유체"},
    {"id":"thermodynamics","name":"열과 통계"},
    {"id":"waves-acoustics","name":"파동과 음향"},
    {"id":"optics","name":"광학"},
    {"id":"electromagnetism","name":"전자기"},
    {"id":"modern-physics","name":"현대물리"},
  ],
  entries: [
    {"id":"aperi21:reference-frame","title":"기준틀","description":"관찰자에 따라 달라지는 운동 기술","domain":"kinematics"},
    {"id":"aperi21:coordinate-choice","title":"좌표계 선택","description":"축을 어디에 두느냐가 식을 바꾸는 방식","domain":"kinematics"},
    {"id":"aperi21:average-velocity","title":"평균 속도","description":"구간 전체를 대표하는 속도","domain":"kinematics"},
    {"id":"aperi21:average-acceleration","title":"평균 가속도","description":"구간의 처음과 끝 속도만으로 정해지는 속도 변화의 비율","domain":"kinematics"},
    {"id":"aperi21:direction-of-acceleration","title":"가속도의 방향","description":"속도와 같은 쪽이면 빨라지고 반대쪽이면 느려진다","domain":"kinematics"},
    {"id":"aperi21:uniform-motion","title":"등속 운동","description":"속도가 변하지 않는 운동","domain":"kinematics"},
    {"id":"aperi21:uniformly-accelerated-motion","title":"등가속도 운동","description":"같은 시간마다 나아간 거리가 일정한 몫씩 길어지는 운동","domain":"kinematics"},
    {"id":"aperi21:position-time-graph","title":"위치-시간 그래프","description":"기울기가 속도인 표현","domain":"kinematics"},
    {"id":"aperi21:velocity-time-graph","title":"속도-시간 그래프","description":"곡선 아래 넓이가 나아간 거리로 읽히는 표현","domain":"kinematics"},
    {"id":"aperi21:acceleration-time-graph","title":"가속도-시간 그래프","description":"넓이가 속도 변화인 표현","domain":"kinematics"},
    {"id":"aperi21:free-fall","title":"자유 낙하","description":"무게와 상관없이 나란히 떨어지는, 중력만 받는 운동","domain":"kinematics"},
    {"id":"aperi21:vertical-throw","title":"연직 투상","description":"올라갔다 내려오는 운동의 대칭","domain":"kinematics"},
    {"id":"aperi21:gravitational-acceleration","title":"중력 가속도","description":"속도가 0인 순간에도 멈추지 않는 가속","domain":"kinematics"},
    {"id":"aperi21:terminal-velocity","title":"종단 속도","description":"저항과 중력이 균형에 이르는 속도","domain":"kinematics"},
    {"id":"aperi21:vector-decomposition","title":"벡터의 성분 분해","description":"한 벡터를 축 방향으로 나누기","domain":"kinematics"},
    {"id":"aperi21:vector-addition","title":"벡터의 합성","description":"꼬리와 머리를 잇는 덧셈","domain":"kinematics"},
    {"id":"aperi21:relative-velocity","title":"상대 속도","description":"기준틀 사이의 속도 변환","domain":"kinematics"},
    {"id":"aperi21:river-crossing","title":"강 건너기","description":"두 속도의 합성이 만드는 경로","domain":"kinematics"},
    {"id":"aperi21:projectile-motion","title":"포물선 운동","description":"수평·연직 성분의 독립","domain":"kinematics"},
    {"id":"aperi21:projectile-range","title":"사거리와 발사각","description":"던지는 각도가 날아가는 거리를 바꾸는 방식","domain":"kinematics"},
    {"id":"aperi21:trajectory-equation","title":"궤적 방정식","description":"시각을 걷어 내도 남는 가로와 높이 사이의 관계","domain":"kinematics"},
    {"id":"aperi21:uniform-circular-motion","title":"등속 원운동","description":"속력이 일정한 원 궤도","domain":"kinematics"},
    {"id":"aperi21:centripetal-acceleration","title":"구심 가속도","description":"속력이 그대로인 운동에서 속도 변화가 향하는 곳","domain":"kinematics"},
    {"id":"aperi21:angular-acceleration","title":"각가속도","description":"각속도의 변화율","domain":"kinematics"},
    {"id":"aperi21:tangential-normal-acceleration","title":"접선·법선 가속도","description":"속력 변화와 방향 변화의 분리","domain":"kinematics"},
    {"id":"aperi21:radius-of-curvature","title":"곡률 반지름","description":"곡선이 국소적으로 닮은 원","domain":"kinematics"},
    {"id":"aperi21:stopping-distance","title":"정지 거리","description":"반응 거리와 제동 거리의 합","domain":"kinematics"},
    {"id":"aperi21:newtons-first-law","title":"관성 법칙","description":"알짜힘이 없을 때의 운동 상태","domain":"newtonian-mechanics"},
    {"id":"aperi21:newtons-second-law","title":"가속도 법칙","description":"알짜힘·질량·가속도의 관계","domain":"newtonian-mechanics"},
    {"id":"aperi21:newtons-third-law","title":"작용 반작용","description":"힘의 쌍과 서로 다른 작용점","domain":"newtonian-mechanics"},
    {"id":"aperi21:net-force","title":"알짜힘","description":"여러 힘의 벡터 합","domain":"newtonian-mechanics"},
    {"id":"aperi21:free-body-diagram","title":"자유물체도","description":"한 물체에 작용하는 힘만 분리하기","domain":"newtonian-mechanics"},
    {"id":"aperi21:inertial-vs-gravitational-mass","title":"관성 질량과 중력 질량","description":"서로 다른 정의가 같은 값을 주는 것","domain":"newtonian-mechanics"},
    {"id":"aperi21:normal-force","title":"수직항력","description":"접촉면이 수직으로 미는 힘","domain":"newtonian-mechanics"},
    {"id":"aperi21:apparent-weight","title":"겉보기 무게","description":"가속하는 엘리베이터 안의 저울","domain":"newtonian-mechanics"},
    {"id":"aperi21:static-friction","title":"정지 마찰력","description":"움직이기 전까지 버티는 힘","domain":"newtonian-mechanics"},
    {"id":"aperi21:kinetic-friction","title":"운동 마찰력","description":"미끄러지는 동안의 마찰","domain":"newtonian-mechanics"},
    {"id":"aperi21:angle-of-friction","title":"마찰각","description":"미끄러지기 시작하는 경사","domain":"newtonian-mechanics"},
    {"id":"aperi21:inclined-plane","title":"빗면","description":"중력을 면에 나란한 성분과 수직 성분으로","domain":"newtonian-mechanics"},
    {"id":"aperi21:tension","title":"장력","description":"줄이 당기는 힘과 그 전달","domain":"newtonian-mechanics"},
    {"id":"aperi21:pulley-system","title":"도르래","description":"줄 가닥이 늘수록 드는 힘은 줄고 당길 줄은 길어지는 장치","domain":"newtonian-mechanics"},
    {"id":"aperi21:connected-bodies","title":"연결된 물체","description":"함께 움직이는 계의 가속도","domain":"newtonian-mechanics"},
    {"id":"aperi21:spring-force","title":"탄성력","description":"변형에 비례하는 복원력","domain":"newtonian-mechanics"},
    {"id":"aperi21:centripetal-force","title":"구심력","description":"원운동을 붙드는 안쪽 힘과 그것이 사라졌을 때의 진로","domain":"newtonian-mechanics"},
    {"id":"aperi21:conical-pendulum","title":"원뿔 진자","description":"장력과 중력이 만드는 원운동","domain":"newtonian-mechanics"},
    {"id":"aperi21:banked-curve","title":"경사진 커브","description":"마찰 없이도 도는 각도","domain":"newtonian-mechanics"},
    {"id":"aperi21:vertical-loop","title":"연직 원운동","description":"고리를 돌기에 속력이 모자라면 레일을 떠나는 자리","domain":"newtonian-mechanics"},
    {"id":"aperi21:drag-force","title":"공기 저항","description":"속도의 1차·2차에 비례하는 저항","domain":"newtonian-mechanics"},
    {"id":"aperi21:buoyant-force-as-force","title":"부력(힘으로서)","description":"유체가 위로 미는 힘","domain":"newtonian-mechanics"},
    {"id":"aperi21:non-inertial-frame","title":"비관성계","description":"가속하는 기준틀에서의 운동","domain":"newtonian-mechanics"},
    {"id":"aperi21:fictitious-force","title":"관성력","description":"비관성계에서 도입하는 겉보기 힘","domain":"newtonian-mechanics"},
    {"id":"aperi21:coriolis-effect","title":"코리올리 효과","description":"회전 기준틀에서 휘는 경로","domain":"newtonian-mechanics"},
    {"id":"aperi21:impulse-force-relation","title":"힘과 충격량","description":"짧고 큰 힘과 길고 작은 힘","domain":"newtonian-mechanics"},
    {"id":"aperi21:equilibrium-of-forces","title":"힘의 평형","description":"알짜힘이 0인 상태","domain":"newtonian-mechanics"},
    {"id":"aperi21:atwood-machine","title":"애트우드 기계","description":"두 추가 도르래로 연결된 계","domain":"newtonian-mechanics"},
    {"id":"aperi21:balance-scale","title":"수평잡기","description":"양팔의 길이와 무게가 함께 정하는 균형","domain":"newtonian-mechanics"},
    {"id":"aperi21:mechanical-advantage","title":"힘의 이득","description":"지레와 빗면이 힘을 줄이는 대신 더 먼 거리를 밀게 하는 맞바꿈","domain":"newtonian-mechanics"},
    {"id":"aperi21:youngs-modulus","title":"영률","description":"한 가닥이 아니라 재료에 속하는 뻣뻣함","domain":"newtonian-mechanics"},
    {"id":"aperi21:stress-strain-curve","title":"응력-변형률 곡선","description":"당길수록 달라지는 재료의 반응","domain":"newtonian-mechanics"},
    {"id":"aperi21:work-by-variable-force","title":"변하는 힘이 한 일","description":"힘-변위 그래프의 넓이","domain":"energy-momentum"},
    {"id":"aperi21:kinetic-energy","title":"운동 에너지","description":"속력이 담고 있는 에너지","domain":"energy-momentum"},
    {"id":"aperi21:work-energy-theorem","title":"일-운동 에너지 정리","description":"힘과 거리를 어떻게 나누든 해 준 일이 같으면 끝 속력도 같음","domain":"energy-momentum"},
    {"id":"aperi21:gravitational-potential-energy","title":"중력 퍼텐셜 에너지","description":"높이에 저장된 에너지","domain":"energy-momentum"},
    {"id":"aperi21:elastic-potential-energy","title":"탄성 퍼텐셜 에너지","description":"변형에 저장된 에너지","domain":"energy-momentum"},
    {"id":"aperi21:conservative-force","title":"보존력","description":"어느 길로 가든 한 일이 같은 힘","domain":"energy-momentum"},
    {"id":"aperi21:non-conservative-force","title":"비보존력","description":"경로에 따라 달라지는 일","domain":"energy-momentum"},
    {"id":"aperi21:conservation-of-mechanical-energy","title":"역학적 에너지 보존","description":"위치에 담긴 몫과 운동에 담긴 몫이 자리를 바꾸는 동안 둘의 합이 그대로임","domain":"energy-momentum"},
    {"id":"aperi21:energy-dissipation","title":"에너지 소산","description":"마찰이 가져가는 몫과 그 행방","domain":"energy-momentum"},
    {"id":"aperi21:potential-energy-curve","title":"퍼텐셜 곡선","description":"곡선의 모양이 운동을 정하는 방식","domain":"energy-momentum"},
    {"id":"aperi21:equilibrium-points","title":"평형점","description":"안정·불안정·중립 평형","domain":"energy-momentum"},
    {"id":"aperi21:efficiency","title":"효율","description":"넣은 것 가운데 쓸모로 나오는 몫","domain":"energy-momentum"},
    {"id":"aperi21:impulse-momentum-theorem","title":"충격량-운동량 정리","description":"충격량이 운동량 변화와 같음","domain":"energy-momentum"},
    {"id":"aperi21:conservation-of-momentum","title":"운동량 보존","description":"외력이 없을 때의 총 운동량","domain":"energy-momentum"},
    {"id":"aperi21:elastic-collision","title":"탄성 충돌","description":"부딪치면 빠르기를 서로 주고받는 충돌","domain":"energy-momentum"},
    {"id":"aperi21:inelastic-collision","title":"비탄성 충돌","description":"되돌려 받지 못하는 몫이 생기는 충돌","domain":"energy-momentum"},
    {"id":"aperi21:perfectly-inelastic-collision","title":"완전 비탄성 충돌","description":"붙어서 함께 움직이는 경우","domain":"energy-momentum"},
    {"id":"aperi21:two-dimensional-collision","title":"2차원 충돌","description":"성분마다 따로 성립하는 보존","domain":"energy-momentum"},
    {"id":"aperi21:center-of-mass-motion","title":"질량 중심의 운동","description":"내부 힘에 영향받지 않는 운동","domain":"energy-momentum"},
    {"id":"aperi21:explosion-and-recoil","title":"폭발과 반동","description":"정지한 계가 갈라질 때","domain":"energy-momentum"},
    {"id":"aperi21:rocket-equation","title":"로켓 방정식","description":"연료를 버려 얻는 속도","domain":"energy-momentum"},
    {"id":"aperi21:ballistic-pendulum","title":"탄동 진자","description":"충돌과 에너지 보존을 잇는 측정","domain":"energy-momentum"},
    {"id":"aperi21:energy-in-collision","title":"충돌에서의 에너지","description":"보존되는 것과 안 되는 것의 구분","domain":"energy-momentum"},
    {"id":"aperi21:energy-flow-diagram","title":"에너지 흐름도","description":"갈래의 굵기로 나타낸 에너지의 행방","domain":"energy-momentum"},
    {"id":"aperi21:torque","title":"돌림힘","description":"회전을 일으키는 양과 팔 길이","domain":"rotation-oscillation"},
    {"id":"aperi21:moment-of-inertia","title":"관성 모멘트","description":"질량 분포가 정하는 회전 저항","domain":"rotation-oscillation"},
    {"id":"aperi21:parallel-axis-theorem","title":"평행축 정리","description":"축을 옮길 때의 관성 모멘트","domain":"rotation-oscillation"},
    {"id":"aperi21:rotational-kinetic-energy","title":"회전 운동 에너지","description":"각속도가 담은 에너지","domain":"rotation-oscillation"},
    {"id":"aperi21:angular-momentum","title":"각운동량","description":"돌고 있는 것이 축을 지키게 하는 양","domain":"rotation-oscillation"},
    {"id":"aperi21:conservation-of-angular-momentum","title":"각운동량 보존","description":"팔을 오므리면 빨라지는 이유","domain":"rotation-oscillation"},
    {"id":"aperi21:rolling-without-slipping","title":"미끄러지지 않는 구름","description":"병진과 회전의 구속 조건","domain":"rotation-oscillation"},
    {"id":"aperi21:rolling-race","title":"구르는 물체의 경주","description":"질량 분포가 정하는 도착 순서","domain":"rotation-oscillation"},
    {"id":"aperi21:static-equilibrium","title":"정적 평형","description":"힘과 돌림힘이 모두 0","domain":"rotation-oscillation"},
    {"id":"aperi21:center-of-gravity","title":"무게 중심","description":"넘어지는 조건을 정하는 점","domain":"rotation-oscillation"},
    {"id":"aperi21:gyroscopic-precession","title":"세차 운동","description":"돌림힘이 각운동량 방향을 돌리는 것","domain":"rotation-oscillation"},
    {"id":"aperi21:angular-momentum-vector","title":"각운동량의 방향","description":"오른손 규칙과 회전축","domain":"rotation-oscillation"},
    {"id":"aperi21:simple-harmonic-motion","title":"단순 조화 운동","description":"복원력이 변위에 비례하는 운동","domain":"rotation-oscillation"},
    {"id":"aperi21:shm-energy","title":"조화 운동의 에너지","description":"운동 에너지와 퍼텐셜의 교환","domain":"rotation-oscillation"},
    {"id":"aperi21:mass-spring-system","title":"용수철 진자","description":"질량과 탄성 계수가 정하는 주기","domain":"rotation-oscillation"},
    {"id":"aperi21:simple-pendulum","title":"단진자","description":"작은 진폭에서의 주기","domain":"rotation-oscillation"},
    {"id":"aperi21:physical-pendulum","title":"물리 진자","description":"크기가 있는 물체의 진동","domain":"rotation-oscillation"},
    {"id":"aperi21:pendulum-amplitude-dependence","title":"진폭과 주기","description":"큰 진폭에서 깨지는 등시성","domain":"rotation-oscillation"},
    {"id":"aperi21:damped-oscillation","title":"감쇠 진동","description":"에너지가 빠져나가는 진동","domain":"rotation-oscillation"},
    {"id":"aperi21:damping-regimes","title":"감쇠의 세 양상","description":"부족·임계·과도 감쇠","domain":"rotation-oscillation"},
    {"id":"aperi21:driven-oscillation","title":"강제 진동","description":"외부 구동에 대한 응답","domain":"rotation-oscillation"},
    {"id":"aperi21:resonance","title":"공명","description":"구동 진동수가 고유 진동수에 맞을 때","domain":"rotation-oscillation"},
    {"id":"aperi21:quality-factor","title":"Q 인자","description":"공명이 날카로울수록 오래 울린다","domain":"rotation-oscillation"},
    {"id":"aperi21:coupled-oscillators","title":"결합 진동자","description":"에너지가 오가는 두 진동자","domain":"rotation-oscillation"},
    {"id":"aperi21:normal-modes","title":"정규 모드","description":"계가 가진 고유 진동 형태","domain":"rotation-oscillation"},
    {"id":"aperi21:beats-in-oscillation","title":"진동의 맥놀이","description":"가까운 두 진동수의 합","domain":"rotation-oscillation"},
    {"id":"aperi21:phase-space","title":"위상 공간","description":"위치-속도 평면에서 본 운동","domain":"rotation-oscillation"},
    {"id":"aperi21:nonlinear-oscillation","title":"비선형 진동","description":"복원력이 비례를 벗어날 때","domain":"rotation-oscillation"},
    {"id":"aperi21:gears","title":"기어","description":"톱니 수가 맞바꾸는 회전 빠르기와 돌림힘","domain":"rotation-oscillation"},
    {"id":"aperi21:newtons-law-of-gravitation","title":"만유인력 법칙","description":"거리 제곱에 반비례하는 힘","domain":"gravitation"},
    {"id":"aperi21:gravitational-field","title":"중력장","description":"공간에 분포한 중력의 세기","domain":"gravitation"},
    {"id":"aperi21:range-and-surface-gravity","title":"중력과 사거리","description":"같은 발사가 중력이 약한 곳에서 더 멀리 가는 것","domain":"gravitation"},
    {"id":"aperi21:shell-theorem","title":"껍질 정리","description":"구 껍질 안팎에서의 중력","domain":"gravitation"},
    {"id":"aperi21:gravity-inside-earth","title":"지구 내부의 중력","description":"깊이에 따라 줄어드는 중력","domain":"gravitation"},
    {"id":"aperi21:gravitational-potential-energy-general","title":"중력 퍼텐셜 에너지(일반)","description":"무한대를 기준으로 한 음의 에너지","domain":"gravitation"},
    {"id":"aperi21:escape-velocity","title":"탈출 속도","description":"중력을 벗어나는 최소 속도","domain":"gravitation"},
    {"id":"aperi21:orbital-velocity","title":"궤도 속도","description":"원 궤도를 유지하는 속도","domain":"gravitation"},
    {"id":"aperi21:circular-orbit","title":"원 궤도","description":"구심력이 중력인 운동","domain":"gravitation"},
    {"id":"aperi21:elliptical-orbit","title":"타원 궤도","description":"초점에 놓인 중심 천체","domain":"gravitation"},
    {"id":"aperi21:keplers-first-law","title":"케플러 제1법칙","description":"태양이 한 초점에 놓인 타원 궤도","domain":"gravitation"},
    {"id":"aperi21:keplers-second-law","title":"케플러 제2법칙","description":"같은 시간에 같은 넓이","domain":"gravitation"},
    {"id":"aperi21:keplers-third-law","title":"케플러 제3법칙","description":"반지름보다 훨씬 빨리 길어지는 한 바퀴 시간","domain":"gravitation"},
    {"id":"aperi21:two-body-problem","title":"이체 문제","description":"질량 중심 둘레를 도는 두 천체","domain":"gravitation"},
    {"id":"aperi21:tidal-force","title":"조석력","description":"중력의 차이가 만드는 늘어남","domain":"gravitation"},
    {"id":"aperi21:roche-limit","title":"로슈 한계","description":"조석력이 천체를 부수는 거리","domain":"gravitation"},
    {"id":"aperi21:weightlessness","title":"무중력","description":"자유 낙하 중의 겉보기 무게","domain":"gravitation"},
    {"id":"aperi21:geostationary-orbit","title":"정지 궤도","description":"적도 위에서 지구 자전과 같은 주기로 도는 궤도","domain":"gravitation"},
    {"id":"aperi21:gravitational-slingshot","title":"중력 도움","description":"천체를 이용한 속도 변화","domain":"gravitation"},
    {"id":"aperi21:lagrange-points","title":"라그랑주 점","description":"함께 도는 두 천체와 보조를 맞추는 다섯 자리","domain":"gravitation"},
    {"id":"aperi21:orbital-transfer","title":"궤도 전이","description":"낮은 궤도에서 높은 궤도로 옮기는 호만 전이","domain":"gravitation"},
    {"id":"aperi21:black-hole-horizon","title":"사건 지평선","description":"탈출 속도가 광속이 되는 반지름","domain":"gravitation"},
    {"id":"aperi21:diurnal-motion","title":"일주 운동","description":"하루 동안 밤하늘 전체가 한 점을 두고 도는 길","domain":"gravitation"},
    {"id":"aperi21:earth-rotation-day-night","title":"자전과 낮과 밤","description":"도는 지구 위에서 낮과 밤이 갈리는 이유","domain":"gravitation"},
    {"id":"aperi21:earth-revolution-constellations","title":"공전과 별자리","description":"계절마다 보이는 별자리가 달라지는 이유","domain":"gravitation"},
    {"id":"aperi21:solar-altitude-shadow","title":"태양 고도와 그림자","description":"고도가 바뀌면 그림자 길이와 햇빛이 퍼지는 넓이가 함께 바뀐다","domain":"gravitation"},
    {"id":"aperi21:seasonal-sun-path","title":"계절과 태양의 길","description":"남중 고도와 낮 길이가 함께 달라지는 것","domain":"gravitation"},
    {"id":"aperi21:axial-tilt-seasons","title":"자전축 기울기와 계절","description":"기울어진 채 도는 것이 만드는 계절","domain":"gravitation"},
    {"id":"aperi21:moon-phases","title":"달의 위상","description":"햇빛을 받는 달의 어느 쪽을 보는가","domain":"gravitation"},
    {"id":"aperi21:eclipse","title":"일식과 월식","description":"해와 지구와 달이 한 줄에 설 때","domain":"gravitation"},
    {"id":"aperi21:stellar-parallax","title":"연주시차","description":"지구가 공전하며 가까운 별이 어긋나 보이는 각","domain":"gravitation"},
    {"id":"aperi21:apparent-brightness","title":"겉보기 밝기","description":"같은 별도 거리에 따라 다르게 밝아 보이는 것","domain":"gravitation"},
    {"id":"aperi21:magnitude-scale","title":"별의 등급","description":"밝기를 등급으로 나타내는 방식","domain":"gravitation"},
    {"id":"aperi21:star-color-temperature","title":"별의 색과 표면 온도","description":"표면 온도가 정하는 별빛의 색","domain":"gravitation"},
    {"id":"aperi21:expanding-universe","title":"우주의 팽창","description":"모든 방향으로 멀어지는 은하들","domain":"gravitation"},
    {"id":"aperi21:stellar-luminosity","title":"광도","description":"별이 실제로 내는 빛의 양","domain":"gravitation"},
    {"id":"aperi21:hr-diagram","title":"HR 도","description":"나이 들수록 무거운 별부터 주계열을 떠나는 성단의 온도-광도 그림","domain":"gravitation"},
    {"id":"aperi21:star-radiation-gravity-balance","title":"압력과 중력의 평형","description":"별이 무너지지도 흩어지지도 않는 이유","domain":"gravitation"},
    {"id":"aperi21:orbital-decay","title":"궤도 감쇠","description":"옅은 대기가 끄는 궤도","domain":"gravitation"},
    {"id":"aperi21:inverse-square-law","title":"역제곱 법칙","description":"퍼지는 만큼 옅어지는 것","domain":"gravitation"},
    {"id":"aperi21:stellar-nucleosynthesis","title":"별의 원소 합성","description":"별 중심의 핵융합이 철까지 차례로 무거운 원소를 쌓는 것","domain":"gravitation"},
    {"id":"aperi21:star-life-cycle","title":"별의 일생","description":"질량이 가르는 별의 경로","domain":"gravitation"},
    {"id":"aperi21:stellar-spectral-class","title":"별의 스펙트럼 분류","description":"온도가 정하는 흡수선 무늬","domain":"gravitation"},
    {"id":"aperi21:supernova-and-neutron-star","title":"초신성과 중성자별","description":"무너지고 튕겨 나가는 최후","domain":"gravitation"},
    {"id":"aperi21:exoplanet-detection","title":"외계행성 탐지","description":"행성이 남기는 흔적","domain":"gravitation"},
    {"id":"aperi21:projectile-in-wind","title":"바람과 사거리","description":"같은 발사라도 바람이 착지점을 옮기는 것","domain":"fluids"},
    {"id":"aperi21:pressure-isotropy","title":"압력의 등방성","description":"방향에 무관하게 같은 크기","domain":"fluids"},
    {"id":"aperi21:hydrostatic-pressure","title":"정수압","description":"깊이에 비례하는 압력","domain":"fluids"},
    {"id":"aperi21:pressure-and-container-shape","title":"그릇 모양과 바닥 압력","description":"바닥 압력이 모양에 무관한 것","domain":"fluids"},
    {"id":"aperi21:atmospheric-pressure","title":"대기압","description":"공기 기둥의 무게","domain":"fluids"},
    {"id":"aperi21:barometer","title":"기압계","description":"수은 기둥의 높이","domain":"fluids"},
    {"id":"aperi21:manometer","title":"압력계","description":"액주 차이로 재는 압력","domain":"fluids"},
    {"id":"aperi21:pascals-principle","title":"파스칼 원리","description":"압력의 전달과 유압 장치","domain":"fluids"},
    {"id":"aperi21:buoyancy","title":"부력","description":"아랫면이 더 세게 밀리는 만큼 남는 위쪽 힘","domain":"fluids"},
    {"id":"aperi21:archimedes-principle","title":"아르키메데스 원리 — 부력의 크기","description":"받는 힘은 밀려난 유체의 무게와 같다","domain":"fluids"},
    {"id":"aperi21:floating-and-draft","title":"뜨는 깊이","description":"잠기는 부피가 정해지는 방식","domain":"fluids"},
    {"id":"aperi21:stability-of-floating-body","title":"부유체의 안정","description":"무게 중심과 부심의 관계","domain":"fluids"},
    {"id":"aperi21:continuity-equation","title":"연속 방정식","description":"단면적과 유속의 반비례","domain":"fluids"},
    {"id":"aperi21:bernoullis-principle","title":"베르누이 원리","description":"속도와 압력의 교환","domain":"fluids"},
    {"id":"aperi21:venturi-effect","title":"벤투리 효과","description":"좁아진 곳에서 낮아지는 압력","domain":"fluids"},
    {"id":"aperi21:torricellis-law","title":"토리첼리 법칙","description":"구멍에서 나오는 유속","domain":"fluids"},
    {"id":"aperi21:lift-force","title":"양력","description":"날개 위아래의 흐름 차이","domain":"fluids"},
    {"id":"aperi21:viscosity","title":"점성","description":"층 사이의 마찰","domain":"fluids"},
    {"id":"aperi21:poiseuille-flow","title":"관 속의 층류","description":"반지름 4제곱에 비례하는 유량","domain":"fluids"},
    {"id":"aperi21:stokes-drag","title":"스토크스 항력","description":"느린 흐름에서 반지름이 두 배면 네 배 빨리 가라앉는 구","domain":"fluids"},
    {"id":"aperi21:laminar-vs-turbulent","title":"층류와 난류","description":"흐름의 두 양상","domain":"fluids"},
    {"id":"aperi21:reynolds-number","title":"레이놀즈 수","description":"흐름의 결을 정하는 무차원 수","domain":"fluids"},
    {"id":"aperi21:boundary-layer","title":"경계층","description":"벽의 0에서 바깥 흐름 속력까지 회복하는 얇은 층","domain":"fluids"},
    {"id":"aperi21:surface-tension","title":"표면 장력","description":"방향을 돌려 짐을 받치는 수면의 당김","domain":"fluids"},
    {"id":"aperi21:laplace-pressure","title":"라플라스 압력","description":"곡률이 만드는 안팎 압력차","domain":"fluids"},
    {"id":"aperi21:capillary-action","title":"모세관 현상","description":"좁은 관에서의 상승과 하강","domain":"fluids"},
    {"id":"aperi21:wetting-and-contact-angle","title":"젖음과 접촉각","description":"액체가 고체 위에 퍼지는 정도","domain":"fluids"},
    {"id":"aperi21:drag-in-fluid","title":"유체 속 항력","description":"빠른 흐름에서 뒤 모양이 정하는 저항","domain":"fluids"},
    {"id":"aperi21:thermal-equilibrium","title":"열평형","description":"접촉한 두 계가 도달하는 상태","domain":"thermodynamics"},
    {"id":"aperi21:specific-heat","title":"비열","description":"물질마다 다른 온도 변화","domain":"thermodynamics"},
    {"id":"aperi21:calorimetry","title":"열량 측정","description":"섞었을 때의 최종 온도","domain":"thermodynamics"},
    {"id":"aperi21:latent-heat","title":"잠열","description":"상변화 중 온도가 멈추는 이유","domain":"thermodynamics"},
    {"id":"aperi21:phase-diagram","title":"상평형 그림","description":"압력과 온도가 정하는 상","domain":"thermodynamics"},
    {"id":"aperi21:triple-point","title":"삼중점","description":"세 상이 공존하는 조건","domain":"thermodynamics"},
    {"id":"aperi21:thermal-conduction","title":"열전도","description":"쇠에서는 빨리, 나무에서는 느리게 물질을 타고 번지는 열","domain":"thermodynamics"},
    {"id":"aperi21:thermal-convection","title":"대류","description":"유체의 이동이 나르는 열","domain":"thermodynamics"},
    {"id":"aperi21:thermal-radiation","title":"열복사","description":"매질 없이 전달되는 열","domain":"thermodynamics"},
    {"id":"aperi21:stefan-boltzmann-law","title":"슈테판-볼츠만 법칙","description":"온도 4제곱에 비례하는 복사","domain":"thermodynamics"},
    {"id":"aperi21:thermal-expansion","title":"열팽창","description":"온도에 따른 고체의 길이 변화","domain":"thermodynamics"},
    {"id":"aperi21:bimetal","title":"바이메탈","description":"팽창률 차이가 만드는 휨","domain":"thermodynamics"},
    {"id":"aperi21:ideal-gas-law","title":"이상 기체 법칙","description":"압력·부피·온도의 관계","domain":"thermodynamics"},
    {"id":"aperi21:boyles-law","title":"보일 법칙","description":"온도가 일정할 때의 압력-부피","domain":"thermodynamics"},
    {"id":"aperi21:charles-law","title":"샤를 법칙","description":"압력이 일정할 때의 부피-온도","domain":"thermodynamics"},
    {"id":"aperi21:gas-pressure","title":"기체 분자와 압력","description":"온도를 올리면 분자가 벽을 더 자주 더 세게 때려 압력이 오르는 것","domain":"thermodynamics"},
    {"id":"aperi21:pressure-from-collisions","title":"충돌이 만드는 압력","description":"더 세게, 더 자주 — 분자 속력의 제곱으로 커지는 벽의 압력","domain":"thermodynamics"},
    {"id":"aperi21:maxwell-boltzmann-distribution","title":"맥스웰-볼츠만 분포","description":"분자 속력의 분포","domain":"thermodynamics"},
    {"id":"aperi21:mean-free-path","title":"평균 자유 행로","description":"충돌과 충돌 사이의 거리","domain":"thermodynamics"},
    {"id":"aperi21:first-law-of-thermodynamics","title":"열역학 제1법칙","description":"내부 에너지·일·열의 관계","domain":"thermodynamics"},
    {"id":"aperi21:pv-diagram","title":"PV 그림","description":"넓이가 일인 표현","domain":"thermodynamics"},
    {"id":"aperi21:isothermal-process","title":"등온 과정","description":"온도를 유지하는 변화","domain":"thermodynamics"},
    {"id":"aperi21:adiabatic-process","title":"단열 과정","description":"열 출입이 없는 변화","domain":"thermodynamics"},
    {"id":"aperi21:isobaric-isochoric","title":"등압·등적 과정","description":"압력 또는 부피를 고정한 변화","domain":"thermodynamics"},
    {"id":"aperi21:cyclic-process","title":"순환 과정","description":"제자리로 돌아오는 변화","domain":"thermodynamics"},
    {"id":"aperi21:second-law-of-thermodynamics","title":"열역학 제2법칙","description":"방향이 있는 변화","domain":"thermodynamics"},
    {"id":"aperi21:irreversibility","title":"엔트로피와 비가역성","description":"되돌릴 수 없는 이유","domain":"thermodynamics"},
    {"id":"aperi21:heat-engine","title":"열기관","description":"받은 열의 일부만 일로 바꾸고 나머지는 찬 쪽에 버리는 순환","domain":"thermodynamics"},
    {"id":"aperi21:carnot-cycle","title":"카르노 순환","description":"이론적 최대 효율","domain":"thermodynamics"},
    {"id":"aperi21:refrigerator-heat-pump","title":"냉장고와 열펌프","description":"일을 넣어 열을 옮기는 것","domain":"thermodynamics"},
    {"id":"aperi21:brownian-motion","title":"브라운 운동","description":"분자 충돌이 만드는 무작위 운동","domain":"thermodynamics"},
    {"id":"aperi21:diffusion","title":"확산","description":"농도 차이가 만드는 흐름","domain":"thermodynamics"},
    {"id":"aperi21:random-walk","title":"무작위 걸음","description":"걸음 수의 제곱근으로만 느는, 처음 자리에서 퍼진 폭","domain":"thermodynamics"},
    {"id":"aperi21:statistical-fluctuation","title":"요동","description":"입자 수가 적을 때 커지는 흔들림","domain":"thermodynamics"},
    {"id":"aperi21:maxwells-demon","title":"맥스웰의 도깨비","description":"살펴본 만큼 갈라지는 기체","domain":"thermodynamics"},
    {"id":"aperi21:insulation","title":"보온과 단열","description":"열의 이동을 늦추는 것","domain":"thermodynamics"},
    {"id":"aperi21:albedo","title":"반사율","description":"되돌아가는 빛의 몫","domain":"thermodynamics"},
    {"id":"aperi21:radiative-equilibrium","title":"복사 평형","description":"들어온 만큼 내보낼 때 정해지는 온도","domain":"thermodynamics"},
    {"id":"aperi21:greenhouse-effect","title":"온실 효과","description":"적외선을 되돌리는 층이 지표를 덥히는 것","domain":"thermodynamics"},
    {"id":"aperi21:wave-basics","title":"파동의 기본량","description":"파장·진동수·속력·진폭","domain":"waves-acoustics"},
    {"id":"aperi21:wave-vs-particle-transport","title":"파동이 나르는 것","description":"매질은 제자리, 에너지는 이동","domain":"waves-acoustics"},
    {"id":"aperi21:transverse-wave","title":"횡파","description":"진동 방향이 진행 방향과 수직","domain":"waves-acoustics"},
    {"id":"aperi21:longitudinal-wave","title":"종파","description":"진동 방향이 진행 방향과 나란함","domain":"waves-acoustics"},
    {"id":"aperi21:wave-speed-in-medium","title":"매질과 파동 속도","description":"장력과 선밀도가 정하는 속도","domain":"waves-acoustics"},
    {"id":"aperi21:wavefront-and-ray","title":"파면과 광선","description":"같은 위상의 면과 그 수직선","domain":"waves-acoustics"},
    {"id":"aperi21:huygens-principle","title":"하위헌스 원리","description":"파면의 각 점이 새 파원이 되는 것","domain":"waves-acoustics"},
    {"id":"aperi21:superposition","title":"중첩 원리","description":"파동이 겹칠 때의 합","domain":"waves-acoustics"},
    {"id":"aperi21:constructive-destructive","title":"보강과 상쇄","description":"위상차가 정하는 합의 크기","domain":"waves-acoustics"},
    {"id":"aperi21:interference","title":"간섭","description":"두 파원이 만드는 무늬","domain":"waves-acoustics"},
    {"id":"aperi21:standing-wave","title":"정상파","description":"마디와 배가 고정되는 파동","domain":"waves-acoustics"},
    {"id":"aperi21:harmonics","title":"배음","description":"경계 조건이 정하는 진동수","domain":"waves-acoustics"},
    {"id":"aperi21:string-vibration","title":"줄의 진동","description":"흔들리는 길이가 정하는 음높이","domain":"waves-acoustics"},
    {"id":"aperi21:air-column-resonance","title":"기주 공명","description":"열린 관과 닫힌 관의 차이","domain":"waves-acoustics"},
    {"id":"aperi21:beats","title":"맥놀이","description":"가까운 두 진동수의 합","domain":"waves-acoustics"},
    {"id":"aperi21:doppler-effect","title":"도플러 효과","description":"움직이는 원천이 앞뒤 파면 간격을 갈라 놓는 것","domain":"waves-acoustics"},
    {"id":"aperi21:doppler-source-vs-observer","title":"음원과 관찰자","description":"누가 움직이냐에 따른 비대칭","domain":"waves-acoustics"},
    {"id":"aperi21:shock-wave","title":"충격파","description":"음속을 넘을 때 생기는 원뿔","domain":"waves-acoustics"},
    {"id":"aperi21:sound-intensity","title":"음의 세기","description":"거리 제곱에 반비례해 꺼지는 세기와 조금씩만 낮아지는 데시벨","domain":"waves-acoustics"},
    {"id":"aperi21:reflection-of-waves","title":"파동의 반사","description":"고정단과 자유단에서의 위상","domain":"waves-acoustics"},
    {"id":"aperi21:refraction-of-waves","title":"파동의 굴절","description":"속도 변화가 만드는 방향 전환","domain":"waves-acoustics"},
    {"id":"aperi21:diffraction","title":"회절","description":"장애물을 돌아가는 파동","domain":"waves-acoustics"},
    {"id":"aperi21:slit-width-and-diffraction","title":"슬릿 폭과 회절","description":"파장과 폭의 비가 정하는 퍼짐","domain":"waves-acoustics"},
    {"id":"aperi21:wave-energy","title":"파동의 에너지","description":"진폭 제곱에 비례하는 에너지","domain":"waves-acoustics"},
    {"id":"aperi21:wave-attenuation","title":"파동의 감쇠","description":"같은 거리마다 같은 비율로 낮아지는 진폭","domain":"waves-acoustics"},
    {"id":"aperi21:impedance-mismatch","title":"임피던스 부정합","description":"경계에서 반사되는 비율","domain":"waves-acoustics"},
    {"id":"aperi21:noise-cancellation","title":"능동 소음 제거","description":"역위상 파동의 중첩","domain":"waves-acoustics"},
    {"id":"aperi21:sound-source-vibration","title":"소리와 떨림","description":"소리 나는 물체는 떨리고, 떨림이 멎으면 소리도 멎는다","domain":"waves-acoustics"},
    {"id":"aperi21:sound-through-materials","title":"물질을 통한 소리 전달","description":"매질이 정하는 소리의 빠르기와 건너감","domain":"waves-acoustics"},
    {"id":"aperi21:digital-vs-analog-signal","title":"디지털 신호와 아날로그","description":"잡음을 견디는 방식의 차이","domain":"waves-acoustics"},
    {"id":"aperi21:seismic-waves","title":"지진파","description":"액체 외핵이 S파를 막고 P파를 꺾어 만드는 그림자대","domain":"waves-acoustics"},
    {"id":"aperi21:rectilinear-propagation","title":"빛의 직진","description":"그림자와 광선 모형","domain":"optics"},
    {"id":"aperi21:shadow-umbra-penumbra","title":"본그림자와 반그림자","description":"광원의 크기가 만드는 경계","domain":"optics"},
    {"id":"aperi21:pinhole-camera","title":"바늘구멍 사진기","description":"구멍 하나가 만드는 상","domain":"optics"},
    {"id":"aperi21:law-of-reflection","title":"반사 법칙","description":"입사각과 반사각","domain":"optics"},
    {"id":"aperi21:specular-diffuse-reflection","title":"정반사와 난반사","description":"표면 거칠기가 정하는 반사","domain":"optics"},
    {"id":"aperi21:plane-mirror-image","title":"평면거울의 상","description":"되짚은 빛이 만나는 거울 뒤의 허상","domain":"optics"},
    {"id":"aperi21:multiple-mirror-images","title":"두 거울의 상","description":"각도가 정하는 상의 개수","domain":"optics"},
    {"id":"aperi21:concave-mirror","title":"오목거울","description":"물체가 초점 밖이면 실상, 안이면 허상","domain":"optics"},
    {"id":"aperi21:convex-mirror","title":"볼록거울","description":"넓은 시야와 작고 바로 선 허상","domain":"optics"},
    {"id":"aperi21:snells-law","title":"굴절 법칙","description":"매질에 따른 경로 꺾임","domain":"optics"},
    {"id":"aperi21:apparent-depth","title":"겉보기 깊이","description":"물속 물체가 떠 보이는 이유","domain":"optics"},
    {"id":"aperi21:total-internal-reflection","title":"전반사","description":"임계각과 그 조건","domain":"optics"},
    {"id":"aperi21:optical-fiber","title":"광섬유","description":"전반사로 가두는 빛","domain":"optics"},
    {"id":"aperi21:mirage","title":"신기루","description":"밀도 기울기가 휘게 하는 빛","domain":"optics"},
    {"id":"aperi21:dispersion","title":"분산","description":"파장에 따른 굴절률 차이","domain":"optics"},
    {"id":"aperi21:prism","title":"프리즘","description":"분산으로 나뉘는 스펙트럼","domain":"optics"},
    {"id":"aperi21:rainbow","title":"무지개","description":"물방울 속 굴절과 반사","domain":"optics"},
    {"id":"aperi21:thin-lens","title":"얇은 렌즈","description":"초점과 결상","domain":"optics"},
    {"id":"aperi21:converging-diverging-lens","title":"볼록 렌즈와 오목 렌즈","description":"모으는 렌즈와 퍼뜨리는 렌즈","domain":"optics"},
    {"id":"aperi21:magnification","title":"배율","description":"상의 크기와 물체의 크기","domain":"optics"},
    {"id":"aperi21:focal-length","title":"초점 거리","description":"초점 거리가 상이 맺히는 자리를 정하는 것","domain":"optics"},
    {"id":"aperi21:real-vs-virtual-image","title":"실상과 허상","description":"빛이 실제로 모이는가","domain":"optics"},
    {"id":"aperi21:lens-combination","title":"렌즈의 조합","description":"두 렌즈가 만드는 합성 초점","domain":"optics"},
    {"id":"aperi21:spherical-aberration","title":"구면 수차","description":"가장자리 광선이 다른 곳에 모임","domain":"optics"},
    {"id":"aperi21:chromatic-aberration","title":"색수차","description":"파장마다 다른 초점","domain":"optics"},
    {"id":"aperi21:human-eye-accommodation","title":"눈의 조절","description":"수정체가 초점을 맞추는 방식","domain":"optics"},
    {"id":"aperi21:myopia-hyperopia","title":"근시와 원시","description":"상이 맺히는 위치와 교정","domain":"optics"},
    {"id":"aperi21:magnifying-glass","title":"돋보기","description":"초점 안의 물체가 크고 바로 선 허상으로 보이는 것","domain":"optics"},
    {"id":"aperi21:microscope","title":"현미경","description":"대물과 접안의 배율 곱","domain":"optics"},
    {"id":"aperi21:telescope","title":"망원경","description":"초점 거리 비가 정하는 배율","domain":"optics"},
    {"id":"aperi21:youngs-double-slit","title":"이중 슬릿 간섭","description":"빛의 파동성 증거","domain":"optics"},
    {"id":"aperi21:single-slit-diffraction","title":"단일 슬릿 회절","description":"틈이 좁을수록 넓어지는 가운데 밝은 띠","domain":"optics"},
    {"id":"aperi21:diffraction-grating","title":"회절 격자","description":"여러 슬릿이 만드는 날카로운 극대","domain":"optics"},
    {"id":"aperi21:thin-film-interference","title":"박막 간섭","description":"두께가 만드는 색","domain":"optics"},
    {"id":"aperi21:newtons-rings","title":"뉴턴 링","description":"곡면과 평면 사이의 간섭","domain":"optics"},
    {"id":"aperi21:resolving-power","title":"분해능","description":"두 점을 가르는 한계","domain":"optics"},
    {"id":"aperi21:polarization","title":"편광","description":"진동면의 선택","domain":"optics"},
    {"id":"aperi21:malus-law","title":"말뤼스 법칙","description":"편광판을 지난 세기","domain":"optics"},
    {"id":"aperi21:brewster-angle","title":"브루스터 각","description":"반사광이 완전 편광되는 각","domain":"optics"},
    {"id":"aperi21:birefringence","title":"복굴절","description":"떨림이 직각인 두 줄기로 갈라져 상이 두 겹으로 보이는 빛","domain":"optics"},
    {"id":"aperi21:scattering","title":"산란","description":"파란 하늘과 흰 구름을 가르는 입자 크기","domain":"optics"},
    {"id":"aperi21:rayleigh-scattering","title":"레일리 산란","description":"파장이 짧을수록 가파르게 느는 산란","domain":"optics"},
    {"id":"aperi21:seeing-requires-light","title":"보려면 빛이 있어야","description":"빛이 없으면 물체가 보이지 않는다","domain":"optics"},
    {"id":"aperi21:color-addition","title":"빛의 합성","description":"세 색의 빛이 겹쳐 만드는 색","domain":"optics"},
    {"id":"aperi21:object-color","title":"물체의 색","description":"물체가 되쏘는 빛이 정하는 색","domain":"optics"},
    {"id":"aperi21:light-through-materials","title":"빛과 재료","description":"재료에 따라 갈리는 빛의 통과","domain":"optics"},
    {"id":"aperi21:electric-charge","title":"전하","description":"두 종류뿐인 전하","domain":"electromagnetism"},
    {"id":"aperi21:charging-methods","title":"대전 방법","description":"마찰·접촉·유도","domain":"electromagnetism"},
    {"id":"aperi21:coulombs-law","title":"쿨롱 법칙","description":"벌린 배수의 제곱만큼 약해지는 전하 사이의 힘","domain":"electromagnetism"},
    {"id":"aperi21:superposition-of-forces","title":"전기력의 중첩","description":"여러 전하가 주는 힘의 합","domain":"electromagnetism"},
    {"id":"aperi21:electric-field","title":"전기장","description":"단위 전하가 받는 힘","domain":"electromagnetism"},
    {"id":"aperi21:field-lines","title":"전기력선","description":"장을 그리는 규약과 그 뜻","domain":"electromagnetism"},
    {"id":"aperi21:field-of-dipole","title":"쌍극자의 전기장","description":"가까운 두 반대 전하","domain":"electromagnetism"},
    {"id":"aperi21:uniform-field","title":"균일한 전기장","description":"평행판 사이의 장","domain":"electromagnetism"},
    {"id":"aperi21:charge-in-uniform-field","title":"균일장 속 전하","description":"포물선 운동과의 대응","domain":"electromagnetism"},
    {"id":"aperi21:gausss-law","title":"가우스 법칙","description":"닫힌 면을 지나는 전기력선속","domain":"electromagnetism"},
    {"id":"aperi21:field-of-charged-sphere","title":"대전된 구의 전기장","description":"안과 밖이 다른 이유","domain":"electromagnetism"},
    {"id":"aperi21:equipotential-surface","title":"등전위면","description":"전기장과 수직인 면","domain":"electromagnetism"},
    {"id":"aperi21:potential-vs-field","title":"전위와 전기장","description":"기울기 관계","domain":"electromagnetism"},
    {"id":"aperi21:electrostatic-shielding","title":"정전기 차폐","description":"도체 내부의 장이 0인 이유","domain":"electromagnetism"},
    {"id":"aperi21:charge-on-conductor-surface","title":"도체 표면의 전하","description":"뾰족한 곳에 몰리는 전하","domain":"electromagnetism"},
    {"id":"aperi21:dielectric","title":"유전체","description":"분극과 전기장의 약화","domain":"electromagnetism"},
    {"id":"aperi21:parallel-plate-capacitor","title":"평행판 축전기","description":"넓이·간격이 정하는 용량","domain":"electromagnetism"},
    {"id":"aperi21:capacitors-in-circuit","title":"축전기의 연결","description":"직렬과 병렬의 합성","domain":"electromagnetism"},
    {"id":"aperi21:energy-in-capacitor","title":"축전기의 에너지","description":"전하를 옮기는 데 든 일","domain":"electromagnetism"},
    {"id":"aperi21:electric-current","title":"전류","description":"전하의 흐름과 방향 규약","domain":"electromagnetism"},
    {"id":"aperi21:drift-velocity","title":"표류 속도","description":"도선 속 전자가 기어가는 속도","domain":"electromagnetism"},
    {"id":"aperi21:ohms-law","title":"옴 법칙","description":"전압·전류·저항","domain":"electromagnetism"},
    {"id":"aperi21:resistance-and-geometry","title":"저항과 형태","description":"길이와 단면적의 영향","domain":"electromagnetism"},
    {"id":"aperi21:temperature-and-resistance","title":"온도와 저항","description":"금속과 반도체의 반대 경향","domain":"electromagnetism"},
    {"id":"aperi21:series-parallel-resistors","title":"저항의 직렬과 병렬","description":"연결을 바꾸면 같은 전지가 내주는 전류가 달라지는 것","domain":"electromagnetism"},
    {"id":"aperi21:emf-and-internal-resistance","title":"기전력과 내부 저항","description":"단자 전압이 낮아지는 이유","domain":"electromagnetism"},
    {"id":"aperi21:kirchhoffs-current-law","title":"키르히호프 전류 법칙","description":"마디에서의 전하 보존","domain":"electromagnetism"},
    {"id":"aperi21:kirchhoffs-voltage-law","title":"키르히호프 전압 법칙","description":"고리에서의 에너지 보존","domain":"electromagnetism"},
    {"id":"aperi21:wheatstone-bridge","title":"휘트스톤 브리지","description":"평형으로 재는 저항","domain":"electromagnetism"},
    {"id":"aperi21:joule-heating","title":"줄 열","description":"저항이 만드는 열","domain":"electromagnetism"},
    {"id":"aperi21:rc-circuit","title":"RC 회로","description":"충전과 방전의 시간 상수","domain":"electromagnetism"},
    {"id":"aperi21:magnetic-field","title":"자기장","description":"자기력의 분포","domain":"electromagnetism"},
    {"id":"aperi21:magnetic-field-lines","title":"자기력선","description":"끊기지 않고 닫히는 선","domain":"electromagnetism"},
    {"id":"aperi21:lorentz-force","title":"로런츠 힘","description":"자기장 속에서 움직이는 전하가 받는 힘","domain":"electromagnetism"},
    {"id":"aperi21:charged-particle-in-magnetic-field","title":"자기장 속 전하의 원운동","description":"속력이 달라도 같은 한 바퀴 시간","domain":"electromagnetism"},
    {"id":"aperi21:velocity-selector","title":"속도 선택기","description":"전기력과 자기력의 균형","domain":"electromagnetism"},
    {"id":"aperi21:mass-spectrometer","title":"질량 분석기","description":"반지름으로 가르는 질량","domain":"electromagnetism"},
    {"id":"aperi21:force-on-current-wire","title":"전류가 받는 힘","description":"도선에 작용하는 자기력","domain":"electromagnetism"},
    {"id":"aperi21:biot-savart-law","title":"비오-사바르 법칙","description":"전류 요소가 만드는 자기장","domain":"electromagnetism"},
    {"id":"aperi21:field-of-straight-wire","title":"전류가 만드는 자기장","description":"거리가 멀수록 주는 세기","domain":"electromagnetism"},
    {"id":"aperi21:field-of-loop-and-solenoid","title":"고리와 솔레노이드","description":"고리를 겹칠수록 안은 고르고 세지고 바깥은 약해지는 자기장","domain":"electromagnetism"},
    {"id":"aperi21:amperes-law","title":"앙페르 법칙","description":"전류와 자기장의 순환","domain":"electromagnetism"},
    {"id":"aperi21:force-between-wires","title":"도선 사이의 힘","description":"나란한 두 전류의 인력·척력","domain":"electromagnetism"},
    {"id":"aperi21:magnetic-dipole","title":"자기 쌍극자","description":"고리 전류와 자석의 동일성","domain":"electromagnetism"},
    {"id":"aperi21:magnetic-materials","title":"자성체","description":"강자성·상자성·반자성","domain":"electromagnetism"},
    {"id":"aperi21:faradays-law","title":"패러데이 법칙","description":"자속 변화가 만드는 기전력","domain":"electromagnetism"},
    {"id":"aperi21:lenzs-law","title":"렌츠 법칙","description":"변화를 방해하는 유도 전류","domain":"electromagnetism"},
    {"id":"aperi21:motional-emf","title":"운동 기전력","description":"도선이 움직여 생기는 전압","domain":"electromagnetism"},
    {"id":"aperi21:eddy-current","title":"맴돌이 전류","description":"덩어리 도체 속의 유도 전류","domain":"electromagnetism"},
    {"id":"aperi21:self-inductance","title":"자체 인덕턴스","description":"자기 전류가 바뀌면 그에 맞서는 전압을 내는 코일","domain":"electromagnetism"},
    {"id":"aperi21:mutual-inductance","title":"상호 인덕턴스","description":"이웃 회로에 유도되는 기전력","domain":"electromagnetism"},
    {"id":"aperi21:energy-in-inductor","title":"인덕터의 에너지","description":"자기장에 저장된 에너지","domain":"electromagnetism"},
    {"id":"aperi21:rl-circuit","title":"RL 회로","description":"전류가 서서히 오르는 이유","domain":"electromagnetism"},
    {"id":"aperi21:lc-oscillation","title":"LC 진동","description":"전기와 자기 에너지의 교환","domain":"electromagnetism"},
    {"id":"aperi21:ac-generation","title":"교류의 발생","description":"회전하는 코일과 사인파","domain":"electromagnetism"},
    {"id":"aperi21:reactance","title":"리액턴스와 임피던스","description":"진동수가 오르면 코일은 교류를 더 막고 축전기는 덜 막는 것","domain":"electromagnetism"},
    {"id":"aperi21:phase-in-ac-circuit","title":"교류의 위상차","description":"전압과 전류가 어긋나는 것","domain":"electromagnetism"},
    {"id":"aperi21:series-rlc-resonance","title":"RLC 공진","description":"임피던스가 최소가 되는 주파수","domain":"electromagnetism"},
    {"id":"aperi21:transformer","title":"변압기","description":"감은 수와 전압비","domain":"electromagnetism"},
    {"id":"aperi21:motor","title":"전동기","description":"전류가 받는 힘으로 도는 것","domain":"electromagnetism"},
    {"id":"aperi21:generator","title":"발전기","description":"전구를 켜면 손잡이가 무거워진다","domain":"electromagnetism"},
    {"id":"aperi21:displacement-current","title":"변위 전류","description":"축전기 사이를 잇는 항","domain":"electromagnetism"},
    {"id":"aperi21:maxwells-equations","title":"맥스웰 방정식","description":"전기와 자기가 서로를 낳는 사슬","domain":"electromagnetism"},
    {"id":"aperi21:electromagnetic-wave","title":"전자기파","description":"전기장과 자기장의 자기 전파","domain":"electromagnetism"},
    {"id":"aperi21:poynting-vector","title":"포인팅 벡터","description":"도선 둘레 공간을 지나는 에너지","domain":"electromagnetism"},
    {"id":"aperi21:radiation-pressure","title":"복사압","description":"빛이 미는 힘","domain":"electromagnetism"},
    {"id":"aperi21:antenna-radiation","title":"안테나의 복사","description":"옆으로 가장 세고 축 방향으로는 내보내지 않는 안테나의 파동","domain":"electromagnetism"},
    {"id":"aperi21:magnet-attraction","title":"자석에 붙는 것","description":"자석이 당기는 물체와 당기지 않는 물체","domain":"electromagnetism"},
    {"id":"aperi21:magnetic-poles","title":"자석의 두 극","description":"같은 극은 밀고 다른 극은 당긴다","domain":"electromagnetism"},
    {"id":"aperi21:simple-circuit","title":"전기 회로 만들기","description":"이어져야 흐르고 끊기면 꺼진다","domain":"electromagnetism"},
    {"id":"aperi21:electromagnet","title":"전자석","description":"전류가 흐를 때만 자석이 되는 것","domain":"electromagnetism"},
    {"id":"aperi21:iv-characteristic","title":"I-V 특성 곡선","description":"전압과 전류의 관계가 직선이 아닌 소자","domain":"electromagnetism"},
    {"id":"aperi21:thermistor-and-ldr","title":"써미스터와 광저항","description":"온도와 빛에 따라 변하는 저항","domain":"electromagnetism"},
    {"id":"aperi21:potential-divider","title":"분압기","description":"저항으로 전압을 나누어 쓰는 것","domain":"electromagnetism"},
    {"id":"aperi21:millikan-experiment","title":"밀리컨 실험","description":"전하가 띄엄띄엄하다는 증거","domain":"electromagnetism"},
    {"id":"aperi21:power-transmission","title":"송전","description":"전압을 올려 손실을 줄이는 것","domain":"electromagnetism"},
    {"id":"aperi21:loudspeaker-and-microphone","title":"스피커와 마이크","description":"전류와 진동을 오가는 변환","domain":"electromagnetism"},
    {"id":"aperi21:michelson-morley","title":"마이컬슨-몰리 실험","description":"에테르가 없다는 증거","domain":"modern-physics"},
    {"id":"aperi21:relativity-of-simultaneity","title":"동시성의 상대성","description":"기준틀마다 다른 '동시'","domain":"modern-physics"},
    {"id":"aperi21:time-dilation","title":"시간 지연","description":"운동하는 시계가 느려짐","domain":"modern-physics"},
    {"id":"aperi21:light-clock","title":"빛 시계","description":"시간 지연을 유도하는 사고 실험","domain":"modern-physics"},
    {"id":"aperi21:length-contraction","title":"길이 수축","description":"운동 방향으로의 수축","domain":"modern-physics"},
    {"id":"aperi21:muon-decay-evidence","title":"뮤온의 도달","description":"시간 지연의 관측 증거","domain":"modern-physics"},
    {"id":"aperi21:relativistic-velocity-addition","title":"속도의 상대론적 덧셈","description":"광속을 넘지 못하는 합성","domain":"modern-physics"},
    {"id":"aperi21:twin-paradox","title":"쌍둥이 역설","description":"비대칭을 만드는 돌아섬","domain":"modern-physics"},
    {"id":"aperi21:spacetime-diagram","title":"시공간 도표","description":"세계선과 동시선","domain":"modern-physics"},
    {"id":"aperi21:light-cone","title":"광원뿔","description":"인과가 닿는 영역","domain":"modern-physics"},
    {"id":"aperi21:relativistic-momentum","title":"상대론적 운동량","description":"광속에 다가갈수록 끝없이 커지는 운동량","domain":"modern-physics"},
    {"id":"aperi21:relativistic-doppler","title":"상대론적 도플러","description":"시간 지연이 더해진 진동수 변화","domain":"modern-physics"},
    {"id":"aperi21:equivalence-principle","title":"등가 원리","description":"가속과 중력의 구별 불가","domain":"modern-physics"},
    {"id":"aperi21:gravitational-time-dilation","title":"중력 시간 지연","description":"퍼텐셜에 따른 시계의 차이","domain":"modern-physics"},
    {"id":"aperi21:gravitational-redshift","title":"중력 적색 이동","description":"빠져나오며 붉어지는 빛","domain":"modern-physics"},
    {"id":"aperi21:light-bending-by-gravity","title":"빛의 휨","description":"질량 근처에서 휘는 경로","domain":"modern-physics"},
    {"id":"aperi21:blackbody-radiation","title":"흑체 복사","description":"고전 이론의 파탄","domain":"modern-physics"},
    {"id":"aperi21:wien-displacement-law","title":"빈 변위 법칙","description":"온도와 봉우리 파장","domain":"modern-physics"},
    {"id":"aperi21:photoelectric-effect","title":"광전 효과","description":"빛의 입자성 증거","domain":"modern-physics"},
    {"id":"aperi21:work-function-and-threshold","title":"일함수와 문턱 진동수","description":"금속마다 다른 문턱, 모두 같은 기울기","domain":"modern-physics"},
    {"id":"aperi21:compton-scattering","title":"콤프턴 산란","description":"광자가 운동량을 가진다는 증거","domain":"modern-physics"},
    {"id":"aperi21:pair-production","title":"쌍생성","description":"에너지가 물질이 되는 것","domain":"modern-physics"},
    {"id":"aperi21:de-broglie-wavelength","title":"드브로이 파장","description":"빠르기가 정하는 물질의 파장","domain":"modern-physics"},
    {"id":"aperi21:electron-diffraction","title":"전자 회절","description":"물질파의 관측 증거","domain":"modern-physics"},
    {"id":"aperi21:double-slit-with-electrons","title":"전자의 이중 슬릿","description":"하나씩 보내도 생기는 무늬","domain":"modern-physics"},
    {"id":"aperi21:uncertainty-principle","title":"불확정성 원리","description":"켤레량의 동시 결정 한계","domain":"modern-physics"},
    {"id":"aperi21:wave-function","title":"파동 함수","description":"확률 진폭과 그 해석","domain":"modern-physics"},
    {"id":"aperi21:superposition-quantum","title":"양자 중첩","description":"여러 상태의 합으로 있는 것","domain":"modern-physics"},
    {"id":"aperi21:measurement-collapse","title":"측정과 붕괴","description":"관측이 상태를 정하는 것","domain":"modern-physics"},
    {"id":"aperi21:particle-in-a-box","title":"무한 우물","description":"경계가 만드는 에너지 양자화","domain":"modern-physics"},
    {"id":"aperi21:finite-well","title":"유한 우물","description":"파동 함수가 벽 속으로 스며든 만큼 낮아지는 에너지 준위","domain":"modern-physics"},
    {"id":"aperi21:quantum-tunneling","title":"터널 효과","description":"장벽을 통과하는 확률","domain":"modern-physics"},
    {"id":"aperi21:scanning-tunneling-microscope","title":"주사 터널 현미경","description":"터널 전류로 그리는 표면","domain":"modern-physics"},
    {"id":"aperi21:quantum-harmonic-oscillator","title":"양자 조화 진동자","description":"등간격 준위와 영점 에너지","domain":"modern-physics"},
    {"id":"aperi21:hydrogen-spectrum","title":"수소 스펙트럼","description":"불연속한 선 스펙트럼","domain":"modern-physics"},
    {"id":"aperi21:bohr-model","title":"보어 모형","description":"궤도의 양자화","domain":"modern-physics"},
    {"id":"aperi21:atomic-orbital","title":"원자 궤도","description":"확률 분포로서의 전자","domain":"modern-physics"},
    {"id":"aperi21:pauli-exclusion","title":"파울리 배타 원리","description":"같은 상태를 못 가짐","domain":"modern-physics"},
    {"id":"aperi21:electron-configuration","title":"전자 배치","description":"주기율표가 나오는 방식","domain":"modern-physics"},
    {"id":"aperi21:spin","title":"스핀","description":"고전 대응물이 없는 각운동량","domain":"modern-physics"},
    {"id":"aperi21:stern-gerlach","title":"슈테른-게를라흐 실험","description":"갈라지는 원자 빔","domain":"modern-physics"},
    {"id":"aperi21:zeeman-effect","title":"제이만 효과","description":"자기장이 가르는 준위","domain":"modern-physics"},
    {"id":"aperi21:laser-and-stimulated-emission","title":"레이저와 유도 방출","description":"결이 맞는 빛의 증폭","domain":"modern-physics"},
    {"id":"aperi21:nuclear-structure","title":"원자핵의 구성","description":"양성자 수는 원소를, 중성자 수는 동위원소를 정한다","domain":"modern-physics"},
    {"id":"aperi21:binding-energy-curve","title":"결합 에너지 곡선","description":"철에서 최대가 되는 이유","domain":"modern-physics"},
    {"id":"aperi21:radioactive-decay","title":"방사성 붕괴","description":"반감기와 지수 감소","domain":"modern-physics"},
    {"id":"aperi21:decay-types","title":"붕괴의 종류","description":"알파·베타·감마","domain":"modern-physics"},
    {"id":"aperi21:radiometric-dating","title":"방사성 연대 측정","description":"남은 비율로 재는 시간","domain":"modern-physics"},
    {"id":"aperi21:nuclear-fission","title":"핵분열","description":"무거운 핵이 갈라지며 내는 에너지","domain":"modern-physics"},
    {"id":"aperi21:chain-reaction","title":"연쇄 반응","description":"중성자가 이어가는 분열","domain":"modern-physics"},
    {"id":"aperi21:nuclear-fusion","title":"핵융합","description":"가벼운 핵이 합쳐지며 내는 에너지","domain":"modern-physics"},
    {"id":"aperi21:antimatter","title":"반물질","description":"전자와 만나 함께 사라지며 광자 둘을 정반대로 내놓는 짝","domain":"modern-physics"},
    {"id":"aperi21:band-theory","title":"띠 이론","description":"도체·부도체·반도체의 구분","domain":"modern-physics"},
    {"id":"aperi21:fermi-level","title":"페르미 준위","description":"전자가 채워진 높이","domain":"modern-physics"},
    {"id":"aperi21:semiconductor-doping","title":"도핑","description":"불순물이 만드는 n형과 p형","domain":"modern-physics"},
    {"id":"aperi21:pn-junction","title":"pn 접합","description":"공핍층과 정류","domain":"modern-physics"},
    {"id":"aperi21:diode-and-led","title":"다이오드와 LED","description":"한 방향 전류와 빛의 방출","domain":"modern-physics"},
    {"id":"aperi21:transistor-principle","title":"트랜지스터","description":"작은 신호가 큰 전류를 제어","domain":"modern-physics"},
    {"id":"aperi21:photovoltaic-effect","title":"광전지 효과","description":"빛이 만드는 전위차","domain":"modern-physics"},
    {"id":"aperi21:superconductivity","title":"초전도","description":"저항이 사라지는 상태","domain":"modern-physics"},
    {"id":"aperi21:meissner-effect","title":"마이스너 효과","description":"자기장을 밀어내는 초전도체","domain":"modern-physics"},
    {"id":"aperi21:bose-einstein-condensate","title":"보스-아인슈타인 응축","description":"같은 상태로 몰리는 저온의 입자","domain":"modern-physics"},
    {"id":"aperi21:scale-of-universe","title":"우주의 규모","description":"원자에서 우주까지 10의 거듭제곱으로 잇는 크기","domain":"modern-physics"},
    {"id":"aperi21:rutherford-scattering","title":"러더퍼드 산란","description":"대부분 지나가고 일부가 튕겨 나온 실험","domain":"modern-physics"},
    {"id":"aperi21:ionizing-radiation","title":"이온화 복사","description":"결합을 끊을 만큼 큰 광자 에너지","domain":"modern-physics"},
    {"id":"aperi21:exchange-particles","title":"교환 입자","description":"전자 사이의 광자, 쿼크 사이의 글루온","domain":"modern-physics"},
  ],
};
