/**
 * 자동 생성 파일 — 직접 편집하지 말 것.
 *
 * 생성: pnpm catalog:gen  (scripts/gen-aperi21-catalog.mts)
 * 출처: 각 sim 의 schema(title/description) + docs/topics/topics.yaml(분야).
 */

import type { Aperi21Catalog } from '../catalog-types.js';

export const CATALOG: Aperi21Catalog = {
  locale: "ko",
  domains: [
    {"id":"kinematics","name":"운동학"},
    {"id":"newtonian-mechanics","name":"뉴턴 역학"},
    {"id":"energy-momentum","name":"일·에너지·운동량"},
    {"id":"rotation-oscillation","name":"회전과 진동"},
    {"id":"gravitation","name":"중력과 천체"},
    {"id":"fluids","name":"유체"},
    {"id":"thermodynamics","name":"열과 통계"},
    {"id":"waves-acoustics","name":"파동과 음향"},
    {"id":"optics","name":"광학"},
    {"id":"electromagnetism","name":"전자기"},
    {"id":"modern-physics","name":"현대물리"},
  ],
  entries: [
    {"id":"aperi21:reference-frame","title":"기준틀","domain":"kinematics"},
    {"id":"aperi21:coordinate-choice","title":"좌표계 선택","domain":"kinematics"},
    {"id":"aperi21:average-velocity","title":"평균 속도","domain":"kinematics"},
    {"id":"aperi21:average-acceleration","title":"평균 가속도","domain":"kinematics"},
    {"id":"aperi21:direction-of-acceleration","title":"가속도의 방향","domain":"kinematics"},
    {"id":"aperi21:uniform-motion","title":"등속 운동","domain":"kinematics"},
    {"id":"aperi21:uniformly-accelerated-motion","title":"등가속도 운동","domain":"kinematics"},
    {"id":"aperi21:position-time-graph","title":"위치-시간 그래프","domain":"kinematics"},
    {"id":"aperi21:velocity-time-graph","title":"속도-시간 그래프","domain":"kinematics"},
    {"id":"aperi21:acceleration-time-graph","title":"가속도-시간 그래프","domain":"kinematics"},
    {"id":"aperi21:free-fall","title":"자유 낙하","domain":"kinematics"},
    {"id":"aperi21:vertical-throw","title":"연직 투상","domain":"kinematics"},
    {"id":"aperi21:gravitational-acceleration","title":"중력 가속도","domain":"kinematics"},
    {"id":"aperi21:terminal-velocity","title":"종단 속도","domain":"kinematics"},
    {"id":"aperi21:vector-decomposition","title":"벡터의 성분 분해","domain":"kinematics"},
    {"id":"aperi21:vector-addition","title":"벡터의 합성","domain":"kinematics"},
    {"id":"aperi21:relative-velocity","title":"상대 속도","domain":"kinematics"},
    {"id":"aperi21:river-crossing","title":"강 건너기","domain":"kinematics"},
    {"id":"aperi21:projectile-motion","title":"포물선 운동","domain":"kinematics"},
    {"id":"aperi21:projectile-range","title":"사거리와 발사각","domain":"kinematics"},
    {"id":"aperi21:trajectory-equation","title":"궤적 방정식","domain":"kinematics"},
    {"id":"aperi21:uniform-circular-motion","title":"등속 원운동","domain":"kinematics"},
    {"id":"aperi21:centripetal-acceleration","title":"구심 가속도","domain":"kinematics"},
    {"id":"aperi21:angular-acceleration","title":"각가속도","domain":"kinematics"},
    {"id":"aperi21:tangential-normal-acceleration","title":"접선·법선 가속도","domain":"kinematics"},
    {"id":"aperi21:radius-of-curvature","title":"곡률 반지름","domain":"kinematics"},
    {"id":"aperi21:stopping-distance","title":"정지 거리","domain":"kinematics"},
    {"id":"aperi21:newtons-first-law","title":"관성 기준계","domain":"newtonian-mechanics"},
    {"id":"aperi21:newtons-second-law","title":"가속도 법칙","domain":"newtonian-mechanics"},
    {"id":"aperi21:newtons-third-law","title":"작용 반작용","domain":"newtonian-mechanics"},
    {"id":"aperi21:net-force","title":"알짜힘","domain":"newtonian-mechanics"},
    {"id":"aperi21:free-body-diagram","title":"자유물체도","domain":"newtonian-mechanics"},
    {"id":"aperi21:inertial-vs-gravitational-mass","title":"관성 질량과 중력 질량","domain":"newtonian-mechanics"},
    {"id":"aperi21:normal-force","title":"수직항력","domain":"newtonian-mechanics"},
    {"id":"aperi21:apparent-weight","title":"겉보기 무게","domain":"newtonian-mechanics"},
    {"id":"aperi21:static-friction","title":"정지 마찰력","domain":"newtonian-mechanics"},
    {"id":"aperi21:kinetic-friction","title":"운동 마찰력","domain":"newtonian-mechanics"},
    {"id":"aperi21:angle-of-friction","title":"마찰각","domain":"newtonian-mechanics"},
    {"id":"aperi21:inclined-plane","title":"빗면","domain":"newtonian-mechanics"},
    {"id":"aperi21:tension","title":"장력","domain":"newtonian-mechanics"},
    {"id":"aperi21:pulley-system","title":"도르래","domain":"newtonian-mechanics"},
    {"id":"aperi21:connected-bodies","title":"연결된 물체","domain":"newtonian-mechanics"},
    {"id":"aperi21:spring-force","title":"탄성력","domain":"newtonian-mechanics"},
    {"id":"aperi21:centripetal-force","title":"구심력","domain":"newtonian-mechanics"},
    {"id":"aperi21:conical-pendulum","title":"원뿔 진자","domain":"newtonian-mechanics"},
    {"id":"aperi21:banked-curve","title":"경사진 커브","domain":"newtonian-mechanics"},
    {"id":"aperi21:vertical-loop","title":"연직 원운동","domain":"newtonian-mechanics"},
    {"id":"aperi21:drag-force","title":"공기 저항","domain":"newtonian-mechanics"},
    {"id":"aperi21:buoyant-force-as-force","title":"부력(힘으로서)","domain":"newtonian-mechanics"},
    {"id":"aperi21:non-inertial-frame","title":"비관성계","domain":"newtonian-mechanics"},
    {"id":"aperi21:fictitious-force","title":"관성력","domain":"newtonian-mechanics"},
    {"id":"aperi21:coriolis-effect","title":"코리올리 효과","domain":"newtonian-mechanics"},
    {"id":"aperi21:impulse-force-relation","title":"힘과 충격량","domain":"newtonian-mechanics"},
    {"id":"aperi21:equilibrium-of-forces","title":"힘의 평형","domain":"newtonian-mechanics"},
    {"id":"aperi21:atwood-machine","title":"애트우드 기계","domain":"newtonian-mechanics"},
    {"id":"aperi21:balance-scale","title":"수평잡기","domain":"newtonian-mechanics"},
    {"id":"aperi21:mechanical-advantage","title":"힘의 이득","domain":"newtonian-mechanics"},
    {"id":"aperi21:youngs-modulus","title":"영률","domain":"newtonian-mechanics"},
    {"id":"aperi21:stress-strain-curve","title":"응력-변형률 곡선","domain":"newtonian-mechanics"},
    {"id":"aperi21:work-by-variable-force","title":"변하는 힘이 한 일","domain":"energy-momentum"},
    {"id":"aperi21:kinetic-energy","title":"운동 에너지","domain":"energy-momentum"},
    {"id":"aperi21:work-energy-theorem","title":"일-운동 에너지 정리","domain":"energy-momentum"},
    {"id":"aperi21:gravitational-potential-energy","title":"중력 퍼텐셜 에너지","domain":"energy-momentum"},
    {"id":"aperi21:elastic-potential-energy","title":"탄성 퍼텐셜 에너지","domain":"energy-momentum"},
    {"id":"aperi21:conservative-force","title":"보존력","domain":"energy-momentum"},
    {"id":"aperi21:non-conservative-force","title":"비보존력","domain":"energy-momentum"},
    {"id":"aperi21:conservation-of-mechanical-energy","title":"역학적 에너지 보존","domain":"energy-momentum"},
    {"id":"aperi21:energy-dissipation","title":"에너지 소산","domain":"energy-momentum"},
    {"id":"aperi21:potential-energy-curve","title":"퍼텐셜 곡선","domain":"energy-momentum"},
    {"id":"aperi21:equilibrium-points","title":"평형점","domain":"energy-momentum"},
    {"id":"aperi21:efficiency","title":"효율","domain":"energy-momentum"},
    {"id":"aperi21:impulse-momentum-theorem","title":"충격량-운동량 정리","domain":"energy-momentum"},
    {"id":"aperi21:conservation-of-momentum","title":"운동량 보존","domain":"energy-momentum"},
    {"id":"aperi21:elastic-collision","title":"탄성 충돌","domain":"energy-momentum"},
    {"id":"aperi21:inelastic-collision","title":"비탄성 충돌","domain":"energy-momentum"},
    {"id":"aperi21:perfectly-inelastic-collision","title":"완전 비탄성 충돌","domain":"energy-momentum"},
    {"id":"aperi21:two-dimensional-collision","title":"2차원 충돌","domain":"energy-momentum"},
    {"id":"aperi21:center-of-mass-motion","title":"질량 중심의 운동","domain":"energy-momentum"},
    {"id":"aperi21:explosion-and-recoil","title":"폭발과 반동","domain":"energy-momentum"},
    {"id":"aperi21:rocket-equation","title":"로켓 방정식","domain":"energy-momentum"},
    {"id":"aperi21:ballistic-pendulum","title":"탄동 진자","domain":"energy-momentum"},
    {"id":"aperi21:energy-in-collision","title":"충돌에서의 에너지","domain":"energy-momentum"},
    {"id":"aperi21:energy-flow-diagram","title":"에너지 흐름도","domain":"energy-momentum"},
    {"id":"aperi21:torque","title":"돌림힘","domain":"rotation-oscillation"},
    {"id":"aperi21:moment-of-inertia","title":"관성 모멘트","domain":"rotation-oscillation"},
    {"id":"aperi21:parallel-axis-theorem","title":"평행축 정리","domain":"rotation-oscillation"},
    {"id":"aperi21:rotational-kinetic-energy","title":"회전 운동 에너지","domain":"rotation-oscillation"},
    {"id":"aperi21:angular-momentum","title":"각운동량","domain":"rotation-oscillation"},
    {"id":"aperi21:conservation-of-angular-momentum","title":"각운동량 보존","domain":"rotation-oscillation"},
    {"id":"aperi21:rolling-without-slipping","title":"미끄러지지 않는 구름","domain":"rotation-oscillation"},
    {"id":"aperi21:rolling-race","title":"구르는 물체의 경주","domain":"rotation-oscillation"},
    {"id":"aperi21:static-equilibrium","title":"정적 평형","domain":"rotation-oscillation"},
    {"id":"aperi21:center-of-gravity","title":"무게 중심","domain":"rotation-oscillation"},
    {"id":"aperi21:gyroscopic-precession","title":"세차 운동","domain":"rotation-oscillation"},
    {"id":"aperi21:angular-momentum-vector","title":"각운동량의 방향","domain":"rotation-oscillation"},
    {"id":"aperi21:simple-harmonic-motion","title":"단순 조화 운동","domain":"rotation-oscillation"},
    {"id":"aperi21:shm-energy","title":"조화 운동의 에너지","domain":"rotation-oscillation"},
    {"id":"aperi21:mass-spring-system","title":"용수철 진자","domain":"rotation-oscillation"},
    {"id":"aperi21:simple-pendulum","title":"단진자","domain":"rotation-oscillation"},
    {"id":"aperi21:physical-pendulum","title":"물리 진자","domain":"rotation-oscillation"},
    {"id":"aperi21:pendulum-amplitude-dependence","title":"진자의 등시성","domain":"rotation-oscillation"},
    {"id":"aperi21:damped-oscillation","title":"감쇠 진동","domain":"rotation-oscillation"},
    {"id":"aperi21:damping-regimes","title":"감쇠의 세 양상","domain":"rotation-oscillation"},
    {"id":"aperi21:driven-oscillation","title":"강제 진동","domain":"rotation-oscillation"},
    {"id":"aperi21:resonance","title":"공명","domain":"rotation-oscillation"},
    {"id":"aperi21:quality-factor","title":"Q 인자","domain":"rotation-oscillation"},
    {"id":"aperi21:coupled-oscillators","title":"결합 진동자","domain":"rotation-oscillation"},
    {"id":"aperi21:normal-modes","title":"정규 모드","domain":"rotation-oscillation"},
    {"id":"aperi21:beats-in-oscillation","title":"진동의 맥놀이","domain":"rotation-oscillation"},
    {"id":"aperi21:phase-space","title":"위상 공간","domain":"rotation-oscillation"},
    {"id":"aperi21:nonlinear-oscillation","title":"비선형 진동","domain":"rotation-oscillation"},
    {"id":"aperi21:gears","title":"기어","domain":"rotation-oscillation"},
    {"id":"aperi21:newtons-law-of-gravitation","title":"만유인력 법칙","domain":"gravitation"},
    {"id":"aperi21:gravitational-field","title":"중력장","domain":"gravitation"},
    {"id":"aperi21:range-and-surface-gravity","title":"중력과 사거리","domain":"gravitation"},
    {"id":"aperi21:shell-theorem","title":"껍질 정리","domain":"gravitation"},
    {"id":"aperi21:gravity-inside-earth","title":"지구 내부의 중력","domain":"gravitation"},
    {"id":"aperi21:gravitational-potential-energy-general","title":"중력 퍼텐셜 에너지(일반)","domain":"gravitation"},
    {"id":"aperi21:escape-velocity","title":"탈출 속도","domain":"gravitation"},
    {"id":"aperi21:orbital-velocity","title":"궤도 속도","domain":"gravitation"},
    {"id":"aperi21:circular-orbit","title":"원 궤도","domain":"gravitation"},
    {"id":"aperi21:elliptical-orbit","title":"타원 궤도","domain":"gravitation"},
    {"id":"aperi21:keplers-first-law","title":"케플러 제1법칙","domain":"gravitation"},
    {"id":"aperi21:keplers-second-law","title":"케플러 제2법칙","domain":"gravitation"},
    {"id":"aperi21:keplers-third-law","title":"케플러 제3법칙","domain":"gravitation"},
    {"id":"aperi21:two-body-problem","title":"이체 문제","domain":"gravitation"},
    {"id":"aperi21:tidal-force","title":"조석력","domain":"gravitation"},
    {"id":"aperi21:roche-limit","title":"로슈 한계","domain":"gravitation"},
    {"id":"aperi21:weightlessness","title":"무중력","domain":"gravitation"},
    {"id":"aperi21:geostationary-orbit","title":"정지 궤도","domain":"gravitation"},
    {"id":"aperi21:gravitational-slingshot","title":"중력 도움","domain":"gravitation"},
    {"id":"aperi21:lagrange-points","title":"라그랑주 점","domain":"gravitation"},
    {"id":"aperi21:orbital-transfer","title":"궤도 전이","domain":"gravitation"},
    {"id":"aperi21:black-hole-horizon","title":"사건 지평선","domain":"gravitation"},
    {"id":"aperi21:diurnal-motion","title":"일주 운동","domain":"gravitation"},
    {"id":"aperi21:earth-rotation-day-night","title":"자전과 낮과 밤","domain":"gravitation"},
    {"id":"aperi21:earth-revolution-constellations","title":"공전과 별자리","domain":"gravitation"},
    {"id":"aperi21:solar-altitude-shadow","title":"태양 고도와 그림자","domain":"gravitation"},
    {"id":"aperi21:seasonal-sun-path","title":"계절과 태양의 길","domain":"gravitation"},
    {"id":"aperi21:axial-tilt-seasons","title":"자전축 기울기와 계절","domain":"gravitation"},
    {"id":"aperi21:moon-phases","title":"달의 위상","domain":"gravitation"},
    {"id":"aperi21:eclipse","title":"일식과 월식","domain":"gravitation"},
    {"id":"aperi21:stellar-parallax","title":"연주시차","domain":"gravitation"},
    {"id":"aperi21:apparent-brightness","title":"겉보기 밝기","domain":"gravitation"},
    {"id":"aperi21:magnitude-scale","title":"별의 등급","domain":"gravitation"},
    {"id":"aperi21:star-color-temperature","title":"별의 색과 표면 온도","domain":"gravitation"},
    {"id":"aperi21:expanding-universe","title":"우주의 팽창","domain":"gravitation"},
    {"id":"aperi21:stellar-luminosity","title":"광도","domain":"gravitation"},
    {"id":"aperi21:hr-diagram","title":"HR 도","domain":"gravitation"},
    {"id":"aperi21:star-radiation-gravity-balance","title":"복사압과 중력의 평형","domain":"gravitation"},
    {"id":"aperi21:orbital-decay","title":"궤도 감쇠","domain":"gravitation"},
    {"id":"aperi21:inverse-square-law","title":"역제곱 법칙","domain":"gravitation"},
    {"id":"aperi21:stellar-nucleosynthesis","title":"별의 원소 합성","domain":"gravitation"},
    {"id":"aperi21:star-life-cycle","title":"별의 일생","domain":"gravitation"},
    {"id":"aperi21:stellar-spectral-class","title":"별의 스펙트럼 분류","domain":"gravitation"},
    {"id":"aperi21:supernova-and-neutron-star","title":"초신성과 중성자별","domain":"gravitation"},
    {"id":"aperi21:exoplanet-detection","title":"외계행성 탐지","domain":"gravitation"},
    {"id":"aperi21:projectile-in-wind","title":"바람과 사거리","domain":"fluids"},
    {"id":"aperi21:pressure-isotropy","title":"압력의 등방성","domain":"fluids"},
    {"id":"aperi21:hydrostatic-pressure","title":"정수압","domain":"fluids"},
    {"id":"aperi21:pressure-and-container-shape","title":"그릇 모양과 바닥 압력","domain":"fluids"},
    {"id":"aperi21:atmospheric-pressure","title":"대기압","domain":"fluids"},
    {"id":"aperi21:barometer","title":"기압계","domain":"fluids"},
    {"id":"aperi21:manometer","title":"압력계","domain":"fluids"},
    {"id":"aperi21:pascals-principle","title":"파스칼 원리","domain":"fluids"},
    {"id":"aperi21:buoyancy","title":"부력","domain":"fluids"},
    {"id":"aperi21:archimedes-principle","title":"아르키메데스 원리 — 부력의 크기","domain":"fluids"},
    {"id":"aperi21:floating-and-draft","title":"뜨는 깊이","domain":"fluids"},
    {"id":"aperi21:stability-of-floating-body","title":"부유체의 안정","domain":"fluids"},
    {"id":"aperi21:continuity-equation","title":"연속 방정식","domain":"fluids"},
    {"id":"aperi21:bernoullis-principle","title":"베르누이 원리","domain":"fluids"},
    {"id":"aperi21:venturi-effect","title":"벤투리 효과","domain":"fluids"},
    {"id":"aperi21:torricellis-law","title":"토리첼리 법칙","domain":"fluids"},
    {"id":"aperi21:lift-force","title":"양력","domain":"fluids"},
    {"id":"aperi21:viscosity","title":"점성","domain":"fluids"},
    {"id":"aperi21:poiseuille-flow","title":"관 속의 층류","domain":"fluids"},
    {"id":"aperi21:stokes-drag","title":"스토크스 항력","domain":"fluids"},
    {"id":"aperi21:laminar-vs-turbulent","title":"층류와 난류","domain":"fluids"},
    {"id":"aperi21:reynolds-number","title":"레이놀즈 수","domain":"fluids"},
    {"id":"aperi21:boundary-layer","title":"경계층","domain":"fluids"},
    {"id":"aperi21:surface-tension","title":"표면 장력","domain":"fluids"},
    {"id":"aperi21:laplace-pressure","title":"라플라스 압력","domain":"fluids"},
    {"id":"aperi21:capillary-action","title":"모세관 현상","domain":"fluids"},
    {"id":"aperi21:wetting-and-contact-angle","title":"젖음과 접촉각","domain":"fluids"},
    {"id":"aperi21:drag-in-fluid","title":"유체 속 항력","domain":"fluids"},
    {"id":"aperi21:thermal-equilibrium","title":"열평형","domain":"thermodynamics"},
    {"id":"aperi21:specific-heat","title":"비열","domain":"thermodynamics"},
    {"id":"aperi21:calorimetry","title":"열량 측정","domain":"thermodynamics"},
    {"id":"aperi21:latent-heat","title":"잠열","domain":"thermodynamics"},
    {"id":"aperi21:phase-diagram","title":"상평형 그림","domain":"thermodynamics"},
    {"id":"aperi21:triple-point","title":"삼중점","domain":"thermodynamics"},
    {"id":"aperi21:thermal-conduction","title":"열전도","domain":"thermodynamics"},
    {"id":"aperi21:thermal-convection","title":"대류","domain":"thermodynamics"},
    {"id":"aperi21:thermal-radiation","title":"열복사","domain":"thermodynamics"},
    {"id":"aperi21:stefan-boltzmann-law","title":"슈테판-볼츠만 법칙","domain":"thermodynamics"},
    {"id":"aperi21:thermal-expansion","title":"열팽창","domain":"thermodynamics"},
    {"id":"aperi21:bimetal","title":"바이메탈","domain":"thermodynamics"},
    {"id":"aperi21:ideal-gas-law","title":"이상 기체 법칙","domain":"thermodynamics"},
    {"id":"aperi21:boyles-law","title":"보일 법칙","domain":"thermodynamics"},
    {"id":"aperi21:charles-law","title":"샤를 법칙","domain":"thermodynamics"},
    {"id":"aperi21:gas-pressure","title":"기체 분자와 압력","domain":"thermodynamics"},
    {"id":"aperi21:pressure-from-collisions","title":"충돌이 만드는 압력","domain":"thermodynamics"},
    {"id":"aperi21:maxwell-boltzmann-distribution","title":"맥스웰-볼츠만 분포","domain":"thermodynamics"},
    {"id":"aperi21:mean-free-path","title":"평균 자유 행로","domain":"thermodynamics"},
    {"id":"aperi21:first-law-of-thermodynamics","title":"열역학 제1법칙","domain":"thermodynamics"},
    {"id":"aperi21:pv-diagram","title":"PV 그림","domain":"thermodynamics"},
    {"id":"aperi21:isothermal-process","title":"등온 과정","domain":"thermodynamics"},
    {"id":"aperi21:adiabatic-process","title":"단열 과정","domain":"thermodynamics"},
    {"id":"aperi21:isobaric-isochoric","title":"등압·등적 과정","domain":"thermodynamics"},
    {"id":"aperi21:cyclic-process","title":"순환 과정","domain":"thermodynamics"},
    {"id":"aperi21:second-law-of-thermodynamics","title":"열역학 제2법칙","domain":"thermodynamics"},
    {"id":"aperi21:irreversibility","title":"엔트로피와 비가역성","domain":"thermodynamics"},
    {"id":"aperi21:heat-engine","title":"열기관","domain":"thermodynamics"},
    {"id":"aperi21:carnot-cycle","title":"카르노 순환","domain":"thermodynamics"},
    {"id":"aperi21:refrigerator-heat-pump","title":"냉장고와 열펌프","domain":"thermodynamics"},
    {"id":"aperi21:brownian-motion","title":"브라운 운동","domain":"thermodynamics"},
    {"id":"aperi21:diffusion","title":"확산","domain":"thermodynamics"},
    {"id":"aperi21:random-walk","title":"무작위 걸음","domain":"thermodynamics"},
    {"id":"aperi21:statistical-fluctuation","title":"요동","domain":"thermodynamics"},
    {"id":"aperi21:maxwells-demon","title":"맥스웰의 도깨비","domain":"thermodynamics"},
    {"id":"aperi21:insulation","title":"보온과 단열","domain":"thermodynamics"},
    {"id":"aperi21:albedo","title":"반사율","domain":"thermodynamics"},
    {"id":"aperi21:radiative-equilibrium","title":"복사 평형","domain":"thermodynamics"},
    {"id":"aperi21:greenhouse-effect","title":"온실 효과","domain":"thermodynamics"},
    {"id":"aperi21:wave-basics","title":"파동의 기본량","domain":"waves-acoustics"},
    {"id":"aperi21:wave-vs-particle-transport","title":"파동이 나르는 것","domain":"waves-acoustics"},
    {"id":"aperi21:transverse-wave","title":"횡파","domain":"waves-acoustics"},
    {"id":"aperi21:longitudinal-wave","title":"종파","domain":"waves-acoustics"},
    {"id":"aperi21:wave-speed-in-medium","title":"매질과 파동 속도","domain":"waves-acoustics"},
    {"id":"aperi21:wavefront-and-ray","title":"파면과 광선","domain":"waves-acoustics"},
    {"id":"aperi21:huygens-principle","title":"하위헌스 원리","domain":"waves-acoustics"},
    {"id":"aperi21:superposition","title":"중첩 원리","domain":"waves-acoustics"},
    {"id":"aperi21:constructive-destructive","title":"보강과 상쇄","domain":"waves-acoustics"},
    {"id":"aperi21:interference","title":"간섭","domain":"waves-acoustics"},
    {"id":"aperi21:standing-wave","title":"정상파","domain":"waves-acoustics"},
    {"id":"aperi21:harmonics","title":"배음","domain":"waves-acoustics"},
    {"id":"aperi21:string-vibration","title":"줄의 진동","domain":"waves-acoustics"},
    {"id":"aperi21:air-column-resonance","title":"기주 공명","domain":"waves-acoustics"},
    {"id":"aperi21:beats","title":"맥놀이","domain":"waves-acoustics"},
    {"id":"aperi21:doppler-effect","title":"도플러 효과","domain":"waves-acoustics"},
    {"id":"aperi21:doppler-source-vs-observer","title":"음원과 관찰자","domain":"waves-acoustics"},
    {"id":"aperi21:shock-wave","title":"충격파","domain":"waves-acoustics"},
    {"id":"aperi21:sound-intensity","title":"음의 세기","domain":"waves-acoustics"},
    {"id":"aperi21:reflection-of-waves","title":"파동의 반사","domain":"waves-acoustics"},
    {"id":"aperi21:refraction-of-waves","title":"파동의 굴절","domain":"waves-acoustics"},
    {"id":"aperi21:diffraction","title":"회절","domain":"waves-acoustics"},
    {"id":"aperi21:slit-width-and-diffraction","title":"슬릿 폭과 회절","domain":"waves-acoustics"},
    {"id":"aperi21:wave-energy","title":"파동의 에너지","domain":"waves-acoustics"},
    {"id":"aperi21:wave-attenuation","title":"파동의 감쇠","domain":"waves-acoustics"},
    {"id":"aperi21:impedance-mismatch","title":"임피던스 부정합","domain":"waves-acoustics"},
    {"id":"aperi21:noise-cancellation","title":"능동 소음 제거","domain":"waves-acoustics"},
    {"id":"aperi21:sound-source-vibration","title":"소리와 떨림","domain":"waves-acoustics"},
    {"id":"aperi21:sound-through-materials","title":"물질을 통한 소리 전달","domain":"waves-acoustics"},
    {"id":"aperi21:digital-vs-analog-signal","title":"디지털 신호와 아날로그","domain":"waves-acoustics"},
    {"id":"aperi21:seismic-waves","title":"지진파","domain":"waves-acoustics"},
    {"id":"aperi21:rectilinear-propagation","title":"빛의 직진","domain":"optics"},
    {"id":"aperi21:shadow-umbra-penumbra","title":"본그림자와 반그림자","domain":"optics"},
    {"id":"aperi21:pinhole-camera","title":"바늘구멍 사진기","domain":"optics"},
    {"id":"aperi21:law-of-reflection","title":"반사 법칙","domain":"optics"},
    {"id":"aperi21:specular-diffuse-reflection","title":"정반사와 난반사","domain":"optics"},
    {"id":"aperi21:plane-mirror-image","title":"평면거울의 상","domain":"optics"},
    {"id":"aperi21:multiple-mirror-images","title":"두 거울의 상","domain":"optics"},
    {"id":"aperi21:concave-mirror","title":"오목거울","domain":"optics"},
    {"id":"aperi21:convex-mirror","title":"볼록거울","domain":"optics"},
    {"id":"aperi21:snells-law","title":"굴절 법칙","domain":"optics"},
    {"id":"aperi21:apparent-depth","title":"겉보기 깊이","domain":"optics"},
    {"id":"aperi21:total-internal-reflection","title":"전반사","domain":"optics"},
    {"id":"aperi21:optical-fiber","title":"광섬유","domain":"optics"},
    {"id":"aperi21:mirage","title":"신기루","domain":"optics"},
    {"id":"aperi21:dispersion","title":"분산","domain":"optics"},
    {"id":"aperi21:prism","title":"프리즘","domain":"optics"},
    {"id":"aperi21:rainbow","title":"무지개","domain":"optics"},
    {"id":"aperi21:thin-lens","title":"얇은 렌즈","domain":"optics"},
    {"id":"aperi21:converging-diverging-lens","title":"볼록 렌즈와 오목 렌즈","domain":"optics"},
    {"id":"aperi21:magnification","title":"배율","domain":"optics"},
    {"id":"aperi21:focal-length","title":"초점 거리","domain":"optics"},
    {"id":"aperi21:real-vs-virtual-image","title":"실상과 허상","domain":"optics"},
    {"id":"aperi21:lens-combination","title":"렌즈의 조합","domain":"optics"},
    {"id":"aperi21:spherical-aberration","title":"구면 수차","domain":"optics"},
    {"id":"aperi21:chromatic-aberration","title":"색수차","domain":"optics"},
    {"id":"aperi21:human-eye-accommodation","title":"눈의 조절","domain":"optics"},
    {"id":"aperi21:myopia-hyperopia","title":"근시와 원시","domain":"optics"},
    {"id":"aperi21:magnifying-glass","title":"돋보기","domain":"optics"},
    {"id":"aperi21:microscope","title":"현미경","domain":"optics"},
    {"id":"aperi21:telescope","title":"망원경","domain":"optics"},
    {"id":"aperi21:youngs-double-slit","title":"이중 슬릿 간섭","domain":"optics"},
    {"id":"aperi21:single-slit-diffraction","title":"단일 슬릿 회절","domain":"optics"},
    {"id":"aperi21:diffraction-grating","title":"회절 격자","domain":"optics"},
    {"id":"aperi21:thin-film-interference","title":"박막 간섭","domain":"optics"},
    {"id":"aperi21:newtons-rings","title":"뉴턴 링","domain":"optics"},
    {"id":"aperi21:resolving-power","title":"분해능","domain":"optics"},
    {"id":"aperi21:polarization","title":"편광","domain":"optics"},
    {"id":"aperi21:malus-law","title":"말뤼스 법칙","domain":"optics"},
    {"id":"aperi21:brewster-angle","title":"브루스터 각","domain":"optics"},
    {"id":"aperi21:birefringence","title":"복굴절","domain":"optics"},
    {"id":"aperi21:scattering","title":"산란","domain":"optics"},
    {"id":"aperi21:rayleigh-scattering","title":"레일리 산란","domain":"optics"},
    {"id":"aperi21:seeing-requires-light","title":"보려면 빛이 있어야","domain":"optics"},
    {"id":"aperi21:color-addition","title":"빛의 합성","domain":"optics"},
    {"id":"aperi21:object-color","title":"물체의 색","domain":"optics"},
    {"id":"aperi21:light-through-materials","title":"빛과 재료","domain":"optics"},
    {"id":"aperi21:electric-charge","title":"전하","domain":"electromagnetism"},
    {"id":"aperi21:charging-methods","title":"대전 방법","domain":"electromagnetism"},
    {"id":"aperi21:coulombs-law","title":"쿨롱 법칙","domain":"electromagnetism"},
    {"id":"aperi21:superposition-of-forces","title":"전기력의 중첩","domain":"electromagnetism"},
    {"id":"aperi21:electric-field","title":"전기장","domain":"electromagnetism"},
    {"id":"aperi21:field-lines","title":"전기력선","domain":"electromagnetism"},
    {"id":"aperi21:field-of-dipole","title":"쌍극자의 전기장","domain":"electromagnetism"},
    {"id":"aperi21:uniform-field","title":"균일한 전기장","domain":"electromagnetism"},
    {"id":"aperi21:charge-in-uniform-field","title":"균일장 속 전하","domain":"electromagnetism"},
    {"id":"aperi21:gausss-law","title":"가우스 법칙","domain":"electromagnetism"},
    {"id":"aperi21:field-of-charged-sphere","title":"대전된 구의 전기장","domain":"electromagnetism"},
    {"id":"aperi21:equipotential-surface","title":"등전위면","domain":"electromagnetism"},
    {"id":"aperi21:potential-vs-field","title":"전위와 전기장","domain":"electromagnetism"},
    {"id":"aperi21:electrostatic-shielding","title":"정전기 차폐","domain":"electromagnetism"},
    {"id":"aperi21:charge-on-conductor-surface","title":"도체 표면의 전하","domain":"electromagnetism"},
    {"id":"aperi21:dielectric","title":"유전체","domain":"electromagnetism"},
    {"id":"aperi21:parallel-plate-capacitor","title":"평행판 축전기","domain":"electromagnetism"},
    {"id":"aperi21:capacitors-in-circuit","title":"축전기의 연결","domain":"electromagnetism"},
    {"id":"aperi21:energy-in-capacitor","title":"축전기의 에너지","domain":"electromagnetism"},
    {"id":"aperi21:electric-current","title":"전류","domain":"electromagnetism"},
    {"id":"aperi21:drift-velocity","title":"표류 속도","domain":"electromagnetism"},
    {"id":"aperi21:ohms-law","title":"옴 법칙","domain":"electromagnetism"},
    {"id":"aperi21:resistance-and-geometry","title":"저항과 형태","domain":"electromagnetism"},
    {"id":"aperi21:temperature-and-resistance","title":"온도와 저항","domain":"electromagnetism"},
    {"id":"aperi21:series-parallel-resistors","title":"저항의 직렬과 병렬","domain":"electromagnetism"},
    {"id":"aperi21:emf-and-internal-resistance","title":"기전력과 내부 저항","domain":"electromagnetism"},
    {"id":"aperi21:kirchhoffs-current-law","title":"키르히호프 전류 법칙","domain":"electromagnetism"},
    {"id":"aperi21:kirchhoffs-voltage-law","title":"키르히호프 전압 법칙","domain":"electromagnetism"},
    {"id":"aperi21:wheatstone-bridge","title":"휘트스톤 브리지","domain":"electromagnetism"},
    {"id":"aperi21:joule-heating","title":"줄 열","domain":"electromagnetism"},
    {"id":"aperi21:rc-circuit","title":"RC 회로","domain":"electromagnetism"},
    {"id":"aperi21:magnetic-field","title":"자기장","domain":"electromagnetism"},
    {"id":"aperi21:magnetic-field-lines","title":"자기력선","domain":"electromagnetism"},
    {"id":"aperi21:lorentz-force","title":"로런츠 힘","domain":"electromagnetism"},
    {"id":"aperi21:charged-particle-in-magnetic-field","title":"자기장 속 전하의 원운동","domain":"electromagnetism"},
    {"id":"aperi21:velocity-selector","title":"속도 선택기","domain":"electromagnetism"},
    {"id":"aperi21:mass-spectrometer","title":"질량 분석기","domain":"electromagnetism"},
    {"id":"aperi21:force-on-current-wire","title":"전류가 받는 힘","domain":"electromagnetism"},
    {"id":"aperi21:biot-savart-law","title":"비오-사바르 법칙","domain":"electromagnetism"},
    {"id":"aperi21:field-of-straight-wire","title":"전류가 만드는 자기장","domain":"electromagnetism"},
    {"id":"aperi21:field-of-loop-and-solenoid","title":"고리와 솔레노이드","domain":"electromagnetism"},
    {"id":"aperi21:amperes-law","title":"앙페르 법칙","domain":"electromagnetism"},
    {"id":"aperi21:force-between-wires","title":"도선 사이의 힘","domain":"electromagnetism"},
    {"id":"aperi21:magnetic-dipole","title":"자기 쌍극자","domain":"electromagnetism"},
    {"id":"aperi21:magnetic-materials","title":"자성체","domain":"electromagnetism"},
    {"id":"aperi21:faradays-law","title":"패러데이 법칙","domain":"electromagnetism"},
    {"id":"aperi21:lenzs-law","title":"렌츠 법칙","domain":"electromagnetism"},
    {"id":"aperi21:motional-emf","title":"운동 기전력","domain":"electromagnetism"},
    {"id":"aperi21:eddy-current","title":"맴돌이 전류","domain":"electromagnetism"},
    {"id":"aperi21:self-inductance","title":"자체 인덕턴스","domain":"electromagnetism"},
    {"id":"aperi21:mutual-inductance","title":"상호 인덕턴스","domain":"electromagnetism"},
    {"id":"aperi21:energy-in-inductor","title":"인덕터의 에너지","domain":"electromagnetism"},
    {"id":"aperi21:rl-circuit","title":"RL 회로","domain":"electromagnetism"},
    {"id":"aperi21:lc-oscillation","title":"LC 진동","domain":"electromagnetism"},
    {"id":"aperi21:ac-generation","title":"교류의 발생","domain":"electromagnetism"},
    {"id":"aperi21:reactance","title":"리액턴스와 임피던스","domain":"electromagnetism"},
    {"id":"aperi21:phase-in-ac-circuit","title":"교류의 위상차","domain":"electromagnetism"},
    {"id":"aperi21:series-rlc-resonance","title":"RLC 공진","domain":"electromagnetism"},
    {"id":"aperi21:transformer","title":"변압기","domain":"electromagnetism"},
    {"id":"aperi21:motor","title":"전동기","domain":"electromagnetism"},
    {"id":"aperi21:generator","title":"발전기","domain":"electromagnetism"},
    {"id":"aperi21:displacement-current","title":"변위 전류","domain":"electromagnetism"},
    {"id":"aperi21:maxwells-equations","title":"맥스웰 방정식","domain":"electromagnetism"},
    {"id":"aperi21:electromagnetic-wave","title":"전자기파","domain":"electromagnetism"},
    {"id":"aperi21:poynting-vector","title":"포인팅 벡터","domain":"electromagnetism"},
    {"id":"aperi21:radiation-pressure","title":"복사압","domain":"electromagnetism"},
    {"id":"aperi21:antenna-radiation","title":"안테나의 복사","domain":"electromagnetism"},
    {"id":"aperi21:magnet-attraction","title":"자석에 붙는 것","domain":"electromagnetism"},
    {"id":"aperi21:magnetic-poles","title":"자석의 두 극","domain":"electromagnetism"},
    {"id":"aperi21:simple-circuit","title":"전기 회로 만들기","domain":"electromagnetism"},
    {"id":"aperi21:electromagnet","title":"전자석","domain":"electromagnetism"},
    {"id":"aperi21:iv-characteristic","title":"I-V 특성 곡선","domain":"electromagnetism"},
    {"id":"aperi21:thermistor-and-ldr","title":"써미스터와 광저항","domain":"electromagnetism"},
    {"id":"aperi21:potential-divider","title":"분압기","domain":"electromagnetism"},
    {"id":"aperi21:millikan-experiment","title":"밀리컨 실험","domain":"electromagnetism"},
    {"id":"aperi21:power-transmission","title":"송전","domain":"electromagnetism"},
    {"id":"aperi21:loudspeaker-and-microphone","title":"스피커와 마이크","domain":"electromagnetism"},
    {"id":"aperi21:michelson-morley","title":"마이컬슨-몰리 실험","domain":"modern-physics"},
    {"id":"aperi21:relativity-of-simultaneity","title":"동시성의 상대성","domain":"modern-physics"},
    {"id":"aperi21:time-dilation","title":"시간 지연","domain":"modern-physics"},
    {"id":"aperi21:light-clock","title":"빛 시계","domain":"modern-physics"},
    {"id":"aperi21:length-contraction","title":"길이 수축","domain":"modern-physics"},
    {"id":"aperi21:muon-decay-evidence","title":"뮤온의 도달","domain":"modern-physics"},
    {"id":"aperi21:relativistic-velocity-addition","title":"속도의 상대론적 덧셈","domain":"modern-physics"},
    {"id":"aperi21:twin-paradox","title":"쌍둥이 역설","domain":"modern-physics"},
    {"id":"aperi21:spacetime-diagram","title":"시공간 도표","domain":"modern-physics"},
    {"id":"aperi21:light-cone","title":"광원뿔","domain":"modern-physics"},
    {"id":"aperi21:relativistic-momentum","title":"상대론적 운동량","domain":"modern-physics"},
    {"id":"aperi21:relativistic-doppler","title":"상대론적 도플러","domain":"modern-physics"},
    {"id":"aperi21:equivalence-principle","title":"등가 원리","domain":"modern-physics"},
    {"id":"aperi21:gravitational-time-dilation","title":"중력 시간 지연","domain":"modern-physics"},
    {"id":"aperi21:gravitational-redshift","title":"중력 적색 이동","domain":"modern-physics"},
    {"id":"aperi21:light-bending-by-gravity","title":"빛의 휨","domain":"modern-physics"},
    {"id":"aperi21:blackbody-radiation","title":"흑체 복사","domain":"modern-physics"},
    {"id":"aperi21:wien-displacement-law","title":"빈 변위 법칙","domain":"modern-physics"},
    {"id":"aperi21:photoelectric-effect","title":"광전 효과","domain":"modern-physics"},
    {"id":"aperi21:work-function-and-threshold","title":"일함수와 문턱 진동수","domain":"modern-physics"},
    {"id":"aperi21:compton-scattering","title":"콤프턴 산란","domain":"modern-physics"},
    {"id":"aperi21:pair-production","title":"쌍생성","domain":"modern-physics"},
    {"id":"aperi21:de-broglie-wavelength","title":"드브로이 파장","domain":"modern-physics"},
    {"id":"aperi21:electron-diffraction","title":"전자 회절","domain":"modern-physics"},
    {"id":"aperi21:double-slit-with-electrons","title":"전자의 이중 슬릿","domain":"modern-physics"},
    {"id":"aperi21:uncertainty-principle","title":"불확정성 원리","domain":"modern-physics"},
    {"id":"aperi21:wave-function","title":"파동 함수","domain":"modern-physics"},
    {"id":"aperi21:superposition-quantum","title":"양자 중첩","domain":"modern-physics"},
    {"id":"aperi21:measurement-collapse","title":"측정과 붕괴","domain":"modern-physics"},
    {"id":"aperi21:particle-in-a-box","title":"무한 우물","domain":"modern-physics"},
    {"id":"aperi21:finite-well","title":"유한 우물","domain":"modern-physics"},
    {"id":"aperi21:quantum-tunneling","title":"터널 효과","domain":"modern-physics"},
    {"id":"aperi21:scanning-tunneling-microscope","title":"주사 터널 현미경","domain":"modern-physics"},
    {"id":"aperi21:quantum-harmonic-oscillator","title":"양자 조화 진동자","domain":"modern-physics"},
    {"id":"aperi21:hydrogen-spectrum","title":"수소 스펙트럼","domain":"modern-physics"},
    {"id":"aperi21:bohr-model","title":"보어 모형","domain":"modern-physics"},
    {"id":"aperi21:atomic-orbital","title":"원자 궤도","domain":"modern-physics"},
    {"id":"aperi21:pauli-exclusion","title":"파울리 배타 원리","domain":"modern-physics"},
    {"id":"aperi21:electron-configuration","title":"전자 배치","domain":"modern-physics"},
    {"id":"aperi21:spin","title":"스핀","domain":"modern-physics"},
    {"id":"aperi21:stern-gerlach","title":"슈테른-게를라흐 실험","domain":"modern-physics"},
    {"id":"aperi21:zeeman-effect","title":"제이만 효과","domain":"modern-physics"},
    {"id":"aperi21:laser-and-stimulated-emission","title":"레이저와 유도 방출","domain":"modern-physics"},
    {"id":"aperi21:nuclear-structure","title":"원자핵의 구성","domain":"modern-physics"},
    {"id":"aperi21:binding-energy-curve","title":"결합 에너지 곡선","domain":"modern-physics"},
    {"id":"aperi21:radioactive-decay","title":"방사성 붕괴","domain":"modern-physics"},
    {"id":"aperi21:decay-types","title":"붕괴의 종류","domain":"modern-physics"},
    {"id":"aperi21:radiometric-dating","title":"방사성 연대 측정","domain":"modern-physics"},
    {"id":"aperi21:nuclear-fission","title":"핵분열","domain":"modern-physics"},
    {"id":"aperi21:chain-reaction","title":"연쇄 반응","domain":"modern-physics"},
    {"id":"aperi21:nuclear-fusion","title":"핵융합","domain":"modern-physics"},
    {"id":"aperi21:antimatter","title":"반물질","domain":"modern-physics"},
    {"id":"aperi21:band-theory","title":"띠 이론","domain":"modern-physics"},
    {"id":"aperi21:fermi-level","title":"페르미 준위","domain":"modern-physics"},
    {"id":"aperi21:semiconductor-doping","title":"도핑","domain":"modern-physics"},
    {"id":"aperi21:pn-junction","title":"pn 접합","domain":"modern-physics"},
    {"id":"aperi21:diode-and-led","title":"다이오드와 LED","domain":"modern-physics"},
    {"id":"aperi21:transistor-principle","title":"트랜지스터","domain":"modern-physics"},
    {"id":"aperi21:photovoltaic-effect","title":"광전지 효과","domain":"modern-physics"},
    {"id":"aperi21:superconductivity","title":"초전도","domain":"modern-physics"},
    {"id":"aperi21:meissner-effect","title":"마이스너 효과","domain":"modern-physics"},
    {"id":"aperi21:bose-einstein-condensate","title":"보스-아인슈타인 응축","domain":"modern-physics"},
    {"id":"aperi21:scale-of-universe","title":"우주의 규모","domain":"modern-physics"},
    {"id":"aperi21:rutherford-scattering","title":"러더퍼드 산란","domain":"modern-physics"},
    {"id":"aperi21:ionizing-radiation","title":"이온화 복사","domain":"modern-physics"},
    {"id":"aperi21:exchange-particles","title":"교환 입자","domain":"modern-physics"},
  ],
};
