/**
 * 자동 생성 파일 — 직접 편집하지 말 것.
 *
 * 생성: pnpm catalog:gen  (scripts/gen-aperi21-catalog.mts)
 * 출처: 각 sim 의 schema(label/description — description 의 원본은 topics.yaml desc) + docs/topics/topics.yaml(분야).
 */

import type { Aperi21Catalog } from '../catalog-types.js';

export const CATALOG: Aperi21Catalog = {
  locale: "pt",
  domains: [
    {"id":"kinematics","name":"Cinemática"},
    {"id":"newtonian-mechanics","name":"Mecânica newtoniana"},
    {"id":"energy-momentum","name":"Trabalho, energia e momento linear"},
    {"id":"rotation-oscillation","name":"Rotação e oscilação"},
    {"id":"gravitation","name":"Gravitação e astronomia"},
    {"id":"fluids","name":"Fluidos"},
    {"id":"thermodynamics","name":"Física térmica e estatística"},
    {"id":"waves-acoustics","name":"Ondas e acústica"},
    {"id":"optics","name":"Óptica"},
    {"id":"electromagnetism","name":"Eletromagnetismo"},
    {"id":"modern-physics","name":"Física moderna"},
  ],
  entries: [
    {"id":"aperi21:reference-frame","title":"Referencial","description":"Como a descrição do movimento depende do observador","domain":"kinematics"},
    {"id":"aperi21:coordinate-choice","title":"Escolha dos eixos","description":"Como a escolha dos eixos muda as equações","domain":"kinematics"},
    {"id":"aperi21:average-velocity","title":"Velocidade média","description":"Uma única velocidade que representa todo um intervalo","domain":"kinematics"},
    {"id":"aperi21:average-acceleration","title":"Aceleração média","description":"A taxa de variação da velocidade num intervalo, fixada só pelas velocidades no início e no fim","domain":"kinematics"},
    {"id":"aperi21:direction-of-acceleration","title":"Direção da aceleração","description":"No sentido da velocidade, o corpo acelera; em sentido contrário, desacelera","domain":"kinematics"},
    {"id":"aperi21:uniform-motion","title":"Movimento uniforme","description":"Movimento cuja velocidade não muda","domain":"kinematics"},
    {"id":"aperi21:uniformly-accelerated-motion","title":"Movimento uniformemente acelerado","description":"Movimento em que a distância percorrida em cada intervalo igual cresce de uma quantidade fixa","domain":"kinematics"},
    {"id":"aperi21:position-time-graph","title":"Gráfico posição-tempo","description":"Uma representação cuja inclinação é a velocidade","domain":"kinematics"},
    {"id":"aperi21:velocity-time-graph","title":"Gráfico velocidade-tempo","description":"Uma representação em que a área sob a curva se lê como a distância percorrida","domain":"kinematics"},
    {"id":"aperi21:acceleration-time-graph","title":"Gráfico aceleração-tempo","description":"A área sob o gráfico é a variação da velocidade","domain":"kinematics"},
    {"id":"aperi21:free-fall","title":"Queda livre","description":"Movimento só sob a gravidade, em que corpos pesados e leves caem lado a lado","domain":"kinematics"},
    {"id":"aperi21:vertical-throw","title":"Lançamento vertical","description":"A simetria entre subir e descer","domain":"kinematics"},
    {"id":"aperi21:gravitational-acceleration","title":"Aceleração da gravidade","description":"Uma aceleração que não para nem quando a velocidade é zero","domain":"kinematics"},
    {"id":"aperi21:terminal-velocity","title":"Velocidade terminal","description":"A velocidade em que o arrasto e a gravidade se equilibram","domain":"kinematics"},
    {"id":"aperi21:vector-decomposition","title":"Componentes de um vetor","description":"Dividir um vetor segundo as direções dos eixos","domain":"kinematics"},
    {"id":"aperi21:vector-addition","title":"Soma de vetores","description":"Uma soma que une a cauda à ponta","domain":"kinematics"},
    {"id":"aperi21:relative-velocity","title":"Velocidade relativa","description":"Conversão da velocidade entre referenciais","domain":"kinematics"},
    {"id":"aperi21:river-crossing","title":"Atravessar um rio","description":"O trajeto formado pela composição de duas velocidades","domain":"kinematics"},
    {"id":"aperi21:projectile-motion","title":"Movimento de projéteis","description":"A independência das componentes horizontal e vertical","domain":"kinematics"},
    {"id":"aperi21:projectile-range","title":"Alcance e ângulo de lançamento","description":"Como o ângulo de lançamento muda a distância que ele voa","domain":"kinematics"},
    {"id":"aperi21:trajectory-equation","title":"Equação da trajetória","description":"A relação entre distância horizontal e altura que resta quando o tempo é eliminado","domain":"kinematics"},
    {"id":"aperi21:uniform-circular-motion","title":"Movimento circular uniforme","description":"Uma trajetória circular com velocidade constante","domain":"kinematics"},
    {"id":"aperi21:centripetal-acceleration","title":"Aceleração centrípeta","description":"Para onde aponta a variação da velocidade quando a velocidade não muda","domain":"kinematics"},
    {"id":"aperi21:angular-acceleration","title":"Aceleração angular","description":"A taxa de variação da velocidade angular","domain":"kinematics"},
    {"id":"aperi21:tangential-normal-acceleration","title":"Aceleração tangencial e normal","description":"Separando a mudança de velocidade da mudança de direção","domain":"kinematics"},
    {"id":"aperi21:radius-of-curvature","title":"Raio de curvatura","description":"A circunferência com que uma curva se parece localmente","domain":"kinematics"},
    {"id":"aperi21:stopping-distance","title":"Distância de parada","description":"A soma da distância de reação e da distância de frenagem","domain":"kinematics"},
    {"id":"aperi21:newtons-first-law","title":"Referencial inercial","description":"O estado de movimento quando não há força resultante","domain":"newtonian-mechanics"},
    {"id":"aperi21:newtons-second-law","title":"Segunda lei de Newton","description":"Força resultante, massa e aceleração","domain":"newtonian-mechanics"},
    {"id":"aperi21:newtons-third-law","title":"Ação e reação","description":"Um par de forças agindo sobre corpos diferentes","domain":"newtonian-mechanics"},
    {"id":"aperi21:net-force","title":"Força resultante","description":"Soma vetorial de várias forças","domain":"newtonian-mechanics"},
    {"id":"aperi21:free-body-diagram","title":"Diagrama de corpo livre","description":"Isolar as forças sobre um único corpo","domain":"newtonian-mechanics"},
    {"id":"aperi21:inertial-vs-gravitational-mass","title":"Massa inercial e massa gravitacional","description":"Duas definições diferentes dão o mesmo valor","domain":"newtonian-mechanics"},
    {"id":"aperi21:normal-force","title":"Força normal","description":"O empurrão perpendicular de uma superfície de contato","domain":"newtonian-mechanics"},
    {"id":"aperi21:apparent-weight","title":"Peso aparente","description":"Uma balança em um elevador acelerado","domain":"newtonian-mechanics"},
    {"id":"aperi21:static-friction","title":"Atrito estático","description":"A força que segura até o objeto se mover","domain":"newtonian-mechanics"},
    {"id":"aperi21:kinetic-friction","title":"Atrito cinético","description":"Atrito durante o deslizamento","domain":"newtonian-mechanics"},
    {"id":"aperi21:angle-of-friction","title":"Ângulo de atrito","description":"A inclinação em que o deslizamento começa","domain":"newtonian-mechanics"},
    {"id":"aperi21:inclined-plane","title":"Plano inclinado","description":"Decompor a gravidade paralela e perpendicular à rampa","domain":"newtonian-mechanics"},
    {"id":"aperi21:tension","title":"Tração","description":"Como uma corda transmite um puxão","domain":"newtonian-mechanics"},
    {"id":"aperi21:pulley-system","title":"Polias","description":"Um dispositivo em que mais trechos de corda significam menos força e mais corda a puxar","domain":"newtonian-mechanics"},
    {"id":"aperi21:connected-bodies","title":"Corpos ligados","description":"Aceleração de corpos que se movem juntos","domain":"newtonian-mechanics"},
    {"id":"aperi21:spring-force","title":"Força elástica","description":"Força restauradora proporcional ao alongamento","domain":"newtonian-mechanics"},
    {"id":"aperi21:centripetal-force","title":"Força centrípeta","description":"A força para dentro que sustenta o movimento circular, e o caminho tomado quando ela desaparece","domain":"newtonian-mechanics"},
    {"id":"aperi21:conical-pendulum","title":"Pêndulo cônico","description":"Movimento circular pela tração e pela gravidade","domain":"newtonian-mechanics"},
    {"id":"aperi21:banked-curve","title":"Curva sobrelevada","description":"O ângulo de inclinação que faz um carro fazer a curva sem atrito","domain":"newtonian-mechanics"},
    {"id":"aperi21:vertical-loop","title":"Loop vertical","description":"O ponto em que um corpo deixa o trilho quando não tem velocidade suficiente para dar a volta ao loop","domain":"newtonian-mechanics"},
    {"id":"aperi21:drag-force","title":"Resistência do ar","description":"Uma resistência proporcional à primeira e à segunda potência da velocidade","domain":"newtonian-mechanics"},
    {"id":"aperi21:buoyant-force-as-force","title":"O empuxo como força","description":"O empurrão para cima de um fluido","domain":"newtonian-mechanics"},
    {"id":"aperi21:non-inertial-frame","title":"Referencial não inercial","description":"O movimento visto de um referencial acelerado","domain":"newtonian-mechanics"},
    {"id":"aperi21:fictitious-force","title":"Força fictícia","description":"A força aparente de um referencial não inercial","domain":"newtonian-mechanics"},
    {"id":"aperi21:coriolis-effect","title":"Efeito Coriolis","description":"Uma trajetória que se curva em um referencial em rotação","domain":"newtonian-mechanics"},
    {"id":"aperi21:impulse-force-relation","title":"Força e impulso","description":"Uma força curta e grande e outra longa e pequena","domain":"newtonian-mechanics"},
    {"id":"aperi21:equilibrium-of-forces","title":"Equilíbrio de forças","description":"Força resultante nula","domain":"newtonian-mechanics"},
    {"id":"aperi21:atwood-machine","title":"Máquina de Atwood","description":"Um sistema de dois pesos ligados por uma roldana","domain":"newtonian-mechanics"},
    {"id":"aperi21:balance-scale","title":"Equilibrar uma balança","description":"Equilíbrio definido ao mesmo tempo pelo comprimento do braço e pelo peso","domain":"newtonian-mechanics"},
    {"id":"aperi21:mechanical-advantage","title":"Vantagem mecânica","description":"Como alavancas e rampas trocam uma força menor por uma distância maior","domain":"newtonian-mechanics"},
    {"id":"aperi21:youngs-modulus","title":"Módulo de Young","description":"Uma rigidez que pertence ao material, não a um só fio","domain":"newtonian-mechanics"},
    {"id":"aperi21:stress-strain-curve","title":"Curva tensão–deformação","description":"Como um material responde ao ser puxado","domain":"newtonian-mechanics"},
    {"id":"aperi21:work-by-variable-force","title":"Trabalho realizado por uma força variável","description":"A área sob o gráfico força–deslocamento","domain":"energy-momentum"},
    {"id":"aperi21:kinetic-energy","title":"Energia cinética","description":"A energia que a velocidade carrega","domain":"energy-momentum"},
    {"id":"aperi21:work-energy-theorem","title":"Teorema do trabalho-energia","description":"Como quer que se dividam força e distância, o mesmo trabalho dá a mesma velocidade final","domain":"energy-momentum"},
    {"id":"aperi21:gravitational-potential-energy","title":"Energia potencial gravitacional","description":"Energia armazenada na altura","domain":"energy-momentum"},
    {"id":"aperi21:elastic-potential-energy","title":"Energia potencial elástica","description":"A energia armazenada em uma deformação","domain":"energy-momentum"},
    {"id":"aperi21:conservative-force","title":"Força conservativa","description":"Uma força que realiza o mesmo trabalho qualquer que seja o caminho","domain":"energy-momentum"},
    {"id":"aperi21:non-conservative-force","title":"Força não conservativa","description":"Trabalho que depende da trajetória","domain":"energy-momentum"},
    {"id":"aperi21:conservation-of-mechanical-energy","title":"Conservação da energia mecânica","description":"A parte guardada na posição e a parte guardada no movimento trocam de lugar enquanto a soma se mantém","domain":"energy-momentum"},
    {"id":"aperi21:energy-dissipation","title":"Dissipação de energia","description":"A parcela que o atrito leva, e para onde ela vai","domain":"energy-momentum"},
    {"id":"aperi21:potential-energy-curve","title":"Curva de energia potencial","description":"Como a forma da curva decide o movimento","domain":"energy-momentum"},
    {"id":"aperi21:equilibrium-points","title":"Pontos de equilíbrio","description":"Equilíbrio estável, instável e indiferente","domain":"energy-momentum"},
    {"id":"aperi21:efficiency","title":"Eficiência","description":"A parte do que entra que sai como saída útil","domain":"energy-momentum"},
    {"id":"aperi21:impulse-momentum-theorem","title":"Teorema do impulso e da quantidade de movimento","description":"O impulso é igual à variação da quantidade de movimento","domain":"energy-momentum"},
    {"id":"aperi21:conservation-of-momentum","title":"Conservação da quantidade de movimento","description":"Quantidade de movimento total quando nenhuma força externa atua","domain":"energy-momentum"},
    {"id":"aperi21:elastic-collision","title":"Colisão elástica","description":"Uma colisão em que os corpos trocam de velocidade","domain":"energy-momentum"},
    {"id":"aperi21:inelastic-collision","title":"Colisão inelástica","description":"Uma colisão em que uma parte não é devolvida","domain":"energy-momentum"},
    {"id":"aperi21:perfectly-inelastic-collision","title":"Colisão perfeitamente inelástica","description":"Quando os dois se movem juntos, grudados","domain":"energy-momentum"},
    {"id":"aperi21:two-dimensional-collision","title":"Colisão bidimensional","description":"Uma conservação que vale separadamente para cada componente","domain":"energy-momentum"},
    {"id":"aperi21:center-of-mass-motion","title":"Movimento do centro de massa","description":"O movimento que as forças internas não conseguem mudar","domain":"energy-momentum"},
    {"id":"aperi21:explosion-and-recoil","title":"Explosão e recuo","description":"Quando um sistema em repouso se separa","domain":"energy-momentum"},
    {"id":"aperi21:rocket-equation","title":"A equação do foguete","description":"Velocidade obtida ao lançar combustível fora","domain":"energy-momentum"},
    {"id":"aperi21:ballistic-pendulum","title":"Pêndulo balístico","description":"A medição que liga uma colisão à conservação da energia","domain":"energy-momentum"},
    {"id":"aperi21:energy-in-collision","title":"Energia nas colisões","description":"Distinguir o que se conserva do que não se conserva","domain":"energy-momentum"},
    {"id":"aperi21:energy-flow-diagram","title":"Diagrama de fluxo de energia","description":"Para onde vai a energia, mostrado pela espessura dos ramos","domain":"energy-momentum"},
    {"id":"aperi21:torque","title":"Torque","description":"O que faz as coisas girarem, e o comprimento do braço de alavanca","domain":"rotation-oscillation"},
    {"id":"aperi21:moment-of-inertia","title":"Momento de inércia","description":"Como a distribuição de massa define a resistência à rotação","domain":"rotation-oscillation"},
    {"id":"aperi21:parallel-axis-theorem","title":"Teorema dos eixos paralelos","description":"Momento de inércia quando o eixo é deslocado","domain":"rotation-oscillation"},
    {"id":"aperi21:rotational-kinetic-energy","title":"Energia cinética de rotação","description":"A energia que o giro carrega","domain":"rotation-oscillation"},
    {"id":"aperi21:angular-momentum","title":"Momento angular","description":"A grandeza que faz o que gira manter o seu eixo","domain":"rotation-oscillation"},
    {"id":"aperi21:conservation-of-angular-momentum","title":"Conservação do momento angular","description":"Por que recolher os braços faz você girar mais rápido","domain":"rotation-oscillation"},
    {"id":"aperi21:rolling-without-slipping","title":"Rolamento sem deslizamento","description":"O vínculo que liga a translação à rotação","domain":"rotation-oscillation"},
    {"id":"aperi21:rolling-race","title":"Corrida de objetos rolando","description":"Ordem de chegada definida pela distribuição de massa","domain":"rotation-oscillation"},
    {"id":"aperi21:static-equilibrium","title":"Equilíbrio estático","description":"A força resultante e o torque resultante são ambos nulos","domain":"rotation-oscillation"},
    {"id":"aperi21:center-of-gravity","title":"Centro de gravidade","description":"O ponto que decide quando algo tomba","domain":"rotation-oscillation"},
    {"id":"aperi21:gyroscopic-precession","title":"Precessão giroscópica","description":"O torque girando a direção do momento angular","domain":"rotation-oscillation"},
    {"id":"aperi21:angular-momentum-vector","title":"Direção do momento angular","description":"A regra da mão direita e o eixo de rotação","domain":"rotation-oscillation"},
    {"id":"aperi21:simple-harmonic-motion","title":"Movimento harmônico simples","description":"Movimento sob uma força restauradora proporcional ao deslocamento","domain":"rotation-oscillation"},
    {"id":"aperi21:shm-energy","title":"Energia no movimento harmônico simples","description":"As energias cinética e potencial trocam de lugar","domain":"rotation-oscillation"},
    {"id":"aperi21:mass-spring-system","title":"Massa presa a uma mola","description":"O período definido pela massa e pela constante elástica","domain":"rotation-oscillation"},
    {"id":"aperi21:simple-pendulum","title":"Pêndulo simples","description":"O período em pequena amplitude","domain":"rotation-oscillation"},
    {"id":"aperi21:physical-pendulum","title":"Pêndulo físico","description":"Oscilação de um corpo extenso","domain":"rotation-oscillation"},
    {"id":"aperi21:pendulum-amplitude-dependence","title":"Amplitude e período","description":"O isocronismo que se quebra em grandes amplitudes","domain":"rotation-oscillation"},
    {"id":"aperi21:damped-oscillation","title":"Oscilação amortecida","description":"Uma oscilação que perde energia","domain":"rotation-oscillation"},
    {"id":"aperi21:damping-regimes","title":"Três regimes de amortecimento","description":"Movimento subamortecido, criticamente amortecido e superamortecido","domain":"rotation-oscillation"},
    {"id":"aperi21:driven-oscillation","title":"Oscilação forçada","description":"A resposta a uma excitação externa","domain":"rotation-oscillation"},
    {"id":"aperi21:resonance","title":"Ressonância","description":"Quando a frequência de excitação coincide com a frequência natural","domain":"rotation-oscillation"},
    {"id":"aperi21:quality-factor","title":"Fator de qualidade","description":"Quanto mais aguda a ressonância, mais tempo continua a vibrar","domain":"rotation-oscillation"},
    {"id":"aperi21:coupled-oscillators","title":"Osciladores acoplados","description":"Dois osciladores trocando energia","domain":"rotation-oscillation"},
    {"id":"aperi21:normal-modes","title":"Modos normais","description":"As formas naturais em que um sistema vibra","domain":"rotation-oscillation"},
    {"id":"aperi21:beats-in-oscillation","title":"Batimentos na oscilação","description":"A soma de duas frequências próximas","domain":"rotation-oscillation"},
    {"id":"aperi21:phase-space","title":"Espaço de fases","description":"O movimento visto no plano posição–velocidade","domain":"rotation-oscillation"},
    {"id":"aperi21:nonlinear-oscillation","title":"Oscilação não linear","description":"Quando a força restauradora deixa de ser proporcional","domain":"rotation-oscillation"},
    {"id":"aperi21:gears","title":"Engrenagens","description":"Como o número de dentes troca velocidade de giro por torque","domain":"rotation-oscillation"},
    {"id":"aperi21:newtons-law-of-gravitation","title":"Lei da gravitação universal de Newton","description":"Uma força que diminui com o quadrado da distância","domain":"gravitation"},
    {"id":"aperi21:gravitational-field","title":"Campo gravitacional","description":"A intensidade da gravidade espalhada pelo espaço","domain":"gravitation"},
    {"id":"aperi21:range-and-surface-gravity","title":"Gravidade e alcance","description":"Como um mesmo lançamento vai mais longe onde a gravidade é mais fraca","domain":"gravitation"},
    {"id":"aperi21:shell-theorem","title":"Teorema das cascas","description":"Gravidade dentro e fora de uma casca esférica","domain":"gravitation"},
    {"id":"aperi21:gravity-inside-earth","title":"Gravidade dentro da Terra","description":"Gravidade que enfraquece com a profundidade","domain":"gravitation"},
    {"id":"aperi21:gravitational-potential-energy-general","title":"Energia potencial gravitacional (geral)","description":"Uma energia negativa medida a partir do infinito","domain":"gravitation"},
    {"id":"aperi21:escape-velocity","title":"Velocidade de escape","description":"A menor velocidade que escapa da gravidade","domain":"gravitation"},
    {"id":"aperi21:orbital-velocity","title":"Velocidade orbital","description":"A velocidade que mantém uma órbita circular","domain":"gravitation"},
    {"id":"aperi21:circular-orbit","title":"Órbita circular","description":"Movimento em que a gravidade é a força centrípeta","domain":"gravitation"},
    {"id":"aperi21:elliptical-orbit","title":"Órbita elíptica","description":"O corpo central fica em um foco","domain":"gravitation"},
    {"id":"aperi21:keplers-first-law","title":"Primeira lei de Kepler","description":"Órbitas elípticas com o Sol num dos focos","domain":"gravitation"},
    {"id":"aperi21:keplers-second-law","title":"Segunda lei de Kepler","description":"Áreas iguais em tempos iguais","domain":"gravitation"},
    {"id":"aperi21:keplers-third-law","title":"Terceira lei de Kepler","description":"O tempo de uma volta, que cresce muito mais depressa que o raio","domain":"gravitation"},
    {"id":"aperi21:two-body-problem","title":"Problema de dois corpos","description":"Dois corpos orbitando seu centro de massa comum","domain":"gravitation"},
    {"id":"aperi21:tidal-force","title":"Força de maré","description":"Estiramento causado por uma diferença de gravidade","domain":"gravitation"},
    {"id":"aperi21:roche-limit","title":"Limite de Roche","description":"A distância em que as marés despedaçam um corpo","domain":"gravitation"},
    {"id":"aperi21:weightlessness","title":"Imponderabilidade","description":"Peso aparente em queda livre","domain":"gravitation"},
    {"id":"aperi21:geostationary-orbit","title":"Órbita geoestacionária","description":"Uma órbita sobre o equador com o mesmo período que a rotação da Terra","domain":"gravitation"},
    {"id":"aperi21:gravitational-slingshot","title":"Assistência gravitacional","description":"Mudar de velocidade passando por um planeta","domain":"gravitation"},
    {"id":"aperi21:lagrange-points","title":"Pontos de Lagrange","description":"Cinco lugares que acompanham o passo de dois corpos que orbitam juntos","domain":"gravitation"},
    {"id":"aperi21:orbital-transfer","title":"Transferência orbital","description":"A transferência de Hohmann de uma órbita baixa para uma mais alta","domain":"gravitation"},
    {"id":"aperi21:black-hole-horizon","title":"Horizonte de eventos","description":"O raio em que a velocidade de escape atinge a da luz","domain":"gravitation"},
    {"id":"aperi21:diurnal-motion","title":"Movimento diurno","description":"O caminho pelo qual todo o céu noturno gira em torno de um ponto ao longo de um dia","domain":"gravitation"},
    {"id":"aperi21:earth-rotation-day-night","title":"A rotação da Terra, o dia e a noite","description":"Por que o dia e a noite se alternam numa Terra que gira","domain":"gravitation"},
    {"id":"aperi21:earth-revolution-constellations","title":"A órbita da Terra e as constelações","description":"Por que as constelações que vemos mudam com as estações","domain":"gravitation"},
    {"id":"aperi21:solar-altitude-shadow","title":"Altura do Sol e sombras","description":"Quando a altura muda, o comprimento da sombra e a área sobre a qual a luz do Sol se espalha mudam juntos","domain":"gravitation"},
    {"id":"aperi21:seasonal-sun-path","title":"O caminho do Sol ao longo das estações","description":"Como a altura do Sol ao meio-dia e a duração do dia mudam juntas","domain":"gravitation"},
    {"id":"aperi21:axial-tilt-seasons","title":"A inclinação do eixo e as estações","description":"As estações criadas por uma Terra que orbita inclinada","domain":"gravitation"},
    {"id":"aperi21:moon-phases","title":"Fases da Lua","description":"Que parte da Lua iluminada pelo Sol fica voltada para nós","domain":"gravitation"},
    {"id":"aperi21:eclipse","title":"Eclipses solares e lunares","description":"Quando o Sol, a Terra e a Lua se alinham","domain":"gravitation"},
    {"id":"aperi21:stellar-parallax","title":"Paralaxe estelar","description":"O ângulo em que uma estrela próxima se desloca enquanto a Terra orbita o Sol","domain":"gravitation"},
    {"id":"aperi21:apparent-brightness","title":"Brilho aparente","description":"Como uma mesma estrela parece mais ou menos brilhante conforme a distância","domain":"gravitation"},
    {"id":"aperi21:magnitude-scale","title":"Magnitude estelar","description":"Como o brilho é expresso em magnitude","domain":"gravitation"},
    {"id":"aperi21:star-color-temperature","title":"Cor das estrelas e temperatura da superfície","description":"Como a temperatura da superfície define a cor da luz das estrelas","domain":"gravitation"},
    {"id":"aperi21:expanding-universe","title":"O universo em expansão","description":"Galáxias se afastando em todas as direções","domain":"gravitation"},
    {"id":"aperi21:stellar-luminosity","title":"Luminosidade","description":"Quanta luz uma estrela realmente emite","domain":"gravitation"},
    {"id":"aperi21:hr-diagram","title":"Diagrama HR","description":"O diagrama temperatura–luminosidade de um aglomerado, em que as estrelas mais pesadas deixam primeiro a sequência principal com a idade","domain":"gravitation"},
    {"id":"aperi21:star-radiation-gravity-balance","title":"Equilíbrio entre pressão de radiação e gravidade","description":"Por que uma estrela nem colapsa nem se desfaz","domain":"gravitation"},
    {"id":"aperi21:orbital-decay","title":"Decaimento orbital","description":"Uma órbita freada pelo ar rarefeito","domain":"gravitation"},
    {"id":"aperi21:inverse-square-law","title":"Lei do inverso do quadrado","description":"Fica mais rarefeito à medida que se espalha","domain":"gravitation"},
    {"id":"aperi21:stellar-nucleosynthesis","title":"Nucleossíntese estelar","description":"A fusão no núcleo de uma estrela, que forma elementos mais pesados passo a passo até o ferro","domain":"gravitation"},
    {"id":"aperi21:star-life-cycle","title":"Ciclo de vida de uma estrela","description":"Como a massa decide o caminho de uma estrela","domain":"gravitation"},
    {"id":"aperi21:stellar-spectral-class","title":"Classes espectrais estelares","description":"Padrões de linhas de absorção definidos pela temperatura","domain":"gravitation"},
    {"id":"aperi21:supernova-and-neutron-star","title":"Supernova e estrela de nêutrons","description":"Um colapso final e um ricochete","domain":"gravitation"},
    {"id":"aperi21:exoplanet-detection","title":"Detectando exoplanetas","description":"Os rastros que um planeta deixa","domain":"gravitation"},
    {"id":"aperi21:projectile-in-wind","title":"Vento e alcance","description":"Como o vento desloca o ponto de queda de um mesmo lançamento","domain":"fluids"},
    {"id":"aperi21:pressure-isotropy","title":"Isotropia da pressão","description":"A mesma intensidade qualquer que seja a direção","domain":"fluids"},
    {"id":"aperi21:hydrostatic-pressure","title":"Pressão hidrostática","description":"Pressão que cresce com a profundidade","domain":"fluids"},
    {"id":"aperi21:pressure-and-container-shape","title":"Forma do recipiente e pressão no fundo","description":"Como a pressão no fundo não depende da forma","domain":"fluids"},
    {"id":"aperi21:atmospheric-pressure","title":"Pressão atmosférica","description":"O peso da coluna de ar","domain":"fluids"},
    {"id":"aperi21:barometer","title":"Barômetro","description":"A altura de uma coluna de mercúrio","domain":"fluids"},
    {"id":"aperi21:manometer","title":"Manômetro","description":"Ler a pressão numa coluna de líquido","domain":"fluids"},
    {"id":"aperi21:pascals-principle","title":"Princípio de Pascal","description":"A pressão transmitida e a prensa hidráulica","domain":"fluids"},
    {"id":"aperi21:buoyancy","title":"Empuxo","description":"A força para cima que sobra porque a face de baixo é empurrada com mais força","domain":"fluids"},
    {"id":"aperi21:archimedes-principle","title":"Princípio de Arquimedes — a intensidade do empuxo","description":"A força recebida é igual ao peso do fluido deslocado","domain":"fluids"},
    {"id":"aperi21:floating-and-draft","title":"Quanto afunda um corpo que flutua","description":"O que define o volume submerso","domain":"fluids"},
    {"id":"aperi21:stability-of-floating-body","title":"Estabilidade de um corpo flutuante","description":"A relação entre o centro de gravidade e o centro de impulsão","domain":"fluids"},
    {"id":"aperi21:continuity-equation","title":"Equação da continuidade","description":"Seção transversal e velocidade do escoamento se compensam","domain":"fluids"},
    {"id":"aperi21:bernoullis-principle","title":"Princípio de Bernoulli","description":"A troca entre velocidade e pressão","domain":"fluids"},
    {"id":"aperi21:venturi-effect","title":"Efeito Venturi","description":"Pressão menor onde o tubo se estreita","domain":"fluids"},
    {"id":"aperi21:torricellis-law","title":"Lei de Torricelli","description":"A velocidade do escoamento que sai por um orifício","domain":"fluids"},
    {"id":"aperi21:lift-force","title":"Sustentação","description":"Como o ar flui por cima e por baixo de uma asa","domain":"fluids"},
    {"id":"aperi21:viscosity","title":"Viscosidade","description":"Atrito entre camadas","domain":"fluids"},
    {"id":"aperi21:poiseuille-flow","title":"Escoamento laminar em um tubo","description":"A vazão cresce com a quarta potência do raio","domain":"fluids"},
    {"id":"aperi21:stokes-drag","title":"Arrasto de Stokes","description":"Num escoamento lento, uma esfera com o dobro do raio afunda quatro vezes mais depressa","domain":"fluids"},
    {"id":"aperi21:laminar-vs-turbulent","title":"Escoamento laminar e turbulento","description":"Dois regimes de escoamento","domain":"fluids"},
    {"id":"aperi21:reynolds-number","title":"Número de Reynolds","description":"O número adimensional que define o caráter de um escoamento","domain":"fluids"},
    {"id":"aperi21:boundary-layer","title":"Camada limite","description":"A camada fina em que a velocidade do escoamento sobe de zero na parede até a do escoamento externo","domain":"fluids"},
    {"id":"aperi21:surface-tension","title":"Tensão superficial","description":"A tração da superfície da água que muda de direção para sustentar uma carga","domain":"fluids"},
    {"id":"aperi21:laplace-pressure","title":"Pressão de Laplace","description":"O salto de pressão que uma superfície curva cria","domain":"fluids"},
    {"id":"aperi21:capillary-action","title":"Capilaridade","description":"Subida e descida em tubos estreitos","domain":"fluids"},
    {"id":"aperi21:wetting-and-contact-angle","title":"Molhamento e ângulo de contato","description":"Quanto um líquido se espalha sobre um sólido","domain":"fluids"},
    {"id":"aperi21:drag-in-fluid","title":"Arrasto em um fluido","description":"A resistência num escoamento rápido definida pela forma da parte de trás","domain":"fluids"},
    {"id":"aperi21:thermal-equilibrium","title":"Equilíbrio térmico","description":"O estado que dois sistemas em contato atingem","domain":"thermodynamics"},
    {"id":"aperi21:specific-heat","title":"Calor específico","description":"Quanto a temperatura muda, material por material","domain":"thermodynamics"},
    {"id":"aperi21:calorimetry","title":"Calorimetria","description":"A temperatura final de uma mistura","domain":"thermodynamics"},
    {"id":"aperi21:latent-heat","title":"Calor latente","description":"Por que a temperatura para durante uma mudança de estado","domain":"thermodynamics"},
    {"id":"aperi21:phase-diagram","title":"Diagrama de fases","description":"A fase definida pela pressão e pela temperatura","domain":"thermodynamics"},
    {"id":"aperi21:triple-point","title":"Ponto triplo","description":"A condição em que três fases coexistem","domain":"thermodynamics"},
    {"id":"aperi21:thermal-conduction","title":"Condução de calor","description":"Calor que se propaga por um material, depressa no aço e devagar na madeira","domain":"thermodynamics"},
    {"id":"aperi21:thermal-convection","title":"Convecção","description":"Calor transportado por um fluido em movimento","domain":"thermodynamics"},
    {"id":"aperi21:thermal-radiation","title":"Radiação térmica","description":"Calor que se propaga sem um meio","domain":"thermodynamics"},
    {"id":"aperi21:stefan-boltzmann-law","title":"Lei de Stefan–Boltzmann","description":"Radiação que cresce com a quarta potência da temperatura","domain":"thermodynamics"},
    {"id":"aperi21:thermal-expansion","title":"Dilatação térmica","description":"A variação do comprimento de um sólido com a temperatura","domain":"thermodynamics"},
    {"id":"aperi21:bimetal","title":"Lâmina bimetálica","description":"Curvatura por dilatação desigual","domain":"thermodynamics"},
    {"id":"aperi21:ideal-gas-law","title":"Lei dos gases ideais","description":"Como pressão, volume e temperatura se relacionam","domain":"thermodynamics"},
    {"id":"aperi21:boyles-law","title":"Lei de Boyle","description":"Pressão e volume a temperatura constante","domain":"thermodynamics"},
    {"id":"aperi21:charles-law","title":"Lei de Charles","description":"Volume e temperatura a pressão constante","domain":"thermodynamics"},
    {"id":"aperi21:gas-pressure","title":"Moléculas e pressão","description":"Como, ao subir a temperatura, as moléculas batem na parede com mais frequência e mais força, e a pressão sobe","domain":"thermodynamics"},
    {"id":"aperi21:pressure-from-collisions","title":"Pressão devida às colisões","description":"Com mais força e mais vezes: a pressão na parede cresce com o quadrado da velocidade das moléculas","domain":"thermodynamics"},
    {"id":"aperi21:maxwell-boltzmann-distribution","title":"Distribuição de Maxwell–Boltzmann","description":"A distribuição das velocidades moleculares","domain":"thermodynamics"},
    {"id":"aperi21:mean-free-path","title":"Livre caminho médio","description":"A distância entre colisões","domain":"thermodynamics"},
    {"id":"aperi21:first-law-of-thermodynamics","title":"Primeira lei da termodinâmica","description":"Como se relacionam energia interna, trabalho e calor","domain":"thermodynamics"},
    {"id":"aperi21:pv-diagram","title":"Diagrama PV","description":"Onde a área é trabalho","domain":"thermodynamics"},
    {"id":"aperi21:isothermal-process","title":"Processo isotérmico","description":"Uma mudança que mantém a temperatura fixa","domain":"thermodynamics"},
    {"id":"aperi21:adiabatic-process","title":"Processo adiabático","description":"Uma mudança sem calor entrando nem saindo","domain":"thermodynamics"},
    {"id":"aperi21:isobaric-isochoric","title":"Processos isobárico e isocórico","description":"Mudanças a pressão fixa ou a volume fixo","domain":"thermodynamics"},
    {"id":"aperi21:cyclic-process","title":"Processo cíclico","description":"Uma mudança que volta ao ponto onde começou","domain":"thermodynamics"},
    {"id":"aperi21:second-law-of-thermodynamics","title":"Segunda lei da termodinâmica","description":"Uma mudança que só vai num sentido","domain":"thermodynamics"},
    {"id":"aperi21:irreversibility","title":"Entropia e irreversibilidade","description":"Por que não pode ser desfeito","domain":"thermodynamics"},
    {"id":"aperi21:heat-engine","title":"Máquina térmica","description":"Um ciclo que converte só parte do seu calor em trabalho e cede o resto ao lado frio","domain":"thermodynamics"},
    {"id":"aperi21:carnot-cycle","title":"Ciclo de Carnot","description":"A eficiência máxima teórica","domain":"thermodynamics"},
    {"id":"aperi21:refrigerator-heat-pump","title":"Refrigeradores e bombas de calor","description":"Mover calor fornecendo trabalho","domain":"thermodynamics"},
    {"id":"aperi21:brownian-motion","title":"Movimento browniano","description":"Movimento aleatório causado por colisões moleculares","domain":"thermodynamics"},
    {"id":"aperi21:diffusion","title":"Difusão","description":"Fluxo impulsionado por uma diferença de concentração","domain":"thermodynamics"},
    {"id":"aperi21:random-walk","title":"Passeio aleatório","description":"O espalhamento em torno do ponto de partida, que só cresce com a raiz quadrada do número de passos","domain":"thermodynamics"},
    {"id":"aperi21:statistical-fluctuation","title":"Flutuação estatística","description":"A oscilação que cresce quando há poucas partículas","domain":"thermodynamics"},
    {"id":"aperi21:maxwells-demon","title":"O demônio de Maxwell","description":"Um gás que se separa na medida em que é observado","domain":"thermodynamics"},
    {"id":"aperi21:insulation","title":"Isolamento térmico","description":"Desacelerar o fluxo de calor","domain":"thermodynamics"},
    {"id":"aperi21:albedo","title":"Albedo","description":"A fração de luz devolvida","domain":"thermodynamics"},
    {"id":"aperi21:radiative-equilibrium","title":"Equilíbrio radiativo","description":"A temperatura que se fixa quando o que sai iguala o que entra","domain":"thermodynamics"},
    {"id":"aperi21:greenhouse-effect","title":"Efeito estufa","description":"Uma camada que devolve o infravermelho para baixo aquece o solo","domain":"thermodynamics"},
    {"id":"aperi21:wave-basics","title":"Grandezas básicas de uma onda","description":"Comprimento de onda, frequência, velocidade e amplitude","domain":"waves-acoustics"},
    {"id":"aperi21:wave-vs-particle-transport","title":"O que uma onda transporta","description":"O meio fica no lugar, a energia segue adiante","domain":"waves-acoustics"},
    {"id":"aperi21:transverse-wave","title":"Onda transversal","description":"O meio vibra em ângulo reto com a direção em que a onda se propaga","domain":"waves-acoustics"},
    {"id":"aperi21:longitudinal-wave","title":"Onda longitudinal","description":"Vibração paralela à direção de propagação","domain":"waves-acoustics"},
    {"id":"aperi21:wave-speed-in-medium","title":"A velocidade da onda e o meio","description":"A velocidade definida pela tração e pela densidade linear","domain":"waves-acoustics"},
    {"id":"aperi21:wavefront-and-ray","title":"Frentes de onda e raios","description":"Superfícies de mesma fase e as linhas normais a elas","domain":"waves-acoustics"},
    {"id":"aperi21:huygens-principle","title":"Princípio de Huygens","description":"Cada ponto de uma frente de onda torna-se uma nova fonte","domain":"waves-acoustics"},
    {"id":"aperi21:superposition","title":"Superposição","description":"O que acontece quando ondas se sobrepõem","domain":"waves-acoustics"},
    {"id":"aperi21:constructive-destructive","title":"Interferência construtiva e destrutiva","description":"Como a diferença de fase define o tamanho da soma","domain":"waves-acoustics"},
    {"id":"aperi21:interference","title":"Interferência","description":"O padrão formado por duas fontes","domain":"waves-acoustics"},
    {"id":"aperi21:standing-wave","title":"Onda estacionária","description":"Uma onda cujos nós e ventres ficam fixos","domain":"waves-acoustics"},
    {"id":"aperi21:harmonics","title":"Harmônicos","description":"Frequências definidas pela fronteira","domain":"waves-acoustics"},
    {"id":"aperi21:string-vibration","title":"Corda vibrante","description":"A altura do som definida pelo comprimento que vibra","domain":"waves-acoustics"},
    {"id":"aperi21:air-column-resonance","title":"Ressonância em colunas de ar","description":"Tubo aberto versus tubo fechado","domain":"waves-acoustics"},
    {"id":"aperi21:beats","title":"Batimentos","description":"A soma de duas frequências próximas","domain":"waves-acoustics"},
    {"id":"aperi21:doppler-effect","title":"Efeito Doppler","description":"Como uma fonte em movimento separa o espaçamento das frentes de onda à frente e atrás","domain":"waves-acoustics"},
    {"id":"aperi21:doppler-source-vs-observer","title":"Fonte em movimento vs. observador em movimento","description":"A assimetria de quem está se movendo","domain":"waves-acoustics"},
    {"id":"aperi21:shock-wave","title":"Onda de choque","description":"O cone que se forma além da velocidade do som","domain":"waves-acoustics"},
    {"id":"aperi21:sound-intensity","title":"Intensidade sonora","description":"A intensidade cai com o quadrado da distância enquanto o nível em decibéis baixa só um pouco","domain":"waves-acoustics"},
    {"id":"aperi21:reflection-of-waves","title":"Reflexão de ondas","description":"Fase em uma extremidade fixa e em uma extremidade livre","domain":"waves-acoustics"},
    {"id":"aperi21:refraction-of-waves","title":"Refração das ondas","description":"Uma mudança de velocidade altera a direção","domain":"waves-acoustics"},
    {"id":"aperi21:diffraction","title":"Difração","description":"Ondas que contornam obstáculos","domain":"waves-acoustics"},
    {"id":"aperi21:slit-width-and-diffraction","title":"Largura da Fenda e Difração","description":"Como a razão entre abertura e comprimento de onda define o espalhamento","domain":"waves-acoustics"},
    {"id":"aperi21:wave-energy","title":"Energia de uma onda","description":"A energia cresce com o quadrado da amplitude","domain":"waves-acoustics"},
    {"id":"aperi21:wave-attenuation","title":"Atenuação de uma onda","description":"Uma amplitude que diminui na mesma proporção a cada distância igual","domain":"waves-acoustics"},
    {"id":"aperi21:impedance-mismatch","title":"Descasamento de impedância","description":"Quanto se reflete numa fronteira","domain":"waves-acoustics"},
    {"id":"aperi21:noise-cancellation","title":"Cancelamento ativo de ruído","description":"Superposição de uma onda invertida","domain":"waves-acoustics"},
    {"id":"aperi21:sound-source-vibration","title":"Som e vibração","description":"Um objeto que soa vibra, e quando a vibração para, o som também para","domain":"waves-acoustics"},
    {"id":"aperi21:sound-through-materials","title":"O som através dos materiais","description":"A velocidade do som e a sua passagem, definidas pelo meio","domain":"waves-acoustics"},
    {"id":"aperi21:digital-vs-analog-signal","title":"Sinais digitais e analógicos","description":"Duas formas de resistir ao ruído","domain":"waves-acoustics"},
    {"id":"aperi21:seismic-waves","title":"Ondas sísmicas","description":"As zonas de sombra criadas quando o núcleo externo líquido barra as ondas S e desvia as ondas P","domain":"waves-acoustics"},
    {"id":"aperi21:rectilinear-propagation","title":"A luz se propaga em linha reta","description":"As sombras e o modelo de raios","domain":"optics"},
    {"id":"aperi21:shadow-umbra-penumbra","title":"Umbra e penumbra","description":"Como o tamanho de uma fonte de luz molda a borda de uma sombra","domain":"optics"},
    {"id":"aperi21:pinhole-camera","title":"Câmara escura de orifício","description":"A imagem formada por um único orifício","domain":"optics"},
    {"id":"aperi21:law-of-reflection","title":"Lei da reflexão","description":"Ângulo de incidência e ângulo de reflexão","domain":"optics"},
    {"id":"aperi21:specular-diffuse-reflection","title":"Reflexão especular e difusa","description":"Reflexão definida pela rugosidade da superfície","domain":"optics"},
    {"id":"aperi21:plane-mirror-image","title":"Imagem em um espelho plano","description":"A imagem virtual atrás do espelho, onde se cruza a luz prolongada para trás","domain":"optics"},
    {"id":"aperi21:multiple-mirror-images","title":"Imagens em dois espelhos","description":"Como o ângulo entre dois espelhos define o número de imagens","domain":"optics"},
    {"id":"aperi21:concave-mirror","title":"Espelho côncavo","description":"Imagem real enquanto o objeto está fora do foco, virtual quando está dentro","domain":"optics"},
    {"id":"aperi21:convex-mirror","title":"Espelho convexo","description":"Um campo de visão mais amplo e uma imagem virtual pequena e direita","domain":"optics"},
    {"id":"aperi21:snells-law","title":"Lei de Snell","description":"Como o caminho se desvia conforme o meio","domain":"optics"},
    {"id":"aperi21:apparent-depth","title":"Profundidade aparente","description":"Por que objetos debaixo d'água parecem elevados","domain":"optics"},
    {"id":"aperi21:total-internal-reflection","title":"Reflexão interna total","description":"O ângulo crítico e sua condição","domain":"optics"},
    {"id":"aperi21:optical-fiber","title":"Fibra óptica","description":"Luz aprisionada por reflexão interna total","domain":"optics"},
    {"id":"aperi21:mirage","title":"Miragem","description":"Luz curvada por um gradiente de densidade","domain":"optics"},
    {"id":"aperi21:dispersion","title":"Dispersão","description":"Índice de refração que depende do comprimento de onda","domain":"optics"},
    {"id":"aperi21:prism","title":"Prisma","description":"Um espectro espalhado pela dispersão","domain":"optics"},
    {"id":"aperi21:rainbow","title":"Arco-íris","description":"Refração e reflexão dentro das gotas de chuva","domain":"optics"},
    {"id":"aperi21:thin-lens","title":"Lente delgada","description":"Focos e formação de imagens","domain":"optics"},
    {"id":"aperi21:converging-diverging-lens","title":"Lentes convergentes e divergentes","description":"Uma lente que concentra a luz e uma lente que a espalha","domain":"optics"},
    {"id":"aperi21:magnification","title":"Ampliação","description":"O tamanho da imagem e o tamanho do objeto","domain":"optics"},
    {"id":"aperi21:focal-length","title":"Distância focal","description":"Como a distância focal decide onde a imagem se forma","domain":"optics"},
    {"id":"aperi21:real-vs-virtual-image","title":"Imagens reais e virtuais","description":"A luz se encontra de verdade?","domain":"optics"},
    {"id":"aperi21:lens-combination","title":"Combinação de lentes","description":"O foco combinado de duas lentes","domain":"optics"},
    {"id":"aperi21:spherical-aberration","title":"Aberração esférica","description":"Os raios da borda se focalizam em outro lugar","domain":"optics"},
    {"id":"aperi21:chromatic-aberration","title":"Aberração cromática","description":"Um foco diferente para cada comprimento de onda","domain":"optics"},
    {"id":"aperi21:human-eye-accommodation","title":"Acomodação do olho","description":"Como o cristalino focaliza as coisas","domain":"optics"},
    {"id":"aperi21:myopia-hyperopia","title":"Miopia e hipermetropia","description":"Onde a imagem se forma e como os óculos a corrigem","domain":"optics"},
    {"id":"aperi21:magnifying-glass","title":"Lupa","description":"Um objeto dentro do foco visto como uma imagem virtual grande e direita","domain":"optics"},
    {"id":"aperi21:microscope","title":"Microscópio","description":"As ampliações da objetiva e da ocular se multiplicam","domain":"optics"},
    {"id":"aperi21:telescope","title":"Telescópio","description":"Ampliação definida pela razão entre as distâncias focais","domain":"optics"},
    {"id":"aperi21:youngs-double-slit","title":"Fenda dupla de Young","description":"Prova de que a luz é uma onda","domain":"optics"},
    {"id":"aperi21:single-slit-diffraction","title":"Difração em fenda única","description":"A faixa clara central, que se alarga quando a fenda se estreita","domain":"optics"},
    {"id":"aperi21:diffraction-grating","title":"Rede de difração","description":"Máximos nítidos formados por muitas fendas","domain":"optics"},
    {"id":"aperi21:thin-film-interference","title":"Interferência em películas finas","description":"Cor criada pela espessura","domain":"optics"},
    {"id":"aperi21:newtons-rings","title":"Anéis de Newton","description":"Interferência entre uma superfície curva e uma plana","domain":"optics"},
    {"id":"aperi21:resolving-power","title":"Poder de resolução","description":"O limite para distinguir dois pontos","domain":"optics"},
    {"id":"aperi21:polarization","title":"Polarização","description":"Seleção do plano de vibração","domain":"optics"},
    {"id":"aperi21:malus-law","title":"Lei de Malus","description":"Intensidade através de um polarizador","domain":"optics"},
    {"id":"aperi21:brewster-angle","title":"Ângulo de Brewster","description":"O ângulo em que a luz refletida fica totalmente polarizada","domain":"optics"},
    {"id":"aperi21:birefringence","title":"Birrefringência","description":"Luz dividida em dois feixes que vibram em ângulo reto, de modo que a imagem se vê dupla","domain":"optics"},
    {"id":"aperi21:scattering","title":"Espalhamento","description":"O tamanho das partículas que separa o céu azul das nuvens brancas","domain":"optics"},
    {"id":"aperi21:rayleigh-scattering","title":"Espalhamento Rayleigh","description":"Um espalhamento que cresce bruscamente quanto menor o comprimento de onda","domain":"optics"},
    {"id":"aperi21:seeing-requires-light","title":"Para ver é preciso luz","description":"Sem luz, um objeto não pode ser visto","domain":"optics"},
    {"id":"aperi21:color-addition","title":"Adição de luzes","description":"A cor que três luzes formam onde se sobrepõem","domain":"optics"},
    {"id":"aperi21:object-color","title":"A cor de um objeto","description":"A cor definida pela luz que um objeto devolve","domain":"optics"},
    {"id":"aperi21:light-through-materials","title":"A luz e os materiais","description":"Como a luz atravessa depende do material","domain":"optics"},
    {"id":"aperi21:electric-charge","title":"Carga elétrica","description":"A carga, que só existe em dois tipos","domain":"electromagnetism"},
    {"id":"aperi21:charging-methods","title":"Processos de eletrização","description":"Atrito, contato e indução","domain":"electromagnetism"},
    {"id":"aperi21:coulombs-law","title":"Lei de Coulomb","description":"A força entre cargas, que enfraquece com o quadrado de quantas vezes se afastam","domain":"electromagnetism"},
    {"id":"aperi21:superposition-of-forces","title":"Superposição de forças elétricas","description":"Somar as forças de várias cargas","domain":"electromagnetism"},
    {"id":"aperi21:electric-field","title":"Campo elétrico","description":"A força sobre uma carga unitária","domain":"electromagnetism"},
    {"id":"aperi21:field-lines","title":"Linhas de campo elétrico","description":"A convenção para desenhar um campo, e o que ela significa","domain":"electromagnetism"},
    {"id":"aperi21:field-of-dipole","title":"Campo elétrico de um dipolo","description":"Duas cargas opostas próximas","domain":"electromagnetism"},
    {"id":"aperi21:uniform-field","title":"Campo elétrico uniforme","description":"O campo entre placas paralelas","domain":"electromagnetism"},
    {"id":"aperi21:charge-in-uniform-field","title":"Uma carga em um campo uniforme","description":"Igual a um projétil","domain":"electromagnetism"},
    {"id":"aperi21:gausss-law","title":"Lei de Gauss","description":"Fluxo elétrico através de uma superfície fechada","domain":"electromagnetism"},
    {"id":"aperi21:field-of-charged-sphere","title":"Campo de uma esfera carregada","description":"Por que o interior e o exterior diferem","domain":"electromagnetism"},
    {"id":"aperi21:equipotential-surface","title":"Superfícies equipotenciais","description":"Superfícies perpendiculares ao campo","domain":"electromagnetism"},
    {"id":"aperi21:potential-vs-field","title":"Potencial e campo elétrico","description":"A relação da inclinação","domain":"electromagnetism"},
    {"id":"aperi21:electrostatic-shielding","title":"Blindagem eletrostática","description":"Por que o campo dentro de um condutor é zero","domain":"electromagnetism"},
    {"id":"aperi21:charge-on-conductor-surface","title":"Carga na superfície de um condutor","description":"A carga se acumula na ponta fina","domain":"electromagnetism"},
    {"id":"aperi21:dielectric","title":"Dielétrico","description":"A polarização enfraquece o campo","domain":"electromagnetism"},
    {"id":"aperi21:parallel-plate-capacitor","title":"Capacitor de placas paralelas","description":"Capacitância definida pela área e pela distância","domain":"electromagnetism"},
    {"id":"aperi21:capacitors-in-circuit","title":"Associação de capacitores","description":"Associação em série e em paralelo","domain":"electromagnetism"},
    {"id":"aperi21:energy-in-capacitor","title":"Energia em um capacitor","description":"O trabalho gasto para mover a carga","domain":"electromagnetism"},
    {"id":"aperi21:electric-current","title":"Corrente elétrica","description":"O fluxo de carga e sua convenção de sentido","domain":"electromagnetism"},
    {"id":"aperi21:drift-velocity","title":"Velocidade de deriva","description":"A velocidade com que os elétrons se arrastam dentro de um fio","domain":"electromagnetism"},
    {"id":"aperi21:ohms-law","title":"Lei de Ohm","description":"Tensão, corrente e resistência","domain":"electromagnetism"},
    {"id":"aperi21:resistance-and-geometry","title":"Resistência e forma","description":"Como influem o comprimento e a seção transversal","domain":"electromagnetism"},
    {"id":"aperi21:temperature-and-resistance","title":"Temperatura e resistência","description":"Metais e semicondutores seguem sentidos opostos","domain":"electromagnetism"},
    {"id":"aperi21:series-parallel-resistors","title":"Resistores em série e em paralelo","description":"Como a ligação muda a corrente que uma bateria fornece","domain":"electromagnetism"},
    {"id":"aperi21:emf-and-internal-resistance","title":"Fem e resistência interna","description":"Por que a tensão nos terminais cai","domain":"electromagnetism"},
    {"id":"aperi21:kirchhoffs-current-law","title":"Lei das correntes de Kirchhoff","description":"Conservação da carga em um nó","domain":"electromagnetism"},
    {"id":"aperi21:kirchhoffs-voltage-law","title":"Lei das tensões de Kirchhoff","description":"Conservação da energia em uma malha","domain":"electromagnetism"},
    {"id":"aperi21:wheatstone-bridge","title":"Ponte de Wheatstone","description":"Medir uma resistência pelo equilíbrio","domain":"electromagnetism"},
    {"id":"aperi21:joule-heating","title":"Efeito Joule","description":"O calor produzido pela resistência","domain":"electromagnetism"},
    {"id":"aperi21:rc-circuit","title":"Circuito RC","description":"A constante de tempo da carga e da descarga","domain":"electromagnetism"},
    {"id":"aperi21:magnetic-field","title":"Campo magnético","description":"Como a força magnética se distribui ao redor de um ímã","domain":"electromagnetism"},
    {"id":"aperi21:magnetic-field-lines","title":"Linhas de campo magnético","description":"Linhas que nunca se rompem e sempre se fecham","domain":"electromagnetism"},
    {"id":"aperi21:lorentz-force","title":"Força de Lorentz","description":"A força sobre uma carga que se move em um campo magnético","domain":"electromagnetism"},
    {"id":"aperi21:charged-particle-in-magnetic-field","title":"Cargas girando em um campo magnético","description":"O mesmo tempo por volta qualquer que seja a velocidade","domain":"electromagnetism"},
    {"id":"aperi21:velocity-selector","title":"Seletor de velocidades","description":"Equilíbrio entre as forças elétrica e magnética","domain":"electromagnetism"},
    {"id":"aperi21:mass-spectrometer","title":"Espectrômetro de massa","description":"Separar massas pelo raio","domain":"electromagnetism"},
    {"id":"aperi21:force-on-current-wire","title":"Força sobre um fio percorrido por corrente","description":"A força magnética sobre um fio que conduz corrente","domain":"electromagnetism"},
    {"id":"aperi21:biot-savart-law","title":"Lei de Biot–Savart","description":"O campo magnético dos elementos de corrente","domain":"electromagnetism"},
    {"id":"aperi21:field-of-straight-wire","title":"O campo magnético de uma corrente","description":"Uma intensidade que diminui com a distância","domain":"electromagnetism"},
    {"id":"aperi21:field-of-loop-and-solenoid","title":"Espira e solenoide","description":"Um campo magnético que as espiras empilhadas tornam uniforme e forte por dentro e fraco por fora","domain":"electromagnetism"},
    {"id":"aperi21:amperes-law","title":"Lei de Ampère","description":"Circulação do campo magnético em torno de uma corrente","domain":"electromagnetism"},
    {"id":"aperi21:force-between-wires","title":"Força entre fios paralelos","description":"Duas correntes paralelas se atraem ou se repelem","domain":"electromagnetism"},
    {"id":"aperi21:magnetic-dipole","title":"Dipolo magnético","description":"Uma espira de corrente e um ímã são a mesma coisa","domain":"electromagnetism"},
    {"id":"aperi21:magnetic-materials","title":"Materiais magnéticos","description":"Ferromagnetismo, paramagnetismo e diamagnetismo","domain":"electromagnetism"},
    {"id":"aperi21:faradays-law","title":"Lei de Faraday","description":"A fem gerada por um fluxo variável","domain":"electromagnetism"},
    {"id":"aperi21:lenzs-law","title":"Lei de Lenz","description":"Uma corrente induzida que se opõe à mudança","domain":"electromagnetism"},
    {"id":"aperi21:motional-emf","title":"Fem de movimento","description":"A tensão gerada por um fio em movimento","domain":"electromagnetism"},
    {"id":"aperi21:eddy-current","title":"Correntes de Foucault","description":"Correntes induzidas dentro de um condutor maciço","domain":"electromagnetism"},
    {"id":"aperi21:self-inductance","title":"Autoindutância","description":"Uma bobina que se opõe com uma tensão própria quando a sua corrente muda","domain":"electromagnetism"},
    {"id":"aperi21:mutual-inductance","title":"Indutância mútua","description":"Uma fem induzida em um circuito vizinho","domain":"electromagnetism"},
    {"id":"aperi21:energy-in-inductor","title":"Energia em um indutor","description":"Energia armazenada no campo magnético","domain":"electromagnetism"},
    {"id":"aperi21:rl-circuit","title":"Circuito RL","description":"Por que a corrente sobe devagar","domain":"electromagnetism"},
    {"id":"aperi21:lc-oscillation","title":"Oscilação LC","description":"As energias elétrica e magnética trocam de lugar","domain":"electromagnetism"},
    {"id":"aperi21:ac-generation","title":"Geração de corrente alternada","description":"Uma bobina girando e uma onda senoidal","domain":"electromagnetism"},
    {"id":"aperi21:reactance","title":"Reatância e impedância","description":"Como uma bobina se opõe mais à corrente alternada e um capacitor menos à medida que a frequência sobe","domain":"electromagnetism"},
    {"id":"aperi21:phase-in-ac-circuit","title":"Diferença de fase em circuitos CA","description":"Tensão e corrente saindo de fase","domain":"electromagnetism"},
    {"id":"aperi21:series-rlc-resonance","title":"Ressonância RLC","description":"A frequência em que a impedância é mínima","domain":"electromagnetism"},
    {"id":"aperi21:transformer","title":"Transformador","description":"As espiras e a razão de tensões","domain":"electromagnetism"},
    {"id":"aperi21:motor","title":"Motor elétrico","description":"Girar pela força sobre uma corrente","domain":"electromagnetism"},
    {"id":"aperi21:generator","title":"Gerador","description":"Acenda a lâmpada e a manivela fica mais pesada","domain":"electromagnetism"},
    {"id":"aperi21:displacement-current","title":"Corrente de deslocamento","description":"O termo que atravessa o vão do capacitor","domain":"electromagnetism"},
    {"id":"aperi21:maxwells-equations","title":"Equações de Maxwell","description":"A cadeia em que a eletricidade e o magnetismo se geram um ao outro","domain":"electromagnetism"},
    {"id":"aperi21:electromagnetic-wave","title":"Ondas eletromagnéticas","description":"Campos elétricos e magnéticos que se propagam sozinhos","domain":"electromagnetism"},
    {"id":"aperi21:poynting-vector","title":"Vetor de Poynting","description":"A energia que atravessa o espaço em torno de um fio","domain":"electromagnetism"},
    {"id":"aperi21:radiation-pressure","title":"Pressão de radiação","description":"O empurrão da luz","domain":"electromagnetism"},
    {"id":"aperi21:antenna-radiation","title":"Radiação de uma antena","description":"As ondas que uma antena emite com mais força para os lados e nada ao longo do seu eixo","domain":"electromagnetism"},
    {"id":"aperi21:magnet-attraction","title":"O que gruda em um ímã","description":"Coisas que um ímã atrai e coisas que não","domain":"electromagnetism"},
    {"id":"aperi21:magnetic-poles","title":"Os dois polos de um ímã","description":"Polos iguais se repelem, polos opostos se atraem","domain":"electromagnetism"},
    {"id":"aperi21:simple-circuit","title":"Montando um circuito elétrico","description":"Só flui quando está ligado; interrompa e a lâmpada apaga","domain":"electromagnetism"},
    {"id":"aperi21:electromagnet","title":"Eletroímã","description":"Um ímã só enquanto a corrente flui","domain":"electromagnetism"},
    {"id":"aperi21:iv-characteristic","title":"Curvas características I–V","description":"Componentes cuja corrente não acompanha a tensão em linha reta","domain":"electromagnetism"},
    {"id":"aperi21:thermistor-and-ldr","title":"Termistor e LDR","description":"Resistência que muda com a temperatura e a luz","domain":"electromagnetism"},
    {"id":"aperi21:potential-divider","title":"Divisor de tensão","description":"Dividir uma tensão com resistores","domain":"electromagnetism"},
    {"id":"aperi21:millikan-experiment","title":"Experimento da gota de óleo de Millikan","description":"Prova de que a carga vem em porções","domain":"electromagnetism"},
    {"id":"aperi21:power-transmission","title":"Transmissão de energia elétrica","description":"Elevar a tensão para reduzir a perda","domain":"electromagnetism"},
    {"id":"aperi21:loudspeaker-and-microphone","title":"Alto-falante e microfone","description":"Transformar corrente em vibração e de volta","domain":"electromagnetism"},
    {"id":"aperi21:michelson-morley","title":"Experimento de Michelson–Morley","description":"Evidência de que não há éter","domain":"modern-physics"},
    {"id":"aperi21:relativity-of-simultaneity","title":"Relatividade da simultaneidade","description":"Um «ao mesmo tempo» que difere de um referencial para outro","domain":"modern-physics"},
    {"id":"aperi21:time-dilation","title":"Dilatação do tempo","description":"Um relógio em movimento anda devagar","domain":"modern-physics"},
    {"id":"aperi21:light-clock","title":"Relógio de luz","description":"O experimento mental por trás da dilatação do tempo","domain":"modern-physics"},
    {"id":"aperi21:length-contraction","title":"Contração do comprimento","description":"Contração na direção do movimento","domain":"modern-physics"},
    {"id":"aperi21:muon-decay-evidence","title":"Múons que chegam ao solo","description":"Evidência observacional da dilatação do tempo","domain":"modern-physics"},
    {"id":"aperi21:relativistic-velocity-addition","title":"Adição relativística de velocidades","description":"Uma composição que nunca ultrapassa a velocidade da luz","domain":"modern-physics"},
    {"id":"aperi21:twin-paradox","title":"Paradoxo dos gêmeos","description":"A inversão de marcha que cria a assimetria","domain":"modern-physics"},
    {"id":"aperi21:spacetime-diagram","title":"Diagrama de espaço-tempo","description":"Linha de universo e linha de simultaneidade","domain":"modern-physics"},
    {"id":"aperi21:light-cone","title":"Cone de luz","description":"Até onde uma causa pode chegar","domain":"modern-physics"},
    {"id":"aperi21:relativistic-momentum","title":"Quantidade de movimento relativística","description":"Uma quantidade de movimento que cresce sem limite quando a velocidade se aproxima da velocidade da luz","domain":"modern-physics"},
    {"id":"aperi21:relativistic-doppler","title":"Efeito Doppler relativístico","description":"Mudança de frequência somada à dilatação do tempo","domain":"modern-physics"},
    {"id":"aperi21:equivalence-principle","title":"Princípio da equivalência","description":"Aceleração e gravidade são indistinguíveis","domain":"modern-physics"},
    {"id":"aperi21:gravitational-time-dilation","title":"Dilatação gravitacional do tempo","description":"Relógios andam em ritmos diferentes em potenciais diferentes","domain":"modern-physics"},
    {"id":"aperi21:gravitational-redshift","title":"Desvio para o vermelho gravitacional","description":"A luz que avermelha ao sair","domain":"modern-physics"},
    {"id":"aperi21:light-bending-by-gravity","title":"Curvatura da luz","description":"A trajetória da luz se curva perto de uma massa","domain":"modern-physics"},
    {"id":"aperi21:blackbody-radiation","title":"Radiação de corpo negro","description":"Onde a teoria clássica falha","domain":"modern-physics"},
    {"id":"aperi21:wien-displacement-law","title":"Lei do deslocamento de Wien","description":"Temperatura e comprimento de onda do pico","domain":"modern-physics"},
    {"id":"aperi21:photoelectric-effect","title":"Efeito fotoelétrico","description":"Evidência de que a luz vem em partículas","domain":"modern-physics"},
    {"id":"aperi21:work-function-and-threshold","title":"Função trabalho e frequência limiar","description":"Um limiar diferente para cada metal, com a mesma inclinação para todos","domain":"modern-physics"},
    {"id":"aperi21:compton-scattering","title":"Espalhamento Compton","description":"Evidência de que um fóton tem quantidade de movimento","domain":"modern-physics"},
    {"id":"aperi21:pair-production","title":"Produção de pares","description":"Energia virando matéria","domain":"modern-physics"},
    {"id":"aperi21:de-broglie-wavelength","title":"Comprimento de onda de de Broglie","description":"O comprimento de onda da matéria, definido pela sua velocidade","domain":"modern-physics"},
    {"id":"aperi21:electron-diffraction","title":"Difração de elétrons","description":"Vendo ondas de matéria","domain":"modern-physics"},
    {"id":"aperi21:double-slit-with-electrons","title":"Fenda dupla com elétrons","description":"Um padrão que se forma um elétron por vez","domain":"modern-physics"},
    {"id":"aperi21:uncertainty-principle","title":"Princípio da incerteza","description":"Com que precisão duas grandezas conjugadas podem ser fixadas ao mesmo tempo","domain":"modern-physics"},
    {"id":"aperi21:wave-function","title":"Função de onda","description":"A amplitude de probabilidade e o que ela significa","domain":"modern-physics"},
    {"id":"aperi21:superposition-quantum","title":"Superposição quântica","description":"Ser uma soma de vários estados","domain":"modern-physics"},
    {"id":"aperi21:measurement-collapse","title":"Medição e colapso","description":"Como a observação define o estado","domain":"modern-physics"},
    {"id":"aperi21:particle-in-a-box","title":"Poço quadrado infinito","description":"Quantização da energia criada pelas paredes","domain":"modern-physics"},
    {"id":"aperi21:finite-well","title":"Poço quadrado finito","description":"Níveis de energia mais baixos porque a função de onda penetra nas paredes","domain":"modern-physics"},
    {"id":"aperi21:quantum-tunneling","title":"Tunelamento quântico","description":"A probabilidade de atravessar uma barreira","domain":"modern-physics"},
    {"id":"aperi21:scanning-tunneling-microscope","title":"Microscópio de tunelamento com varredura","description":"Desenhando uma superfície com corrente de tunelamento","domain":"modern-physics"},
    {"id":"aperi21:quantum-harmonic-oscillator","title":"Oscilador harmônico quântico","description":"Níveis igualmente espaçados e energia de ponto zero","domain":"modern-physics"},
    {"id":"aperi21:hydrogen-spectrum","title":"Espectro do hidrogênio","description":"Um espectro de linhas discreto","domain":"modern-physics"},
    {"id":"aperi21:bohr-model","title":"Modelo de Bohr","description":"Órbitas quantizadas","domain":"modern-physics"},
    {"id":"aperi21:atomic-orbital","title":"Orbital atômico","description":"O elétron como distribuição de probabilidade","domain":"modern-physics"},
    {"id":"aperi21:pauli-exclusion","title":"Princípio de exclusão de Pauli","description":"Nunca dois no mesmo estado","domain":"modern-physics"},
    {"id":"aperi21:electron-configuration","title":"Configuração eletrônica","description":"Como surge a tabela periódica","domain":"modern-physics"},
    {"id":"aperi21:spin","title":"Spin","description":"Momento angular sem análogo clássico","domain":"modern-physics"},
    {"id":"aperi21:stern-gerlach","title":"Experimento de Stern–Gerlach","description":"Um feixe atômico que se divide","domain":"modern-physics"},
    {"id":"aperi21:zeeman-effect","title":"Efeito Zeeman","description":"Níveis de energia desdobrados por um campo magnético","domain":"modern-physics"},
    {"id":"aperi21:laser-and-stimulated-emission","title":"Lasers e emissão estimulada","description":"Amplificar a luz em fase","domain":"modern-physics"},
    {"id":"aperi21:nuclear-structure","title":"Do que é feito um núcleo","description":"O número de prótons fixa o elemento; o de nêutrons, o isótopo","domain":"modern-physics"},
    {"id":"aperi21:binding-energy-curve","title":"Curva da energia de ligação","description":"Por que o pico está no ferro","domain":"modern-physics"},
    {"id":"aperi21:radioactive-decay","title":"Decaimento radioativo","description":"Meia-vida e decaimento exponencial","domain":"modern-physics"},
    {"id":"aperi21:decay-types","title":"Tipos de radiação de decaimento","description":"Alfa, beta, gama","domain":"modern-physics"},
    {"id":"aperi21:radiometric-dating","title":"Datação radiométrica","description":"Medir o tempo pelo que resta","domain":"modern-physics"},
    {"id":"aperi21:nuclear-fission","title":"Fissão nuclear","description":"A energia liberada quando um núcleo pesado se divide","domain":"modern-physics"},
    {"id":"aperi21:chain-reaction","title":"Reação em cadeia","description":"Fissão levada adiante por nêutrons","domain":"modern-physics"},
    {"id":"aperi21:nuclear-fusion","title":"Fusão nuclear","description":"Energia liberada quando núcleos leves se unem","domain":"modern-physics"},
    {"id":"aperi21:antimatter","title":"Antimatéria","description":"O parceiro do elétron, que desaparece com ele e emite dois fótons em sentidos opostos","domain":"modern-physics"},
    {"id":"aperi21:band-theory","title":"Teoria de bandas","description":"O que separa condutores, isolantes e semicondutores","domain":"modern-physics"},
    {"id":"aperi21:fermi-level","title":"Nível de Fermi","description":"Até que altura os elétrons preenchem","domain":"modern-physics"},
    {"id":"aperi21:semiconductor-doping","title":"Dopagem","description":"Como as impurezas criam o tipo n e o tipo p","domain":"modern-physics"},
    {"id":"aperi21:pn-junction","title":"Junção p–n","description":"Camada de depleção e retificação","domain":"modern-physics"},
    {"id":"aperi21:diode-and-led","title":"Diodos e LEDs","description":"Corrente em um só sentido e emissão de luz","domain":"modern-physics"},
    {"id":"aperi21:transistor-principle","title":"Transistor","description":"Um sinal pequeno controla uma corrente grande","domain":"modern-physics"},
    {"id":"aperi21:photovoltaic-effect","title":"Efeito fotovoltaico","description":"Uma tensão criada pela luz","domain":"modern-physics"},
    {"id":"aperi21:superconductivity","title":"Supercondutividade","description":"O estado em que a resistência desaparece","domain":"modern-physics"},
    {"id":"aperi21:meissner-effect","title":"Efeito Meissner","description":"Um supercondutor expulsa o campo magnético","domain":"modern-physics"},
    {"id":"aperi21:bose-einstein-condensate","title":"Condensação de Bose–Einstein","description":"Partículas frias que se amontoam num só estado","domain":"modern-physics"},
    {"id":"aperi21:scale-of-universe","title":"A escala do universo","description":"Tamanhos do átomo ao universo, ligados por potências de dez","domain":"modern-physics"},
    {"id":"aperi21:rutherford-scattering","title":"Espalhamento de Rutherford","description":"O experimento em que a maioria atravessou e algumas ricochetearam","domain":"modern-physics"},
    {"id":"aperi21:ionizing-radiation","title":"Radiação ionizante","description":"Energia de fóton grande o bastante para romper ligações","domain":"modern-physics"},
    {"id":"aperi21:exchange-particles","title":"Partículas de troca","description":"Fótons entre elétrons, glúons entre quarks","domain":"modern-physics"},
  ],
};
