/**
 * 자동 생성 파일 — 직접 편집하지 말 것.
 *
 * 생성: pnpm catalog:gen  (scripts/gen-aperi21-catalog.mts)
 * 출처: 각 sim 의 schema(label/operation) + docs/topics/topics.yaml(분야).
 */

import type { Aperi21Catalog } from '../catalog-types.js';

export const CATALOG: Aperi21Catalog = {
  locale: "zh",
  domains: [
    {"id":"kinematics","name":"运动学"},
    {"id":"newtonian-mechanics","name":"牛顿力学"},
    {"id":"energy-momentum","name":"功、能量与动量"},
    {"id":"rotation-oscillation","name":"转动与振动"},
    {"id":"gravitation","name":"引力与天文"},
    {"id":"fluids","name":"流体"},
    {"id":"thermodynamics","name":"热学与统计物理"},
    {"id":"waves-acoustics","name":"波动与声学"},
    {"id":"optics","name":"光学"},
    {"id":"electromagnetism","name":"电磁学"},
    {"id":"modern-physics","name":"近代物理"},
  ],
  entries: [
    {"id":"aperi21:reference-frame","title":"Reference frame","description":"How the description of motion depends on the observer","domain":"kinematics"},
    {"id":"aperi21:coordinate-choice","title":"Choosing axes","description":"How the choice of axes changes the equations","domain":"kinematics"},
    {"id":"aperi21:average-velocity","title":"Average velocity","description":"One velocity standing for a whole interval","domain":"kinematics"},
    {"id":"aperi21:average-acceleration","title":"平均加速度","description":"速度的变化率","domain":"kinematics"},
    {"id":"aperi21:direction-of-acceleration","title":"Direction of acceleration","description":"Whether it points with or against the velocity","domain":"kinematics"},
    {"id":"aperi21:uniform-motion","title":"匀速运动","description":"相等时间内，相等间隔","domain":"kinematics"},
    {"id":"aperi21:uniformly-accelerated-motion","title":"Uniformly accelerated motion","description":"Distance in equal times grows by equal amounts","domain":"kinematics"},
    {"id":"aperi21:position-time-graph","title":"Position-time graph","description":"The faster it rises, the steeper the line it leaves","domain":"kinematics"},
    {"id":"aperi21:velocity-time-graph","title":"Velocity-time graph","description":"The area under the graph is the distance travelled","domain":"kinematics"},
    {"id":"aperi21:acceleration-time-graph","title":"Acceleration-time graph","description":"The area under the graph is the change in velocity","domain":"kinematics"},
    {"id":"aperi21:free-fall","title":"Free fall","description":"However different their weights, the two balls fall together and land together","domain":"kinematics"},
    {"id":"aperi21:vertical-throw","title":"Vertical throw","description":"The symmetry of going up and coming down","domain":"kinematics"},
    {"id":"aperi21:gravitational-acceleration","title":"Gravitational acceleration","description":"Acceleration that does not stop even when the velocity is zero","domain":"kinematics"},
    {"id":"aperi21:terminal-velocity","title":"Terminal velocity","description":"It stops speeding up the moment drag catches gravity","domain":"kinematics"},
    {"id":"aperi21:vector-decomposition","title":"Vector components","description":"Drop straight from the tip to each axis — that is where each component ends","domain":"kinematics"},
    {"id":"aperi21:vector-addition","title":"Vector addition","description":"Slide b onto the head of a, walk both, and the far end is the sum","domain":"kinematics"},
    {"id":"aperi21:relative-velocity","title":"Relative velocity","description":"Change who is watching and the path the boat left tilts","domain":"kinematics"},
    {"id":"aperi21:river-crossing","title":"Crossing a river","description":"Aimed straight across, the boat is pushed downstream by the current","domain":"kinematics"},
    {"id":"aperi21:projectile-motion","title":"抛体运动","description":"水平与竖直互不影响，各自进行","domain":"kinematics"},
    {"id":"aperi21:projectile-range","title":"Range and launch angle","description":"How the launch angle changes how far it flies","domain":"kinematics"},
    {"id":"aperi21:trajectory-equation","title":"Trajectory equation","description":"The path left when time is eliminated","domain":"kinematics"},
    {"id":"aperi21:uniform-circular-motion","title":"Uniform circular motion","description":"The velocity arrow keeps its length and only turns","domain":"kinematics"},
    {"id":"aperi21:centripetal-acceleration","title":"Centripetal acceleration","description":"The change in velocity always turns toward the center","domain":"kinematics"},
    {"id":"aperi21:angular-acceleration","title":"Angular acceleration","description":"Each half-second sweeps a wider angle than the last","domain":"kinematics"},
    {"id":"aperi21:tangential-normal-acceleration","title":"Tangential and normal acceleration","description":"Separating change of speed from change of direction","domain":"kinematics"},
    {"id":"aperi21:radius-of-curvature","title":"曲率半径","description":"与弯曲程度相符的圆沿路径移动","domain":"kinematics"},
    {"id":"aperi21:stopping-distance","title":"Stopping distance","description":"Reaction grows linearly, braking as the square","domain":"kinematics"},
    {"id":"aperi21:newtons-first-law","title":"Inertial frame","description":"Only the bus slows; the passenger keeps going","domain":"newtonian-mechanics"},
    {"id":"aperi21:newtons-second-law","title":"Newton's second law","description":"Net force, mass and acceleration","domain":"newtonian-mechanics"},
    {"id":"aperi21:newtons-third-law","title":"Action and reaction","description":"A force pair acting on different bodies","domain":"newtonian-mechanics"},
    {"id":"aperi21:net-force","title":"Net force","description":"Vector sum of several forces","domain":"newtonian-mechanics"},
    {"id":"aperi21:free-body-diagram","title":"Free-body diagram","description":"Isolating the forces on a single body","domain":"newtonian-mechanics"},
    {"id":"aperi21:inertial-vs-gravitational-mass","title":"Inertial and gravitational mass","description":"Two different definitions give the same value","domain":"newtonian-mechanics"},
    {"id":"aperi21:normal-force","title":"Normal force","description":"The perpendicular push of a contact surface","domain":"newtonian-mechanics"},
    {"id":"aperi21:apparent-weight","title":"Apparent weight","description":"A scale in an accelerating elevator","domain":"newtonian-mechanics"},
    {"id":"aperi21:static-friction","title":"Static friction","description":"The force that holds until the object moves","domain":"newtonian-mechanics"},
    {"id":"aperi21:kinetic-friction","title":"Kinetic friction","description":"Friction while sliding","domain":"newtonian-mechanics"},
    {"id":"aperi21:angle-of-friction","title":"摩擦角","description":"开始滑动时的倾斜","domain":"newtonian-mechanics"},
    {"id":"aperi21:inclined-plane","title":"Inclined plane","description":"Splitting gravity along and into the slope","domain":"newtonian-mechanics"},
    {"id":"aperi21:tension","title":"Tension","description":"How a rope carries a pull","domain":"newtonian-mechanics"},
    {"id":"aperi21:pulley-system","title":"Pulleys","description":"A device that changes the direction and size of a force","domain":"newtonian-mechanics"},
    {"id":"aperi21:connected-bodies","title":"Connected bodies","description":"Acceleration of bodies moving together","domain":"newtonian-mechanics"},
    {"id":"aperi21:spring-force","title":"Spring force","description":"Restoring force proportional to stretch","domain":"newtonian-mechanics"},
    {"id":"aperi21:centripetal-force","title":"Centripetal force","description":"What keeps a body moving in a circle","domain":"newtonian-mechanics"},
    {"id":"aperi21:conical-pendulum","title":"Conical pendulum","description":"Circular motion from tension and gravity","domain":"newtonian-mechanics"},
    {"id":"aperi21:banked-curve","title":"Banked curve","description":"The bank angle that turns a car without friction","domain":"newtonian-mechanics"},
    {"id":"aperi21:vertical-loop","title":"Vertical loop","description":"The minimum speed that keeps a ball on the loop at the top","domain":"newtonian-mechanics"},
    {"id":"aperi21:drag-force","title":"Air drag","description":"The faster it goes, the steeper the part of drag proportional to speed squared grows","domain":"newtonian-mechanics"},
    {"id":"aperi21:buoyant-force-as-force","title":"Buoyant force as a force","description":"The upward push of a fluid","domain":"newtonian-mechanics"},
    {"id":"aperi21:non-inertial-frame","title":"Non-inertial frame","description":"Motion seen from an accelerating frame","domain":"newtonian-mechanics"},
    {"id":"aperi21:fictitious-force","title":"Fictitious force","description":"The apparent force of a non-inertial frame","domain":"newtonian-mechanics"},
    {"id":"aperi21:coriolis-effect","title":"Coriolis effect","description":"A path that curves in a rotating frame","domain":"newtonian-mechanics"},
    {"id":"aperi21:impulse-force-relation","title":"Force and impulse","description":"A short, large force and a long, small one","domain":"newtonian-mechanics"},
    {"id":"aperi21:equilibrium-of-forces","title":"Equilibrium of forces","description":"Zero net force","domain":"newtonian-mechanics"},
    {"id":"aperi21:atwood-machine","title":"Atwood machine","description":"With the same total mass, the difference sets the acceleration","domain":"newtonian-mechanics"},
    {"id":"aperi21:balance-scale","title":"Balancing a scale","description":"Balance set by both arm length and weight","domain":"newtonian-mechanics"},
    {"id":"aperi21:mechanical-advantage","title":"Mechanical advantage","description":"How levers and ramps cut the force you need","domain":"newtonian-mechanics"},
    {"id":"aperi21:youngs-modulus","title":"Young's modulus","description":"How much a wire stretches is set by its material, not its length","domain":"newtonian-mechanics"},
    {"id":"aperi21:stress-strain-curve","title":"Stress–strain curve","description":"How a material responds as it is pulled","domain":"newtonian-mechanics"},
    {"id":"aperi21:work-by-variable-force","title":"Work done by a varying force","description":"The area under the force–displacement graph","domain":"energy-momentum"},
    {"id":"aperi21:kinetic-energy","title":"Kinetic energy","description":"The energy that speed carries","domain":"energy-momentum"},
    {"id":"aperi21:work-energy-theorem","title":"Work-energy theorem","description":"Net work equals the change in kinetic energy","domain":"energy-momentum"},
    {"id":"aperi21:gravitational-potential-energy","title":"Gravitational potential energy","description":"Energy stored in height","domain":"energy-momentum"},
    {"id":"aperi21:elastic-potential-energy","title":"Elastic potential energy","description":"The energy stored in a deformation","domain":"energy-momentum"},
    {"id":"aperi21:conservative-force","title":"Conservative force","description":"A force whose work ignores the path — and the potential it allows","domain":"energy-momentum"},
    {"id":"aperi21:non-conservative-force","title":"Non-conservative force","description":"Work that depends on the path","domain":"energy-momentum"},
    {"id":"aperi21:conservation-of-mechanical-energy","title":"Conservation of mechanical energy","description":"The sum that holds while height and motion trade places","domain":"energy-momentum"},
    {"id":"aperi21:energy-dissipation","title":"Energy dissipation","description":"The share friction takes, and where it goes","domain":"energy-momentum"},
    {"id":"aperi21:potential-energy-curve","title":"Potential energy curve","description":"How the shape of the curve decides the motion","domain":"energy-momentum"},
    {"id":"aperi21:equilibrium-points","title":"Equilibrium points","description":"Stable, unstable and neutral equilibrium","domain":"energy-momentum"},
    {"id":"aperi21:efficiency","title":"Efficiency","description":"The ratio of what comes out to what goes in","domain":"energy-momentum"},
    {"id":"aperi21:impulse-momentum-theorem","title":"Impulse–momentum theorem","description":"Impulse equals the change in momentum","domain":"energy-momentum"},
    {"id":"aperi21:conservation-of-momentum","title":"Conservation of momentum","description":"Total momentum when no external force acts","domain":"energy-momentum"},
    {"id":"aperi21:elastic-collision","title":"Elastic collision","description":"A collision that keeps even the kinetic energy","domain":"energy-momentum"},
    {"id":"aperi21:inelastic-collision","title":"Inelastic collision","description":"A collision that loses energy","domain":"energy-momentum"},
    {"id":"aperi21:perfectly-inelastic-collision","title":"Perfectly inelastic collision","description":"When the two move together, stuck","domain":"energy-momentum"},
    {"id":"aperi21:two-dimensional-collision","title":"Two-dimensional collision","description":"Conservation that holds separately for each component","domain":"energy-momentum"},
    {"id":"aperi21:center-of-mass-motion","title":"Motion of the centre of mass","description":"The motion that internal forces cannot change","domain":"energy-momentum"},
    {"id":"aperi21:explosion-and-recoil","title":"Explosion and recoil","description":"When a system at rest splits apart","domain":"energy-momentum"},
    {"id":"aperi21:rocket-equation","title":"The rocket equation","description":"Speed bought by throwing fuel away","domain":"energy-momentum"},
    {"id":"aperi21:ballistic-pendulum","title":"Ballistic pendulum","description":"The measurement that links a collision to energy conservation","domain":"energy-momentum"},
    {"id":"aperi21:energy-in-collision","title":"Energy in collisions","description":"Telling what is conserved from what is not","domain":"energy-momentum"},
    {"id":"aperi21:energy-flow-diagram","title":"Energy flow diagram","description":"Where the energy goes, shown by branch thickness","domain":"energy-momentum"},
    {"id":"aperi21:torque","title":"Torque","description":"What makes things turn, and the length of the lever arm","domain":"rotation-oscillation"},
    {"id":"aperi21:moment-of-inertia","title":"Moment of inertia","description":"How mass distribution sets rotational resistance","domain":"rotation-oscillation"},
    {"id":"aperi21:parallel-axis-theorem","title":"Parallel axis theorem","description":"Moment of inertia when the axis is moved","domain":"rotation-oscillation"},
    {"id":"aperi21:rotational-kinetic-energy","title":"Rotational kinetic energy","description":"The energy that spin carries","domain":"rotation-oscillation"},
    {"id":"aperi21:angular-momentum","title":"Angular momentum","description":"The momentum of rotation","domain":"rotation-oscillation"},
    {"id":"aperi21:conservation-of-angular-momentum","title":"Conservation of angular momentum","description":"Why pulling your arms in makes you spin faster","domain":"rotation-oscillation"},
    {"id":"aperi21:rolling-without-slipping","title":"Rolling without slipping","description":"The constraint that ties translation to rotation","domain":"rotation-oscillation"},
    {"id":"aperi21:rolling-race","title":"Rolling race","description":"Arrival order set by mass distribution","domain":"rotation-oscillation"},
    {"id":"aperi21:static-equilibrium","title":"Static equilibrium","description":"Both the net force and the net torque are zero","domain":"rotation-oscillation"},
    {"id":"aperi21:center-of-gravity","title":"Center of gravity","description":"The point that decides when things tip over","domain":"rotation-oscillation"},
    {"id":"aperi21:gyroscopic-precession","title":"Gyroscopic precession","description":"Torque turning the direction of angular momentum","domain":"rotation-oscillation"},
    {"id":"aperi21:angular-momentum-vector","title":"Direction of angular momentum","description":"The right-hand rule and the axis of rotation","domain":"rotation-oscillation"},
    {"id":"aperi21:simple-harmonic-motion","title":"Simple harmonic motion","description":"Motion under a restoring force proportional to displacement","domain":"rotation-oscillation"},
    {"id":"aperi21:shm-energy","title":"Energy in simple harmonic motion","description":"Kinetic and potential energy trade places","domain":"rotation-oscillation"},
    {"id":"aperi21:mass-spring-system","title":"Mass on a spring","description":"The period set by mass and spring constant","domain":"rotation-oscillation"},
    {"id":"aperi21:simple-pendulum","title":"Simple pendulum","description":"The period at small amplitude","domain":"rotation-oscillation"},
    {"id":"aperi21:physical-pendulum","title":"Physical pendulum","description":"Oscillation of an extended body","domain":"rotation-oscillation"},
    {"id":"aperi21:pendulum-amplitude-dependence","title":"Isochronism of the pendulum","description":"Drag the swing size to widen all five together","domain":"rotation-oscillation"},
    {"id":"aperi21:damped-oscillation","title":"Damped oscillation","description":"An oscillation that loses energy","domain":"rotation-oscillation"},
    {"id":"aperi21:damping-regimes","title":"Three regimes of damping","description":"Underdamped, critically damped and overdamped motion","domain":"rotation-oscillation"},
    {"id":"aperi21:driven-oscillation","title":"Driven oscillation","description":"The response to an external drive","domain":"rotation-oscillation"},
    {"id":"aperi21:resonance","title":"Resonance","description":"When the driving frequency matches the natural frequency","domain":"rotation-oscillation"},
    {"id":"aperi21:quality-factor","title":"Quality factor","description":"How sharp a resonance is","domain":"rotation-oscillation"},
    {"id":"aperi21:coupled-oscillators","title":"Coupled oscillators","description":"Two oscillators trading energy","domain":"rotation-oscillation"},
    {"id":"aperi21:normal-modes","title":"Normal modes","description":"The natural shapes a system vibrates in","domain":"rotation-oscillation"},
    {"id":"aperi21:beats-in-oscillation","title":"Beats in oscillation","description":"The sum of two nearby frequencies","domain":"rotation-oscillation"},
    {"id":"aperi21:phase-space","title":"Phase space","description":"Motion seen on the position–velocity plane","domain":"rotation-oscillation"},
    {"id":"aperi21:nonlinear-oscillation","title":"Nonlinear oscillation","description":"When the restoring force stops being proportional","domain":"rotation-oscillation"},
    {"id":"aperi21:gears","title":"齿轮","description":"齿数如何以转动换取力","domain":"rotation-oscillation"},
    {"id":"aperi21:newtons-law-of-gravitation","title":"Newton's law of gravitation","description":"A force that falls with the square of distance","domain":"gravitation"},
    {"id":"aperi21:gravitational-field","title":"Gravitational field","description":"The strength of gravity spread through space","domain":"gravitation"},
    {"id":"aperi21:range-and-surface-gravity","title":"Gravity and range","description":"Same launch, different gravity","domain":"gravitation"},
    {"id":"aperi21:shell-theorem","title":"Shell theorem","description":"Gravity inside and outside a spherical shell","domain":"gravitation"},
    {"id":"aperi21:gravity-inside-earth","title":"Gravity inside the Earth","description":"Gravity that weakens with depth","domain":"gravitation"},
    {"id":"aperi21:gravitational-potential-energy-general","title":"Gravitational potential energy (general)","description":"A negative energy measured from infinity","domain":"gravitation"},
    {"id":"aperi21:escape-velocity","title":"Escape velocity","description":"The least speed that breaks free of gravity","domain":"gravitation"},
    {"id":"aperi21:orbital-velocity","title":"Orbital velocity","description":"The speed that keeps an orbit circular","domain":"gravitation"},
    {"id":"aperi21:circular-orbit","title":"Circular orbit","description":"Motion in which gravity is the centripetal force","domain":"gravitation"},
    {"id":"aperi21:elliptical-orbit","title":"Elliptical orbit","description":"The central body sits at a focus","domain":"gravitation"},
    {"id":"aperi21:keplers-first-law","title":"Kepler's first law","description":"Orbits are ellipses","domain":"gravitation"},
    {"id":"aperi21:keplers-second-law","title":"Kepler's second law","description":"Equal areas in equal times","domain":"gravitation"},
    {"id":"aperi21:keplers-third-law","title":"Kepler's third law","description":"How the period depends on the semi-major axis","domain":"gravitation"},
    {"id":"aperi21:two-body-problem","title":"Two-body problem","description":"Two bodies orbiting their common center of mass","domain":"gravitation"},
    {"id":"aperi21:tidal-force","title":"Tidal force","description":"Stretching made by a difference in gravity","domain":"gravitation"},
    {"id":"aperi21:roche-limit","title":"Roche limit","description":"The distance at which tides tear a body apart","domain":"gravitation"},
    {"id":"aperi21:weightlessness","title":"Weightlessness","description":"Apparent weight in free fall","domain":"gravitation"},
    {"id":"aperi21:geostationary-orbit","title":"Geostationary orbit","description":"An orbit as long as one turn of Earth","domain":"gravitation"},
    {"id":"aperi21:gravitational-slingshot","title":"Gravity assist","description":"Changing speed by passing a planet","domain":"gravitation"},
    {"id":"aperi21:lagrange-points","title":"Lagrange points","description":"Drifting off the saddles, circling the peaks","domain":"gravitation"},
    {"id":"aperi21:orbital-transfer","title":"Orbital transfer","description":"The Hohmann transfer and what it costs","domain":"gravitation"},
    {"id":"aperi21:black-hole-horizon","title":"Event horizon","description":"The radius where escape speed reaches light speed","domain":"gravitation"},
    {"id":"aperi21:diurnal-motion","title":"Diurnal motion","description":"The paths the Sun and stars trace across the sky in a day","domain":"gravitation"},
    {"id":"aperi21:earth-rotation-day-night","title":"Earth’s rotation, day and night","description":"Why day and night alternate on a turning Earth","domain":"gravitation"},
    {"id":"aperi21:earth-revolution-constellations","title":"Earth’s orbit and the constellations","description":"Why the constellations we see change with the seasons","domain":"gravitation"},
    {"id":"aperi21:solar-altitude-shadow","title":"Solar altitude and shadows","description":"As the Sun’s altitude changes, shadow length and warmth change together","domain":"gravitation"},
    {"id":"aperi21:seasonal-sun-path","title":"The Sun’s path through the seasons","description":"How the noon altitude and the length of day change together","domain":"gravitation"},
    {"id":"aperi21:axial-tilt-seasons","title":"Axial tilt and the seasons","description":"The seasons made by an Earth that orbits tilted","domain":"gravitation"},
    {"id":"aperi21:moon-phases","title":"Phases of the Moon","description":"Which part of the sunlit Moon faces us","domain":"gravitation"},
    {"id":"aperi21:eclipse","title":"Solar and lunar eclipses","description":"When the Sun, Earth and Moon line up","domain":"gravitation"},
    {"id":"aperi21:stellar-parallax","title":"Stellar parallax","description":"The angle by which a nearby star shifts as Earth orbits the Sun","domain":"gravitation"},
    {"id":"aperi21:apparent-brightness","title":"Apparent brightness","description":"The same light divides over a wider area","domain":"gravitation"},
    {"id":"aperi21:magnitude-scale","title":"Stellar magnitude","description":"How brightness is written as magnitude","domain":"gravitation"},
    {"id":"aperi21:star-color-temperature","title":"Star color and surface temperature","description":"How surface temperature sets the color of starlight","domain":"gravitation"},
    {"id":"aperi21:expanding-universe","title":"The expanding universe","description":"Galaxies receding in every direction","domain":"gravitation"},
    {"id":"aperi21:stellar-luminosity","title":"Luminosity","description":"How much light a star actually gives off","domain":"gravitation"},
    {"id":"aperi21:hr-diagram","title":"HR diagram","description":"The heaviest stars leave the main sequence first","domain":"gravitation"},
    {"id":"aperi21:star-radiation-gravity-balance","title":"Radiation pressure and gravity in balance","description":"Why a star neither collapses nor flies apart","domain":"gravitation"},
    {"id":"aperi21:orbital-decay","title":"Orbital decay","description":"An orbit dragged by thin air","domain":"gravitation"},
    {"id":"aperi21:inverse-square-law","title":"Inverse-square law","description":"Thinning out as it spreads","domain":"gravitation"},
    {"id":"aperi21:stellar-nucleosynthesis","title":"Stellar nucleosynthesis","description":"How heavier elements are made inside stars","domain":"gravitation"},
    {"id":"aperi21:star-life-cycle","title":"恒星的一生","description":"质量如何决定恒星的演化路径","domain":"gravitation"},
    {"id":"aperi21:stellar-spectral-class","title":"Stellar spectral classes","description":"Absorption-line patterns set by temperature","domain":"gravitation"},
    {"id":"aperi21:supernova-and-neutron-star","title":"Supernova and neutron star","description":"A final collapse and rebound","domain":"gravitation"},
    {"id":"aperi21:exoplanet-detection","title":"Detecting exoplanets","description":"The traces a planet leaves","domain":"gravitation"},
    {"id":"aperi21:projectile-in-wind","title":"Wind and range","description":"Same launch, different wind","domain":"fluids"},
    {"id":"aperi21:pressure-isotropy","title":"压强的各向同性","description":"板自行转半圈，把轨迹闭合成圆，然后由读者亲手转动","domain":"fluids"},
    {"id":"aperi21:hydrostatic-pressure","title":"Hydrostatic pressure","description":"Pressure that grows with depth","domain":"fluids"},
    {"id":"aperi21:pressure-and-container-shape","title":"容器形状与底部压强","description":"调整水面高度，重新给三个容器注水","domain":"fluids"},
    {"id":"aperi21:atmospheric-pressure","title":"Atmospheric pressure","description":"The weight of the air column","domain":"fluids"},
    {"id":"aperi21:barometer","title":"Barometer","description":"The height of a mercury column","domain":"fluids"},
    {"id":"aperi21:manometer","title":"Manometer","description":"Reading pressure from a liquid column","domain":"fluids"},
    {"id":"aperi21:pascals-principle","title":"Pascal's principle","description":"Transmitted pressure and the hydraulic press","domain":"fluids"},
    {"id":"aperi21:buoyancy","title":"Buoyancy","description":"As much as the weight of the fluid pushed aside","domain":"fluids"},
    {"id":"aperi21:archimedes-principle","title":"阿基米德原理 — 浮力的大小","description":"把 2.0 kg、1.0 L 的物体放入盛满水直到溢水口的溢水杯中。被排开的水流进小杯，物体一侧的秤减少多少，水一侧的秤就增加多少。","domain":"fluids"},
    {"id":"aperi21:floating-and-draft","title":"How deep a floating body sits","description":"What sets the submerged volume","domain":"fluids"},
    {"id":"aperi21:stability-of-floating-body","title":"Stability of a floating body","description":"When a boat heels, its centre of buoyancy shifts and rights it","domain":"fluids"},
    {"id":"aperi21:continuity-equation","title":"Continuity equation","description":"Cross-section and flow speed trade off","domain":"fluids"},
    {"id":"aperi21:bernoullis-principle","title":"Bernoulli's principle","description":"Where water speeds up, its pressure drops","domain":"fluids"},
    {"id":"aperi21:venturi-effect","title":"Venturi effect","description":"Lower pressure where the pipe narrows","domain":"fluids"},
    {"id":"aperi21:torricellis-law","title":"Torricelli's law","description":"The deeper the hole, the faster the jet","domain":"fluids"},
    {"id":"aperi21:lift-force","title":"Lift","description":"How air flows over and under a wing","domain":"fluids"},
    {"id":"aperi21:viscosity","title":"Viscosity","description":"Friction between layers","domain":"fluids"},
    {"id":"aperi21:poiseuille-flow","title":"Laminar flow in a pipe","description":"Flow rate grows as the fourth power of the radius","domain":"fluids"},
    {"id":"aperi21:stokes-drag","title":"Stokes drag","description":"Drag in slow, viscous flow","domain":"fluids"},
    {"id":"aperi21:laminar-vs-turbulent","title":"Laminar and turbulent flow","description":"Where flow suddenly breaks up","domain":"fluids"},
    {"id":"aperi21:reynolds-number","title":"Reynolds number","description":"The dimensionless number that decides the transition","domain":"fluids"},
    {"id":"aperi21:boundary-layer","title":"Boundary layer","description":"The layer near a wall where the flow slows to zero","domain":"fluids"},
    {"id":"aperi21:surface-tension","title":"Surface tension","description":"The pull that shrinks a surface","domain":"fluids"},
    {"id":"aperi21:laplace-pressure","title":"Laplace pressure","description":"The pressure jump a curved surface makes","domain":"fluids"},
    {"id":"aperi21:capillary-action","title":"Capillary action","description":"Rise and fall in narrow tubes","domain":"fluids"},
    {"id":"aperi21:wetting-and-contact-angle","title":"Wetting and contact angle","description":"How far a liquid spreads over a solid","domain":"fluids"},
    {"id":"aperi21:drag-in-fluid","title":"Drag in a fluid","description":"Drag set by shape and speed","domain":"fluids"},
    {"id":"aperi21:thermal-equilibrium","title":"Thermal equilibrium","description":"The state two systems in contact reach","domain":"thermodynamics"},
    {"id":"aperi21:specific-heat","title":"Specific heat","description":"How much the temperature changes, material by material","domain":"thermodynamics"},
    {"id":"aperi21:calorimetry","title":"Calorimetry","description":"The final temperature of a mixture","domain":"thermodynamics"},
    {"id":"aperi21:latent-heat","title":"Latent heat","description":"Why the temperature stops during a change of state","domain":"thermodynamics"},
    {"id":"aperi21:phase-diagram","title":"Phase diagram","description":"Below the triple point, the liquid range is skipped","domain":"thermodynamics"},
    {"id":"aperi21:triple-point","title":"三相点","description":"三相共存的条件","domain":"thermodynamics"},
    {"id":"aperi21:thermal-conduction","title":"Heat conduction","description":"It spreads in steel and stays in wood","domain":"thermodynamics"},
    {"id":"aperi21:thermal-convection","title":"Convection","description":"Heat carried by moving fluid","domain":"thermodynamics"},
    {"id":"aperi21:thermal-radiation","title":"Thermal radiation","description":"Heat that travels without a medium","domain":"thermodynamics"},
    {"id":"aperi21:stefan-boltzmann-law","title":"Stefan–Boltzmann law","description":"Radiation that grows as the fourth power of temperature","domain":"thermodynamics"},
    {"id":"aperi21:thermal-expansion","title":"Thermal expansion","description":"How length and volume change with temperature","domain":"thermodynamics"},
    {"id":"aperi21:bimetal","title":"Bimetallic strip","description":"Bending from unequal expansion","domain":"thermodynamics"},
    {"id":"aperi21:ideal-gas-law","title":"理想气体状态方程","description":"压强、体积与温度的关系","domain":"thermodynamics"},
    {"id":"aperi21:boyles-law","title":"Boyle's law","description":"Pressure and volume at constant temperature","domain":"thermodynamics"},
    {"id":"aperi21:charles-law","title":"Charles's law","description":"Volume and temperature at constant pressure","domain":"thermodynamics"},
    {"id":"aperi21:gas-pressure","title":"Molecules and pressure","description":"Pressure is the sum of the knocks","domain":"thermodynamics"},
    {"id":"aperi21:pressure-from-collisions","title":"Pressure from collisions","description":"The momentum molecules bring to the wall","domain":"thermodynamics"},
    {"id":"aperi21:maxwell-boltzmann-distribution","title":"Maxwell–Boltzmann distribution","description":"Heating spreads the speed distribution and lowers its peak","domain":"thermodynamics"},
    {"id":"aperi21:mean-free-path","title":"Mean free path","description":"The distance between collisions","domain":"thermodynamics"},
    {"id":"aperi21:first-law-of-thermodynamics","title":"First law of thermodynamics","description":"How internal energy, work and heat relate","domain":"thermodynamics"},
    {"id":"aperi21:pv-diagram","title":"PV diagram","description":"Where area is work","domain":"thermodynamics"},
    {"id":"aperi21:isothermal-process","title":"Isothermal process","description":"A change that keeps the temperature fixed","domain":"thermodynamics"},
    {"id":"aperi21:adiabatic-process","title":"Adiabatic process","description":"A change with no heat in or out","domain":"thermodynamics"},
    {"id":"aperi21:isobaric-isochoric","title":"Isobaric and isochoric processes","description":"Changes at fixed pressure or fixed volume","domain":"thermodynamics"},
    {"id":"aperi21:cyclic-process","title":"Cyclic process","description":"A change that comes back to where it began","domain":"thermodynamics"},
    {"id":"aperi21:second-law-of-thermodynamics","title":"Second law of thermodynamics","description":"Change that runs one way","domain":"thermodynamics"},
    {"id":"aperi21:irreversibility","title":"Entropy and irreversibility","description":"Why it cannot be undone","domain":"thermodynamics"},
    {"id":"aperi21:heat-engine","title":"Heat engine","description":"A cycle that turns heat into work","domain":"thermodynamics"},
    {"id":"aperi21:carnot-cycle","title":"Carnot cycle","description":"The theoretical maximum efficiency","domain":"thermodynamics"},
    {"id":"aperi21:refrigerator-heat-pump","title":"Refrigerators and heat pumps","description":"Moving heat by putting in work","domain":"thermodynamics"},
    {"id":"aperi21:brownian-motion","title":"Brownian motion","description":"Random motion driven by molecular collisions","domain":"thermodynamics"},
    {"id":"aperi21:diffusion","title":"Diffusion","description":"Flow driven by a difference in concentration","domain":"thermodynamics"},
    {"id":"aperi21:random-walk","title":"Random walk","description":"Distance that grows as a square root","domain":"thermodynamics"},
    {"id":"aperi21:statistical-fluctuation","title":"Statistical fluctuation","description":"The wobble that grows when particles are few","domain":"thermodynamics"},
    {"id":"aperi21:maxwells-demon","title":"Maxwell's demon","description":"Information and entropy","domain":"thermodynamics"},
    {"id":"aperi21:insulation","title":"Insulation","description":"Slowing the flow of heat","domain":"thermodynamics"},
    {"id":"aperi21:albedo","title":"Albedo","description":"The share of light sent back","domain":"thermodynamics"},
    {"id":"aperi21:radiative-equilibrium","title":"Radiative equilibrium","description":"The temperature set when what goes out matches what comes in","domain":"thermodynamics"},
    {"id":"aperi21:greenhouse-effect","title":"Greenhouse effect","description":"A layer that sends infrared back down warms the ground","domain":"thermodynamics"},
    {"id":"aperi21:wave-basics","title":"Basic quantities of a wave","description":"Wavelength, frequency, speed and amplitude","domain":"waves-acoustics"},
    {"id":"aperi21:wave-vs-particle-transport","title":"What a wave carries","description":"The medium stays put, the energy moves on","domain":"waves-acoustics"},
    {"id":"aperi21:transverse-wave","title":"Transverse wave","description":"The medium shakes at right angles to the direction the wave travels","domain":"waves-acoustics"},
    {"id":"aperi21:longitudinal-wave","title":"Longitudinal wave","description":"Particles sway in place while the crowded places travel on","domain":"waves-acoustics"},
    {"id":"aperi21:wave-speed-in-medium","title":"Wave speed and the medium","description":"Speed set by tension, density and elasticity","domain":"waves-acoustics"},
    {"id":"aperi21:wavefront-and-ray","title":"Wavefronts and rays","description":"Surfaces of equal phase and the lines normal to them","domain":"waves-acoustics"},
    {"id":"aperi21:huygens-principle","title":"Huygens' principle","description":"Circular wavelets from points on a wavefront overlap into a straight front","domain":"waves-acoustics"},
    {"id":"aperi21:superposition","title":"Superposition","description":"What happens when waves overlap","domain":"waves-acoustics"},
    {"id":"aperi21:constructive-destructive","title":"Constructive and destructive interference","description":"How phase difference sets the size of the sum","domain":"waves-acoustics"},
    {"id":"aperi21:interference","title":"Interference","description":"Two sets of ripples cancel and leave calm lines","domain":"waves-acoustics"},
    {"id":"aperi21:standing-wave","title":"Standing wave","description":"Two waves running in opposite directions pin the nodes in place","domain":"waves-acoustics"},
    {"id":"aperi21:harmonics","title":"Harmonics","description":"Frequencies set by the boundary","domain":"waves-acoustics"},
    {"id":"aperi21:string-vibration","title":"Vibrating string","description":"Modes of a string fixed at both ends","domain":"waves-acoustics"},
    {"id":"aperi21:air-column-resonance","title":"Air-column resonance","description":"Open pipe versus closed pipe","domain":"waves-acoustics"},
    {"id":"aperi21:beats","title":"Beats","description":"The sum cancels as the two drift apart","domain":"waves-acoustics"},
    {"id":"aperi21:doppler-effect","title":"Doppler effect","description":"The source drags its emission points, crowding the front","domain":"waves-acoustics"},
    {"id":"aperi21:doppler-source-vs-observer","title":"Moving source vs. moving observer","description":"The asymmetry of who is moving","domain":"waves-acoustics"},
    {"id":"aperi21:shock-wave","title":"Shock wave","description":"The cone that forms past the speed of sound","domain":"waves-acoustics"},
    {"id":"aperi21:sound-intensity","title":"声强","description":"随距离平方衰减","domain":"waves-acoustics"},
    {"id":"aperi21:reflection-of-waves","title":"Reflection of waves","description":"Phase at a fixed end and at a free end","domain":"waves-acoustics"},
    {"id":"aperi21:refraction-of-waves","title":"Refraction of waves","description":"A change of speed turns the direction","domain":"waves-acoustics"},
    {"id":"aperi21:diffraction","title":"Diffraction","description":"Waves bending around obstacles","domain":"waves-acoustics"},
    {"id":"aperi21:slit-width-and-diffraction","title":"Slit Width and Diffraction","description":"How the gap-to-wavelength ratio sets the spread","domain":"waves-acoustics"},
    {"id":"aperi21:wave-energy","title":"Energy of a wave","description":"Energy grows with the square of the amplitude","domain":"waves-acoustics"},
    {"id":"aperi21:wave-attenuation","title":"Attenuation of a wave","description":"Energy absorbed by the medium","domain":"waves-acoustics"},
    {"id":"aperi21:impedance-mismatch","title":"Impedance mismatch","description":"How much reflects at a boundary","domain":"waves-acoustics"},
    {"id":"aperi21:noise-cancellation","title":"Active noise cancellation","description":"Superposing an inverted wave","domain":"waves-acoustics"},
    {"id":"aperi21:sound-source-vibration","title":"Sound and vibration","description":"A sounding object vibrates, and when the vibration stops, so does the sound","domain":"waves-acoustics"},
    {"id":"aperi21:sound-through-materials","title":"Sound through materials","description":"How sound travels differently through different materials","domain":"waves-acoustics"},
    {"id":"aperi21:digital-vs-analog-signal","title":"Digital and analog signals","description":"Two ways of standing up to noise","domain":"waves-acoustics"},
    {"id":"aperi21:seismic-waves","title":"Seismic waves","description":"P and S waves travelling through the Earth","domain":"waves-acoustics"},
    {"id":"aperi21:rectilinear-propagation","title":"Light travels in straight lines","description":"Shadows and the ray model","domain":"optics"},
    {"id":"aperi21:shadow-umbra-penumbra","title":"Umbra and penumbra","description":"How the size of a light source shapes a shadow’s edge","domain":"optics"},
    {"id":"aperi21:pinhole-camera","title":"Pinhole camera","description":"The image made by a single hole","domain":"optics"},
    {"id":"aperi21:law-of-reflection","title":"Law of reflection","description":"Angle of incidence and angle of reflection","domain":"optics"},
    {"id":"aperi21:specular-diffuse-reflection","title":"Specular and diffuse reflection","description":"Reflection set by surface roughness","domain":"optics"},
    {"id":"aperi21:plane-mirror-image","title":"Image in a plane mirror","description":"Where the virtual image stands, and why it looks reversed","domain":"optics"},
    {"id":"aperi21:multiple-mirror-images","title":"Images in two mirrors","description":"How the angle between two mirrors sets the number of images","domain":"optics"},
    {"id":"aperi21:concave-mirror","title":"Concave mirror","description":"The focal point and the real image","domain":"optics"},
    {"id":"aperi21:convex-mirror","title":"Convex mirror","description":"A wider view and a virtual image","domain":"optics"},
    {"id":"aperi21:snells-law","title":"斯涅尔定律","description":"路径随介质的偏折","domain":"optics"},
    {"id":"aperi21:apparent-depth","title":"Apparent depth","description":"Why things under water look raised","domain":"optics"},
    {"id":"aperi21:total-internal-reflection","title":"Total internal reflection","description":"The critical angle and its condition","domain":"optics"},
    {"id":"aperi21:optical-fiber","title":"Optical fiber","description":"Light trapped by total internal reflection","domain":"optics"},
    {"id":"aperi21:mirage","title":"Mirage","description":"Light bent by a density gradient","domain":"optics"},
    {"id":"aperi21:dispersion","title":"Dispersion","description":"Refractive index that depends on wavelength","domain":"optics"},
    {"id":"aperi21:prism","title":"Prism","description":"A spectrum spread out by dispersion","domain":"optics"},
    {"id":"aperi21:rainbow","title":"Rainbow","description":"Refraction and reflection inside raindrops","domain":"optics"},
    {"id":"aperi21:thin-lens","title":"Thin lens","description":"Locating the image with three rays","domain":"optics"},
    {"id":"aperi21:converging-diverging-lens","title":"Converging and diverging lenses","description":"A lens that gathers light and a lens that spreads it","domain":"optics"},
    {"id":"aperi21:magnification","title":"Magnification","description":"The size of the image and the size of the object","domain":"optics"},
    {"id":"aperi21:focal-length","title":"Focal length","description":"What decides where the image forms","domain":"optics"},
    {"id":"aperi21:real-vs-virtual-image","title":"Real and virtual images","description":"Does the light really meet?","domain":"optics"},
    {"id":"aperi21:lens-combination","title":"Combining lenses","description":"The combined focus of two lenses","domain":"optics"},
    {"id":"aperi21:spherical-aberration","title":"Spherical aberration","description":"Edge rays come to focus at a different place","domain":"optics"},
    {"id":"aperi21:chromatic-aberration","title":"Chromatic aberration","description":"A different focus for each wavelength","domain":"optics"},
    {"id":"aperi21:human-eye-accommodation","title":"Accommodation of the eye","description":"How the lens of the eye brings things into focus","domain":"optics"},
    {"id":"aperi21:myopia-hyperopia","title":"Nearsightedness and farsightedness","description":"Where the image forms, and how glasses correct it","domain":"optics"},
    {"id":"aperi21:magnifying-glass","title":"Magnifying glass","description":"An object inside the near focal point","domain":"optics"},
    {"id":"aperi21:microscope","title":"Microscope","description":"Objective and eyepiece magnifications multiply","domain":"optics"},
    {"id":"aperi21:telescope","title":"Telescope","description":"Magnification set by the ratio of focal lengths","domain":"optics"},
    {"id":"aperi21:youngs-double-slit","title":"Young's double slit","description":"Evidence that light is a wave","domain":"optics"},
    {"id":"aperi21:single-slit-diffraction","title":"Single-slit diffraction","description":"The pattern a width makes","domain":"optics"},
    {"id":"aperi21:diffraction-grating","title":"Diffraction grating","description":"Sharp maxima made by many slits","domain":"optics"},
    {"id":"aperi21:thin-film-interference","title":"Thin-film interference","description":"Colour made by thickness","domain":"optics"},
    {"id":"aperi21:newtons-rings","title":"Newton's rings","description":"Interference between a curved and a flat surface","domain":"optics"},
    {"id":"aperi21:resolving-power","title":"Resolving power","description":"The limit of telling two points apart","domain":"optics"},
    {"id":"aperi21:polarization","title":"Polarization","description":"Selecting the plane of vibration","domain":"optics"},
    {"id":"aperi21:malus-law","title":"Malus's law","description":"Intensity through a polarizer","domain":"optics"},
    {"id":"aperi21:brewster-angle","title":"Brewster's angle","description":"The angle at which reflected light is fully polarized","domain":"optics"},
    {"id":"aperi21:birefringence","title":"Birefringence","description":"Refractive index that depends on direction","domain":"optics"},
    {"id":"aperi21:scattering","title":"Scattering","description":"The colours of the sky and the sunset","domain":"optics"},
    {"id":"aperi21:rayleigh-scattering","title":"Rayleigh scattering","description":"Scattering that falls with the fourth power of wavelength","domain":"optics"},
    {"id":"aperi21:seeing-requires-light","title":"Seeing needs light","description":"Without light, an object cannot be seen","domain":"optics"},
    {"id":"aperi21:color-addition","title":"Adding light","description":"The colour three lights make where they overlap","domain":"optics"},
    {"id":"aperi21:object-color","title":"The colour of an object","description":"The colour set by the light an object sends back","domain":"optics"},
    {"id":"aperi21:light-through-materials","title":"Light and materials","description":"How light gets through depends on the material","domain":"optics"},
    {"id":"aperi21:electric-charge","title":"Electric charge","description":"Two kinds of charge and their conservation","domain":"electromagnetism"},
    {"id":"aperi21:charging-methods","title":"Charging methods","description":"Friction, contact and induction","domain":"electromagnetism"},
    {"id":"aperi21:coulombs-law","title":"Coulomb's law","description":"The force between charges","domain":"electromagnetism"},
    {"id":"aperi21:superposition-of-forces","title":"Superposition of electric forces","description":"Adding the forces from several charges","domain":"electromagnetism"},
    {"id":"aperi21:electric-field","title":"Electric field","description":"The force on a unit charge","domain":"electromagnetism"},
    {"id":"aperi21:field-lines","title":"Electric field lines","description":"Where the lines crowd, the field is strong","domain":"electromagnetism"},
    {"id":"aperi21:field-of-dipole","title":"Electric field of a dipole","description":"Two nearby opposite charges","domain":"electromagnetism"},
    {"id":"aperi21:uniform-field","title":"Uniform electric field","description":"The field between parallel plates","domain":"electromagnetism"},
    {"id":"aperi21:charge-in-uniform-field","title":"A charge in a uniform field","description":"Just like a projectile","domain":"electromagnetism"},
    {"id":"aperi21:gausss-law","title":"Gauss’s law","description":"Electric flux through a closed surface","domain":"electromagnetism"},
    {"id":"aperi21:field-of-charged-sphere","title":"Field of a charged sphere","description":"Why inside and outside differ","domain":"electromagnetism"},
    {"id":"aperi21:equipotential-surface","title":"Equipotential surfaces","description":"Surfaces perpendicular to the field","domain":"electromagnetism"},
    {"id":"aperi21:potential-vs-field","title":"Potential and electric field","description":"The slope relation","domain":"electromagnetism"},
    {"id":"aperi21:electrostatic-shielding","title":"Electrostatic shielding","description":"Why the field inside a conductor is zero","domain":"electromagnetism"},
    {"id":"aperi21:charge-on-conductor-surface","title":"Charge on a conductor surface","description":"Charge crowds at the sharp end","domain":"electromagnetism"},
    {"id":"aperi21:dielectric","title":"Dielectric","description":"Polarization weakens the field","domain":"electromagnetism"},
    {"id":"aperi21:parallel-plate-capacitor","title":"Parallel-plate capacitor","description":"Capacitance set by area and gap","domain":"electromagnetism"},
    {"id":"aperi21:capacitors-in-circuit","title":"Connecting capacitors","description":"Combining in series and in parallel","domain":"electromagnetism"},
    {"id":"aperi21:energy-in-capacitor","title":"Energy in a capacitor","description":"Energy stored in the electric field","domain":"electromagnetism"},
    {"id":"aperi21:electric-current","title":"Electric current","description":"The flow of charge and its sign convention","domain":"electromagnetism"},
    {"id":"aperi21:drift-velocity","title":"Drift velocity","description":"Slow electrons, fast signal","domain":"electromagnetism"},
    {"id":"aperi21:ohms-law","title":"Ohm's law","description":"Voltage, current and resistance","domain":"electromagnetism"},
    {"id":"aperi21:resistance-and-geometry","title":"Resistance and shape","description":"How length and cross-section matter","domain":"electromagnetism"},
    {"id":"aperi21:temperature-and-resistance","title":"Temperature and resistance","description":"Metals and semiconductors go opposite ways","domain":"electromagnetism"},
    {"id":"aperi21:series-parallel-resistors","title":"电阻的串联与并联","description":"连接方式如何改变同一个电池输出的电流","domain":"electromagnetism"},
    {"id":"aperi21:emf-and-internal-resistance","title":"电动势与内阻","description":"端电压为何下降","domain":"electromagnetism"},
    {"id":"aperi21:kirchhoffs-current-law","title":"Kirchhoff's current law","description":"Conservation of charge at a junction","domain":"electromagnetism"},
    {"id":"aperi21:kirchhoffs-voltage-law","title":"Kirchhoff's voltage law","description":"Conservation of energy around a loop","domain":"electromagnetism"},
    {"id":"aperi21:wheatstone-bridge","title":"惠斯通电桥","description":"用平衡测电阻","domain":"electromagnetism"},
    {"id":"aperi21:joule-heating","title":"Joule heating","description":"Heat made by resistance","domain":"electromagnetism"},
    {"id":"aperi21:rc-circuit","title":"RC circuit","description":"The remaining gap shrinks by the same ratio every τ","domain":"electromagnetism"},
    {"id":"aperi21:magnetic-field","title":"Magnetic field","description":"How magnetic force is spread around a magnet","domain":"electromagnetism"},
    {"id":"aperi21:magnetic-field-lines","title":"磁感线","description":"永不中断、总是闭合的线","domain":"electromagnetism"},
    {"id":"aperi21:lorentz-force","title":"Lorentz force","description":"The force on a charge moving in a magnetic field","domain":"electromagnetism"},
    {"id":"aperi21:charged-particle-in-magnetic-field","title":"Charges circling in a magnetic field","description":"A faster charge takes the same time per turn","domain":"electromagnetism"},
    {"id":"aperi21:velocity-selector","title":"Velocity selector","description":"Balancing the electric and magnetic forces","domain":"electromagnetism"},
    {"id":"aperi21:mass-spectrometer","title":"Mass spectrometer","description":"Sorting masses by radius","domain":"electromagnetism"},
    {"id":"aperi21:force-on-current-wire","title":"Force on a current-carrying wire","description":"The magnetic force on a wire carrying a current","domain":"electromagnetism"},
    {"id":"aperi21:biot-savart-law","title":"Biot–Savart law","description":"The magnetic field of current elements","domain":"electromagnetism"},
    {"id":"aperi21:field-of-straight-wire","title":"The field a current makes","description":"Needles turn along the loop, and less so farther out","domain":"electromagnetism"},
    {"id":"aperi21:field-of-loop-and-solenoid","title":"Loop and solenoid","description":"The magnetic field along the axis","domain":"electromagnetism"},
    {"id":"aperi21:amperes-law","title":"Ampère’s law","description":"Circulation of the magnetic field around a current","domain":"electromagnetism"},
    {"id":"aperi21:force-between-wires","title":"Force between parallel wires","description":"Two parallel currents attract or repel","domain":"electromagnetism"},
    {"id":"aperi21:magnetic-dipole","title":"Magnetic dipole","description":"A current loop and a magnet are the same","domain":"electromagnetism"},
    {"id":"aperi21:magnetic-materials","title":"Magnetic materials","description":"Ferromagnetic, paramagnetic and diamagnetic","domain":"electromagnetism"},
    {"id":"aperi21:faradays-law","title":"Faraday's law","description":"The EMF made by a changing flux","domain":"electromagnetism"},
    {"id":"aperi21:lenzs-law","title":"Lenz's law","description":"The current flips, the force never does","domain":"electromagnetism"},
    {"id":"aperi21:motional-emf","title":"Motional EMF","description":"The voltage made by a moving wire","domain":"electromagnetism"},
    {"id":"aperi21:eddy-current","title":"Eddy currents","description":"Induced currents inside a solid conductor","domain":"electromagnetism"},
    {"id":"aperi21:self-inductance","title":"Self-inductance","description":"A coil opposing changes in its own flux","domain":"electromagnetism"},
    {"id":"aperi21:mutual-inductance","title":"Mutual inductance","description":"An EMF induced in a neighbouring circuit","domain":"electromagnetism"},
    {"id":"aperi21:energy-in-inductor","title":"Energy in an inductor","description":"Energy stored in the magnetic field","domain":"electromagnetism"},
    {"id":"aperi21:rl-circuit","title":"RL circuit","description":"Why the current rises slowly","domain":"electromagnetism"},
    {"id":"aperi21:lc-oscillation","title":"LC oscillation","description":"Electric and magnetic energy trade places","domain":"electromagnetism"},
    {"id":"aperi21:ac-generation","title":"Generating alternating current","description":"A turning coil and a sine wave","domain":"electromagnetism"},
    {"id":"aperi21:reactance","title":"Reactance and impedance","description":"A resistance that depends on frequency","domain":"electromagnetism"},
    {"id":"aperi21:phase-in-ac-circuit","title":"Phase difference in AC circuits","description":"Voltage and current falling out of step","domain":"electromagnetism"},
    {"id":"aperi21:series-rlc-resonance","title":"RLC resonance","description":"The frequency where impedance is smallest","domain":"electromagnetism"},
    {"id":"aperi21:transformer","title":"Transformer","description":"Turns and the voltage ratio","domain":"electromagnetism"},
    {"id":"aperi21:motor","title":"Electric motor","description":"Turning by the force on a current","domain":"electromagnetism"},
    {"id":"aperi21:generator","title":"Generator","description":"The EMF made by turning","domain":"electromagnetism"},
    {"id":"aperi21:displacement-current","title":"Displacement current","description":"The term that bridges the capacitor gap","domain":"electromagnetism"},
    {"id":"aperi21:maxwells-equations","title":"Maxwell's equations","description":"Four equations that bind electromagnetism","domain":"electromagnetism"},
    {"id":"aperi21:electromagnetic-wave","title":"Electromagnetic waves","description":"Self-propagating electric and magnetic fields","domain":"electromagnetism"},
    {"id":"aperi21:poynting-vector","title":"Poynting vector","description":"The energy flow carried by electromagnetic waves","domain":"electromagnetism"},
    {"id":"aperi21:radiation-pressure","title":"Radiation pressure","description":"The push of light","domain":"electromagnetism"},
    {"id":"aperi21:antenna-radiation","title":"Antenna radiation","description":"The waves an accelerating charge sends out","domain":"electromagnetism"},
    {"id":"aperi21:magnet-attraction","title":"What sticks to a magnet","description":"Things a magnet pulls and things it does not","domain":"electromagnetism"},
    {"id":"aperi21:magnetic-poles","title":"The two poles of a magnet","description":"Like poles repel, unlike poles attract","domain":"electromagnetism"},
    {"id":"aperi21:simple-circuit","title":"Building an electric circuit","description":"It flows only when joined; break it and the bulb goes out","domain":"electromagnetism"},
    {"id":"aperi21:electromagnet","title":"Electromagnet","description":"A magnet only while current flows","domain":"electromagnetism"},
    {"id":"aperi21:iv-characteristic","title":"I–V characteristic curves","description":"Devices whose current does not follow voltage in a straight line","domain":"electromagnetism"},
    {"id":"aperi21:thermistor-and-ldr","title":"Thermistor and LDR","description":"Resistance that changes with temperature and light","domain":"electromagnetism"},
    {"id":"aperi21:potential-divider","title":"Potential divider","description":"Splitting a voltage with resistors","domain":"electromagnetism"},
    {"id":"aperi21:millikan-experiment","title":"Millikan oil-drop experiment","description":"Evidence that charge comes in lumps","domain":"electromagnetism"},
    {"id":"aperi21:power-transmission","title":"Power transmission","description":"Raising the voltage to cut the loss","domain":"electromagnetism"},
    {"id":"aperi21:loudspeaker-and-microphone","title":"Loudspeaker and microphone","description":"Turning current into vibration and back","domain":"electromagnetism"},
    {"id":"aperi21:michelson-morley","title":"Michelson–Morley experiment","description":"Evidence that there is no ether","domain":"modern-physics"},
    {"id":"aperi21:relativity-of-simultaneity","title":"Relativity of simultaneity","description":"Each frame has its own “at the same time”","domain":"modern-physics"},
    {"id":"aperi21:time-dilation","title":"Time dilation","description":"A moving clock runs slow","domain":"modern-physics"},
    {"id":"aperi21:light-clock","title":"Light clock","description":"The thought experiment behind time dilation","domain":"modern-physics"},
    {"id":"aperi21:length-contraction","title":"Length contraction","description":"Contraction along the direction of motion","domain":"modern-physics"},
    {"id":"aperi21:muon-decay-evidence","title":"Muons reaching the ground","description":"Observational evidence for time dilation","domain":"modern-physics"},
    {"id":"aperi21:relativistic-velocity-addition","title":"Relativistic velocity addition","description":"Composition that never exceeds light speed","domain":"modern-physics"},
    {"id":"aperi21:twin-paradox","title":"Twin paradox","description":"The acceleration that breaks the symmetry","domain":"modern-physics"},
    {"id":"aperi21:spacetime-diagram","title":"Spacetime diagram","description":"Worldline and line of simultaneity","domain":"modern-physics"},
    {"id":"aperi21:light-cone","title":"Light cone","description":"Where a cause can reach","domain":"modern-physics"},
    {"id":"aperi21:relativistic-momentum","title":"Relativistic momentum","description":"Momentum diverges as speed grows","domain":"modern-physics"},
    {"id":"aperi21:relativistic-doppler","title":"Relativistic Doppler effect","description":"Frequency shift with time dilation added","domain":"modern-physics"},
    {"id":"aperi21:equivalence-principle","title":"Equivalence principle","description":"Acceleration and gravity are indistinguishable","domain":"modern-physics"},
    {"id":"aperi21:gravitational-time-dilation","title":"Gravitational time dilation","description":"Clocks run at different rates at different potentials","domain":"modern-physics"},
    {"id":"aperi21:gravitational-redshift","title":"Gravitational redshift","description":"Energy lost climbing out of a gravity well","domain":"modern-physics"},
    {"id":"aperi21:light-bending-by-gravity","title":"Bending of light","description":"The path of light bends near a mass","domain":"modern-physics"},
    {"id":"aperi21:blackbody-radiation","title":"Blackbody radiation","description":"Where classical theory breaks down","domain":"modern-physics"},
    {"id":"aperi21:wien-displacement-law","title":"Wien's displacement law","description":"Temperature and peak wavelength","domain":"modern-physics"},
    {"id":"aperi21:photoelectric-effect","title":"Photoelectric effect","description":"Evidence that light comes in particles","domain":"modern-physics"},
    {"id":"aperi21:work-function-and-threshold","title":"Work function and threshold frequency","description":"Set by frequency, not by intensity","domain":"modern-physics"},
    {"id":"aperi21:compton-scattering","title":"Compton scattering","description":"Evidence that a photon carries momentum","domain":"modern-physics"},
    {"id":"aperi21:pair-production","title":"Pair production","description":"Energy turning into matter","domain":"modern-physics"},
    {"id":"aperi21:de-broglie-wavelength","title":"de Broglie wavelength","description":"The wave nature of matter","domain":"modern-physics"},
    {"id":"aperi21:electron-diffraction","title":"Electron diffraction","description":"Seeing matter waves","domain":"modern-physics"},
    {"id":"aperi21:double-slit-with-electrons","title":"Double slit with electrons","description":"A pattern that forms one electron at a time","domain":"modern-physics"},
    {"id":"aperi21:uncertainty-principle","title":"Uncertainty principle","description":"How sharply two conjugate quantities can be fixed at once","domain":"modern-physics"},
    {"id":"aperi21:wave-function","title":"Wave function","description":"Probability amplitude and what it means","domain":"modern-physics"},
    {"id":"aperi21:superposition-quantum","title":"Quantum superposition","description":"Being a sum of several states","domain":"modern-physics"},
    {"id":"aperi21:measurement-collapse","title":"Measurement and collapse","description":"How observing settles the state","domain":"modern-physics"},
    {"id":"aperi21:particle-in-a-box","title":"Infinite square well","description":"Energy quantization made by the walls","domain":"modern-physics"},
    {"id":"aperi21:finite-well","title":"Finite square well","description":"A wave function that leaks past the walls","domain":"modern-physics"},
    {"id":"aperi21:quantum-tunneling","title":"Quantum tunneling","description":"The chance of passing through a barrier","domain":"modern-physics"},
    {"id":"aperi21:scanning-tunneling-microscope","title":"Scanning tunneling microscope","description":"Drawing a surface with tunneling current","domain":"modern-physics"},
    {"id":"aperi21:quantum-harmonic-oscillator","title":"Quantum harmonic oscillator","description":"Evenly spaced levels and zero-point energy","domain":"modern-physics"},
    {"id":"aperi21:hydrogen-spectrum","title":"Hydrogen spectrum","description":"A discrete line spectrum","domain":"modern-physics"},
    {"id":"aperi21:bohr-model","title":"Bohr model","description":"Quantized orbits","domain":"modern-physics"},
    {"id":"aperi21:atomic-orbital","title":"Atomic orbital","description":"The electron as a probability distribution","domain":"modern-physics"},
    {"id":"aperi21:pauli-exclusion","title":"Pauli exclusion principle","description":"No two in the same state","domain":"modern-physics"},
    {"id":"aperi21:electron-configuration","title":"Electron configuration","description":"How the periodic table arises","domain":"modern-physics"},
    {"id":"aperi21:spin","title":"Spin","description":"Angular momentum with no classical counterpart","domain":"modern-physics"},
    {"id":"aperi21:stern-gerlach","title":"Stern–Gerlach experiment","description":"An atomic beam that splits","domain":"modern-physics"},
    {"id":"aperi21:zeeman-effect","title":"Zeeman effect","description":"Energy levels split by a magnetic field","domain":"modern-physics"},
    {"id":"aperi21:laser-and-stimulated-emission","title":"Lasers and stimulated emission","description":"Amplifying light in step","domain":"modern-physics"},
    {"id":"aperi21:nuclear-structure","title":"What a nucleus is made of","description":"Protons and neutrons","domain":"modern-physics"},
    {"id":"aperi21:binding-energy-curve","title":"Binding energy curve","description":"Why it peaks at iron","domain":"modern-physics"},
    {"id":"aperi21:radioactive-decay","title":"Radioactive decay","description":"Half-life and exponential decay","domain":"modern-physics"},
    {"id":"aperi21:decay-types","title":"Types of decay radiation","description":"Alpha, beta, gamma","domain":"modern-physics"},
    {"id":"aperi21:radiometric-dating","title":"Radiometric dating","description":"Telling time by what remains","domain":"modern-physics"},
    {"id":"aperi21:nuclear-fission","title":"Nuclear fission","description":"The energy released when a heavy nucleus splits","domain":"modern-physics"},
    {"id":"aperi21:chain-reaction","title":"Chain reaction","description":"Fission carried on by neutrons","domain":"modern-physics"},
    {"id":"aperi21:nuclear-fusion","title":"Nuclear fusion","description":"Energy released when light nuclei join","domain":"modern-physics"},
    {"id":"aperi21:antimatter","title":"Antimatter","description":"A partner with the opposite charge","domain":"modern-physics"},
    {"id":"aperi21:band-theory","title":"Band theory","description":"What separates conductors, insulators and semiconductors","domain":"modern-physics"},
    {"id":"aperi21:fermi-level","title":"Fermi level","description":"How high the electrons fill","domain":"modern-physics"},
    {"id":"aperi21:semiconductor-doping","title":"Doping","description":"How impurities make n-type and p-type","domain":"modern-physics"},
    {"id":"aperi21:pn-junction","title":"p–n junction","description":"Depletion layer and rectification","domain":"modern-physics"},
    {"id":"aperi21:diode-and-led","title":"二极管与LED","description":"单向电流与光的发射","domain":"modern-physics"},
    {"id":"aperi21:transistor-principle","title":"Transistor","description":"A small signal controls a large current","domain":"modern-physics"},
    {"id":"aperi21:photovoltaic-effect","title":"Photovoltaic effect","description":"A voltage made by light","domain":"modern-physics"},
    {"id":"aperi21:superconductivity","title":"Superconductivity","description":"The state in which resistance vanishes","domain":"modern-physics"},
    {"id":"aperi21:meissner-effect","title":"Meissner effect","description":"A superconductor pushes out the magnetic field","domain":"modern-physics"},
    {"id":"aperi21:bose-einstein-condensate","title":"Bose–Einstein condensation","description":"Cold particles crowding into one state","domain":"modern-physics"},
    {"id":"aperi21:scale-of-universe","title":"宇宙的尺度","description":"从原子到宇宙，以10的幂相连的尺寸","domain":"modern-physics"},
    {"id":"aperi21:rutherford-scattering","title":"Rutherford scattering","description":"The experiment where most passed through and a few bounced back","domain":"modern-physics"},
    {"id":"aperi21:ionizing-radiation","title":"Ionizing radiation","description":"Photon energy large enough to break bonds","domain":"modern-physics"},
    {"id":"aperi21:exchange-particles","title":"Exchange particles","description":"Particles that carry a force","domain":"modern-physics"},
  ],
};
