/**
 * 자동 생성 파일 — 직접 편집하지 말 것.
 *
 * 생성: pnpm catalog:gen  (scripts/gen-aperi21-catalog.mts)
 * 출처: 각 sim 의 schema(label/operation/category) + registerAperi21Bundles 의 loader id.
 *
 * 이 배열은 순수 데이터라 sim 의 무거운 시각화 chunk 를 참조하지 않는다.
 * 따라서 호스트는 이 카탈로그를 읽어도 sim 모듈을 로드하지 않는다 (lazy 보존).
 */

import type { Aperi21CatalogEntry } from './catalog-types.js';

export const APERI21_CATALOG: readonly Aperi21CatalogEntry[] = [
  {"id":"aperi21:apparent-brightness","title":{"ko":"겉보기 밝기","en":"Apparent brightness"},"description":{"ko":"같은 빛이 넓은 면에 나뉜다","en":"The same light divides over a wider area"},"domain":"astro"},
  {"id":"aperi21:axial-tilt-seasons","title":{"ko":"자전축 기울기와 계절","en":"Axial tilt and the seasons"},"description":{"ko":"기울어진 채 도는 것이 만드는 계절","en":"The seasons made by an Earth that orbits tilted"},"domain":"astro"},
  {"id":"aperi21:black-hole-horizon","title":{"ko":"사건 지평선","en":"Event horizon"},"description":{"ko":"탈출 속도가 광속이 되는 반지름","en":"The radius where escape speed reaches light speed"},"domain":"astro"},
  {"id":"aperi21:circular-orbit","title":{"ko":"원 궤도","en":"Circular orbit"},"description":{"ko":"구심력이 중력인 운동","en":"Motion in which gravity is the centripetal force"},"domain":"astro"},
  {"id":"aperi21:diurnal-motion","title":{"ko":"일주 운동","en":"Diurnal motion"},"description":{"ko":"하루 동안 태양과 별이 하늘을 가로지르는 길","en":"The paths the Sun and stars trace across the sky in a day"},"domain":"astro"},
  {"id":"aperi21:earth-revolution-constellations","title":{"ko":"공전과 별자리","en":"Earth’s orbit and the constellations"},"description":{"ko":"계절마다 보이는 별자리가 달라지는 이유","en":"Why the constellations we see change with the seasons"},"domain":"astro"},
  {"id":"aperi21:earth-rotation-day-night","title":{"ko":"자전과 낮과 밤","en":"Earth’s rotation, day and night"},"description":{"ko":"도는 지구 위에서 낮과 밤이 갈리는 이유","en":"Why day and night alternate on a turning Earth"},"domain":"astro"},
  {"id":"aperi21:eclipse","title":{"ko":"일식과 월식","en":"Solar and lunar eclipses"},"description":{"ko":"해와 지구와 달이 한 줄에 설 때","en":"When the Sun, Earth and Moon line up"},"domain":"astro"},
  {"id":"aperi21:elliptical-orbit","title":{"ko":"타원 궤도","en":"Elliptical orbit"},"description":{"ko":"초점에 놓인 중심 천체","en":"The central body sits at a focus"},"domain":"astro"},
  {"id":"aperi21:escape-velocity","title":{"ko":"탈출 속도","en":"Escape velocity"},"description":{"ko":"중력을 벗어나는 최소 속도","en":"The least speed that breaks free of gravity"},"domain":"astro"},
  {"id":"aperi21:exoplanet-detection","title":{"ko":"외계행성 탐지","en":"Detecting exoplanets"},"description":{"ko":"행성이 남기는 흔적","en":"The traces a planet leaves"},"domain":"astro"},
  {"id":"aperi21:expanding-universe","title":{"ko":"우주의 팽창","en":"The expanding universe"},"description":{"ko":"모든 방향으로 멀어지는 은하들","en":"Galaxies receding in every direction"},"domain":"astro"},
  {"id":"aperi21:geostationary-orbit","title":{"ko":"정지 궤도","en":"Geostationary orbit"},"description":{"ko":"자전 주기와 같은 궤도","en":"An orbit as long as one turn of Earth"},"domain":"astro"},
  {"id":"aperi21:gravitational-field","title":{"ko":"중력장","en":"Gravitational field"},"description":{"ko":"공간에 분포한 중력의 세기","en":"The strength of gravity spread through space"},"domain":"astro"},
  {"id":"aperi21:gravitational-potential-energy-general","title":{"ko":"중력 퍼텐셜 에너지(일반)","en":"Gravitational potential energy (general)"},"description":{"ko":"무한대를 기준으로 한 음의 에너지","en":"A negative energy measured from infinity"},"domain":"astro"},
  {"id":"aperi21:gravitational-slingshot","title":{"ko":"중력 도움","en":"Gravity assist"},"description":{"ko":"천체를 이용한 속도 변화","en":"Changing speed by passing a planet"},"domain":"astro"},
  {"id":"aperi21:gravity-inside-earth","title":{"ko":"지구 내부의 중력","en":"Gravity inside the Earth"},"description":{"ko":"깊이에 따라 줄어드는 중력","en":"Gravity that weakens with depth"},"domain":"astro"},
  {"id":"aperi21:hr-diagram","title":{"ko":"HR 도","en":"HR diagram"},"description":{"ko":"무거운 별부터 주계열 띠를 떠난다","en":"The heaviest stars leave the main sequence first"},"domain":"astro"},
  {"id":"aperi21:inverse-square-law","title":{"ko":"역제곱 법칙","en":"Inverse-square law"},"description":{"ko":"퍼지는 만큼 옅어지는 것","en":"Thinning out as it spreads"},"domain":"astro"},
  {"id":"aperi21:keplers-first-law","title":{"ko":"케플러 제1법칙","en":"Kepler's first law"},"description":{"ko":"궤도는 타원이다","en":"Orbits are ellipses"},"domain":"astro"},
  {"id":"aperi21:keplers-second-law","title":{"ko":"케플러 제2법칙","en":"Kepler's second law"},"description":{"ko":"같은 시간에 같은 넓이","en":"Equal areas in equal times"},"domain":"astro"},
  {"id":"aperi21:keplers-third-law","title":{"ko":"케플러 제3법칙","en":"Kepler's third law"},"description":{"ko":"주기와 긴반지름의 관계","en":"How the period depends on the semi-major axis"},"domain":"astro"},
  {"id":"aperi21:lagrange-points","title":{"ko":"라그랑주 점","en":"Lagrange points"},"description":{"ko":"안장에서는 흘러나가고 꼭대기에서는 맴돈다","en":"Drifting off the saddles, circling the peaks"},"domain":"astro"},
  {"id":"aperi21:magnitude-scale","title":{"ko":"별의 등급","en":"Stellar magnitude"},"description":{"ko":"밝기를 등급으로 나타내는 방식","en":"How brightness is written as magnitude"},"domain":"astro"},
  {"id":"aperi21:moon-phases","title":{"ko":"달의 위상","en":"Phases of the Moon"},"description":{"ko":"햇빛을 받는 달의 어느 쪽을 보는가","en":"Which part of the sunlit Moon faces us"},"domain":"astro"},
  {"id":"aperi21:newtons-law-of-gravitation","title":{"ko":"만유인력 법칙","en":"Newton's law of gravitation"},"description":{"ko":"거리 제곱에 반비례하는 힘","en":"A force that falls with the square of distance"},"domain":"astro"},
  {"id":"aperi21:orbital-decay","title":{"ko":"궤도 감쇠","en":"Orbital decay"},"description":{"ko":"옅은 대기가 끄는 궤도","en":"An orbit dragged by thin air"},"domain":"astro"},
  {"id":"aperi21:orbital-transfer","title":{"ko":"궤도 전이","en":"Orbital transfer"},"description":{"ko":"호만 전이와 그 비용","en":"The Hohmann transfer and what it costs"},"domain":"astro"},
  {"id":"aperi21:orbital-velocity","title":{"ko":"궤도 속도","en":"Orbital velocity"},"description":{"ko":"원 궤도를 유지하는 속도","en":"The speed that keeps an orbit circular"},"domain":"astro"},
  {"id":"aperi21:roche-limit","title":{"ko":"로슈 한계","en":"Roche limit"},"description":{"ko":"조석력이 천체를 부수는 거리","en":"The distance at which tides tear a body apart"},"domain":"astro"},
  {"id":"aperi21:seasonal-sun-path","title":{"ko":"계절과 태양의 길","en":"The Sun’s path through the seasons"},"description":{"ko":"남중 고도와 낮 길이가 함께 달라지는 것","en":"How the noon altitude and the length of day change together"},"domain":"astro"},
  {"id":"aperi21:shell-theorem","title":{"ko":"껍질 정리","en":"Shell theorem"},"description":{"ko":"구 껍질 안팎에서의 중력","en":"Gravity inside and outside a spherical shell"},"domain":"astro"},
  {"id":"aperi21:solar-altitude-shadow","title":{"ko":"태양 고도와 그림자","en":"Solar altitude and shadows"},"description":{"ko":"고도가 바뀌면 그림자 길이와 기온이 함께 바뀐다","en":"As the Sun’s altitude changes, shadow length and warmth change together"},"domain":"astro"},
  {"id":"aperi21:star-color-temperature","title":{"ko":"별의 색과 표면 온도","en":"Star color and surface temperature"},"description":{"ko":"표면 온도가 정하는 별빛의 색","en":"How surface temperature sets the color of starlight"},"domain":"astro"},
  {"id":"aperi21:star-life-cycle","title":{"ko":"별의 일생","en":"Life cycle of a star"},"description":{"ko":"질량이 가르는 별의 경로","en":"How mass decides a star’s path"},"domain":"astro"},
  {"id":"aperi21:star-radiation-gravity-balance","title":{"ko":"복사압과 중력의 평형","en":"Radiation pressure and gravity in balance"},"description":{"ko":"별이 무너지지도 흩어지지도 않는 이유","en":"Why a star neither collapses nor flies apart"},"domain":"astro"},
  {"id":"aperi21:stellar-luminosity","title":{"ko":"광도","en":"Luminosity"},"description":{"ko":"별이 실제로 내는 빛의 양","en":"How much light a star actually gives off"},"domain":"astro"},
  {"id":"aperi21:stellar-nucleosynthesis","title":{"ko":"별의 원소 합성","en":"Stellar nucleosynthesis"},"description":{"ko":"무거운 원소가 별에서 만들어지는 것","en":"How heavier elements are made inside stars"},"domain":"astro"},
  {"id":"aperi21:stellar-parallax","title":{"ko":"연주시차","en":"Stellar parallax"},"description":{"ko":"지구가 공전하며 가까운 별이 어긋나 보이는 각","en":"The angle by which a nearby star shifts as Earth orbits the Sun"},"domain":"astro"},
  {"id":"aperi21:stellar-spectral-class","title":{"ko":"별의 스펙트럼 분류","en":"Stellar spectral classes"},"description":{"ko":"온도가 정하는 흡수선 무늬","en":"Absorption-line patterns set by temperature"},"domain":"astro"},
  {"id":"aperi21:supernova-and-neutron-star","title":{"ko":"초신성과 중성자별","en":"Supernova and neutron star"},"description":{"ko":"무너지고 튕겨 나가는 최후","en":"A final collapse and rebound"},"domain":"astro"},
  {"id":"aperi21:tidal-force","title":{"ko":"조석력","en":"Tidal force"},"description":{"ko":"중력의 차이가 만드는 늘어남","en":"Stretching made by a difference in gravity"},"domain":"astro"},
  {"id":"aperi21:two-body-problem","title":{"ko":"이체 문제","en":"Two-body problem"},"description":{"ko":"질량 중심 둘레를 도는 두 천체","en":"Two bodies orbiting their common center of mass"},"domain":"astro"},
  {"id":"aperi21:weightlessness","title":{"ko":"무중력","en":"Weightlessness"},"description":{"ko":"자유 낙하 중의 겉보기 무게","en":"Apparent weight in free fall"},"domain":"astro"},
  {"id":"aperi21:dc-circuit","title":{"ko":"DC 회로","en":"DC Circuit"},"description":{"ko":"배터리·저항으로 단순·직렬·병렬 회로를 구성해 전압·전류를 확인.","en":"Build simple/series/parallel DC circuits with batteries and resistors; inspect V/I."},"domain":"electromagnetism"},
  {"id":"aperi21:charged-particle-in-magnetic-field","title":{"ko":"자기장 속 전하의 원운동","en":"Charges circling in a magnetic field"},"description":{"ko":"빠른 전하도 한 바퀴 시간은 같다","en":"A faster charge takes the same time per turn"},"domain":"em"},
  {"id":"aperi21:current-magnetic-field","title":{"ko":"전류가 만드는 자기장","en":"The field a current makes"},"description":{"ko":"전선을 감아 도는 쪽으로 돌아서고, 멀수록 덜 돌아선다","en":"Needles turn along the loop, and less so farther out"},"domain":"em"},
  {"id":"aperi21:electromagnetic-wave","title":{"ko":"전자기파","en":"Electromagnetic waves"},"description":{"ko":"전기장과 자기장의 자기 전파","en":"Self-propagating electric and magnetic fields"},"domain":"em"},
  {"id":"aperi21:equipotential-surface","title":{"ko":"등전위면","en":"Equipotential surfaces"},"description":{"ko":"전기장과 수직인 면","en":"Surfaces perpendicular to the field"},"domain":"em"},
  {"id":"aperi21:field-lines","title":{"ko":"전기력선","en":"Electric field lines"},"description":{"ko":"선이 촘촘한 곳이 장이 센 곳이다","en":"Where the lines crowd, the field is strong"},"domain":"em"},
  {"id":"aperi21:lenz-law","title":{"ko":"렌츠 법칙","en":"Lenz's law"},"description":{"ko":"전류는 뒤집혀도 힘은 늘 움직임을 거스른다","en":"The current flips, the force never does"},"domain":"em"},
  {"id":"aperi21:rc-circuit","title":{"ko":"RC 회로","en":"RC circuit"},"description":{"ko":"남은 차이가 τ 마다 같은 비율로 줄어든다","en":"The remaining gap shrinks by the same ratio every τ"},"domain":"em"},
  {"id":"aperi21:archimedes-principle","title":{"ko":"아르키메데스 원리 — 부력의 크기","en":"Archimedes principle — the size of the buoyant force"},"description":{"ko":"2.0 kg · 1.0 L 물체를 주둥이까지 가득 찬 물에 천천히 담근다. 밀려난 물이 주둥이로 넘쳐 컵에 모이고, 물체 쪽 저울이 줄어드는 만큼 넘친 물 쪽 저울이 늘어난다.","en":"A 2.0 kg, 1.0 L object is lowered into a can filled to its spout. The displaced water pours into the cup, and the scale holding the water gains exactly what the scale holding the object loses."},"domain":"fluids"},
  {"id":"aperi21:atmospheric-pressure","title":{"ko":"대기압","en":"Atmospheric pressure"},"description":{"ko":"공기 기둥의 무게","en":"The weight of the air column"},"domain":"fluids"},
  {"id":"aperi21:barometer","title":{"ko":"기압계","en":"Barometer"},"description":{"ko":"수은 기둥의 높이","en":"The height of a mercury column"},"domain":"fluids"},
  {"id":"aperi21:bernoullis-principle","title":{"ko":"베르누이 원리","en":"Bernoulli's principle"},"description":{"ko":"빨라진 만큼 압력이 내려간다","en":"Where water speeds up, its pressure drops"},"domain":"fluids"},
  {"id":"aperi21:boundary-layer","title":{"ko":"경계층","en":"Boundary layer"},"description":{"ko":"벽 근처에서 속도가 0이 되는 층","en":"The layer near a wall where the flow slows to zero"},"domain":"fluids"},
  {"id":"aperi21:buoyancy","title":{"ko":"부력","en":"Buoyancy"},"description":{"ko":"밀려난 유체의 무게만큼","en":"As much as the weight of the fluid pushed aside"},"domain":"fluids"},
  {"id":"aperi21:capillary-action","title":{"ko":"모세관 현상","en":"Capillary action"},"description":{"ko":"좁은 관에서의 상승과 하강","en":"Rise and fall in narrow tubes"},"domain":"fluids"},
  {"id":"aperi21:continuity-equation","title":{"ko":"연속 방정식","en":"Continuity equation"},"description":{"ko":"단면적과 유속의 반비례","en":"Cross-section and flow speed trade off"},"domain":"fluids"},
  {"id":"aperi21:drag-in-fluid","title":{"ko":"유체 속 항력","en":"Drag in a fluid"},"description":{"ko":"형상과 속도가 정하는 저항","en":"Drag set by shape and speed"},"domain":"fluids"},
  {"id":"aperi21:floating-and-draft","title":{"ko":"뜨는 깊이","en":"How deep a floating body sits"},"description":{"ko":"잠기는 부피가 정해지는 방식","en":"What sets the submerged volume"},"domain":"fluids"},
  {"id":"aperi21:hydrostatic-pressure","title":{"ko":"정수압","en":"Hydrostatic pressure"},"description":{"ko":"깊이에 비례하는 압력","en":"Pressure that grows with depth"},"domain":"fluids"},
  {"id":"aperi21:laminar-vs-turbulent","title":{"ko":"층류와 난류","en":"Laminar and turbulent flow"},"description":{"ko":"흐름이 갑자기 흐트러지는 지점","en":"Where flow suddenly breaks up"},"domain":"fluids"},
  {"id":"aperi21:laplace-pressure","title":{"ko":"라플라스 압력","en":"Laplace pressure"},"description":{"ko":"곡률이 만드는 안팎 압력차","en":"The pressure jump a curved surface makes"},"domain":"fluids"},
  {"id":"aperi21:lift-force","title":{"ko":"양력","en":"Lift"},"description":{"ko":"날개 위아래의 흐름 차이","en":"How air flows over and under a wing"},"domain":"fluids"},
  {"id":"aperi21:manometer","title":{"ko":"압력계","en":"Manometer"},"description":{"ko":"액주 차이로 재는 압력","en":"Reading pressure from a liquid column"},"domain":"fluids"},
  {"id":"aperi21:pascals-principle","title":{"ko":"파스칼 원리","en":"Pascal's principle"},"description":{"ko":"압력의 전달과 유압 장치","en":"Transmitted pressure and the hydraulic press"},"domain":"fluids"},
  {"id":"aperi21:poiseuille-flow","title":{"ko":"관 속의 층류","en":"Laminar flow in a pipe"},"description":{"ko":"반지름 4제곱에 비례하는 유량","en":"Flow rate grows as the fourth power of the radius"},"domain":"fluids"},
  {"id":"aperi21:pressure-and-container-shape","title":{"ko":"그릇 모양과 바닥 압력","en":"Container shape and bottom pressure"},"description":{"ko":"수면 높이를 옮겨 세 그릇을 다시 채운다","en":"Move the water level and refill all three"},"domain":"fluids"},
  {"id":"aperi21:pressure-isotropy","title":{"ko":"압력의 등방성","en":"Pressure isotropy"},"description":{"ko":"판이 저절로 반 바퀴 돌아 자취를 원으로 닫고, 그다음 독자가 다이얼로 직접 돌린다","en":"the plate turns half a revolution to close the trail into a circle, then the reader turns it by hand"},"domain":"fluids"},
  {"id":"aperi21:reynolds-number","title":{"ko":"레이놀즈 수","en":"Reynolds number"},"description":{"ko":"전이를 가르는 무차원 수","en":"The dimensionless number that decides the transition"},"domain":"fluids"},
  {"id":"aperi21:stability-of-floating-body","title":{"ko":"부유체의 안정","en":"Stability of a floating body"},"description":{"ko":"기울면 부심이 옮겨 가 배를 되세운다","en":"When a boat heels, its centre of buoyancy shifts and rights it"},"domain":"fluids"},
  {"id":"aperi21:stokes-drag","title":{"ko":"스토크스 항력","en":"Stokes drag"},"description":{"ko":"느린 흐름에서의 저항","en":"Drag in slow, viscous flow"},"domain":"fluids"},
  {"id":"aperi21:surface-tension","title":{"ko":"표면 장력","en":"Surface tension"},"description":{"ko":"표면을 줄이려는 힘","en":"The pull that shrinks a surface"},"domain":"fluids"},
  {"id":"aperi21:torricellis-law","title":{"ko":"토리첼리 법칙","en":"Torricelli's law"},"description":{"ko":"깊은 구멍일수록 더 빠르게 뿜는다","en":"The deeper the hole, the faster the jet"},"domain":"fluids"},
  {"id":"aperi21:venturi-effect","title":{"ko":"벤투리 효과","en":"Venturi effect"},"description":{"ko":"좁아진 곳에서 낮아지는 압력","en":"Lower pressure where the pipe narrows"},"domain":"fluids"},
  {"id":"aperi21:viscosity","title":{"ko":"점성","en":"Viscosity"},"description":{"ko":"층 사이의 마찰","en":"Friction between layers"},"domain":"fluids"},
  {"id":"aperi21:wetting-and-contact-angle","title":{"ko":"젖음과 접촉각","en":"Wetting and contact angle"},"description":{"ko":"액체가 고체 위에 퍼지는 정도","en":"How far a liquid spreads over a solid"},"domain":"fluids"},
  {"id":"aperi21:acceleration-time-graph","title":{"ko":"가속도-시간 그래프","en":"Acceleration-time graph"},"description":{"ko":"넓이가 속도 변화인 표현","en":"The area under the graph is the change in velocity"},"domain":"kinematics"},
  {"id":"aperi21:angular-acceleration","title":{"ko":"각가속도","en":"Angular acceleration"},"description":{"ko":"같은 0.5초에 도는 각이 매번 더 커진다","en":"Each half-second sweeps a wider angle than the last"},"domain":"kinematics"},
  {"id":"aperi21:average-acceleration","title":{"ko":"평균 가속도","en":"Average acceleration"},"description":{"ko":"속도 변화의 비율","en":"Rate of change of velocity"},"domain":"kinematics"},
  {"id":"aperi21:average-velocity","title":{"ko":"평균 속도","en":"Average velocity"},"description":{"ko":"구간 전체를 대표하는 속도","en":"One velocity standing for a whole interval"},"domain":"kinematics"},
  {"id":"aperi21:centripetal-acceleration","title":{"ko":"구심 가속도","en":"Centripetal acceleration"},"description":{"ko":"속도의 변화는 늘 중심 쪽으로 꺾인다","en":"The change in velocity always turns toward the center"},"domain":"kinematics"},
  {"id":"aperi21:coordinate-choice","title":{"ko":"좌표계 선택","en":"Choosing axes"},"description":{"ko":"축을 어디에 두느냐가 식을 바꾸는 방식","en":"How the choice of axes changes the equations"},"domain":"kinematics"},
  {"id":"aperi21:direction-of-acceleration","title":{"ko":"가속도의 방향","en":"Direction of acceleration"},"description":{"ko":"속도와 같은 방향인지 반대인지가 정하는 것","en":"Whether it points with or against the velocity"},"domain":"kinematics"},
  {"id":"aperi21:free-fall","title":{"ko":"자유 낙하","en":"Free fall"},"description":{"ko":"무게가 달라도 두 공은 나란히 내려가 함께 닿는다","en":"However different their weights, the two balls fall together and land together"},"domain":"kinematics"},
  {"id":"aperi21:gravitational-acceleration","title":{"ko":"중력 가속도","en":"Gravitational acceleration"},"description":{"ko":"속도가 0인 순간에도 멈추지 않는 가속","en":"Acceleration that does not stop even when the velocity is zero"},"domain":"kinematics"},
  {"id":"aperi21:position-time-graph","title":{"ko":"위치-시간 그래프","en":"Position-time graph"},"description":{"ko":"빨리 오를수록 남기는 선이 가파르다","en":"The faster it rises, the steeper the line it leaves"},"domain":"kinematics"},
  {"id":"aperi21:projectile-motion","title":{"ko":"포물선 운동","en":"Projectile motion"},"description":{"ko":"수평과 연직이 서로를 건드리지 않고 따로 간다","en":"Horizontal and vertical go on untouched"},"domain":"kinematics"},
  {"id":"aperi21:radius-of-curvature","title":{"ko":"곡률 반지름","en":"Radius of curvature"},"description":{"ko":"굽은 정도에 맞는 원이 경로에 얹힌다","en":"A circle matching the bend rides the path"},"domain":"kinematics"},
  {"id":"aperi21:reference-frame","title":{"ko":"기준틀","en":"Reference frame"},"description":{"ko":"관찰자에 따라 달라지는 운동 기술","en":"How the description of motion depends on the observer"},"domain":"kinematics"},
  {"id":"aperi21:relative-velocity","title":{"ko":"상대 속도","en":"Relative velocity"},"description":{"ko":"보는 사람이 달라지면 배가 지나온 길이 기운다","en":"Change who is watching and the path the boat left tilts"},"domain":"kinematics"},
  {"id":"aperi21:river-crossing","title":{"ko":"강 건너기","en":"Crossing a river"},"description":{"ko":"뱃머리를 맞은편에 두어도 물살에 떠밀려 하류에 닿는다","en":"Aimed straight across, the boat is pushed downstream by the current"},"domain":"kinematics"},
  {"id":"aperi21:stopping-distance","title":{"ko":"정지 거리","en":"Stopping distance"},"description":{"ko":"반응 거리는 비례로, 제동 거리는 제곱으로 늘어난다","en":"Reaction grows linearly, braking as the square"},"domain":"kinematics"},
  {"id":"aperi21:tangential-normal-acceleration","title":{"ko":"접선·법선 가속도","en":"Tangential and normal acceleration"},"description":{"ko":"속력 변화와 방향 변화의 분리","en":"Separating change of speed from change of direction"},"domain":"kinematics"},
  {"id":"aperi21:terminal-velocity","title":{"ko":"종단 속도","en":"Terminal velocity"},"description":{"ko":"공기 저항이 중력을 따라잡는 순간부터 더 빨라지지 않는다","en":"It stops speeding up the moment drag catches gravity"},"domain":"kinematics"},
  {"id":"aperi21:trajectory-equation","title":{"ko":"궤적 방정식","en":"Trajectory equation"},"description":{"ko":"시간을 소거해 얻은 경로의 식","en":"The path left when time is eliminated"},"domain":"kinematics"},
  {"id":"aperi21:uniform-circular-motion","title":{"ko":"등속 원운동","en":"Uniform circular motion"},"description":{"ko":"속도 화살표는 길이가 그대로인 채 방향만 바뀐다","en":"The velocity arrow keeps its length and only turns"},"domain":"kinematics"},
  {"id":"aperi21:uniform-motion","title":{"ko":"등속 운동","en":"Uniform motion"},"description":{"ko":"같은 시간에 같은 간격으로 자리를 옮긴다","en":"Equal intervals in equal times"},"domain":"kinematics"},
  {"id":"aperi21:uniformly-accelerated-motion","title":{"ko":"등가속도 운동","en":"Uniformly accelerated motion"},"description":{"ko":"같은 시간 동안 간 거리가 같은 만큼씩 늘어난다","en":"Distance in equal times grows by equal amounts"},"domain":"kinematics"},
  {"id":"aperi21:vector-addition","title":{"ko":"벡터의 합성","en":"Vector addition"},"description":{"ko":"나를 가의 머리에 옮겨 붙이고 이어 걸으면 그 끝이 합이다","en":"Slide b onto the head of a, walk both, and the far end is the sum"},"domain":"kinematics"},
  {"id":"aperi21:vector-decomposition","title":{"ko":"벡터의 성분 분해","en":"Vector components"},"description":{"ko":"끝점에서 두 축으로 곧게 내린 자리까지가 두 성분이다","en":"Drop straight from the tip to each axis — that is where each component ends"},"domain":"kinematics"},
  {"id":"aperi21:velocity-time-graph","title":{"ko":"속도-시간 그래프","en":"Velocity-time graph"},"description":{"ko":"그래프 아래 넓이가 간 거리다","en":"The area under the graph is the distance travelled"},"domain":"kinematics"},
  {"id":"aperi21:vertical-throw","title":{"ko":"연직 투상","en":"Vertical throw"},"description":{"ko":"올라갔다 내려오는 운동의 대칭","en":"The symmetry of going up and coming down"},"domain":"kinematics"},
  {"id":"aperi21:angle-of-friction","title":{"ko":"마찰각","en":"Angle of friction"},"description":{"ko":"미끄러지기 시작하는 경사","en":"The slope at which sliding begins"},"domain":"mechanics"},
  {"id":"aperi21:apparent-weight","title":{"ko":"겉보기 무게","en":"Apparent weight"},"description":{"ko":"가속하는 엘리베이터 안의 저울","en":"A scale in an accelerating elevator"},"domain":"mechanics"},
  {"id":"aperi21:atwood-machine","title":{"ko":"애트우드 기계","en":"Atwood machine"},"description":{"ko":"두 추의 합이 같으면 차이가 가속도를 정한다","en":"With the same total mass, the difference sets the acceleration"},"domain":"mechanics"},
  {"id":"aperi21:balance-scale","title":{"ko":"수평잡기","en":"Balancing a scale"},"description":{"ko":"양팔의 길이와 무게가 함께 정하는 균형","en":"Balance set by both arm length and weight"},"domain":"mechanics"},
  {"id":"aperi21:ballistic-pendulum","title":{"ko":"탄동 진자","en":"Ballistic pendulum"},"description":{"ko":"충돌과 에너지 보존을 잇는 측정","en":"The measurement that links a collision to energy conservation"},"domain":"mechanics"},
  {"id":"aperi21:banked-curve","title":{"ko":"경사진 커브","en":"Banked curve"},"description":{"ko":"마찰 없이도 도는 각도","en":"The bank angle that turns a car without friction"},"domain":"mechanics"},
  {"id":"aperi21:buoyant-force-as-force","title":{"ko":"부력(힘으로서)","en":"Buoyant force as a force"},"description":{"ko":"유체가 위로 미는 힘","en":"The upward push of a fluid"},"domain":"mechanics"},
  {"id":"aperi21:center-of-mass-motion","title":{"ko":"질량 중심의 운동","en":"Motion of the centre of mass"},"description":{"ko":"내부 힘에 영향받지 않는 운동","en":"The motion that internal forces cannot change"},"domain":"mechanics"},
  {"id":"aperi21:centripetal-force","title":{"ko":"구심력","en":"Centripetal force"},"description":{"ko":"원운동을 유지시키는 힘의 정체","en":"What keeps a body moving in a circle"},"domain":"mechanics"},
  {"id":"aperi21:conical-pendulum","title":{"ko":"원뿔 진자","en":"Conical pendulum"},"description":{"ko":"장력과 중력이 만드는 원운동","en":"Circular motion from tension and gravity"},"domain":"mechanics"},
  {"id":"aperi21:connected-bodies","title":{"ko":"연결된 물체","en":"Connected bodies"},"description":{"ko":"함께 움직이는 계의 가속도","en":"Acceleration of bodies moving together"},"domain":"mechanics"},
  {"id":"aperi21:conservation-of-momentum","title":{"ko":"운동량 보존","en":"Conservation of momentum"},"description":{"ko":"외력이 없을 때의 총 운동량","en":"Total momentum when no external force acts"},"domain":"mechanics"},
  {"id":"aperi21:conservative-force","title":{"ko":"보존력","en":"Conservative force"},"description":{"ko":"경로에 무관한 힘과 퍼텐셜의 존재","en":"A force whose work ignores the path — and the potential it allows"},"domain":"mechanics"},
  {"id":"aperi21:coriolis-effect","title":{"ko":"코리올리 효과","en":"Coriolis effect"},"description":{"ko":"회전 기준틀에서 휘는 경로","en":"A path that curves in a rotating frame"},"domain":"mechanics"},
  {"id":"aperi21:drag-force","title":{"ko":"공기 저항","en":"Air drag"},"description":{"ko":"빨라질수록 속도 제곱에 비례하는 저항이 가파르게 불어난다","en":"The faster it goes, the steeper the part of drag proportional to speed squared grows"},"domain":"mechanics"},
  {"id":"aperi21:efficiency","title":{"ko":"효율","en":"Efficiency"},"description":{"ko":"넣은 것과 얻은 것의 비","en":"The ratio of what comes out to what goes in"},"domain":"mechanics"},
  {"id":"aperi21:elastic-collision","title":{"ko":"탄성 충돌","en":"Elastic collision"},"description":{"ko":"운동 에너지까지 보존되는 충돌","en":"A collision that keeps even the kinetic energy"},"domain":"mechanics"},
  {"id":"aperi21:elastic-potential-energy","title":{"ko":"탄성 퍼텐셜 에너지","en":"Elastic potential energy"},"description":{"ko":"변형에 저장된 에너지","en":"The energy stored in a deformation"},"domain":"mechanics"},
  {"id":"aperi21:energy-dissipation","title":{"ko":"에너지 소산","en":"Energy dissipation"},"description":{"ko":"마찰이 가져가는 몫과 그 행방","en":"The share friction takes, and where it goes"},"domain":"mechanics"},
  {"id":"aperi21:energy-flow-diagram","title":{"ko":"에너지 흐름도","en":"Energy flow diagram"},"description":{"ko":"갈래의 굵기로 나타낸 에너지의 행방","en":"Where the energy goes, shown by branch thickness"},"domain":"mechanics"},
  {"id":"aperi21:energy-in-collision","title":{"ko":"충돌에서의 에너지","en":"Energy in collisions"},"description":{"ko":"보존되는 것과 안 되는 것의 구분","en":"Telling what is conserved from what is not"},"domain":"mechanics"},
  {"id":"aperi21:equilibrium-of-forces","title":{"ko":"힘의 평형","en":"Equilibrium of forces"},"description":{"ko":"알짜힘이 0인 상태","en":"Zero net force"},"domain":"mechanics"},
  {"id":"aperi21:equilibrium-points","title":{"ko":"평형점","en":"Equilibrium points"},"description":{"ko":"안정·불안정·중립 평형","en":"Stable, unstable and neutral equilibrium"},"domain":"mechanics"},
  {"id":"aperi21:explosion-and-recoil","title":{"ko":"폭발과 반동","en":"Explosion and recoil"},"description":{"ko":"정지한 계가 갈라질 때","en":"When a system at rest splits apart"},"domain":"mechanics"},
  {"id":"aperi21:fictitious-force","title":{"ko":"관성력","en":"Fictitious force"},"description":{"ko":"비관성계에서 도입하는 겉보기 힘","en":"The apparent force of a non-inertial frame"},"domain":"mechanics"},
  {"id":"aperi21:free-body-diagram","title":{"ko":"자유물체도","en":"Free-body diagram"},"description":{"ko":"한 물체에 작용하는 힘만 분리하기","en":"Isolating the forces on a single body"},"domain":"mechanics"},
  {"id":"aperi21:gravitational-potential-energy","title":{"ko":"중력 퍼텐셜 에너지","en":"Gravitational potential energy"},"description":{"ko":"높이에 저장된 에너지","en":"Energy stored in height"},"domain":"mechanics"},
  {"id":"aperi21:impulse-force-relation","title":{"ko":"힘과 충격량","en":"Force and impulse"},"description":{"ko":"짧고 큰 힘과 길고 작은 힘","en":"A short, large force and a long, small one"},"domain":"mechanics"},
  {"id":"aperi21:impulse-momentum-theorem","title":{"ko":"충격량-운동량 정리","en":"Impulse–momentum theorem"},"description":{"ko":"충격량이 운동량 변화와 같음","en":"Impulse equals the change in momentum"},"domain":"mechanics"},
  {"id":"aperi21:inclined-plane","title":{"ko":"빗면","en":"Inclined plane"},"description":{"ko":"중력을 면에 나란한 성분과 수직 성분으로","en":"Splitting gravity along and into the slope"},"domain":"mechanics"},
  {"id":"aperi21:inelastic-collision","title":{"ko":"비탄성 충돌","en":"Inelastic collision"},"description":{"ko":"에너지가 사라지는 충돌","en":"A collision that loses energy"},"domain":"mechanics"},
  {"id":"aperi21:inertial-frame","title":{"ko":"관성 기준계","en":"Inertial frame"},"description":{"ko":"버스만 느려지고 승객은 그대로 간다","en":"Only the bus slows; the passenger keeps going"},"domain":"mechanics"},
  {"id":"aperi21:inertial-vs-gravitational-mass","title":{"ko":"관성 질량과 중력 질량","en":"Inertial and gravitational mass"},"description":{"ko":"서로 다른 정의가 같은 값을 주는 것","en":"Two different definitions give the same value"},"domain":"mechanics"},
  {"id":"aperi21:kinetic-energy","title":{"ko":"운동 에너지","en":"Kinetic energy"},"description":{"ko":"속력이 담고 있는 에너지","en":"The energy that speed carries"},"domain":"mechanics"},
  {"id":"aperi21:kinetic-friction","title":{"ko":"운동 마찰력","en":"Kinetic friction"},"description":{"ko":"미끄러지는 동안의 마찰","en":"Friction while sliding"},"domain":"mechanics"},
  {"id":"aperi21:mechanical-advantage","title":{"ko":"힘의 이득","en":"Mechanical advantage"},"description":{"ko":"지레와 빗면이 드는 힘을 줄이는 방식","en":"How levers and ramps cut the force you need"},"domain":"mechanics"},
  {"id":"aperi21:net-force","title":{"ko":"알짜힘","en":"Net force"},"description":{"ko":"여러 힘의 벡터 합","en":"Vector sum of several forces"},"domain":"mechanics"},
  {"id":"aperi21:newtons-second-law","title":{"ko":"가속도 법칙","en":"Newton's second law"},"description":{"ko":"알짜힘·질량·가속도의 관계","en":"Net force, mass and acceleration"},"domain":"mechanics"},
  {"id":"aperi21:newtons-third-law","title":{"ko":"작용 반작용","en":"Action and reaction"},"description":{"ko":"힘의 쌍과 서로 다른 작용점","en":"A force pair acting on different bodies"},"domain":"mechanics"},
  {"id":"aperi21:non-conservative-force","title":{"ko":"비보존력","en":"Non-conservative force"},"description":{"ko":"경로에 따라 달라지는 일","en":"Work that depends on the path"},"domain":"mechanics"},
  {"id":"aperi21:non-inertial-frame","title":{"ko":"비관성계","en":"Non-inertial frame"},"description":{"ko":"가속하는 기준틀에서의 운동","en":"Motion seen from an accelerating frame"},"domain":"mechanics"},
  {"id":"aperi21:normal-force","title":{"ko":"수직항력","en":"Normal force"},"description":{"ko":"접촉면이 수직으로 미는 힘","en":"The perpendicular push of a contact surface"},"domain":"mechanics"},
  {"id":"aperi21:perfectly-inelastic-collision","title":{"ko":"완전 비탄성 충돌","en":"Perfectly inelastic collision"},"description":{"ko":"붙어서 함께 움직이는 경우","en":"When the two move together, stuck"},"domain":"mechanics"},
  {"id":"aperi21:potential-energy-curve","title":{"ko":"퍼텐셜 곡선","en":"Potential energy curve"},"description":{"ko":"곡선의 모양이 운동을 정하는 방식","en":"How the shape of the curve decides the motion"},"domain":"mechanics"},
  {"id":"aperi21:projectile","title":{"ko":"발사체","en":"Projectile"},"description":{"ko":"각도 다이얼 + 핀볼 런처","en":"Angle dial + pinball launcher"},"domain":"mechanics"},
  {"id":"aperi21:pulley-system","title":{"ko":"도르래","en":"Pulleys"},"description":{"ko":"힘의 방향과 크기를 바꾸는 장치","en":"A device that changes the direction and size of a force"},"domain":"mechanics"},
  {"id":"aperi21:ramp-energy","title":{"ko":"경사면과 에너지","en":"Ramps and energy"},"description":{"ko":"길이 달라도 바닥에서의 속력은 같다","en":"Different paths, same speed at the bottom"},"domain":"mechanics"},
  {"id":"aperi21:rocket-equation","title":{"ko":"로켓 방정식","en":"The rocket equation"},"description":{"ko":"연료를 버려 얻는 속도","en":"Speed bought by throwing fuel away"},"domain":"mechanics"},
  {"id":"aperi21:spring-force","title":{"ko":"탄성력","en":"Spring force"},"description":{"ko":"변형에 비례하는 복원력","en":"Restoring force proportional to stretch"},"domain":"mechanics"},
  {"id":"aperi21:static-friction","title":{"ko":"정지 마찰력","en":"Static friction"},"description":{"ko":"움직이기 전까지 버티는 힘","en":"The force that holds until the object moves"},"domain":"mechanics"},
  {"id":"aperi21:stress-strain-curve","title":{"ko":"응력-변형률 곡선","en":"Stress–strain curve"},"description":{"ko":"당길수록 달라지는 재료의 반응","en":"How a material responds as it is pulled"},"domain":"mechanics"},
  {"id":"aperi21:tension","title":{"ko":"장력","en":"Tension"},"description":{"ko":"줄이 당기는 힘과 그 전달","en":"How a rope carries a pull"},"domain":"mechanics"},
  {"id":"aperi21:two-dimensional-collision","title":{"ko":"2차원 충돌","en":"Two-dimensional collision"},"description":{"ko":"성분마다 따로 성립하는 보존","en":"Conservation that holds separately for each component"},"domain":"mechanics"},
  {"id":"aperi21:vertical-loop","title":{"ko":"연직 원운동","en":"Vertical loop"},"description":{"ko":"꼭대기에서 떨어지지 않는 최소 속력","en":"The minimum speed that keeps a ball on the loop at the top"},"domain":"mechanics"},
  {"id":"aperi21:work-by-variable-force","title":{"ko":"변하는 힘이 한 일","en":"Work done by a varying force"},"description":{"ko":"힘-변위 그래프의 넓이","en":"The area under the force–displacement graph"},"domain":"mechanics"},
  {"id":"aperi21:work-energy-theorem","title":{"ko":"일-운동 에너지 정리","en":"Work-energy theorem"},"description":{"ko":"알짜일이 운동 에너지 변화와 같음","en":"Net work equals the change in kinetic energy"},"domain":"mechanics"},
  {"id":"aperi21:youngs-modulus","title":{"ko":"영률","en":"Young's modulus"},"description":{"ko":"늘어나는 정도는 선의 길이가 아니라 재료가 정한다","en":"How much a wire stretches is set by its material, not its length"},"domain":"mechanics"},
  {"id":"aperi21:atomic-orbital","title":{"ko":"원자 궤도","en":"Atomic orbital"},"description":{"ko":"확률 분포로서의 전자","en":"The electron as a probability distribution"},"domain":"modern"},
  {"id":"aperi21:double-slit-with-electrons","title":{"ko":"전자의 이중 슬릿","en":"Double slit with electrons"},"description":{"ko":"하나씩 보내도 생기는 무늬","en":"A pattern that forms one electron at a time"},"domain":"modern"},
  {"id":"aperi21:hydrogen-spectrum","title":{"ko":"수소 스펙트럼","en":"Hydrogen spectrum"},"description":{"ko":"불연속한 선 스펙트럼","en":"A discrete line spectrum"},"domain":"modern"},
  {"id":"aperi21:radioactive-decay","title":{"ko":"방사성 붕괴","en":"Radioactive decay"},"description":{"ko":"반감기와 지수 감소","en":"Half-life and exponential decay"},"domain":"modern"},
  {"id":"aperi21:spacetime-diagram","title":{"ko":"시공간 도표","en":"Spacetime diagram"},"description":{"ko":"세계선과 동시선","en":"Worldline and line of simultaneity"},"domain":"modern"},
  {"id":"aperi21:color-addition","title":{"ko":"빛의 합성","en":"Adding light"},"description":{"ko":"세 색의 빛이 겹쳐 만드는 색","en":"The colour three lights make where they overlap"},"domain":"optics"},
  {"id":"aperi21:polarization","title":{"ko":"편광","en":"Polarization"},"description":{"ko":"진동면의 선택","en":"Selecting the plane of vibration"},"domain":"optics"},
  {"id":"aperi21:ray-tracing","title":{"ko":"광선 추적","en":"Ray Tracing"},"description":{"ko":"광원과 렌즈·거울을 배치해 광선 경로와 결상을 관찰.","en":"Place source and lens/mirror to watch ray paths and image formation."},"domain":"optics"},
  {"id":"aperi21:thin-film-interference","title":{"ko":"박막 간섭","en":"Thin-film interference"},"description":{"ko":"두께가 만드는 색","en":"Colour made by thickness"},"domain":"optics"},
  {"id":"aperi21:total-internal-reflection","title":{"ko":"전반사","en":"Total internal reflection"},"description":{"ko":"임계각과 그 조건","en":"The critical angle and its condition"},"domain":"optics"},
  {"id":"aperi21:youngs-double-slit","title":{"ko":"이중 슬릿 간섭","en":"Young's double slit"},"description":{"ko":"빛의 파동성 증거","en":"Evidence that light is a wave"},"domain":"optics"},
  {"id":"aperi21:angular-momentum","title":{"ko":"각운동량","en":"Angular momentum"},"description":{"ko":"회전의 운동량","en":"The momentum of rotation"},"domain":"oscillation"},
  {"id":"aperi21:angular-momentum-vector","title":{"ko":"각운동량의 방향","en":"Direction of angular momentum"},"description":{"ko":"오른손 규칙과 회전축","en":"The right-hand rule and the axis of rotation"},"domain":"oscillation"},
  {"id":"aperi21:beats-in-oscillation","title":{"ko":"진동의 맥놀이","en":"Beats in oscillation"},"description":{"ko":"가까운 두 진동수의 합","en":"The sum of two nearby frequencies"},"domain":"oscillation"},
  {"id":"aperi21:center-of-gravity","title":{"ko":"무게 중심","en":"Center of gravity"},"description":{"ko":"넘어지는 조건을 정하는 점","en":"The point that decides when things tip over"},"domain":"oscillation"},
  {"id":"aperi21:conservation-of-angular-momentum","title":{"ko":"각운동량 보존","en":"Conservation of angular momentum"},"description":{"ko":"팔을 오므리면 빨라지는 이유","en":"Why pulling your arms in makes you spin faster"},"domain":"oscillation"},
  {"id":"aperi21:coupled-oscillators","title":{"ko":"결합 진동자","en":"Coupled oscillators"},"description":{"ko":"에너지가 오가는 두 진동자","en":"Two oscillators trading energy"},"domain":"oscillation"},
  {"id":"aperi21:damped-oscillation","title":{"ko":"감쇠 진동","en":"Damped oscillation"},"description":{"ko":"에너지가 빠져나가는 진동","en":"An oscillation that loses energy"},"domain":"oscillation"},
  {"id":"aperi21:damping-regimes","title":{"ko":"감쇠의 세 양상","en":"Three regimes of damping"},"description":{"ko":"부족·임계·과도 감쇠","en":"Underdamped, critically damped and overdamped motion"},"domain":"oscillation"},
  {"id":"aperi21:driven-oscillation","title":{"ko":"강제 진동","en":"Driven oscillation"},"description":{"ko":"외부 구동에 대한 응답","en":"The response to an external drive"},"domain":"oscillation"},
  {"id":"aperi21:gears","title":{"ko":"기어","en":"Gears"},"description":{"ko":"톱니 수가 바꾸는 회전과 힘","en":"How tooth counts trade turning for force"},"domain":"oscillation"},
  {"id":"aperi21:gyroscopic-precession","title":{"ko":"세차 운동","en":"Gyroscopic precession"},"description":{"ko":"돌림힘이 각운동량 방향을 돌리는 것","en":"Torque turning the direction of angular momentum"},"domain":"oscillation"},
  {"id":"aperi21:mass-spring-system","title":{"ko":"용수철 진자","en":"Mass on a spring"},"description":{"ko":"질량과 탄성 계수가 정하는 주기","en":"The period set by mass and spring constant"},"domain":"oscillation"},
  {"id":"aperi21:moment-of-inertia","title":{"ko":"관성 모멘트","en":"Moment of inertia"},"description":{"ko":"질량 분포가 정하는 회전 저항","en":"How mass distribution sets rotational resistance"},"domain":"oscillation"},
  {"id":"aperi21:nonlinear-oscillation","title":{"ko":"비선형 진동","en":"Nonlinear oscillation"},"description":{"ko":"복원력이 비례를 벗어날 때","en":"When the restoring force stops being proportional"},"domain":"oscillation"},
  {"id":"aperi21:normal-modes","title":{"ko":"정규 모드","en":"Normal modes"},"description":{"ko":"계가 가진 고유 진동 형태","en":"The natural shapes a system vibrates in"},"domain":"oscillation"},
  {"id":"aperi21:parallel-axis-theorem","title":{"ko":"평행축 정리","en":"Parallel axis theorem"},"description":{"ko":"축을 옮길 때의 관성 모멘트","en":"Moment of inertia when the axis is moved"},"domain":"oscillation"},
  {"id":"aperi21:pendulum-isochronism","title":{"ko":"진자의 등시성","en":"Isochronism of the pendulum"},"description":{"ko":"폭이 달라도 같은 박자로 돌아온다","en":"Different amplitudes, same beat"},"domain":"oscillation"},
  {"id":"aperi21:phase-space","title":{"ko":"위상 공간","en":"Phase space"},"description":{"ko":"위치-속도 평면에서 본 운동","en":"Motion seen on the position–velocity plane"},"domain":"oscillation"},
  {"id":"aperi21:physical-pendulum","title":{"ko":"물리 진자","en":"Physical pendulum"},"description":{"ko":"크기가 있는 물체의 진동","en":"Oscillation of an extended body"},"domain":"oscillation"},
  {"id":"aperi21:quality-factor","title":{"ko":"Q 인자","en":"Quality factor"},"description":{"ko":"공명의 날카로움","en":"How sharp a resonance is"},"domain":"oscillation"},
  {"id":"aperi21:resonance","title":{"ko":"공명","en":"Resonance"},"description":{"ko":"구동 진동수가 고유 진동수에 맞을 때","en":"When the driving frequency matches the natural frequency"},"domain":"oscillation"},
  {"id":"aperi21:rolling-race","title":{"ko":"구르는 물체의 경주","en":"Rolling race"},"description":{"ko":"질량 분포가 정하는 도착 순서","en":"Arrival order set by mass distribution"},"domain":"oscillation"},
  {"id":"aperi21:rolling-without-slipping","title":{"ko":"미끄러지지 않는 구름","en":"Rolling without slipping"},"description":{"ko":"병진과 회전의 구속 조건","en":"The constraint that ties translation to rotation"},"domain":"oscillation"},
  {"id":"aperi21:rotational-kinetic-energy","title":{"ko":"회전 운동 에너지","en":"Rotational kinetic energy"},"description":{"ko":"각속도가 담은 에너지","en":"The energy that spin carries"},"domain":"oscillation"},
  {"id":"aperi21:shm-energy","title":{"ko":"조화 운동의 에너지","en":"Energy in simple harmonic motion"},"description":{"ko":"운동 에너지와 퍼텐셜의 교환","en":"Kinetic and potential energy trade places"},"domain":"oscillation"},
  {"id":"aperi21:simple-harmonic-motion","title":{"ko":"단순 조화 운동","en":"Simple harmonic motion"},"description":{"ko":"복원력이 변위에 비례하는 운동","en":"Motion under a restoring force proportional to displacement"},"domain":"oscillation"},
  {"id":"aperi21:simple-pendulum","title":{"ko":"단진자","en":"Simple pendulum"},"description":{"ko":"작은 진폭에서의 주기","en":"The period at small amplitude"},"domain":"oscillation"},
  {"id":"aperi21:static-equilibrium","title":{"ko":"정적 평형","en":"Static equilibrium"},"description":{"ko":"힘과 돌림힘이 모두 0","en":"Both the net force and the net torque are zero"},"domain":"oscillation"},
  {"id":"aperi21:torque","title":{"ko":"돌림힘","en":"Torque"},"description":{"ko":"회전을 일으키는 양과 팔 길이","en":"What makes things turn, and the length of the lever arm"},"domain":"oscillation"},
  {"id":"aperi21:carnot-cycle","title":{"ko":"카르노 순환","en":"Carnot cycle"},"description":{"ko":"이론적 최대 효율","en":"The theoretical maximum efficiency"},"domain":"thermal"},
  {"id":"aperi21:gas-pressure","title":{"ko":"기체 분자와 압력","en":"Molecules and pressure"},"description":{"ko":"두드림이 쌓여 압력이 된다","en":"Pressure is the sum of the knocks"},"domain":"thermal"},
  {"id":"aperi21:heat-conduction","title":{"ko":"열전도","en":"Heat conduction"},"description":{"ko":"쇠에서는 번져 나가고 나무에서는 머문다","en":"It spreads in steel and stays in wood"},"domain":"thermal"},
  {"id":"aperi21:maxwell-boltzmann-distribution","title":{"ko":"맥스웰-볼츠만 분포","en":"Maxwell–Boltzmann distribution"},"description":{"ko":"데우면 분자 속력 분포가 퍼지며 내려앉는다","en":"Heating spreads the speed distribution and lowers its peak"},"domain":"thermal"},
  {"id":"aperi21:phase-diagram","title":{"ko":"상평형 그림","en":"Phase diagram"},"description":{"ko":"삼중점보다 낮은 압력에서는 액체 구간을 건너뛴다","en":"Below the triple point, the liquid range is skipped"},"domain":"thermal"},
  {"id":"aperi21:thermal-convection","title":{"ko":"대류","en":"Convection"},"description":{"ko":"유체의 이동이 나르는 열","en":"Heat carried by moving fluid"},"domain":"thermal"},
  {"id":"aperi21:air-column-resonance","title":{"ko":"기주 공명","en":"Air-column resonance"},"description":{"ko":"열린 관과 닫힌 관의 차이","en":"Open pipe versus closed pipe"},"domain":"waves"},
  {"id":"aperi21:beats","title":{"ko":"맥놀이","en":"Beats"},"description":{"ko":"두 음이 어긋나는 만큼 합이 지워진다","en":"The sum cancels as the two drift apart"},"domain":"waves"},
  {"id":"aperi21:constructive-destructive","title":{"ko":"보강과 상쇄","en":"Constructive and destructive interference"},"description":{"ko":"위상차가 정하는 합의 크기","en":"How phase difference sets the size of the sum"},"domain":"waves"},
  {"id":"aperi21:diffraction","title":{"ko":"회절","en":"Diffraction"},"description":{"ko":"장애물을 돌아가는 파동","en":"Waves bending around obstacles"},"domain":"waves"},
  {"id":"aperi21:digital-vs-analog-signal","title":{"ko":"디지털 신호와 아날로그","en":"Digital and analog signals"},"description":{"ko":"잡음을 견디는 방식의 차이","en":"Two ways of standing up to noise"},"domain":"waves"},
  {"id":"aperi21:doppler-effect","title":{"ko":"도플러 효과","en":"Doppler effect"},"description":{"ko":"원천이 방출점을 밀고 가 앞쪽 간격이 좁아진다","en":"The source drags its emission points, crowding the front"},"domain":"waves"},
  {"id":"aperi21:doppler-source-vs-observer","title":{"ko":"음원과 관찰자","en":"Moving source vs. moving observer"},"description":{"ko":"누가 움직이냐에 따른 비대칭","en":"The asymmetry of who is moving"},"domain":"waves"},
  {"id":"aperi21:harmonics","title":{"ko":"배음","en":"Harmonics"},"description":{"ko":"경계 조건이 정하는 진동수","en":"Frequencies set by the boundary"},"domain":"waves"},
  {"id":"aperi21:huygens-principle","title":{"ko":"하위헌스 원리","en":"Huygens' principle"},"description":{"ko":"파면 위 점마다 나간 동그란 파가 겹쳐 곧게 펴진다","en":"Circular wavelets from points on a wavefront overlap into a straight front"},"domain":"waves"},
  {"id":"aperi21:impedance-mismatch","title":{"ko":"임피던스 부정합","en":"Impedance mismatch"},"description":{"ko":"경계에서 반사되는 비율","en":"How much reflects at a boundary"},"domain":"waves"},
  {"id":"aperi21:interference","title":{"ko":"간섭","en":"Interference"},"description":{"ko":"두 물결이 서로를 지워 줄지어 잠잠해진다","en":"Two sets of ripples cancel and leave calm lines"},"domain":"waves"},
  {"id":"aperi21:longitudinal-wave","title":{"ko":"종파","en":"Longitudinal wave"},"description":{"ko":"입자는 제자리에서 흔들리고, 빽빽한 자리가 나아간다","en":"Particles sway in place while the crowded places travel on"},"domain":"waves"},
  {"id":"aperi21:noise-cancellation","title":{"ko":"능동 소음 제거","en":"Active noise cancellation"},"description":{"ko":"역위상 파동의 중첩","en":"Superposing an inverted wave"},"domain":"waves"},
  {"id":"aperi21:reflection-of-waves","title":{"ko":"파동의 반사","en":"Reflection of waves"},"description":{"ko":"고정단과 자유단에서의 위상","en":"Phase at a fixed end and at a free end"},"domain":"waves"},
  {"id":"aperi21:refraction-of-waves","title":{"ko":"파동의 굴절","en":"Refraction of waves"},"description":{"ko":"속도 변화가 만드는 방향 전환","en":"A change of speed turns the direction"},"domain":"waves"},
  {"id":"aperi21:seismic-waves","title":{"ko":"지진파","en":"Seismic waves"},"description":{"ko":"지구 속을 지나는 P파와 S파","en":"P and S waves travelling through the Earth"},"domain":"waves"},
  {"id":"aperi21:shock-wave","title":{"ko":"충격파","en":"Shock wave"},"description":{"ko":"음속을 넘을 때 생기는 원뿔","en":"The cone that forms past the speed of sound"},"domain":"waves"},
  {"id":"aperi21:slit-width-and-diffraction","title":{"ko":"슬릿 폭과 회절","en":"Slit Width and Diffraction"},"description":{"ko":"파장과 폭의 비가 정하는 퍼짐","en":"How the gap-to-wavelength ratio sets the spread"},"domain":"waves"},
  {"id":"aperi21:sound-intensity","title":{"ko":"음의 세기","en":"Sound intensity"},"description":{"ko":"거리 제곱에 반비례하는 감쇠","en":"Falling off with the square of distance"},"domain":"waves"},
  {"id":"aperi21:sound-source-vibration","title":{"ko":"소리와 떨림","en":"Sound and vibration"},"description":{"ko":"소리 나는 물체는 떨리고, 떨림이 멎으면 소리도 멎는다","en":"A sounding object vibrates, and when the vibration stops, so does the sound"},"domain":"waves"},
  {"id":"aperi21:sound-through-materials","title":{"ko":"물질을 통한 소리 전달","en":"Sound through materials"},"description":{"ko":"매질에 따라 달라지는 소리의 전달","en":"How sound travels differently through different materials"},"domain":"waves"},
  {"id":"aperi21:standing-wave","title":{"ko":"정상파","en":"Standing wave"},"description":{"ko":"반대로 달리는 두 파동이 겹치면 마디가 제자리에 고정된다","en":"Two waves running in opposite directions pin the nodes in place"},"domain":"waves"},
  {"id":"aperi21:string-vibration","title":{"ko":"줄의 진동","en":"Vibrating string"},"description":{"ko":"양끝이 고정된 줄의 모드","en":"Modes of a string fixed at both ends"},"domain":"waves"},
  {"id":"aperi21:superposition","title":{"ko":"중첩 원리","en":"Superposition"},"description":{"ko":"파동이 겹칠 때의 합","en":"What happens when waves overlap"},"domain":"waves"},
  {"id":"aperi21:transverse-wave","title":{"ko":"횡파","en":"Transverse wave"},"description":{"ko":"진동 방향이 진행 방향과 수직","en":"The medium shakes at right angles to the direction the wave travels"},"domain":"waves"},
  {"id":"aperi21:wave-attenuation","title":{"ko":"파동의 감쇠","en":"Attenuation of a wave"},"description":{"ko":"매질이 흡수하는 에너지","en":"Energy absorbed by the medium"},"domain":"waves"},
  {"id":"aperi21:wave-basics","title":{"ko":"파동의 기본량","en":"Basic quantities of a wave"},"description":{"ko":"파장·진동수·속력·진폭","en":"Wavelength, frequency, speed and amplitude"},"domain":"waves"},
  {"id":"aperi21:wave-energy","title":{"ko":"파동의 에너지","en":"Energy of a wave"},"description":{"ko":"진폭 제곱에 비례하는 에너지","en":"Energy grows with the square of the amplitude"},"domain":"waves"},
  {"id":"aperi21:wave-speed-in-medium","title":{"ko":"매질과 파동 속도","en":"Wave speed and the medium"},"description":{"ko":"장력·밀도·탄성이 정하는 속도","en":"Speed set by tension, density and elasticity"},"domain":"waves"},
  {"id":"aperi21:wave-vs-particle-transport","title":{"ko":"파동이 나르는 것","en":"What a wave carries"},"description":{"ko":"매질은 제자리, 에너지는 이동","en":"The medium stays put, the energy moves on"},"domain":"waves"},
  {"id":"aperi21:wavefront-and-ray","title":{"ko":"파면과 광선","en":"Wavefronts and rays"},"description":{"ko":"같은 위상의 면과 그 수직선","en":"Surfaces of equal phase and the lines normal to them"},"domain":"waves"},
];
