/**
 * 자동 생성 파일 — 직접 편집하지 말 것.
 *
 * 생성: pnpm catalog:gen  (scripts/gen-aperi21-catalog.mts)
 * 출처: 각 sim 의 schema(label/operation/category) + registerAperi21Bundles 의 loader id.
 *
 * 이 배열은 순수 데이터라 sim 의 무거운 시각화 chunk 를 참조하지 않는다.
 * 따라서 호스트는 이 카탈로그를 읽어도 sim 모듈을 로드하지 않는다 (lazy 보존).
 */

import type { Aperi21CatalogEntry } from './catalog-types.js';

export const APERI21_CATALOG: readonly Aperi21CatalogEntry[] = [
  {"id":"aperi21:apparent-brightness","title":{"ko":"겉보기 밝기","en":"Apparent brightness"},"description":{"ko":"같은 빛이 넓은 면에 나뉜다","en":"The same light divides over a wider area"},"domain":"astro"},
  {"id":"aperi21:dc-circuit","title":{"ko":"DC 회로","en":"DC Circuit"},"description":{"ko":"배터리·저항으로 단순·직렬·병렬 회로를 구성해 전압·전류를 확인.","en":"Build simple/series/parallel DC circuits with batteries and resistors; inspect V/I."},"domain":"electromagnetism"},
  {"id":"aperi21:current-magnetic-field","title":{"ko":"전류가 만드는 자기장","en":"The field a current makes"},"description":{"ko":"전선을 감아 도는 쪽으로 돌아서고, 멀수록 덜 돌아선다","en":"Needles turn along the loop, and less so farther out"},"domain":"em"},
  {"id":"aperi21:lenz-law","title":{"ko":"렌츠 법칙","en":"Lenz's law"},"description":{"ko":"전류는 뒤집혀도 힘은 늘 움직임을 거스른다","en":"The current flips, the force never does"},"domain":"em"},
  {"id":"aperi21:archimedes-principle","title":{"ko":"아르키메데스 원리 — 부력의 크기","en":"Archimedes principle — the size of the buoyant force"},"description":{"ko":"2.0 kg · 1.0 L 물체를 주둥이까지 가득 찬 물에 천천히 담근다. 밀려난 물이 주둥이로 넘쳐 컵에 모이고, 물체 쪽 저울이 줄어드는 만큼 넘친 물 쪽 저울이 늘어난다.","en":"A 2.0 kg, 1.0 L object is lowered into a can filled to its spout. The displaced water pours into the cup, and the scale holding the water gains exactly what the scale holding the object loses."},"domain":"fluids"},
  {"id":"aperi21:laminar-vs-turbulent","title":{"ko":"층류와 난류","en":"Laminar and turbulent flow"},"description":{"ko":"흐름이 갑자기 흐트러지는 지점","en":"Where flow suddenly breaks up"},"domain":"fluids"},
  {"id":"aperi21:pressure-and-container-shape","title":{"ko":"그릇 모양과 바닥 압력","en":"Container shape and bottom pressure"},"description":{"ko":"수면 높이를 옮겨 세 그릇을 다시 채운다","en":"Move the water level and refill all three"},"domain":"fluids"},
  {"id":"aperi21:pressure-isotropy","title":{"ko":"압력의 등방성","en":"Pressure isotropy"},"description":{"ko":"판이 저절로 반 바퀴 돌아 자취를 원으로 닫고, 그다음 독자가 다이얼로 직접 돌린다","en":"the plate turns half a revolution to close the trail into a circle, then the reader turns it by hand"},"domain":"fluids"},
  {"id":"aperi21:torricellis-law","title":{"ko":"토리첼리 법칙","en":"Torricelli's law"},"description":{"ko":"깊은 구멍일수록 더 빠르게 뿜는다","en":"The deeper the hole, the faster the jet"},"domain":"fluids"},
  {"id":"aperi21:acceleration-time-graph","title":{"ko":"가속도-시간 그래프","en":"Acceleration-time graph"},"description":{"ko":"넓이가 속도 변화인 표현","en":"The area under the graph is the change in velocity"},"domain":"kinematics"},
  {"id":"aperi21:angular-acceleration","title":{"ko":"각가속도","en":"Angular acceleration"},"description":{"ko":"같은 0.5초에 도는 각이 매번 더 커진다","en":"Each half-second sweeps a wider angle than the last"},"domain":"kinematics"},
  {"id":"aperi21:average-acceleration","title":{"ko":"평균 가속도","en":"Average acceleration"},"description":{"ko":"속도 변화의 비율","en":"Rate of change of velocity"},"domain":"kinematics"},
  {"id":"aperi21:average-velocity","title":{"ko":"평균 속도","en":"Average velocity"},"description":{"ko":"구간 전체를 대표하는 속도","en":"One velocity standing for a whole interval"},"domain":"kinematics"},
  {"id":"aperi21:centripetal-acceleration","title":{"ko":"구심 가속도","en":"Centripetal acceleration"},"description":{"ko":"속도의 변화는 늘 중심 쪽으로 꺾인다","en":"The change in velocity always turns toward the center"},"domain":"kinematics"},
  {"id":"aperi21:coordinate-choice","title":{"ko":"좌표계 선택","en":"Choosing axes"},"description":{"ko":"축을 어디에 두느냐가 식을 바꾸는 방식","en":"How the choice of axes changes the equations"},"domain":"kinematics"},
  {"id":"aperi21:direction-of-acceleration","title":{"ko":"가속도의 방향","en":"Direction of acceleration"},"description":{"ko":"속도와 같은 방향인지 반대인지가 정하는 것","en":"Whether it points with or against the velocity"},"domain":"kinematics"},
  {"id":"aperi21:free-fall","title":{"ko":"자유 낙하","en":"Free fall"},"description":{"ko":"무게가 달라도 두 공은 나란히 내려가 함께 닿는다","en":"However different their weights, the two balls fall together and land together"},"domain":"kinematics"},
  {"id":"aperi21:gravitational-acceleration","title":{"ko":"중력 가속도","en":"Gravitational acceleration"},"description":{"ko":"속도가 0인 순간에도 멈추지 않는 가속","en":"Acceleration that does not stop even when the velocity is zero"},"domain":"kinematics"},
  {"id":"aperi21:position-time-graph","title":{"ko":"위치-시간 그래프","en":"Position-time graph"},"description":{"ko":"빨리 오를수록 남기는 선이 가파르다","en":"The faster it rises, the steeper the line it leaves"},"domain":"kinematics"},
  {"id":"aperi21:projectile-motion","title":{"ko":"포물선 운동","en":"Projectile motion"},"description":{"ko":"수평과 연직이 서로를 건드리지 않고 따로 간다","en":"Horizontal and vertical go on untouched"},"domain":"kinematics"},
  {"id":"aperi21:radius-of-curvature","title":{"ko":"곡률 반지름","en":"Radius of curvature"},"description":{"ko":"굽은 정도에 맞는 원이 경로에 얹힌다","en":"A circle matching the bend rides the path"},"domain":"kinematics"},
  {"id":"aperi21:reference-frame","title":{"ko":"기준틀","en":"Reference frame"},"description":{"ko":"관찰자에 따라 달라지는 운동 기술","en":"How the description of motion depends on the observer"},"domain":"kinematics"},
  {"id":"aperi21:relative-velocity","title":{"ko":"상대 속도","en":"Relative velocity"},"description":{"ko":"보는 사람이 달라지면 배가 지나온 길이 기운다","en":"Change who is watching and the path the boat left tilts"},"domain":"kinematics"},
  {"id":"aperi21:river-crossing","title":{"ko":"강 건너기","en":"Crossing a river"},"description":{"ko":"뱃머리를 맞은편에 두어도 물살에 떠밀려 하류에 닿는다","en":"Aimed straight across, the boat is pushed downstream by the current"},"domain":"kinematics"},
  {"id":"aperi21:stopping-distance","title":{"ko":"정지 거리","en":"Stopping distance"},"description":{"ko":"반응 거리는 비례로, 제동 거리는 제곱으로 늘어난다","en":"Reaction grows linearly, braking as the square"},"domain":"kinematics"},
  {"id":"aperi21:tangential-normal-acceleration","title":{"ko":"접선·법선 가속도","en":"Tangential and normal acceleration"},"description":{"ko":"속력 변화와 방향 변화의 분리","en":"Separating change of speed from change of direction"},"domain":"kinematics"},
  {"id":"aperi21:terminal-velocity","title":{"ko":"종단 속도","en":"Terminal velocity"},"description":{"ko":"공기 저항이 중력을 따라잡는 순간부터 더 빨라지지 않는다","en":"It stops speeding up the moment drag catches gravity"},"domain":"kinematics"},
  {"id":"aperi21:trajectory-equation","title":{"ko":"궤적 방정식","en":"Trajectory equation"},"description":{"ko":"시간을 소거해 얻은 경로의 식","en":"The path left when time is eliminated"},"domain":"kinematics"},
  {"id":"aperi21:uniform-circular-motion","title":{"ko":"등속 원운동","en":"Uniform circular motion"},"description":{"ko":"속도 화살표는 길이가 그대로인 채 방향만 바뀐다","en":"The velocity arrow keeps its length and only turns"},"domain":"kinematics"},
  {"id":"aperi21:uniform-motion","title":{"ko":"등속 운동","en":"Uniform motion"},"description":{"ko":"같은 시간에 같은 간격으로 자리를 옮긴다","en":"Equal intervals in equal times"},"domain":"kinematics"},
  {"id":"aperi21:uniformly-accelerated-motion","title":{"ko":"등가속도 운동","en":"Uniformly accelerated motion"},"description":{"ko":"같은 시간 동안 간 거리가 같은 만큼씩 늘어난다","en":"Distance in equal times grows by equal amounts"},"domain":"kinematics"},
  {"id":"aperi21:vector-addition","title":{"ko":"벡터의 합성","en":"Vector addition"},"description":{"ko":"나를 가의 머리에 옮겨 붙이고 이어 걸으면 그 끝이 합이다","en":"Slide b onto the head of a, walk both, and the far end is the sum"},"domain":"kinematics"},
  {"id":"aperi21:vector-decomposition","title":{"ko":"벡터의 성분 분해","en":"Vector components"},"description":{"ko":"끝점에서 두 축으로 곧게 내린 자리까지가 두 성분이다","en":"Drop straight from the tip to each axis — that is where each component ends"},"domain":"kinematics"},
  {"id":"aperi21:velocity-time-graph","title":{"ko":"속도-시간 그래프","en":"Velocity-time graph"},"description":{"ko":"그래프 아래 넓이가 간 거리다","en":"The area under the graph is the distance travelled"},"domain":"kinematics"},
  {"id":"aperi21:vertical-throw","title":{"ko":"연직 투상","en":"Vertical throw"},"description":{"ko":"올라갔다 내려오는 운동의 대칭","en":"The symmetry of going up and coming down"},"domain":"kinematics"},
  {"id":"aperi21:angle-of-friction","title":{"ko":"마찰각","en":"Angle of friction"},"description":{"ko":"미끄러지기 시작하는 경사","en":"The slope at which sliding begins"},"domain":"mechanics"},
  {"id":"aperi21:apparent-weight","title":{"ko":"겉보기 무게","en":"Apparent weight"},"description":{"ko":"가속하는 엘리베이터 안의 저울","en":"A scale in an accelerating elevator"},"domain":"mechanics"},
  {"id":"aperi21:atwood-machine","title":{"ko":"애트우드 기계","en":"Atwood machine"},"description":{"ko":"두 추의 합이 같으면 차이가 가속도를 정한다","en":"With the same total mass, the difference sets the acceleration"},"domain":"mechanics"},
  {"id":"aperi21:balance-scale","title":{"ko":"수평잡기","en":"Balancing a scale"},"description":{"ko":"양팔의 길이와 무게가 함께 정하는 균형","en":"Balance set by both arm length and weight"},"domain":"mechanics"},
  {"id":"aperi21:banked-curve","title":{"ko":"경사진 커브","en":"Banked curve"},"description":{"ko":"마찰 없이도 도는 각도","en":"The bank angle that turns a car without friction"},"domain":"mechanics"},
  {"id":"aperi21:buoyant-force-as-force","title":{"ko":"부력(힘으로서)","en":"Buoyant force as a force"},"description":{"ko":"유체가 위로 미는 힘","en":"The upward push of a fluid"},"domain":"mechanics"},
  {"id":"aperi21:centripetal-force","title":{"ko":"구심력","en":"Centripetal force"},"description":{"ko":"원운동을 유지시키는 힘의 정체","en":"What keeps a body moving in a circle"},"domain":"mechanics"},
  {"id":"aperi21:conical-pendulum","title":{"ko":"원뿔 진자","en":"Conical pendulum"},"description":{"ko":"장력과 중력이 만드는 원운동","en":"Circular motion from tension and gravity"},"domain":"mechanics"},
  {"id":"aperi21:connected-bodies","title":{"ko":"연결된 물체","en":"Connected bodies"},"description":{"ko":"함께 움직이는 계의 가속도","en":"Acceleration of bodies moving together"},"domain":"mechanics"},
  {"id":"aperi21:coriolis-effect","title":{"ko":"코리올리 효과","en":"Coriolis effect"},"description":{"ko":"회전 기준틀에서 휘는 경로","en":"A path that curves in a rotating frame"},"domain":"mechanics"},
  {"id":"aperi21:drag-force","title":{"ko":"공기 저항","en":"Air drag"},"description":{"ko":"빨라질수록 속도 제곱에 비례하는 저항이 가파르게 불어난다","en":"The faster it goes, the steeper the part of drag proportional to speed squared grows"},"domain":"mechanics"},
  {"id":"aperi21:equilibrium-of-forces","title":{"ko":"힘의 평형","en":"Equilibrium of forces"},"description":{"ko":"알짜힘이 0인 상태","en":"Zero net force"},"domain":"mechanics"},
  {"id":"aperi21:fictitious-force","title":{"ko":"관성력","en":"Fictitious force"},"description":{"ko":"비관성계에서 도입하는 겉보기 힘","en":"The apparent force of a non-inertial frame"},"domain":"mechanics"},
  {"id":"aperi21:free-body-diagram","title":{"ko":"자유물체도","en":"Free-body diagram"},"description":{"ko":"한 물체에 작용하는 힘만 분리하기","en":"Isolating the forces on a single body"},"domain":"mechanics"},
  {"id":"aperi21:impulse-force-relation","title":{"ko":"힘과 충격량","en":"Force and impulse"},"description":{"ko":"짧고 큰 힘과 길고 작은 힘","en":"A short, large force and a long, small one"},"domain":"mechanics"},
  {"id":"aperi21:inclined-plane","title":{"ko":"빗면","en":"Inclined plane"},"description":{"ko":"중력을 면에 나란한 성분과 수직 성분으로","en":"Splitting gravity along and into the slope"},"domain":"mechanics"},
  {"id":"aperi21:inertial-frame","title":{"ko":"관성 기준계","en":"Inertial frame"},"description":{"ko":"버스만 느려지고 승객은 그대로 간다","en":"Only the bus slows; the passenger keeps going"},"domain":"mechanics"},
  {"id":"aperi21:inertial-vs-gravitational-mass","title":{"ko":"관성 질량과 중력 질량","en":"Inertial and gravitational mass"},"description":{"ko":"서로 다른 정의가 같은 값을 주는 것","en":"Two different definitions give the same value"},"domain":"mechanics"},
  {"id":"aperi21:kinetic-friction","title":{"ko":"운동 마찰력","en":"Kinetic friction"},"description":{"ko":"미끄러지는 동안의 마찰","en":"Friction while sliding"},"domain":"mechanics"},
  {"id":"aperi21:mechanical-advantage","title":{"ko":"힘의 이득","en":"Mechanical advantage"},"description":{"ko":"지레와 빗면이 드는 힘을 줄이는 방식","en":"How levers and ramps cut the force you need"},"domain":"mechanics"},
  {"id":"aperi21:net-force","title":{"ko":"알짜힘","en":"Net force"},"description":{"ko":"여러 힘의 벡터 합","en":"Vector sum of several forces"},"domain":"mechanics"},
  {"id":"aperi21:newtons-second-law","title":{"ko":"가속도 법칙","en":"Newton's second law"},"description":{"ko":"알짜힘·질량·가속도의 관계","en":"Net force, mass and acceleration"},"domain":"mechanics"},
  {"id":"aperi21:newtons-third-law","title":{"ko":"작용 반작용","en":"Action and reaction"},"description":{"ko":"힘의 쌍과 서로 다른 작용점","en":"A force pair acting on different bodies"},"domain":"mechanics"},
  {"id":"aperi21:non-inertial-frame","title":{"ko":"비관성계","en":"Non-inertial frame"},"description":{"ko":"가속하는 기준틀에서의 운동","en":"Motion seen from an accelerating frame"},"domain":"mechanics"},
  {"id":"aperi21:normal-force","title":{"ko":"수직항력","en":"Normal force"},"description":{"ko":"접촉면이 수직으로 미는 힘","en":"The perpendicular push of a contact surface"},"domain":"mechanics"},
  {"id":"aperi21:projectile","title":{"ko":"발사체","en":"Projectile"},"description":{"ko":"각도 다이얼 + 핀볼 런처","en":"Angle dial + pinball launcher"},"domain":"mechanics"},
  {"id":"aperi21:pulley-system","title":{"ko":"도르래","en":"Pulleys"},"description":{"ko":"힘의 방향과 크기를 바꾸는 장치","en":"A device that changes the direction and size of a force"},"domain":"mechanics"},
  {"id":"aperi21:ramp-energy","title":{"ko":"경사면과 에너지","en":"Ramps and energy"},"description":{"ko":"길이 달라도 바닥에서의 속력은 같다","en":"Different paths, same speed at the bottom"},"domain":"mechanics"},
  {"id":"aperi21:spring-force","title":{"ko":"탄성력","en":"Spring force"},"description":{"ko":"변형에 비례하는 복원력","en":"Restoring force proportional to stretch"},"domain":"mechanics"},
  {"id":"aperi21:static-friction","title":{"ko":"정지 마찰력","en":"Static friction"},"description":{"ko":"움직이기 전까지 버티는 힘","en":"The force that holds until the object moves"},"domain":"mechanics"},
  {"id":"aperi21:stress-strain-curve","title":{"ko":"응력-변형률 곡선","en":"Stress–strain curve"},"description":{"ko":"당길수록 달라지는 재료의 반응","en":"How a material responds as it is pulled"},"domain":"mechanics"},
  {"id":"aperi21:tension","title":{"ko":"장력","en":"Tension"},"description":{"ko":"줄이 당기는 힘과 그 전달","en":"How a rope carries a pull"},"domain":"mechanics"},
  {"id":"aperi21:vertical-loop","title":{"ko":"연직 원운동","en":"Vertical loop"},"description":{"ko":"꼭대기에서 떨어지지 않는 최소 속력","en":"The minimum speed that keeps a ball on the loop at the top"},"domain":"mechanics"},
  {"id":"aperi21:youngs-modulus","title":{"ko":"영률","en":"Young's modulus"},"description":{"ko":"늘어나는 정도는 선의 길이가 아니라 재료가 정한다","en":"How much a wire stretches is set by its material, not its length"},"domain":"mechanics"},
  {"id":"aperi21:ray-tracing","title":{"ko":"광선 추적","en":"Ray Tracing"},"description":{"ko":"광원과 렌즈·거울을 배치해 광선 경로와 결상을 관찰.","en":"Place source and lens/mirror to watch ray paths and image formation."},"domain":"optics"},
  {"id":"aperi21:pendulum-isochronism","title":{"ko":"진자의 등시성","en":"Isochronism of the pendulum"},"description":{"ko":"폭이 달라도 같은 박자로 돌아온다","en":"Different amplitudes, same beat"},"domain":"oscillation"},
  {"id":"aperi21:gas-pressure","title":{"ko":"기체 분자와 압력","en":"Molecules and pressure"},"description":{"ko":"두드림이 쌓여 압력이 된다","en":"Pressure is the sum of the knocks"},"domain":"thermal"},
  {"id":"aperi21:heat-conduction","title":{"ko":"열전도","en":"Heat conduction"},"description":{"ko":"쇠에서는 번져 나가고 나무에서는 머문다","en":"It spreads in steel and stays in wood"},"domain":"thermal"},
  {"id":"aperi21:beats","title":{"ko":"맥놀이","en":"Beats"},"description":{"ko":"두 음이 어긋나는 만큼 합이 지워진다","en":"The sum cancels as the two drift apart"},"domain":"waves"},
  {"id":"aperi21:doppler-effect","title":{"ko":"도플러 효과","en":"Doppler effect"},"description":{"ko":"원천이 방출점을 밀고 가 앞쪽 간격이 좁아진다","en":"The source drags its emission points, crowding the front"},"domain":"waves"},
];
